### DISCUSSION TITLE
Azure Disks are not reclaimed when deleting PV

### DISCUSSION THREAD

**Discussion by mbendtsen** [Azure/AKS#2630] [Q&A]
According to this [page](https://docs.microsoft.com/en-us/azure/aks/concepts-storage), unused disks should be delete when persistent volume is deleted.

> The reclaim policy ensures that the underlying Azure Disk is deleted when the persistent volume that used it is deleted.

I uses this storageClass to create my PV.

``` yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
```

But when I delete both the PV and PVC, the Azure Disk remains. Is it reclaimed later? To my understanding, the disk resource in Azure should be deleted if the `recalimPolicy` is `Delete` when the PV is deleted.

The disk just change state to `Unattached`.
