### DISCUSSION TITLE
Setting shm-size and ulimit in AKS

### DISCUSSION THREAD

**Discussion by RobinFrcd** [Azure/AKS#3638] [Q&A]
Hi,
I'm trying to deploy a torchserve service on my EKS cluster. The thing is it needs some [specific configuration](https://github.com/pytorch/serve/blob/master/docker/README.md#running-torchserve-in-a-production-docker-environment) to work.

How can I set `shm-size` and `ulimit` for my deployments on AKS ? `--shm-size=1g`, `--ulimit memlock=-1` and `--ulimit stack=67108864 `

```
docker run --rm --shm-size=1g \
        --ulimit memlock=-1 \
        --ulimit stack=67108864 \
        -p8080:8080 \
        -p8081:8081 \
        -p8082:8082 \
        -p7070:7070 \
        -p7071:7071 \
        --mount type=bind,source=/path/to/model/store,target=/tmp/models <container> torchserve --model-store=/tmp/models
```

Thanks,

**Comment by freddyrios** [comment]
@RobinFrcd did you ever found out how to do this?

**Reply by RobinFrcd** [reply]
Wow, that was a long time ago.
Not sure anymore, the only stuff I could retrieve was:
```
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```

So I guess I didn't need the `ulimit`, `shm-size` was enough.

Hope it helps.
