### ISSUE TITLE
mount --bind mount: permission denied  within the system

### ISSUE THREAD

**Issue by knowings** [Azure/AKS#1018]
**What happened**:

I tried to apply the following deployment (some irrelevant pieces are missing) :
```yaml
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: sftp-shared-resources
  labels:
    environment: production
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        environment: production
        app: sftp-shared-resources
    spec:
      volumes:
        - name: sftp-shared-resources-user-configuration
          configMap:
            name: sftp-shared-resources-user-configuration
            defaultMode: 0755
        - name: sftp-shared-resources-ssh-keys
          configMap:
            name: sftp-shared-resources-ssh-keys
            defaultMode: 0600
      containers:
        - name: sftp-shared-resources
          image: atmoz/sftp:debian
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          volumeMounts:
            - mountPath: /etc/sftp/users.conf
              name: sftp-shared-resources-user-configuration
              subPath: users.conf
              readOnly: true
            - mountPath: /etc/sftp.d/bindmount.sh
              name: sftp-shared-resources-user-configuration
              subPath: bindmount.sh
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
          resources: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sftp-shared-resources-user-configuration
data:
  users.conf: |
    developer:nottherealpassword:1001:100:resources
    automatonsample:nottherealpassword:1002:101:resources
  bindmount.sh: |
    #!/bin/bash
    function bindmount() {
        if [ -d "$1" ]; then
            mkdir -p "$2"
        fi
        mount --bind $3 "$1" "$2"
    }
    mkdir -p /data/resources
    chown -R 1001:100 /data/resources
    chmod -R g+r /data/resources
    bindmount /data/resources /home/developer/resources
    bindmount /data/resources /home/automatonsample/resources --read-only
```
In AKS, in keeps crashing with the following logs:
```
[/entrypoint] Running /etc/sftp.d/bindmount.sh ...
mount: mount /data/resources on /home/developer/resources failed: Permission denied
mount: cannot mount /data/resources read-only
/entrypoint: Error on line 81: $f
```

**What you expected to happen**:

It works fine on my local Kubernetes (supplied with Docker) on Windows 10, so I'm expecting it to works like a charm on AKS 😄 More seriously, I don't understand why it can't start.

**How to reproduce it (as minimally and precisely as possible)**:

Just apply this deployment in AKS ! Something like `kubectl apply -f ./sftp-shared-resources.yaml`.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?) 3 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): HTTP microservices and Java apps
