### ISSUE TITLE
The L series Virtual Machines are now supported?

### ISSUE THREAD

**Issue by patrickmslatteryvt** [Azure/AKS#1039]
In:
https://github.com/Azure/AKS/blame/2019-05-28/CHANGELOG.md#L8
it says:
`The L and M series Virtual Machines are now supported`

@jnoller 
Was this intended to be the L v2 series VMs?
Because when I go to deploy an L series VM only the old L v1 VMs are available in any region I try.
Since the L v1 VMs were previously available to deploy in AKS for at least the past few months, what exactly was supposed to be added in this release?

**Comment by jnoller** [comment]
The following are the SKUs that were added:

        "Standard_L16s",
        "Standard_L16s_v2",
        "Standard_L32s",
        "Standard_L32s_v2",
        "Standard_L4s",
        "Standard_L64s_v2",
        "Standard_L80s_v2",
        "Standard_L8s",
        "Standard_L8s_v2",
        "Standard_M128",
        "Standard_M128-32ms",
        "Standard_M128-64ms",
        "Standard_M128m",
        "Standard_M128ms",
        "Standard_M128s",
        "Standard_M16-4ms",
        "Standard_M16-8ms",
        "Standard_M16ms",
        "Standard_M32-16ms",
        "Standard_M32-8ms",
        "Standard_M32ls",
        "Standard_M32ms",
        "Standard_M32ts",
        "Standard_M64",
        "Standard_M64-16ms",
        "Standard_M64-32ms",
        "Standard_M64ls",
        "Standard_M64m",
        "Standard_M64ms",
        "Standard_M64s",
        "Standard_M8-2ms",
        "Standard_M8-4ms",
        "Standard_M8ms",

**Comment by patrickmslatteryvt** [comment]
Hmm, the L v2's are definitely in that list, we were looking for the "Standard_L8s_v2" in particular, which I see listed.

Do we have to do anything special to make them show up in our subscriptions?
I went through every region in the US and Europe and I only get offered the old L v1 VMs

**Comment by jnoller** [comment]
@patrickmslatteryvt I suspect that this is a restriction at the subscription level - if you open a general or quota related support ticket, they should be able to enable that VM type for the subscription. I'll also ask on my end - are you creating via the portal, or CLI? `az vm list-skus -l <region> | grep name` should show the VM skus available to your subscription in the region

**Comment by patrickmslatteryvt** [comment]
Generally when there is a subscription level restriction the VM models show up as being greyed out or with a note that there is insufficient quota or they are not available in that region, in my case I see nothing at all in the list when I filter it for the Lv2's when selecting a VM for AKS.
There was a basic level of 10 vCPUs of Lv2 enabled for the subscription, which I increased to 25 and that did nothing.
The portal will allow me to create a plain Linux VM with the L8s_v2 so the subscription certainly supports them.
I was trying through the portal but I'll try via the CLI as you suggest.
Thanks

**Comment by patrickmslatteryvt** [comment]
```
az vm list-skus --subscription=v8t-sub --location=eastus --all=true --size=Standard_L8s_v2 --output=yaml
- apiVersions: null
  capabilities:
  - name: MaxResourceVolumeMB
    value: '1811981'
  - name: OSVhdSizeMB
    value: '1047552'
  - name: vCPUs
    value: '8'
  - name: HyperVGenerations
    value: V1,V2
  - name: MemoryGB
    value: '64'
  - name: MaxDataDiskCount
    value: '16'
  - name: LowPriorityCapable
    value: 'True'
  - name: PremiumIO
    value: 'True'
  - name: vCPUsAvailable
    value: '8'
  - name: CachedDiskBytes
    value: '32212254720'
  - name: EphemeralOSDiskSupported
    value: 'False'
  capacity: null
  costs: null
  family: standardLSv2Family
  kind: null
  locationInfo:
  - location: eastus
    zones:
    - '3'
  locations:
  - eastus
  name: Standard_L8s_v2
  resourceType: virtualMachines
  restrictions:
  - reasonCode: NotAvailableForSubscription
    restrictionInfo:
      locations:
      - eastus
      zones:
      - '1'
      - '2'
      - '3'
    type: Zone
    values:
    - eastus
  size: L8s_v2
  tier: Standard
```

I've taken it up with our TAM.
Thanks
