### ISSUE TITLE
Why 2 nodes has different memory limit?

### ISSUE THREAD

**Issue by ifle** [Azure/AKS#1067]
I have cluster with 2 nodes D2 V3 - 8GB memory
Why the one node has 2.133 Gb memory limit and second 550 Mb?

![image](https://user-images.githubusercontent.com/1140474/59943321-9e03bc80-946a-11e9-8150-fdb1862440b7.png)

**Comment by bhicks329** [comment]
I believe that will be the total of the limit ranges set on the pods running on the nodes. 

https://kubernetes.io/docs/concepts/policy/limit-range/

**Comment by ifle** [comment]
Thanks for your answer.
It's not clear for me, where is defined resource limit for node? I have reource limit for pod

I have :

- 2 nodes, each node is  D2-V3 8 GB Ram
- 1 Pod with 2 replicas.

I defined memory limit for my container
```
resources:
          requests:
            memory: "500Mi"        
          limits:
            memory: "6Gi"
```
I expect that limits of nodes should be identical. 
I see that my pods runs on first node and memory limit is 161%
![image](https://user-images.githubusercontent.com/1140474/59962788-abfd2000-94f2-11e9-95e6-eb645ea4b1cf.png)

What is wrong?
Sorry, I'm new in AKS and Kubernetes
