### ISSUE TITLE
Unable to use existing Load Balancer

### ISSUE THREAD

**Issue by dbourcet** [Azure/AKS#1071]
**What happened**:

I created a AKS cluster with Terraform. I want the cluster to have a LoadBalancer and a static public IP, and I want those to be pre-existing to my Ingress Controller / LoadBalancer Service definitions, as I don't want them to be created/deleted dynamically by Kubernetes manifests.

So I also created with Terraform a LoadBalancer and a static public IP, in the node resource group and with SKU basic, according to the [documentation recommendations](https://docs.microsoft.com/bs-cyrl-ba/azure/aks/static-ip), and attached the public IP to the LB.

Then I created a service of type LoadBalancer:
```yaml
---                                                                                                                                                                                                                                            
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  type: LoadBalancer
  loadBalancerIP: 8.8.8.8 (the public static IP allocated by Terraform, 8.8.8.8 is a fake example)
  selector:
    name: my-pods-selector
  ports:
    - name: my-port
      protocol: TCP 
      port: 1234
      targetPort: 1234
```

**What you expected to happen**:

The service ends up by running correctly.

But instead, the service is stuck in the PENDING state, and a `describe` give me this:
```bash
$ kubectl describe svc my-service
[...]
Events:
  Type     Reason                      Age               From                Message
  ----     ------                      ----              ----                -------
  Normal   EnsuringLoadBalancer        5s (x9 over 15m)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  4s (x9 over 15m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service my-service: timed out waiting for the condition
```

**How to reproduce it (as minimally and precisely as possible)**:

Create an AKS cluster, an LB and a public static IP in the cluster node resource group, attach the public IP to the LB, apply the service manifest above and see that the service is stuck in PENDING, with this error in the `describe` section:
```bash
Error creating load balancer (will retry): failed to ensure load balancer for service my-service: timed out waiting for the condition
```

**Anything else we need to know?**:

If not pre-creating the LoadBalancer but only the public IP, the LoadBalancer is created dynamically and everything is going well.

Question is: **how-to make Azure successfully (which configuration parameter am I missing?) use the pre-existing LB?**

**Environment**:
- Kubernetes version: 1.13.5
- Size of cluster: 3 nodes
