### ISSUE TITLE
Somehow two containers, in different namespaces,  have the same AzureDisk mounted.

### ISSUE THREAD

**Issue by rtyler** [Azure/AKS#110]
I recently upgraded to 1.8.2 and have discovered that two containers running as a result of two difference StatefulSets, with two different volume claims, have the exact same filesystem mounted.

Embedded below are the object definitions for the StatefulSets, but the characteristics which have me baffled are:

* These are in two different namespcaes
* The volumes have an Access Mode of `ReadWriteOnce` (so this should be impossible right?)
* The volumes claims are named differently.
* The two containers are scheduled on the same node,, but there are two other containers which are similiarly provisioned on the node which are _not_ exhibiting this shared-azuredisk-behavior.

Despite these qualities, I have exec'd into both containers and found that they share the same filesystem mounted at `/var/jenkins_home`

I have no idea how this is possible, but I'm guessing the AzureDisk StorageClass might have a gnarly bug hiding in it.

```yaml
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: "jenkins-abayer"
      namespace: "jenkins-abayer"
      labels:
        name: "jenkins-abayer"
    spec:
      serviceName: 'jenkins-abayer'
      replicas: 1
      selector:
        matchLabels:
          app: 'jenkins-abayer'
      volumeClaimTemplates:
        - metadata:
            name: "jenkins-abayer"
            namespace: "jenkins-abayer"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
      template:
        metadata:
          labels:
            app: 'jenkins-abayer'
            owner: 'abayer'
            kind: 'master'
          annotations:
        spec:
          securityContext:
            fsGroup: 1000
            # https://github.com/kubernetes/kubernetes/issues/2630#issuecomment-344091454
            runAsUser: 0
          containers:
            - name: "jenkins-abayer"
              image: "codevalet/master:latest"
              imagePullPolicy: Always
              ports:
                - containerPort: 80
                  name: http
                - containerPort: 50000
                  name: jnlp
              resources:
                requests:
                  memory: 384M
                limits:
                  memory: 1G
              volumeMounts:
                - name: "jenkins-abayer"
                  mountPath: "/var/jenkins_home"
```

```yaml
  - apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      name: "jenkins-jruby-gradle"
      namespace: "jenkins-jruby-gradle"
      labels:
        name: "jenkins-jruby-gradle"
    spec:
      serviceName: 'jenkins-jruby-gradle'
      replicas: 1
      selector:
        matchLabels:
          app: 'jenkins-jruby-gradle'
      volumeClaimTemplates:
        - metadata:
            name: "jenkins-jruby-gradle"
            namespace: "jenkins-jruby-gradle"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
      template:
        metadata:
          labels:
            app: 'jenkins-jruby-gradle'
            owner: 'jruby-gradle'
            kind: 'master'
          annotations:
        spec:
          securityContext:
            fsGroup: 1000
            # https://github.com/kubernetes/kubernetes/issues/2630#issuecomment-344091454
            runAsUser: 0
          containers:
            - name: "jenkins-jruby-gradle"
              image: "codevalet/master:latest"
              imagePullPolicy: Always
              ports:
                - containerPort: 80
                  name: http
                - containerPort: 50000
                  name: jnlp
              resources:
                requests:
                  memory: 384M
                limits:
                  memory: 1G
              volumeMounts:
                - name: "jenkins-jruby-gradle"
                  mountPath: "/var/jenkins_home"
```

**Comment by andyzhangx** [comment]
hi @rtyler, could you 
1. run `kubectl get pvc --all-namespaces`  to show these two PVCs 
2. Check whether these two disks are attached into this agent VM
3. follow below link to collect info:
https://github.com/andyzhangx/Demo/blob/master/linux/azuredisk/azuredisk-attachment-debugging.md
And point out which path is your disk?
Recently I fixed a [issue](https://github.com/kubernetes/kubernetes/issues/57444) related to device name change after disk attachment, not sure whether your issue is the same.

**Comment by andyzhangx** [comment]
In AKS, there is a shadow resource group(`MC_`+RESOUCE-GROUP-NAME+CLUSTER-NAME+REGION) which contains all your VMs, and follow below link to assign a Public IP to that agent VM first:
https://github.com/andyzhangx/Demo/blob/master/debug/README.md#assign-a-public-ip-to-a-vm-in-azure-portal

**Comment by rtyler** [comment]
@andyzhangx I'll do some probing later today after the usual cavalcade of meetings that litter my workday 😸 

Will report back

**Comment by rtyler** [comment]
From `kubectl get pvc --all-namespaces` it looks like both have disparate volume IDs attached:

```
NAMESPACE              NAME                                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
jenkins-abayer         jenkins-abayer-jenkins-abayer-0               Bound     pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434   5Gi        RWO            managed-premium   36d
jenkins-jruby-gradle   jenkins-jruby-gradle-jenkins-jruby-gradle-0   Bound     pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434   5Gi        RWO            managed-premium   26d
```

At least in my AKS created clusters I am not able to SSH into machines using their existing public IPs despite the fact that NSGs are open for port 22. Perhaps `sshd` isn't running on those buggers by default?

**Comment by rtyler** [comment]
@andyzhangx I'm avoiding killing and recreating these StatefulSets because I would like to help tirage this issue, to  the determine of the end-user service I am provided. Please let me know what kind of diagnostics I can provide.

I'm happy to provide instance information out-of-band if you would like to look at this cluster yourself.

**Comment by andyzhangx** [comment]
@rtyler Thanks. By default, there would be only internal IP for agent VM, and `sshd` should be open, you need to `Click under network\network interface\ip config\enable public IP address` to assign a Public IP to that VM in azure portal,, and also you could check the disks attached to that VM in azure portal, all resources is in that **shadow resource group(MC_+RESOUCE-GROUP-NAME+CLUSTER-NAME+REGION)**. And could you also share the `kubectl describe pod POD-NAME` of those two pods? Thanks.

**Comment by andyzhangx** [comment]
Recently I am investigating such azure disk issue, I will support you as my P1 priority, thanks.

**Comment by rtyler** [comment]
```# tree /dev/disk/azure
/dev/disk/azure
├── resource -> ../../sdb
├── resource-part1 -> ../../sdb1
├── root -> ../../sda
├── root-part1 -> ../../sda1
└── scsi1
    ├── lun0 -> ../../../sdc
    ├── lun1 -> ../../../sdd
    ├── lun2 -> ../../../sde
    └── lun3 -> ../../../sdf
```

```
# lsscsi 
[0:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sda 
[1:0:1:0]    disk    Msft     Virtual Disk     1.0   /dev/sdb 
[3:0:0:0]    disk    Msft     Virtual Disk     1.0   /dev/sdc 
[3:0:0:1]    disk    Msft     Virtual Disk     1.0   /dev/sdd 
[3:0:0:2]    disk    Msft     Virtual Disk     1.0   /dev/sde 
[3:0:0:3]    disk    Msft     Virtual Disk     1.0   /dev/sdf 
[5:0:0:0]    cd/dvd  Msft     Virtual CD/ROM   1.0   /dev/sr0 
```


Unfortunately `df` is hanging so I cannot report what that should output. I cannot even list `/proc/sys/fs`

**Comment by andyzhangx** [comment]
what about `sudo mount | grep dev`?

**Comment by rtyler** [comment]
```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=14389388k,nr_inodes=3597347,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
/dev/sda1 on / type ext4 (rw,relatime,discard,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
/dev/sdb1 on /mnt type ext4 (rw,relatime,data=ordered)
lxcfs on /var/lib/lxcfs type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
/dev/sda1 on /var/lib/kubelet type ext4 (rw,relatime,discard,data=ordered)
/dev/sda1 on /var/lib/docker/overlay2 type ext4 (rw,relatime,discard,data=ordered)
shm on /var/lib/docker/containers/1f4914ea79b42b75699c188ce4311f0f54e28b6bbeac9b22e6237219c52f3a53/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/6522a5315ed80d50e547132bf5ab3641d7aec3a6adddba581169dce8f8d3a273/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/88b928e0c11ec86de0cc67bd210b750f6d049c678898082f16e23b9688b3cb64/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/796ef3233c12fd35c62b7d80e622301fa47b400780d3f567c9d2d9092e9c241e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/d6c03d42f38b8612693943566916786dbdacf66526904361367dc977abb44427/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/ddb21b060c8873438fcf38687cdaaf3cfdb3b02ac8b0c8725b9c82ae2179a078/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/c6058bbc7b48d42f92eda821e76a22491464c4bb302eac69626cebe0330ec415/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/34e29a31daf2f62de6136157ab0fdc27a72ebd989226bd14908b06aa7edc101a/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
shm on /var/lib/docker/containers/bdaac3162f59f70998fa82e0f769623739ac98770ab3f35b220da00f5d74832b/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
/dev/sdd on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m1118824185 type ext4 (rw,relatime,data=ordered)
/dev/sdd on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m1118824185 type ext4 (rw,relatime,data=ordered)
/dev/sdd on /var/lib/kubelet/pods/43054f22-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-1ec939bf-d7d8-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
/dev/sdd on /var/lib/kubelet/pods/43054f22-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-1ec939bf-d7d8-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
shm on /var/lib/docker/containers/a193acd416cc297e8fae8609c111232ab62ff2f80637c8051364b3463c596b46/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m2107505330 type ext4 (rw,relatime,data=ordered)
/dev/sdc on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m2107505330 type ext4 (rw,relatime,data=ordered)
/dev/sdc on /var/lib/kubelet/pods/7e9cc117-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-4168e588-df8d-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
/dev/sdc on /var/lib/kubelet/pods/7e9cc117-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-4168e588-df8d-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
shm on /var/lib/docker/containers/02a8554d2d2f45132d32620a4185e174e2768af17037ec05301479ca327c4e1e/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
/dev/sde on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3609723133 type ext4 (rw,relatime,data=ordered)
/dev/sde on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3609723133 type ext4 (rw,relatime,data=ordered)
/dev/sde on /var/lib/kubelet/pods/0f1e332c-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
/dev/sde on /var/lib/kubelet/pods/0f1e332c-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
shm on /var/lib/docker/containers/327d887c058a89793df196acd724ec29fb1ba91c7d3ea36bdf9551e05e287433/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
/dev/sde on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3170516566 type ext4 (rw,relatime,data=ordered)
/dev/sde on /var/lib/kubelet/plugins/kubernetes.io/azure-disk/mounts/m3170516566 type ext4 (rw,relatime,data=ordered)
/dev/sde on /var/lib/kubelet/pods/c238a1f4-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
/dev/sde on /var/lib/kubelet/pods/c238a1f4-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434 type ext4 (rw,relatime,data=ordered)
shm on /var/lib/docker/containers/59790d40b6ae4646b4dea6fa75265f5495283a4466d72e4b91d5bfc395e0ea21/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=2879908k,mode=700,uid=1000,gid=1000)
```

**Comment by andyzhangx** [comment]
And which disk is `jenkins-abayer-jenkins-abayer-0` or `jenkins-jruby-gradle-jenkins-jruby-gradle-0`?
could you also check whether these two disks are attached to that VM in azure portal? You could check by volume name `pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434` and `pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434`, thanks.

**Comment by andyzhangx** [comment]
according to your logs, `/dev/sde` is the disk that has issue? you could check files under `/var/lib/kubelet/pods/c238a1f4-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434` and `/var/lib/kubelet/pods/0f1e332c-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434`, actually they both point to `/dev/sde`

**Comment by andyzhangx** [comment]
could you also collect kubelet logs from that VM? follow:
https://github.com/andyzhangx/Demo/tree/master/debug#q-how-to-get-k8s-kubelet-logs-on-linux-agent

**Comment by rtyler** [comment]
[kubelet logs](https://gist.github.com/rtyler/8aac168b62a4dbc47045ed326901f89e)

**Comment by rtyler** [comment]
@andyzhangx The files are in fact identical between `/var/lib/kubelet/pods/0f1e332c-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434` and `/var/lib/kubelet/pods/c238a1f4-f239-11e7-985e-0a58ac1f148f/volumes/kubernetes.io~azure-disk/pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434/`

**Comment by andyzhangx** [comment]
@rtyler  could you point out which disk is `pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434` and which disk is `pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434`? You could check that in azure portal under VM\disks, and check according to disk name which should be following two:
```
pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434 
pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434
```
And tell me the LUN number.

**Comment by rtyler** [comment]
* pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434  - LUN 3
* pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434  - LUN 2

**Comment by andyzhangx** [comment]
so the volume `pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434 - LUN 3` is never used, and I observed in kubelet logs that k8s was trying to attach this volume `pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434` to VM, and failed to lots of times(see below logs). Do you know is it the time between the `Intel CPU Azure update`?

```
E0105 16:54:29.622685    7560 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/azure-disk//subscriptions/0ee859ed-0f8b-45c0-b61c-011a254f5736/resourceGroups/MC_codevalet_codevalet_eastus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434\"" failed. No retries permitted until 2018-01-05 16:54:45.622656946 +0000 UTC (durationBeforeRetry 16s). Error: Volume not attached according to node status for volume "pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434" (UniqueName: "kubernetes.io/azure-disk//subscriptions/0ee859ed-0f8b-45c0-b61c-011a254f5736/resourceGroups/MC_codevalet_codevalet_eastus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434") pod "jenkins-abayer-0" (UID: "0f1e332c-f239-11e7-985e-0a58ac1f148f") 
```

**Comment by rtyler** [comment]
@andyzhangx Indede I suspect that this occurred around the time of the rolling Spectre reboots.

**Comment by andyzhangx** [comment]
@rtyler could you also provide controller-manager logs? Thanks.
```
kubectl logs `kubectl get po --all-namespaces | grep controller-manager | cut -d ' ' -f4` --namespace=kube-system >> controller-manager.log
```

**Comment by rtyler** [comment]
There is no `controller-manager` in this environment?

```
kube-system            heapster-75667786bb-bdccv                   2/2       Running   0          5d
kube-system            kube-dns-v20-6c8f7f988b-7wg74               3/3       Running   0          5d
kube-system            kube-dns-v20-6c8f7f988b-zq7fs               3/3       Running   0          5d
kube-system            kube-proxy-g5ksv                            1/1       Running   0          5d
kube-system            kube-proxy-l97vt                            1/1       Running   0          5d
kube-system            kube-proxy-p5jkq                            1/1       Running   0          5d
kube-system            kube-svc-redirect-7nps2                     1/1       Running   0          5d
kube-system            kube-svc-redirect-ggz4c                     1/1       Running   0          5d
kube-system            kube-svc-redirect-qgvhr                     1/1       Running   0          5d
kube-system            kubernetes-dashboard-6fc8cf9586-4xnkx       1/1       Running   2          5d
kube-system            tunnelfront-7797c9df77-fh2ch                1/1       Running   0          5d
```

**Comment by rtyler** [comment]
@andyzhangx have we learned all we can from this broken envifonrment? I would like to reprovision these StatefulSets and try to return services for these two applications today.

**Comment by andyzhangx** [comment]
@weinong do you know a workaround to get controller-manager logs from master node? I still like to get conroller manager logs if possible

**Comment by andyzhangx** [comment]
@rtyler thanks for providing all info. I have collected all necessary info from agent node, while according to my investigation, the issue is in controller-manager code, the two pods will first get an available LUN number and then begin to AttachDisk, it seems that the two pods both get the same LUN 2 and both AttachDisk succeeded finally. Next I will try to repro on my env. Thanks.

Just paste the usualful info here, below two pods returned same `DevicePath "2"` from master, which uses same LUN2 disk.

disk `jenkins-abayer-0`:
```
I0105 17:01:40.934526    7560 operation_generator.go:416] MountVolume.WaitForAttach entering for volume "pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434" (UniqueName: "kubernetes.io/azure-disk//subscriptions/0ee859ed-0f8b-45c0-b61c-011a254f5736/resourceGroups/MC_codevalet_codevalet_eastus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-06ede6bc-d7d8-11e7-93c3-0a58ac1f0434") pod "jenkins-abayer-0" (UID: "0f1e332c-f239-11e7-985e-0a58ac1f148f") DevicePath "2"
```

disk `jenkins-jruby-gradle-0`:
```
I0105 17:03:24.436750    7560 operation_generator.go:416] MountVolume.WaitForAttach entering for volume "pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434" (UniqueName: "kubernetes.io/azure-disk//subscriptions/0ee859ed-0f8b-45c0-b61c-011a254f5736/resourceGroups/MC_codevalet_codevalet_eastus/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-f1622750-dfa2-11e7-93c3-0a58ac1f0434") pod "jenkins-jruby-gradle-0" (UID: "c238a1f4-f239-11e7-985e-0a58ac1f148f") DevicePath "2"
I0105 17:03:26.006619    7560 azure_common_linux.go:160] azureDisk - Disk /dev/sde already formatted, will not format
```

**Comment by rtyler** [comment]
@andyzhangx So I'm clear to delete these two StatefulSets and re-deploy them?

**Comment by andyzhangx** [comment]
yes, thanks.

**Comment by joaocc** [comment]
I have something "similar" in nature. Files from one pod on an AzureDisk are seen in another pod. Worse yet, I just removed the disk that was supposed to be mounted on one of these pods, and kubernetes didn't complain!
These are managed disks created manually, and mounted via AzureDisk.
Any hints?

**Comment by andyzhangx** [comment]
@joaocc could you provide following info:
 - k8s version
 - `kubectl get no NODE-NAME -o yaml > a.log`
 - `sudo df -aTH | grep dev` on the node in problem

We fixed a azure disk race condition issue which could be related to this issue:
 - PR [fix race condition issue when detaching azure disk](https://github.com/kubernetes/kubernetes/pull/60183) has fixed this issue by add a lock before DetachDisk

| k8s version | fixed version |
| ---- | ---- |
| v1.6 | no fix since v1.6 does not accept any cherry-pick |
| v1.7 | 1.7.14 |
| v1.8 | 1.8.9 |
| v1.9 | 1.9.5 |
| v1.10 | 1.10.0 |

Details could be found here:
https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#1-disk-attach-error

**Comment by joaocc** [comment]
Hi.
I'm using v1.9.6 installed from scratch.
I have since removed all the services/deployments/pods and restarted the machine.
I am trying redeploy and reproduce.

**Comment by joaocc** [comment]
Also, just confirmed that the container (db) writing to the deleted disk was indeed writing to another disk that was mounted on another container (mgo), even though they are different pods and deployments (but same node).
This is really unexpected... I will have to redeploy and reinstall this second container.

**Comment by joaocc** [comment]
Hi. I was not able to repro. Once the machine booted, things went back to normal. 
Sorry I could not collect the data then.

**Comment by andyzhangx** [comment]
you could email me: `xiazhang@microsoft.com`, provide me following info:
 -  k8s version
 - `kubectl get no NODE-NAME -o yaml > a.log`  on master
 - `sudo sudo df -aTH | grep dev` on the node in problem
 - `tree /dev/disk/azure` on the node in problem

**Comment by joaocc** [comment]
@andyzhangx I have tried the workaround (cachingMode: None) as per https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#2-disk-unavailable-after-attachdetach-a-data-disk-on-a-node

After removing all deployments, waiting for all disks to be unmounted, I redeployed all configs again.
Overlapping is happening again!

This is really bad!
Data becomes corrupted with folders from one pod becoming mixed with those of another!

**Comment by andyzhangx** [comment]
hi @joaocc , could you provide same debugging info again? and also provide your config, I would like to repro in my env, it looks like it's an easy repro which is good for fix. Thanks.

**Comment by joaocc** [comment]
ok. i'll try to pack and send via pm.

**Comment by andyzhangx** [comment]
Hi @joaocc , I tried to use following statefulset config to repro, while finally it works well. If `cachingMode` is set as `None`, dev name sequence would be like following:
```
azureuser@k8s-agentpool-88970029-0:~$ sudo tree /dev/disk/azure/
...
â””â”€â”€ scsi1
    â”œâ”€â”€ lun0 -> ../../../sdc
    â”œâ”€â”€ lun1 -> ../../../sdd
    â”œâ”€â”€ lun2 -> ../../../sde
    â”œâ”€â”€ lun3 -> ../../../sdf
    â”œâ”€â”€ lun4 -> ../../../sdg
    â”œâ”€â”€ lun5 -> ../../../sdh
    â”œâ”€â”€ lun6 -> ../../../sdi
    â””â”€â”€ lun7 -> ../../../sdj
```

could you recheck on azure portal whether your `cachingMode` of azure data disk is set as `None`? thanks.

**Comment by andyzhangx** [comment]
Update:
Actually I tried 6 times totally for both statefulset and deployment config, 8 pods with one disk each, did not repro this issue.
 - [statefulset config 8 pods with one disk each](https://github.com/andyzhangx/demo/tree/master/linux/azuredisk/attach-stress-test/statefulset)
 - [deployment config 8 pods with one disk each](https://github.com/andyzhangx/demo/tree/master/linux/azuredisk/attach-stress-test/deployment)

**Up to now, there are two issues(both fixed) I could find out that would lead to this disk conflict issue**
### issue#1: [lack of lock before DetachDisk operation in controller-manager on master node](https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#1-disk-attach-error)

**Fix**
 - PR [fix race condition issue when detaching azure disk](https://github.com/kubernetes/kubernetes/pull/60183) has fixed this issue by add a lock before DetachDisk

| k8s version | fixed version |
| ---- | ---- |
| v1.6 | no fix since v1.6 does not accept any cherry-pick |
| v1.7 | 1.7.14 |
| v1.8 | 1.8.9 |
| v1.9 | 1.9.5 |
| v1.10 | 1.10.0 |

### issue#2: [`cachingmode` of azure disk setting issue](https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#2-disk-unavailable-after-attachdetach-a-data-disk-on-a-node)
please make sure that `cachingmode` is set as 'None' in `VM\disks` setting, otherwise there could be disk device name change in VM running.

 - add `cachingmode: None` in azure disk storage class(default is `ReadWrite`), e.g.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hdd
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Standard_LRS
  kind: Managed
  cachingmode: None
```
