### ISSUE TITLE
Can't create file share with Premium Azure File storage

### ISSUE THREAD

**Issue by EwanNoble** [Azure/AKS#1114]
**What happened**:
PersistentVolumeClaim stuck in pending with errors in events

**What you expected to happen**:
PersistentVolumeClaim created successfully

**How to reproduce it (as minimally and precisely as possible)**:
Storage Class
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefiles-premium
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Premium_LRS
```
RBAC
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:azure-cloud-provider
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
```
PVC
```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefiles-premium
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefiles-premium
  resources:
    requests:
      storage: 5Gi
```

Run `kubectl describe pvc azurefiles-premium`, see following error in events:
```
Warning  ProvisioningFailed  29s  persistentvolume-controller  Failed to provision volume with StorageClass "azurefiles-premium": failed to create share kubernetes-dynamic-pvc-45b115a5-a8a1-11e9-9716-da868e120b27 in account f497a3bc2a89f11e9bbbb16: failed to create file share, err: storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.    
RequestId:cd8d4a7e-701a-0000-53ae-3c65c1000000
Time:2019-07-17T14:45:59.8520804Z, RequestInitiated=Wed, 17 Jul 2019 14:45:59 GMT, RequestId=cd8d4a7e-701a-0000-53ae-3c65c1000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
```

**Anything else we need to know?**:
Storage account is being created successfully, I can see that the cluster is successfully running ListKeys on the storage account

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
```
```
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
2 node pools: 2 nodes in pool 1, 1 node in pool 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Azure Pipelines Agents on Pool 1 (which I'm trying to set up PVC for)
Grafana and Ingress Controllers on Pool 2
