### ISSUE TITLE
Controlling egress ip for pods in AKS with multiple load balancers

### ISSUE THREAD

**Issue by gitkoyot** [Azure/AKS#1116]
Hello,

I have 5 node AKS service with following services and I wanted to control which IP is used for egress for my pods (like this article suggests -> https://docs.microsoft.com/pl-pl/azure/aks/egress )

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-load-balancer-test1
  labels:
    app: multi-load-balancer-test1
spec:
  replicas: 10
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: multi-load-balancer-test1
  template:
    metadata:
      labels:
        app: multi-load-balancer-test1
        role: rolling-update
    spec:
      containers:
      - name: mult-load-balancer-test1
        image: byrnedo/alpine-curl
        imagePullPolicy: Always
        args: ["ifconfig.me"]
---
apiVersion: v1
kind: Service
metadata:
  name: multi-load-balancer-service
  labels:
    app: multi-load-balancer-test1
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
  selector:
    app: multi-load-balancer-test1


apiVersion: v1
kind: Service
metadata:
  name: load-balancer-test1
  labels:
    app: multi-load-balancer-test1
spec:
  type: LoadBalancer
  ports:
    - name: ssh 
      port: 22
  selector:
    app: multi-load-balancer-test1

```

When I deploy It, after some time all pods contain ip of load-balancer-test1. Now If I deploy something similar :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-load-balancer-test2
  labels:
    app: multi-load-balancer-test2
spec:
  replicas: 10
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: multi-load-balancer-test2
  template:
    metadata:
      labels:
        app: multi-load-balancer-test2
        role: rolling-update
    spec:
      containers:
      - name: mult-load-balancer-test2
        image: byrnedo/alpine-curl
        imagePullPolicy: Always
        args: ["ifconfig.me"]
---
apiVersion: v1
kind: Service
metadata:
  name: multi-load-balancer-service
  labels:
    app: multi-load-balancer-test2
spec:
  type: ClusterIP
  ports:
    - name: ssh
      port: 22
  selector:
    app: multi-load-balancer-test2


apiVersion: v1
kind: Service
metadata:
  name: load-balancer-test2
  labels:
    app: multi-load-balancer-test2
spec:
  type: LoadBalancer
  ports:
    - name: ssh 
      port: 22
  selector:
    app: multi-load-balancer-test2

```
I am unable to bind and control egress of multi-load-balancer-test2 pods. They always use ip of load-balancer-test1.

Is this even possible to control egress in such way and if so, than what am I missing ?
