### ISSUE TITLE
When using virtual nodes pods are not created if the Downward API status.podIP value is requested in the yaml file

### ISSUE THREAD

**Issue by matthew-horrocks** [Azure/AKS#1139]
When using virtual nodes, it's not possible to access the [Downward API](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) ```status.podIP``` value.

If you try and use the ```status.podIP``` value in your ```.yaml``` file, the pod ends up in a ```NotFound``` state and another pod is created. This cycle goes on and on and on and on.

```
Matt@Azure:~/2019/examples/staging/selenium$ kubectl create -f selenium-node-chrome-deployment.yaml
deployment.apps/selenium-node-chrome created
matt@Azure:~/2019/examples/staging/selenium$ kubectl get pods -o wide
NAME                                   READY   STATUS    RESTARTS   AGE     IP            NODE                       NOMINATED NODE
selenium-hub-85db86cb-b9pf5            1/1     Running   0          3h53m   10.241.0.4    virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-h8htf   0/1     Pending   0          4s      <none>        virtual-node-aci-linux     <none>
virtual-node-test-57dfdc6fb9-gh9zk     1/1     Running   0          6h41m   10.240.0.10   aks-agentpool-31745675-1   <none>
matt@Azure:~/2019/examples/staging/selenium$ kubectl get pods -o wide
NAME                                   READY   STATUS     RESTARTS   AGE     IP            NODE                       NOMINATED NODE
selenium-hub-85db86cb-b9pf5            1/1     Running    0          3h54m   10.241.0.4    virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-h8htf   0/1     NotFound   0          61s     <none>        virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-sz8mk   0/1     Pending    0          1s      <none>        virtual-node-aci-linux     <none>
virtual-node-test-57dfdc6fb9-gh9zk     1/1     Running    0          6h42m   10.240.0.10   aks-agentpool-31745675-1   <none>
matt@Azure:~/2019/examples/staging/selenium$ kubectl get pods -o wide
NAME                                   READY   STATUS     RESTARTS   AGE     IP            NODE                       NOMINATED NODE
selenium-hub-85db86cb-b9pf5            1/1     Running    0          3h54m   10.241.0.4    virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-h8htf   0/1     NotFound   0          111s    <none>        virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-sz8mk   0/1     Pending    0          51s     <none>        virtual-node-aci-linux     <none>
virtual-node-test-57dfdc6fb9-gh9zk     1/1     Running    0          6h43m   10.240.0.10   aks-agentpool-31745675-1   <none>
matt@Azure:~/2019/examples/staging/selenium$ kubectl get pods -o wide
NAME                                   READY   STATUS     RESTARTS   AGE     IP            NODE                       NOMINATED NODE
selenium-hub-85db86cb-b9pf5            1/1     Running    0          3h58m   10.241.0.4    virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-4fgdk   0/1     NotFound   0          2m2s    <none>        virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-d6mwc   0/1     Pending    0          57s     <none>        virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-h8htf   0/1     NotFound   0          5m3s    <none>        virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-hdq7m   0/1     NotFound   0          3m3s    <none>        virtual-node-aci-linux     <none>
selenium-node-chrome-b6cf75fcf-sz8mk   0/1     NotFound   0          4m3s    <none>        virtual-node-aci-linux     <none>
virtual-node-test-57dfdc6fb9-gh9zk     1/1     Running    0          6h46m   10.240.0.10   aks-agentpool-31745675-1   <none>
matt@Azure:~/2019/examples/staging/selenium$
```

I require the ```status.podID``` as a work around for bug #901 .

**Steps**
With virtual nodes enabled, deploy the following ```.yaml``` file.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  labels:
    app: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome
        ports:
          - containerPort: 5555
          - containerPort: 4444
          - containerPort: 5900
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: HUB_HOST
            value: "selenium-hub.default.svc.cluster.local"
          - name: HUB_PORT
            value: "4444"
          - name: REMOTE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
```

```
matt@Azure:~/2019/examples/staging/selenium$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

```
matt@Azure:~/2019/examples/staging/selenium$ kubectl get nodes
NAME                       STATUS   ROLES   AGE     VERSION
aks-agentpool-31745675-0   Ready    agent   7h29m   v1.12.8
aks-agentpool-31745675-1   Ready    agent   7h29m   v1.12.8
aks-agentpool-31745675-2   Ready    agent   7h29m   v1.12.8
virtual-node-aci-linux     Ready    agent   7h28m   v1.13.1-vk-v0.9.0-1-g7b92d1ee-dev
```
