### ISSUE TITLE
Cannot change default value for --service-node-port-range

### ISSUE THREAD

**Issue by tahovskym** [Azure/AKS#1150]
**What happened**:

I created AKS on Azure and tried to deploy application, but it failed with error:
```
The Service "th-syslog-svc01" is invalid: spec.ports[0].nodePort: Invalid value: 39001: provided port is not in the valid range. The range of valid ports is 30000-32767
```

In AKS doc I can see, that it is possible to set 
...
[--service-cidr]
[--service-principal]
...
but there is no option to specify 
--service-node-port-range
to overwrite kubernetes apiserver default range 30000-32767

**What you expected to happen**:
It will be good to have options to overwrite kube-apiserver default parameters 

**How to reproduce it**:
Create AKS on Azure and try deploy any service with nodePort out of the default node port range
e.g.: 
create test namespaces in kubernetes cluster
```
kubectl create namespace test
```
and deploy try create service resource
```
apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: th-syslog-svc01
  labels:
    product: th
    app: th-cth-syslog
spec:
  type: NodePort
  ports:
  - port: 9001
    nodePort: 39001
    name: mngport1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: v1.13.9
