### ISSUE TITLE
Inconsistency between Azure and Calico NetworkPolicy when combining Ingress and Egress

### ISSUE THREAD

**Issue by NillsF** [Azure/AKS#1158]
**What happened**:
When deploying a combination of Ingress and Egress network policies there is an inconsitency between Calico and Azure NetworkPolicy. Design below:
![design](https://pbs.twimg.com/media/ECSdzj0UwAEayze?format=jpg&name=medium)

Ingress policy on label app=web, allowing traffic from trusted=yes
Egress policy on trusted=yes, allowing egress to env=dev

Behavior:
**Azure NetworkPolicy**: Ingress policy rules, traffic from trusted=yes goes to both env=dev and env=prod
**Calico**: Both policies rule: traffic from trusted=yes only flows to env=dev, not to env=prod. 

**What you expected to happen**:
I expected the Calico behavior. 
**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-curl-1
  labels:
    trusted: "yes"
spec:
  containers:
  - name: busybox
    image: yauritux/busybox-curl
    args:
    - sleep
    - "1000000"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    app: "web"
    env: "dev"
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
  labels:
    app: "web"
    env: "prod"
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy1-allow-trusted-busybox
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          trusted: "yes"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy2-allow-to-dev
spec:
  podSelector:
    matchLabels:
      trusted: "yes"
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          env: dev
```
```bash
kubectl create -f inconsitency.yaml
kubectl get pods -o wide #to get IP addresses
kubectl exec -it busybox-curl-1 sh
curl *ip of nginx-dev* #this should work
curl *ip of nginx-prod* #this works with Azure NetworkPolicy - not with Calico
```

**Anything else we need to know?**:
I believe to be related - but distinct - to #1138 .

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:14:29Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
test cluster, running nginx and busybox
- Others:
