### ISSUE TITLE
Persistent Volumes Claims fail in AKS cluster

### ISSUE THREAD

**Issue by SpicySyntax** [Azure/AKS#1169]
**What happened**:
I setup a static file share mounted on Persistent Volume as described in this [tutorial](https://docs.microsoft.com/en-us/azure/aks/azure-files-volume).
See my source code used for the volumes, claims, and deployments 
at this [Gist](https://gist.github.com/SpicySyntax/1ee3ef06241448fa8205d20de706969a)

However when I deploy (using helm) and add the persistent volume claim to a pod it fails:

```
pod has unbound immediate PersistentVolumeClaims
```

**What you expected to happen**:
The deployment to work and for the pod to be able to access the persisted volume

**How to reproduce it (as minimally and precisely as possible)**:
Using source from [Gist](https://gist.github.com/SpicySyntax/1ee3ef06241448fa8205d20de706969a)
Or following this [tutorial](https://docs.microsoft.com/en-us/azure/aks/azure-files-volume).

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?)
2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Http Microservices + Machine Learning
- Others:
Helm Version:
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}

**Comment by andyzhangx** [comment]
Your PV is not bound to PVC, you could write PV/PVC like following:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: k8stest
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-azuredisk
  storageClassName: ""
```
