### ISSUE TITLE
NetworkPolicy - using named NetworkPolicyPort with azure network policy provider not supported 

### ISSUE THREAD

**Issue by landro** [Azure/AKS#1192]
The following NetworkPolicy works as expected:

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whatever-network-policy
  namespace: whatever
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: netshoot
      ports:
        - port: 8080
          protocol: TCP
  podSelector:
    matchLabels:
      app: mypod
  policyTypes:
    - Ingress
```

whereas the same one, using a named port instead, does not work.

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whatever-network-policy
  namespace: whatever
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: netshoot
      ports:
        - port: http
          protocol: TCP
  podSelector:
    matchLabels:
      app: mypod
  policyTypes:
    - Ingress
```

According to the [NetworkPolicy API spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#networkpolicyport-v1-networking-k8s-io) and the [official Azure docs ](https://docs.microsoft.com/en-us/azure/aks/use-network-policies#differences-between-azure-and-calico-policies-and-their-capabilities), this should be supported.

Apparently, Calico had a [similar issue](https://github.com/projectcalico/libcalico-go/issues/770) in previous versions
