### ISSUE TITLE
Should be able to add https to Kubernetes-Dashboard with auto-generate-certificates

### ISSUE THREAD

**Issue by henrylilei** [Azure/AKS#1198]
**What happened**:
We added an "args: - --auto-generate-certificates" to the kubernetes-dashboard deployment with container port 8443, after changing the livenessProbe to port 8443 and HTTPS scheme, the livenessProbe in this deployment kept changing itself back to 9090 and HTTP.

**What you expected to happen**:
livenessProbe keeps at 8443 and HTTPS.

**How to reproduce it (as minimally and precisely as possible)**:
```
    - args:
        - --auto-generate-certificates
        image: aksrepos.azurecr.io/mirror/kubernetes-dashboard-amd64:v1.10.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: main
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 12

I found a workround by changing the k8s-app label to a different string, and yet this is a bit inconvenient and that cluster-service:true worries me.
