### ISSUE TITLE
NetworkPolicy - Egress is not allowed by default and filtering inbound connections

### ISSUE THREAD

**Issue by desek** [Azure/AKS#1253]
**What happened**:
When applying a NetworkPolicy in a Namespace with only an ingress policy egress network traffic stops working.

**What you expected to happen**:
Only ingress network traffic affected according to policy definition.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: ns1
  name: deny-from-other-namespaces
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```

Run a pod in Namespace ns1 and curl a public website, i.e. http://httpbin.org/status/418

**Anything else we need to know?**:

Using the below allow all egress policy does not work:
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: ns1
  name: deny-from-other-namespaces
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - {}
```

But the below allow all egress works:
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: ns1
  name: deny-from-other-namespaces
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
```

But it also opens up for inter-namespace traffic. Expectation is that ingress rules should block traffic between namespaces. Egress rule should not filter inbound traffic.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
NAME                              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
aks-lowprio-29327172-vmss000002   856m         21%    7305Mi          57%       
aks-lowprio-29327172-vmss000003   690m         17%    8047Mi          63%       
aks-lowprio-29327172-vmss000004   785m         20%    7671Mi          60%    

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

httpbin services in each namespace for testing.

- Others:
AKS deployed with networkPlugin=azure and networkPolicy=azure

**Comment by sauryadas** [comment]
@aanandr can you please take a look?

**Comment by shibshibw** [comment]
I ran into the similar probelm.
If a policy which contains "podSelector: {}" but does not contain Ingress nor Egress,
all out-bound communications are blocked.
This problem reproduced only when used Azure Network Policies.

Results
-  Bad : Azure AKS 1.15.3 + Azure Network Policies
-  Bad : Azure AKS 1.14.6 + Azure Network Policies
-  Okay : Azure AKS 1.14.6 + Calico
-  Okay : AWS EKS 1.14.6 + Calico
-  Okay : Google GKE 1.14.6 + Calico
-  Okay : Kubernetes 1.16.1 + Calico
-  Okay : Kubernetes 1.16.1 + WeaveNet
-  Okay : Kubernetes 1.16.1 + Kube-Router

Reproduction
Manifest:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-ingress-deny-all
spec:
  podSelector: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: c1
    image: nginx
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64
```

Command:
```
kubectl delete netpol --all
kubectl apply -f p.yaml
kubectl exec -it p1  apt update  # Fails
```
