### ISSUE TITLE
AKS autoscaler not scaling

### ISSUE THREAD

**Issue by jemag** [Azure/AKS#1256]
**What happened**:
Scheduled 9 pods above cluster resource limit, and although they are all pending no node is being added.
![image](https://user-images.githubusercontent.com/7985687/66318504-6e79a280-e8e9-11e9-9e93-c429bc7cb064.png)

**What you expected to happen**:
Cluster autoscaler should add a node in response to the failed scheduling due to insufficient resources.

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster version 1.14.6 with autoscaling enabled (min count 3, max count 4), and add more pods than there are resources.

**az aks show output**:

``` yaml
aadProfile:
  clientAppId: XXXX
  serverAppId: XXXX
  serverAppSecret: null
  tenantId: XXXXXXXX
addonProfiles:
  omsagent:
    config:
      logAnalyticsWorkspaceResourceID: /subscriptions/XXXXXXXX
    enabled: true
agentPoolProfiles:
- availabilityZones: null
  count: 3
  enableAutoScaling: true
  enableNodePublicIp: null
  maxCount: 4
  maxPods: 30
  minCount: 3
  name: default
  nodeTaints: null
  orchestratorVersion: 1.14.6
  osDiskSizeGb: 30
  osType: Linux
  provisioningState: Succeeded
  scaleSetEvictionPolicy: null
  scaleSetPriority: null
  type: VirtualMachineScaleSets
  vmSize: Standard_DS2_v2
  vnetSubnetId: /subscriptions/XXXXXXXXXX
apiServerAccessProfile: null
dnsPrefix: XXXXXXX
enablePodSecurityPolicy: false
enableRbac: true
fqdn: XXXXXXX
identity: null
kubernetesVersion: 1.14.6
linuxProfile: null
location: canadacentral
maxAgentPools: 1
name: XXXXX
networkProfile:
  dnsServiceIp: 192.168.0.10
  dockerBridgeCidr: 172.17.0.1/16
  loadBalancerProfile: null
  loadBalancerSku: Basic
  networkPlugin: azure
  networkPolicy: azure
  podCidr: null
  serviceCidr: 192.168.0.0/24
nodeResourceGroup: XXXX
provisioningState: Succeeded
resourceGroup: XXXX
servicePrincipalProfile:
  clientId: XXXXXXXX
type: Microsoft.ContainerService/ManagedClusters
windowsProfile: null

```

**Logs**
No logs appear with either log analytics stream or archiving to a storage account despite being activated (kube-apiserver worked when activated).
![image](https://user-images.githubusercontent.com/7985687/66318317-1347b000-e8e9-11e9-9f45-5e559aab959a.png)

**Other**
Not sure if this is how it should be, but despite creating the cluster with autoscaling the VMSS scaling is still set to manual:
![image](https://user-images.githubusercontent.com/7985687/66318460-57d34b80-e8e9-11e9-98c2-539831d69270.png)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.6
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : java microservices
- Others:
