### ISSUE TITLE
Azure-file provider expected storage account resource group

### ISSUE THREAD

**Issue by decoverri** [Azure/AKS#1263]
**What happened**:
PVC that uses storage class with provider kubernetes.io/azure-file looks for a storage account in the automatically created resource group (MC_resource-group_aks-name_location).

**What you expected to happen**:
It should look for the storage account in the same resource group as the aks resource.

**How to reproduce it (as minimally and precisely as possible)**:
Create a storage class and pvc.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: accountname
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-name
spec:
  storageClassName: azurefile
```

It will show the error
Warning    ProvisioningFailed  persistentvolume-controller  Failed to provision volume with StorageClass "azurefile": could not get storage key for storage account accountname: could not get storage key for storage account accountname: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Storage/storageAccounts/accountname' under resource group **'mc_resource-group_aks-name_location'** was not found."

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6

**Comment by andyzhangx** [comment]
@decoverri Since you have specified account name in your azurefile storage class, aks have to find that storage account name. If you want to use an arbitrary storage acccount under MC_ resource group, pls remove `storageAccount` parameter, AKS will search a suitable storage acccount under MC_ resource group

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: accountname
```

**Comment by decoverri** [comment]
@andyzhangx I want to provide both AKS and the storage account through terraform, so the storage account is NOT on the MC_ resource group, but theres is no option to look for one outside of it. That is my issue

**Comment by andyzhangx** [comment]
@decoverri you could use a storage account from an external resource group:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  resourceGroup: RESOURCE_GROUP_NAME
  storageAccount: accountname
```
