### ISSUE TITLE
nvidia-smi isn't mounted into pod through nvidia runtime

### ISSUE THREAD

**Issue by ydye** [Azure/AKS#1271]
**What happened**:  nvidia-smi isn't mounted into pod on GPU node in aks cluster through nvidia runtime.

**What you expected to happen**: nvidia-smi should be mounted into pod on GPU nodes in aks cluster through nvidia runtime.

**How to reproduce it (as minimally and precisely as possible)**:

create a job and reqeust 1 gpu in gpu aks cluster.

```
# kubectl exec -it samples-tf-mnist-demo-gf4zs sh
#
# nvidia-smi
sh: 27: nvidia-smi: not found
# find / -name nvidia-smi
#
```

Yaml file
```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: samples-tf-mnist-demo
  name: samples-tf-mnist-demo
spec:
  template:
    metadata:
      labels:
        app: samples-tf-mnist-demo
    spec:
      containers:
      - name: samples-tf-mnist-demo
        image: microsoft/samples-tf-mnist-demo:gpu
        command: 
        - "sleep"
        - "10000"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
           nvidia.com/gpu: 1
      restartPolicy: OnFailure
```

The image is from Azure's tutorial. 
https://docs.microsoft.com/en-us/azure/aks/gpu-cluster#run-a-gpu-enabled-workload

**Anything else we need to know?**:

**Environment**: AKS
- Kubernetes version (use `kubectl version`): 
   
v1.15.3

- Size of cluster (how many worker nodes are in the cluster?)  

NC6 * 3

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

When training job, if there is some issue occrus, we hope we could see the gpu status through nvidia-smi. And nvidia runtime should provide the function to mount nvidia-smi, but aks didn't do it.

- Others:
