### ISSUE TITLE
Stuck on creating AKS Internal LB

### ISSUE THREAD

**Issue by al3xisb** [Azure/AKS#1282]
Hello, 

I created a Internal Load Balancer with this yaml (for instance the app run an elasticsearch container) : 
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ek
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-subnet"
  name: ek-elastic
spec:
  selector:
    app: ek
  ports:
  - port: 9200
    name: http-elastic
    protocol: TCP
  type: LoadBalancer
```

IP was corretly assigned :
```
ek-elastic   LoadBalancer   10.0.219.212   10.240.0.8     9200:32103/TCP   21m
```

I tried to : 
- reach the IP within the cluster with a busybox pod (ping or wget on 9200) but the IP was unreachable
- reach the IP through a peered vnet with the AKS vnet. Same behavior (FYI i can reach nodes IP)

Any clue to correct this ?

Some informations :
- the container is up and running. If i exposed it with a external IP (without the annotations), it works perfectly
- aks-subnet is the name of  the subnet (10.240.0.0/16) automaticaly created by Azure (on a specific RG). My nodes IP are 10.240.0.4 to 10.240.0.7
- AKS cluster : 1.14.6
