### ISSUE TITLE
AKS Dashboard problems with 1.14.7

### ISSUE THREAD

**Issue by PirateBread** [Azure/AKS#1285]
We expose the Kubernetes Dashboard via an NGINX Ingress resource, secured with an oauth proxy integration for authentication.

This has been working well, however the upgrade to 1.14.7 has essentially broken this integration and we get constant 500 errors and timeouts. 

When using the **az aks browse** tunnel, the dashboard works smoothly.

**What happened**:
Upgrade to 1.14.7 has broken Dashboard exposed via Ingress.

**What you expected to happen**:
It should work as smoothly as it's being accessed directly without the tunnel.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Ingress to 1.14.7

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kube-system
  labels:
    k8s-app: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx-external
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start"
spec:
  tls:
  - hosts:
    - #{dashboardSubDomain}#.#{environmentDomain}#
    secretName: kubernetes-dashboard
  rules:
  - host: #{dashboardSubDomain}#.#{environmentDomain}#
    http:
      paths:
      - backend:
          serviceName: kubernetes-dashboard
          servicePort: 80
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: {Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:39:02Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster: 2
- Others: Java microservices, very lightly loaded.

We have 8 AKS clusters total, 6 of the clusters which are running **1.14.7** are showing the same problem. 2 of the clusters which we have not upgraded yet, are running **1.14.6** are not showing the problem.
