### ISSUE TITLE
Use realistic resource requirements for Tunnelfront

### ISSUE THREAD

**Issue by epa095** [Azure/AKS#1306]
**What happened**:
I looked at the tunnelfront deployment resource requirements, and it shows 
```yaml
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
```
I do `kubectl describe` on the pod, and I see
```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
```
137 means it has been OOM killed, so the requested memory is to little in certain situations.

**What you expected to happen**:
I expect the requests to reflect what tunnelfront will need in a high-load situation so it does not get killed when the cluster is under pressure.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Size of cluster: 5
- Running argo workflows with a few thousand steps.
