### ISSUE TITLE
Helm chart stable/mssql-linux fails with Sql Server 2019

### ISSUE THREAD

**Issue by giggio** [Azure/AKS#1319]
**What happened**:

If you try to run Sql Server 2019 on AKS using the Helm Chart `stable/mssql-linux` it fails. 2017 run fine.

**What you expected to happen**:

To run like 2017 runs.

**How to reproduce it (as minimally and precisely as possible)**:

Create the namespace:

````bash
kubectl create namespace sql
````

Create the PVCs:

````bash
  for data in data log backup master; do
    pvcname=pvc-mssql-$data
    cat <<EOF | kubectl apply -f -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: $pvcname
  namespace: sql
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
EOF
````

Create the release with Helm:

````
cat <<EOF | helm upgrade sql stable/mssql-linux --install --namespace sql --version 0.10.1 --wait --values -
image:
  repository: mcr.microsoft.com/mssql/server
#  tag: 2017-latest-ubuntu
  tag: 2019-GA-ubuntu-16.04
acceptEula:
  value: 'Y'
edition:
  value: developer
persistence:
  enabled: true
  existingDataClaim: pvc-mssql-data
  existingTransactionLogClaim: pvc-mssql-log
  existingBackupClaim: pvc-mssql-backup
  existingMasterClaim: pvc-mssql-master
EOF
````

**Anything else we need to know?**:

The Helm Chart works on my local Docker for Windows Kubernetes cluster, so it seems the problem is the chart on AKS.

Related issue: https://github.com/helm/charts/issues/18929

**Environment**:

- Kubernetes version (use `kubectl version`):
````
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}   
````
- Size of cluster: 1 node (dev cluster)
- General description of workloads in the cluster: .NET Microservices, an Istio mesh etc.
- Helm:
````
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}     
````

**Comment by giggio** [comment]
I did a little digging, and this is definitely related to the fact that the chart is mounting the master data file, by setting the env var `MSSQL_MASTER_DATA_FILE` (see https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-ver15#environment-variables).

This is only an issue on AKS, and only when using the 2019 tag. I can't figure out why this is happening.

I tried using azure files instead of azure disks, got the same bad results.

**Comment by giggio** [comment]
Ok, I just tried on a different cluster, now using Helm 3 and a cluster at v1.14.6. Exact same results.

**Comment by squillace** [comment]
File an issue with the chart. Happy to locate the creator if they're inside the firewall and have them follow up.

**Comment by tirelibirefe** [comment]
Look at here.
https://hub.helm.sh/charts/stable/mssql-linux
It's explicitly indicated that stable/mssql-linux helm chart is based on MS SQL 2017 not 2019.
Instead of waitting for Microsoft, maybe you can code your own MS SQL helm chart and share it with the community.

**Comment by squillace** [comment]
that would be great; I'd sign on to have the internal team vet it if you do it

**Comment by pierrepook** [comment]
@squillace I am looking to use the 2019 image and create a chart for the 2019 image. I am happy to create the chart and share it with the community. Does the offer to have it vetted by the internal team still stand? Helm are also deprecating the https://github.com/helm/charts repo so unsure where this should live eventually. Let me know if this is still something that you would be interested in.

**Comment by squillace** [comment]
Yes, I'll get it vetted internally, which will get you "best effort" support. No **initial** commitment from the team for future work, but best effort. In any case, the outcome of the effort I'll post back here. (Note, it's not my team.)

**Comment by squillace** [comment]
Oh, and I do not have an answer yet for location, but I'll ask what they think as well.

**Comment by vin-yu** [comment]
This is likely due to the fact the container is running as non-root by default now.

We made a security improvement with SQL Server 2019 containers to run as a non-root user by default. To get this running in AKS using an external PV, you'll need to add a security context with `fsGroup:10001` (which is the uid of the `mssql` user in the container) in your spec and it should work. 

Example deployment.yaml 

```yaml
apiVersion: apps/v1beta1
   kind: Deployment
   metadata:
     name: mssql-deployment
   spec:
     replicas: 1
     template:
       metadata:
         labels:
           app: mssql
       spec:
         terminationGracePeriodSeconds: 10
         securityContext:
         fsGroup: 10001
         containers:
         - name: mssql
           image: mcr.microsoft.com/mssql/server:2019-latest
           ports:
           - containerPort: 1433
           env:
           - name: MSSQL_PID
             value: "Developer"
           - name: ACCEPT_EULA
             value: "Y"
           - name: MSSQL_SA_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: mssql
                 key: SA_PASSWORD 
           volumeMounts:
           - name: mssqldb
             mountPath: /var/opt/mssql
         volumes:
         - name: mssqldb
           persistentVolumeClaim:
             claimName: mssql-data
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: mssql-deployment
   spec:
     selector:
       app: mssql
     ports:
       - protocol: TCP
         port: 1433
         targetPort: 1433
     type: LoadBalancer
```
