### ISSUE TITLE
AKS - unable to upgrade to apiVersion: apps/v1 from extensions/v1beta1

### ISSUE THREAD

**Issue by rkrgarlapati** [Azure/AKS#1346]
I am unable to upgrade to latest apiVersion apps/v1. Using Azure Kubernetes 1.14.x

new yaml file:

```
---
apiVersion: apps/v1                   --------------> new apiVersion, earlier it was 'extensions/v1beta1'
kind: Deployment
metadata:
  name: myservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
      - name: myservice
        image: myimage
        ports:
        - name: http-api
          containerPort: 8450
        envFrom:
        - configMapRef:
            name: myservice
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 768Mi
      imagePullSecrets:
        - name: my-secret
```

in Kubernetes browser i have clicked on 'View/edit YAML' option, surprisingly i see old apiVersion extensions/v1beta1 :

```

{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",      ------------> old apiVersion
  "metadata": {
    "name": "myservice",
    "namespace": "mynamespace",
    "selfLink": "/apis/extensions/v1beta1/namespaces/mynamespace/deployments/myservice",
    "uid": "bb74f2d6-17f0-11ea-9e6f-6e9ccde05ce1",
    "resourceVersion": "26820687",
    "generation": 1,
    "creationTimestamp": "2019-12-06T06:22:09Z",
    "annotations": {
      "deployment.kubernetes.io/revision": "1",
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"name\":\"myservice\",\"namespace\":\"mynamespace\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"app\":\"myservice\"}},\"strategy\":{\"type\":\"RollingUpdate\"},\"template\":{\"metadata\":{\"labels\":{\"app\":\"myservice\"}},\"spec\":{\"containers\":[{\"envFrom\":[{\"configMapRef\":{\"name\":\"myservice\"}}],\"image\":\"myacr/dev1.1/myservice:v1.0.6552\",\"name\":\"myservice\",\"ports\":[{\"containerPort\":8330,\"name\":\"http-api\"}],\"resources\":{\"limits\":{\"memory\":\"1Gi\"},\"requests\":{\"memory\":\"768Mi\"}}}],\"imagePullSecrets\":[{\"name\":\"mynamespace\"}]}}}}\n"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "myservice"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "myservice"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "myservice",
            "image": "myacr/dev1.1/myservice:v1.0.6552",
            "ports": [
              {
                "name": "http-api",
                "containerPort": 8330,
                "protocol": "TCP"
              }
            ],
            "envFrom": [
              {
                "configMapRef": {
                  "name": "myservice"
                }
              }
            ],
            "resources": {
              "limits": {
                "memory": "1Gi"
              },
              "requests": {
                "memory": "768Mi"
              }
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "imagePullSecrets": [
          {
            "name": "mynamespace"
          }
        ],
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 1,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2019-12-06T06:22:17Z",
        "lastTransitionTime": "2019-12-06T06:22:17Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      },
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2019-12-06T06:22:17Z",
        "lastTransitionTime": "2019-12-06T06:22:09Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"myservice-5bcb55c447\" has successfully progressed."
      }
    ]
  }
}
```
