### ISSUE TITLE
Routing Incoming Traffic Through VNet-to-VNet Connection

### ISSUE THREAD

**Issue by matkam** [Azure/AKS#138]
I'm trying to connect a regular Azure VNet with an AKS cluster. I've created a VNet-to-VNet connection on both sides. The AKS cluster is able to route out and connect to the other VNet VMs, the VMs can ping the Kubernetes nodes, but the VMs do not have a route to AKS services.

Is there any way for the external VMs to route through a VNet-to-VNet connection to AKS services?

**Comment by TallOrderDev** [comment]
@matkam did you find a solution for this? I'm doing the same thing now and am at roughly the same spot.

**Comment by OguzPastirmaci** [comment]
Try creating an Azure Internal Load Balancer to expose your service.

Example:

```
apiVersion: v1
kind: Service
metadata:
  name: your-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: your-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9080
    protocol: TCP
    name: httpport
  selector:
    app: your-service


```
