### ISSUE TITLE
Memory leak on Windows nodes, svchost.exe consumed a lot of memory

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1397]
**What happened**:
We observed slowly memory leak on Windows nodes, for example on one Windows node, svchost.exe(a lot of them) used more than 8GB memory(16 GB total).

![Capture](https://user-images.githubusercontent.com/22001089/72714333-8380f580-3ba9-11ea-8e8e-27130deb6357.PNG)

**How to reproduce it**:
Nothing special, we ran about 10 pods on each Windows node.

**Environment**:
- Kubernetes version:
1.14.8

- Size of cluster
2 Linux nodes, 3 Windows nodes.

Here is the process list on that Windows node,
[process.txt](https://github.com/Azure/AKS/files/4085427/process.txt)

**Comment by zhiweiv** [comment]
@MikkelHegn 
Do you mind to take a look at this? It can be reproduced constantly.

**Comment by MikkelHegn** [comment]
Thanks for reporting this, let us take a quick look to assess.

**Comment by zhiweiv** [comment]
@MikkelHegn 
Windows support is GA, any updates about this?

**Comment by MikkelHegn** [comment]
We don't see this reported widespread or have observed during validation. However we've got it on the backlog for reproduction and diagnostics.

**Comment by zhiweiv** [comment]
We are running clusters on 1.14.8 with old Windows release. We plan to upgrade to 1.17 at July.

I will post the update if it is still reproduced after that.

**Comment by zhiweiv** [comment]
@MikkelHegn @immuzz  FYI
Issue can be reproduced on AKS 1.17.5 with following yaml on a single node Windows Pool. The total memory of svchost.exe increased about 50MB per day. 
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memtest
  labels:
    app: memtest
spec:
  replicas: 10
  serviceName: headless
  selector:
    matchLabels:
      app: memtest
  template:
    metadata:
      name: memtest
      labels:
        app: memtest
    spec:
      containers:
      - name: web
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      nodeSelector:
        kubernetes.io/os: windows
```
