### ISSUE TITLE
Azure file storage class specify file share

### ISSUE THREAD

**Issue by lgarcia11** [Azure/AKS#1399]
Is it possible to create a StorageClass with the desired storage account and specific a file share?
Maybe something like this?

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  storageAccount: azure_storage_account_name
  **shareName: file_share_name**
```
