### ISSUE TITLE
Traffic from MutatingWebhookConfiguration does not reach Kube cluster through NGINX proxy

### ISSUE THREAD

**Issue by blomquistr** [Azure/AKS#1470]
**What happened**: When registering a MutatingWebhookConfiguration or ValidatingWebhookConfiguration object in an AKS cluster on version 1.15.7 to a public-facing URL that is exposed via a cluster of NGINX servers external to the cluster, traffic from the MutatingWebhookConfiguration does not reach the NGINX cluster.

**What you expected to happen**: Traffic from the control plane should appear in the NGINX logs for the NGINX servers. Traffic should pass from there to the in-cluster NGINX servers, and then be routed to the pod serving the webhook server.

**How to reproduce it (as minimally and precisely as possible)**: including stripped-down versions of the appropriate webserver, deployment, and webhook configuration
**app.py**
```python
#!/usr/bin/env python3

'''
app.py - run me as the webserver
'''
from flask import Flask, Config, request, jsonify
from pprint import pprint
import copy
import logging
import pprint

logging.basicConfig(level=logging.DEBUG)
l = logging.getLogger(__name__)

def _log_debug_output(body):
    l.debug("Logging request body for debugging...")
    clone = copy.deepcopy(body)
    l.debug('-' * 40)
    for line in pprint.pformat(clone).split('\n'):
        l.debug(line)

# constructor for app
def create_app():
    app = Flask(__name__)  

    @app.route('/ping')
    def ping():
        return ("pong", 200)

    @app.route('/admit', methods=['POST'])
    def admit():
        '''
        This endpoint could serve a hypothetical validating admission controller
        '''
        l.info("Received request!")
        _log_debug_output(request.json)

    @app.route('/mutate', methods=['POST'])
    def mutate():
        '''
        This endpoint could serve a hypothetical mutating admission controller
        '''
        l.info("Received request!")
        _log_debug_output(request.json)
            
    return app

app = create_app()

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=int(os.getenv("PORT", 5001)), debug=True, threaded=True)
```
**requirements.txt**
```requirements.txt
kubernetes
flask
pyyml
dict_recursive_update
jsonpatch
uwsgi
```
**Generic Dockerfile for the app**
```Dockerfile
FROM ubuntu:19.10

RUN export DEBIAN_FRONTEND=noninteractive;\
    apt-get update; apt-get -y install apt-utils\
                                        python3.7\
                                        python3-pip\
                                        python3-pipdeptree\
                                        sudo\
                                        strace\
                                        curl\
                                        nano\
                                        apt-transport-https\
                                        lsb-release

WORKDIR /usr/src/app
COPY . .
RUN pip3 install --no-cache-dir -r requirements.txt

#RUN python3 setup.py install
CMD ["bash", "-c", "python3 app.py"]
```
**deployment yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-webhooks
  namespace: sample-webhooks
data:
  ca.crt: ${your-ca-crt}
  tls.crt: ${your-tls-cert}
  tls.key: ${your-tls-key}
type: kubernetes.io/tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webhooks
  namespace: sample-webhooks
  labels:
    app: sample-webhooks
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sample-webhooks
  template:
    metadata:
      labels:
        app: sample-webhooks
    spec:
      containers:
      - name: sample-webhooks
        image: sample-webhooks:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: '5000'
        ports:
        - containerPort: 5000
        command: ["bash", "-c", "python3 app.py"]
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sample-webhooks
  namespace: sample-webhooks
spec:
  ports:
  - port: 5000
  selector:
    app: sample-webhooks
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: sample-webhooks
  namespace: sample-webhooks
spec:
  tls:
  - hosts:
    - public-webhook-url.yourdomain.com
    secretName: sample-webhooks
  rules:
    - host: public-webhook-url.yourdomain.com
      http:
        paths:
        - backend:
            serviceName: sample-webhooks
            servicePort: 5000
          path: /webhook(/|$)(.*)
```

Once you have a webhook server running in your cluster, first cURL the endpoints to make sure they're alive, then try to create a Service object with kubectl. Logs appear for us when we cURL, but not when we create the Service object.

**Anything else we need to know?**: Our certs are issued using LetsEncrypt. A more fleshed-out implementation of this configuration worked with AKS version 1.14.6 on a nodepool based on Availability Sets, using Azure DNS instead of our NGINX web servers. However, we can successfully cURL the URLs being exposed by our NGINX cluster both internally and from personal devices (i.e., navigate to the URL from a browser on one's cell phone) and get the response back we expect - either a "pong" from the /ping endpoint, or a 405 from either of the two POST URLs. We also see this traffic in our NGINX logs, the cluster NGINX logs, and in the server's logs. We see no traffic at any point when the request is generated with `kubectl apply -f {some-service-yaml}.yaml`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.7
- Size of cluster (how many worker nodes are in the cluster?): 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): operator development / lower environment devops workloads
- Others:
