### ISSUE TITLE
Pods in not ready state caused by K8s issue, requires >= 1.15.8

### ISSUE THREAD

**Issue by jdamata** [Azure/AKS#1472]
**What happened**:
Pods are marked as not ready in container conditions:
```
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   True
  PodScheduled      True
```

This prevents pods from being added as endpoints in services. This is critical as its possible for an entire kubernetes service to be down while pods are running normally.

From reading online i believe the problem occurs when kubelet is unable to communicate to the api server for some period of time. Issues on this problem: https://github.com/kubernetes/kubernetes/issues/84931, https://github.com/kubernetes/kubernetes/issues/53023, https://github.com/kubernetes/kubernetes/issues/82405, https://github.com/kubernetes/kubernetes/issues/85389

The fix is in 1.15.8 here: https://github.com/kubernetes/kubernetes/pull/86195

**Anything else we need to know?**:
This can be fixed by recreating pods.

**Environment**:
- 1.15.7
- 55 node cluster
- java applications

**Comment by jdamata** [comment]
SR opened: 120030424004883

**Comment by djsly** [comment]
We have the same issue. 1.15.7 

```
❯ kubectl get endpoints -n monitoring
NAME                                           ENDPOINTS                                                               AGE
prometheus-operator-grafana                                                                                            121d
prometheus-operator-prometheus                                                                                         121d
```

endpoint info
```
subsets:
- notReadyAddresses:
  - ip: <ip>
    nodeName: <nodename>
    targetRef:
      kind: Pod
      name: prometheus-operator-grafana-7b7d6995cd-mhvj4
      namespace: monitoring
```

pod info
```
status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-03-06T05:28:49Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-03-07T07:12:21Z"
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2020-03-06T05:33:24Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-03-06T05:27:19Z"
      status: "True"
      type: PodScheduled
```
