### ISSUE TITLE
storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by bitsofinfo** [Azure/AKS#1516]
This setup results in the error below 
```

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tekton-azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Premium_LRS

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: tekton-azurefile
  resources:
    requests:
      storage: 50Gi
```

The error is erroneous and badly stated! 

Please fix this. 

The error is due to the minimum size of 100gi min requirement. 

Giant time waster

```
storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format
```
