### ISSUE TITLE
Kubernetes v1.16.7 and kubernetes-dashboard v2.0.0-beta8 ClusterRoleBinding breaking change

### ISSUE THREAD

**Issue by matthewhartstonge** [Azure/AKS#1534]
**What happened**:
After upgrading a cluster from Kubernetes `v1.15.7` to `v1.16.7` I was unable to gain unfettered access to the Kubernetes Dashboard with an admin cluster role binding using:

`az aks browse --resource-group my-resource-group --name my-cluster-name`

Or `kubectl proxy`

I noticed the dashboard had been upgraded, and it doesn't seem like it respects the Cluster Role for kubernetes-dashboard anymore. Refer: https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard

I also tried using the development cluster role due to  `kube-dashboard@v2.0.0-beta8` being beta as documented here, but that didn't resolve the issue either: https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md#admin-privileges

**What you expected to happen**:

The dashboard still respects the config for Cluster Admin.

**How to reproduce it (as minimally and precisely as possible)**:

- Add cluster role for kubernetes dashboard as `kube-dashboard.rbac.yaml`:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubernetes-dashboard
  namespace: kube-system
```
- run `kubectl apply -f kube-dashboard.rbac.yaml`
- Upgrade from `1.15.7` to `1.16.7`
- Run `az aks browse --resource-group my-resource-group --name my-cluster-name`
- Get stuck at login page.

![image](https://user-images.githubusercontent.com/6119549/77973832-e92ff180-7351-11ea-9253-44de354536a7.png)

**Anything else we need to know?**:
- The work around is to make a service account and bind that into the dashboard, extract said service token and pass it around all our devs, but that's makes our developers sad.. 😢 

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"20c697423de11d4d5d08c6832a513217ca11a6aa", GitTreeState:"clean", BuildDate:"2020-02-21T10:47:45Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?): **3**
- General description of workloads in the cluster: **HTTP microservices**
- Others:

Service Account:
![image](https://user-images.githubusercontent.com/6119549/77975119-9e17dd80-7355-11ea-8d98-cf71a3528415.png)

Cluster Role Binding:
![image](https://user-images.githubusercontent.com/6119549/77975241-fbac2a00-7355-11ea-9255-522a16eb1b1f.png)

**Comment by mullerlele** [comment]
I experience the same issue - and the most interesting thing is, in Kubernetes project, they have already moved the kubernete-dashboard into [its own namespace](https://v1-16.docs.kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#accessing-the-dashboard-ui).  Now the dashboard that comes with the AKS have all the default configurations (service principals, clusterrolebindings etc.) that points to kubernete-dashboard namespace, which does NOT exist. I even tried to create a kubernete-dashboard namespace upfront to see if AKS would put the correct configurations there  - but no, it did not. In my view this is a bug, and AKS team would need to communicate to all the AKS users - are they going to stick to their own way of handling the dashboard in the kube-system namespace in future AKS versions? or are they planning to correct it soon?

**Comment by kahoona77** [comment]
We have the same issue, but our cluster does not have RBAC enabled. It occured after upgrading to 1.16.7. 
Creating ClusterRoleBindings does not help. because do not have RBAC enabled.
Are there maybe any other workarounds to this issue?

**Comment by nmehlei** [comment]
I'm also experiencing this issue. Basically, the dashboard is no longer accessible since I upgraded the AKS cluster. I would appreciate either a fix or a workaround to restore the lost access.

**Comment by yarko686** [comment]
Hi, I've upgraded cluster from 1.14.8 to 1.15.10 and then to 1.16.7 recently.
After upgrade to 1.16.7 I get this error `Error trying to reach service: 'dial tcp 10.220.17.113:8443: connect: connection refused`
Checked deployment and service yaml configs and everything seems in order.

Just for testing purposes, I've created another cluster with 1.14.8 and upgraded it in the same way and it there dashboard worked as expected.

Any suggestions?

@kahoona77 @nmehlei as a workaround I use octant https://github.com/vmware-tanzu/octant

**Comment by jellebens** [comment]
same issue as above after upgrade from 1.15 to 1.16.7

**Comment by cosmos0703** [comment]
same issue too

**Comment by MXClyde** [comment]
Anybody has a workaround for this issue?

**Comment by lilbaek** [comment]
We have the same issue with our staging cluster. We upgraded from 
1.15.10 to 1.16.7. Any workaround? Glad we upgraded staging before doing the live cluster.

**Comment by zodraz** [comment]
As a workaround, and waiting for a solution (if that is possible) because this is the new default option for the Dashboard v2, and because the AKS recreates those "kubernetes-dashboard"  objects (if you have the addon enabled), follow these steps:

Create a new ServiceAccount and ClusterRoleBinding linked to the cluster-admin role, but bind it to kube-system namespace:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
```

Then you can grab your token and put on the login screen.

`kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | sls admin-user | ForEach-Object { $_ -Split '\s+' } | Select -First 1) ` 

You can find more info on this k8s link:

https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

Another workaround would be to not install the dashboard addon and install the v2 Dashboard yourself on the kubernetes-dashboard namespace.

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml`

Is not a perfect solution because you will have to get the token when it expires and it neither bypasses the login screen but better than nothing...


Hope it helps.
