### ISSUE TITLE
mount error(115): Operation now in progress (azure file mount won't work due to 445 port blocked)

### ISSUE THREAD

**Issue by mislavcosic** [Azure/AKS#1592]
**What happened**:
A pod unable to attach or mount volumes

The error:
Warning  FailedMount  15s  kubelet, aks-nodepool1-*  (combined from similar events): MountVolume.SetUp failed for volume "pvc-*" : mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/* --scope -- mount -t cifs -o cache=none,dir_mode=0777,file_mode=0777,gid=1000,mfsymlinks,nobrl,uid=1000,username=*,password=*,vers=3.0 //*.file.core.windows.net/kubernetes-dynamic-pvc-* /var/lib/kubelet/pods/1*/volumes/kubernetes.io~azure-file/pvc-*
Output: Running scope as unit run-*.scope.
mount error(115): Operation now in progress
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

**How to reproduce it (as minimally and precisely as possible)**:

StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
```
PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-upload
  namespace: lego
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 500Mi
```
PV:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                              STORAGECLASS   REASON   AGE
pvc-4641a509-ccfa-4e2a-95b6-a43f6cbeed14   1Gi        RWX            Delete           Bound    lego/azure-managed-disk-upload     azurefile               13d
```

**Anything else we need to know?**:
Storage and Nodes are in the same region.
The nodes are in a Virtual Network
We haven't enabled TCP 445 in our firewall, it is not clear from the documentation if is required.
The documentation we followed:
https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic#required-ports-and-addresses-for-aks-clusters
The troubleshoot documentation:
https://docs.microsoft.com/en-us/azure/storage/files/storage-troubleshoot-linux-file-connection-problems

**Environment**:
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"1fc58d90cc4bc569394d9a882522adcb99fbaa57", GitTreeState:"clean", BuildDate:"2020-04-03T15:20:08Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster: 3
- General description of workloads in the cluster: Python Flask
- Others: Node OS Ubuntu 16.04
