### ISSUE TITLE
Azure-files error on Openshift 4.3 : exit status 32 mount error(2): No such file or directory 

### ISSUE THREAD

**Issue by abudavis** [Azure/AKS#1597]
We are trying to dynamically provision azure file persistent volume on Openshift cluster 4.3.18 (as per instructions in  https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv) deployed on Azure and gott the below reported error (see at the bottom). Please help!
 
More info:
- Successfully able to reproduce the issue on PRE-PROD and PROD Openshift cluster 4.3.18
- Kubernetes version : v1.16.2
- Size of cluster : 3 masters, 2 workers.
- Static provisioning also gives the same error (see at the bottom)
-*This is similar to issue reported: Using Azure Files with Kubernetes causes mount error(2): No such file or directory #46*
- NOTE: It was verified to work okay with Openshift 4.2 (k8s version v1.14) with Azure files. But not with Openshift 4.3. May be a k8s version problem? 

Storage class yaml:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurerwx
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: Immediate
```
 
Azurefilepod yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurerwx
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mountfilepod
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /mnt/azure
      name: volume
  restartPolicy: Always
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azurefile
```
 
---------
 
$ oc get pvc
```
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
azurefile   Bound    pvc-18a0f889-6dce-4cc9-9785-6a7ecaad8520   5Gi        RWX            azurerwx       5s
```

$ oc get pv
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                STORAGECLASS   REASON   AGE
pvc-18a0f889-6dce-4cc9-9785-6a7ecaad8520   5Gi        RWX            Retain           Bound      ace/azurefile                                        azurerwx                3m7s
```
 
$ oc get pods
```
NAME           READY   STATUS              RESTARTS   AGE
mountfilepod   0/1     ContainerCreating   0          2m33s
```

——
THE ERROR:

`MountVolume.SetUp failed for volume "pvc-86c125f8-3c77-4bc2-b0ec-1c6035e5b2f6" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/3329b0d9-7491-4c32-b932-38c298d7bbd0/volumes/kubernetes.io~azure-file/pvc-86c125f8-3c77-4bc2-b0ec-1c6035e5b2f6 --scope -- mount -t cifs -o mfsymlinks,username=f21150e7e1f014d15a77c20,password=redactedxxxhtBA==,file_mode=0777,dir_mode=0777,vers=3.0 //f21150e7e1f014d15a77c20.file.core.windows.net/testcluster-d68nv-dyna-pvc-86c125f8-3c77-4bc2-b0ec-1c6035e5b2f6 /var/lib/kubelet/pods/3329b0d9-7491-4c32-b932-38c298d7bbd0/volumes/kubernetes.io~azure-file/pvc-86c125f8-3c77-4bc2-b0ec-1c6035e5b2f6 Output: Running scope as unit: run-r94f81185afed4319b44490d2a2f446ce.scope mount error(2): No such file or directory Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)`
