### ISSUE TITLE
Error using xfs filesystem

### ISSUE THREAD

**Issue by derekperkins** [Azure/AKS#162]
I created a new storage class to use `xfs`, but it never worked. I'm currently using 1.9.1 in centralus. I'm able to use the default `managed-premium` disks without any trouble, and I'm using `Standard_D8s_v3` nodes.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: xfs
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
  fsType: xfs
reclaimPolicy: Delete
```
Here is the error I got when trying to mount a PVC to a StatefulSet
```
MountVolume.MountDevice failed for volume "pvc-853e0486-089b-11e8-ae38-0a58ac1f0b1c" :
azureDisk - mountDevice:FormatAndMount failed with executable file not found in $PATH
```
This looks like it was previous reported here:
https://github.com/kubernetes/kubernetes/issues/50150

and then supposedly fixed on the k8s side of things in this PR, which was merged into the 1.8 branch
https://github.com/kubernetes/kubernetes/pull/54334
