### ISSUE TITLE
Unable to use the same static IP for multiple LoadBalancer type services

### ISSUE THREAD

**Issue by xenalite** [Azure/AKS#1621]
**What happened**:
I tried to deploy 2 services of `loadBalancer` type referencing the same static standard SKU public IP address for ingress. One service is nginx ingress controller. Another service is a redis cluster. Deploying second service failed with the following error (kubectl describe):
```
Name:                     redis-master
Namespace:                omtest-redis
Labels:                   app=redis
                          chart=redis-10.6.15
                          heritage=Helm
                          release=redis
Annotations:              service.beta.kubernetes.io/azure-load-balancer-resource-group: <redacted-ingress-pip-rg>
Selector:                 app=redis,release=redis,role=master
Type:                     LoadBalancer
IP:                       10.0.207.71
IP:                       <redacted-ingress-pip>
Port:                     redis  6379/TCP
TargetPort:               redis/TCP
NodePort:                 redis  30082/TCP
Endpoints:                10.2.0.32:6379
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                      Age                 From                  Message
  ----     ------                      ----                ----                  -------
  Normal   EnsuringLoadBalancer        30s (x5 over 106s)  service-controller    Ensuring load balancer
  Warning  CreateOrUpdateLoadBalancer  29s (x5 over 106s)  azure-cloud-provider  Code="PublicIPReferencedByMultipleIPConfigs" Message="Public ip address <redacted-ingress-pip-resource-id> is referenced by multiple ipconfigs in resource <redacted-kubernetes-lb-resource-id>." Details=[]
  Warning  SyncLoadBalancerFailed      29s (x5 over 106s)  service-controller    Error syncing load balancer: failed to ensure load balancer: timed out waiting for the condition
```

- Activity log entry for auto-generated kubernetes cluster.
Error code: `PublicIPReferencedByMultipleIPConfigs`
Message:
```
Public ip address <redacted-ingress-pip-resource-id> is referenced by multiple ipconfigs in resource <redacted-kubernetes-lb-resource-id>.
```

**What you expected to happen**:
- 2nd service should have been successfully deployed like the first one.
- Auto-generated kubernetes load balancer should have 3 entries for load balancing rules over the same static PIP.
- Auto-generated NSG to add entry for port 6379 as specified in the 2nd serviceon top of existing 80 and 443.

**How to reproduce it (as minimally and precisely as possible)**:
- Create 2 static standard Public IPs: 1 for ingress, 1 for egress
- Create a new cluster. Specify egress PIP as outbound IP.
- Deploy nginx ingress controller Helm chart. Specify to use ingress PIP and resource group in annotations.
```
helm upgrade ingress-controller stable/nginx-ingress --namespace ingress-controller --version 1.33.0 --values values.ci.yaml --install --debug --wait --timeout '5m'
```
values.ci.yaml:
```
controller:
  service:
    loadBalancerIP: "#{ingress_ip_address}#"
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "#{aks_cluster_resource_group_name}#"
```

- Resulting nginx service configuration:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <redacted-ingress-pip-rg>
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.33.0
    component: controller
    heritage: Helm
    release: ingress-controller
  name: ingress-controller-nginx-ingress-controller
  namespace: ingress-controller
spec:
  clusterIP: 10.0.126.193
  externalTrafficPolicy: Cluster
  loadBalancerIP: <redacted-ingress-pip>
  ports:
  - name: http
    nodePort: 31470
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31475
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-ingress
    component: controller
    release: ingress-controller
  sessionAffinity: None
  type: LoadBalancer
```

- nginx ingress controller will bind to auto-generated standard load balancer and ingress PIP, exposing port 80 and 443 in NSG and in load balancing rules.

![image](https://user-images.githubusercontent.com/4509839/82497760-b8b13c00-9ae6-11ea-9351-09db383e5b9c.png)

- Deploy [redis Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/redis). Specify to use `loadBalancer` type for master service and same ingress PIP for `loadBalancerIP`.
```
helm install redis bitnami/redis --values values.yaml
```
values.yaml:
```
master:
  service:
    type: LoadBalancer
    loadBalancerIP: <redacted-ingress-pip>
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: <redacted-ingress-pip-rg>
```

- Redis master service will fail to deploy due to errors described above.
- Resulting redis master service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: <redacted-ingress-pip-rg>
  labels:
    app: redis
    chart: redis-10.6.15
    heritage: Helm
    release: redis
  name: redis-master
  namespace: omtest-redis
spec:
  clusterIP: 10.0.207.71
  externalTrafficPolicy: Cluster
  loadBalancerIP: <redacted-ingress-pip>
  ports:
  - name: redis
    nodePort: 30082
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: redis
    release: redis
    role: master
  sessionAffinity: None
  type: LoadBalancer
```

**Anything else we need to know?**:
Workaround is to specify a different public IP for redis service. What this effectively means that any externally exposable HTTP-based services can go through ingress controller PIP, but any non-HTTP based protocols must have their own external ingress PIP per service.

This upstream issue seems related:
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/267

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"e2d9f8479783020904aba3de7499a49be6c75ebd", GitTreeState:"clean", BuildDate:"2020-04-09T02:31:15Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
2
- General description of workloads in the cluster:
HTTP services + Redis cluster
