### ISSUE TITLE
pvc mounting takes long time

### ISSUE THREAD

**Issue by boraozkan** [Azure/AKS#1623]
**What happened**:
When I allocate my nodes to my aks cluster I am waiting all pvc mounting more than ten minutes, this cause zookeeper cluster dns resolve issue and leader election cannot handle and my clickhouse cluster cannot handshake with  zookeeper and all replicated table change to read only mode
**What you expected to happen**:
immediately mounting
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.14.6
- Size of cluster (how many worker nodes are in the cluster?)4 nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)clickhouse and zookeeper nodes
- Others:

**Comment by andyzhangx** [comment]
is it disk pvc mount? what's your error events of the pod when it take 10 mins?

**Comment by boraozkan** [comment]
When I delete pod statefulSet start immediately create pod and here is starting this error:
<img width="1431" alt="Screenshot 2020-05-23 at 12 15 44" src="https://user-images.githubusercontent.com/14857646/82729805-562c8b80-9cf2-11ea-81b8-157f26ce7ad6.png">

Maybe it is related with multi az and local pvc(aks has only option with local pvc cannot mount different az). Can we overcome this problem by affinity rules?

**Comment by andyzhangx** [comment]
if you mean local persistent volume, I think you can try this: https://github.com/Azure/kubernetes-volume-drivers/tree/master/local, it would have `nodeAffinity` property.

**Comment by boraozkan** [comment]
Here is my manifest with pvc template(data-volume-template), I am pretty sure I need pvc, I wrote some suggestion about using affinity but actually I tried to give some ides what is the reason behind the multi attachment issue. This basically create 4 pieces 200Gi pvc for each pod and when a pod recreated or deleted it takes too much time to attach/detach PVCs.

```
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "dashboard-sharded"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper.zoons
    clusters:
      - name: "dashboard04"
        templates:
          podTemplate: clickhouse-with-volume-template
        layout:
          shardsCount: 4
  templates:
    podTemplates:
        - name: clickhouse-with-volume-template
          spec:
            containers:
              - name: clickhouse-pod
                image: yandex/clickhouse-server:latest
                resources:
                  requests:
                    cpu: 2
                    memory: 20Gi
                  limits:
                    cpu: 3
                    memory: 48Gi
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
```

**Comment by andyzhangx** [comment]
is it azure disk PVC?

**Comment by boraozkan** [comment]
Yes azure disk. Here is my default-storageclass.json

```
{
  "kind": "StorageClass",
  "apiVersion": "storage.k8s.io/v1",
  "metadata": {
    "name": "default",
    "selfLink": "/apis/storage.k8s.io/v1/storageclasses/default",
    "uid": "464eb6d9-9d6e-11ea-8271-02cc9903c027",
    "resourceVersion": "13925892",
    "creationTimestamp": "2020-05-24T03:25:53Z",
    "labels": {
      "kubernetes.io/cluster-service": "true"
    },
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"allowVolumeExpansion\":true,\"apiVersion\":\"storage.k8s.io/v1beta1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{\"storageclass.beta.kubernetes.io/is-default-class\":\"true\"},\"labels\":{\"kubernetes.io/cluster-service\":\"true\"},\"name\":\"default\"},\"parameters\":{\"cachingmode\":\"ReadOnly\",\"kind\":\"Managed\",\"storageaccounttype\":\"StandardSSD_LRS\"},\"provisioner\":\"kubernetes.io/azure-disk\"}\n",
      "storageclass.beta.kubernetes.io/is-default-class": "true"
    }
  },
  "provisioner": "kubernetes.io/azure-disk",
  "parameters": {
    "cachingmode": "ReadOnly",
    "kind": "Managed",
    "storageaccounttype": "StandardSSD_LRS"
  },
  "reclaimPolicy": "Delete",
  "allowVolumeExpansion": true,
  "volumeBindingMode": "Immediate"
}
```

**Comment by andyzhangx** [comment]
hi, could you try on higher AKS version, e.g. 1.16.9, there is slow disk attach issue in 1.14.x version.
Also, for availability zone cluster, disk in zone#1 cannot be attached to zone#2, I think your cluster is not a zone cluster, otherwise it won't work.

**Comment by andyzhangx** [comment]
I realized it could be due to this issue: https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#24-attach-disk-costs-10min, fixed on 1.15.0+

**Comment by boraozkan** [comment]
Here is my nodes zones

```
kubectl describe nodes | grep -e "Name:" -e "failure-domain.beta.kubernetes.io/zone"
Name:               aks-agentpool-42641663-vmss000000
                    failure-domain.beta.kubernetes.io/zone=0
Name:               aks-agentpool-42641663-vmss000001
                    failure-domain.beta.kubernetes.io/zone=1
Name:               aks-agentpool-42641663-vmss000002
                    failure-domain.beta.kubernetes.io/zone=2
Name:               aks-agentpool-42641663-vmss000003
                    failure-domain.beta.kubernetes.io/zone=3
```

but should be like `uksouth2-1` instead of `zone=0`,  `zone=1`,  `zone=2`

And I tested with version 1.16.9 and version 1.18.2 and i got the similar error and delay about PVCs
And in azure documentation storage section for aks availability zones:

```
**Azure disks limitations**
Volumes that use Azure managed disks are currently not zone-redundant resources. 
Volumes cannot be attached across zones and must be co-located in the same zone 
as a given node hosting a the target pod.

If you must run stateful workloads, use node pool taints and tolerations 
in pod specs to  group pod scheduling in the same zone as your disks. 
Alternatively,  use network-based storage such as Azure Files 
that can attach  to pods as they're scheduled between zones. 
```
How do I know where is my pv storage zones? Is it something schedule by azure or do I have to say if my pod crashed binding pvc attach the same pod again?

**Comment by andyzhangx** [comment]
I think you should set `volumeBindingMode: WaitForFirstConsumer` in azure disk storage class, and `use node pool taints and tolerations 
in pod specs to  group pod scheduling in one zone`, follow details here:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/docs/using-availability-zones.md#storageclass-examples

**Comment by andyzhangx** [comment]
BTW, why would it take long time to attach? if zone#1 disk is attached to zone#2 node, it will report error and would never succeed.

**Comment by boraozkan** [comment]
I delete whole cluster and redeploy again, I changed my storageclass for ch and here is timestamps events on dashboard I have seen

First: When I deleted my cluster this pvc is waiting around 5 minutes for totaly erasing.
<img width="1422" alt="Screenshot 2020-05-25 at 12 42 22" src="https://user-images.githubusercontent.com/14857646/82810443-6d03e700-9e86-11ea-927a-11f19d71922f.png">

Second: Now I deleted everthing and I create all of things again and I received another typical error which i always faced

<img width="1412" alt="Screenshot 2020-05-25 at 12 47 03" src="https://user-images.githubusercontent.com/14857646/82810521-a2103980-9e86-11ea-9d4e-b2d2ae403017.png">

Third: and after around 5-10 mins it looks health running

<img width="1417" alt="Screenshot 2020-05-25 at 12 53 39" src="https://user-images.githubusercontent.com/14857646/82810656-e69bd500-9e86-11ea-91ac-348582cf7dae.png">

about your question zone disk attachment, I totally don't know still it is mystery to me

**Comment by andyzhangx** [comment]
if your vmss is in one zone or non-zone, disk attach from node to another won't have issue. The `Multi-Attach` error is reported by k8s volume controller since that disk is being detached on another node, and it should recover after a while.

**Comment by boraozkan** [comment]
can I check k8s volume controller logs?

**Comment by boraozkan** [comment]
> BTW, why would it take long time to attach? if zone#1 disk is attached to zone#2 node, it will report error and would never succeed.
```
kubectl describe nodes | grep -e "Name:" -e "failure-domain.beta.kubernetes.io/zone"
Name:               aks-agentpool-42641663-vmss000000
                    failure-domain.beta.kubernetes.io/zone=0
Name:               aks-agentpool-42641663-vmss000001
                    failure-domain.beta.kubernetes.io/zone=1
Name:               aks-agentpool-42641663-vmss000002
                    failure-domain.beta.kubernetes.io/zone=2
Name:               aks-agentpool-42641663-vmss000003
                    failure-domain.beta.kubernetes.io/zone=3
```
I cannot use affinity in pod and topology-aware storageclass provisioning as it is giving error with couldn't find a nodes to deploy pods error. Because` failure-domain.beta.kubernetes.io/zone=3` is a correct syntax idk, because I saw in examples :

```
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - centralus-1
    - centralus-2
```

but in my scenario if I add like:
```

allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - 1
    - 2
```
it doesn't accept so I change it with 

```

allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - "1"
    - "2"
```
but still couldn't match with the nodes

**Comment by andyzhangx** [comment]
run `kubectl get no --show-labels` to get the correct `failure-domain.beta.kubernetes.io/zone` values

**Comment by boraozkan** [comment]
here is output, it is same which I wrote above
```

kubectl get no --show-labels
NAME                                STATUS   ROLES   AGE    VERSION   LABELS
aks-agentpool-42641663-vmss000000   Ready    agent   112d   v1.14.8   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=0,kubernetes.azure.com/cluster=MC_ClickHouse_ClickHouseCluster_uksouth,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-agentpool-42641663-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
aks-agentpool-42641663-vmss000001   Ready    agent   112d   v1.14.8   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=1,kubernetes.azure.com/cluster=MC_ClickHouse_ClickHouseCluster_uksouth,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-agentpool-42641663-vmss000001,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
aks-agentpool-42641663-vmss000002   Ready    agent   112d   v1.14.8   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=2,kubernetes.azure.com/cluster=MC_ClickHouse_ClickHouseCluster_uksouth,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-agentpool-42641663-vmss000002,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
aks-agentpool-42641663-vmss000003   Ready    agent   112d   v1.14.8   agentpool=agentpool,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=3,kubernetes.azure.com/cluster=MC_ClickHouse_ClickHouseCluster_uksouth,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-agentpool-42641663-vmss000003,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
```

**Comment by andyzhangx** [comment]
try with this?
```
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - uksouth-1
    - uksouth-2
```

**Comment by boraozkan** [comment]
I got the same error, maybe we need to give another values

![image](https://user-images.githubusercontent.com/14857646/83129402-aaf64a80-a0d4-11ea-969a-a5df12b14d35.png)

**Comment by andyzhangx** [comment]
in my aks cluster, it's node label is like this: `failure-domain.beta.kubernetes.io/zone=uksouth-1`, not sure why your cluster is like this `failure-domain.beta.kubernetes.io/zone=1`:

```
# k get no --show-labels
NAME                                STATUS   ROLES   AGE     VERSION   LABELS
aks-nodepool1-19045973-vmss000000   Ready    agent   3m17s   v1.14.7   agentpool=nodepool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=uksouth-1,kubernetes.azure.com/cluster=MC_andy-akszone11472_andy-akszone11472_uksouth,kubernetes.azure.com/mode=system,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-nodepool1-19045973-vmss000000,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
aks-nodepool1-19045973-vmss000001   Ready    agent   3m9s    v1.14.7   agentpool=nodepool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=uksouth-2,kubernetes.azure.com/cluster=MC_andy-akszone11472_andy-akszone11472_uksouth,kubernetes.azure.com/mode=system,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-nodepool1-19045973-vmss000001,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
aks-nodepool1-19045973-vmss000002   Ready    agent   3m5s    v1.14.7   agentpool=nodepool1,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_DS2_v2,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=uksouth,failure-domain.beta.kubernetes.io/zone=uksouth-3,kubernetes.azure.com/cluster=MC_andy-akszone11472_andy-akszone11472_uksouth,kubernetes.azure.com/mode=system,kubernetes.azure.com/role=agent,kubernetes.io/arch=amd64,kubernetes.io/hostname=aks-nodepool1-19045973-vmss000002,kubernetes.io/os=linux,kubernetes.io/role=agent,node-role.kubernetes.io/agent=,storageprofile=managed,storagetier=Premium_LRS
```

**Comment by andyzhangx** [comment]
o, i see, your cluster is not a zone cluster(`failure-domain.beta.kubernetes.io/zone=1` mean that instance is in FaultDomain#1). In your case, you may not need to create a zone cluster. Anyway, to create a zone cluster, you could refer to https://docs.microsoft.com/en-us/azure/aks/availability-zones

**Comment by andyzhangx** [comment]
https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
When a cluster operator specifies the `WaitForFirstConsumer` volume binding mode, it is no longer necessary to restrict provisioning to specific topologies in most situations. However, if still required, `allowedTopologies` can be specified.

An example of zone-aware provisioning storage class is:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer
```
