### ISSUE TITLE
Unable to add new nodepool to existing AKS joined to a VirtualNetwork subnet

### ISSUE THREAD

**Issue by AAATechGuy** [Azure/AKS#1652]
# **What happened**:

# **Context**: 
- I created AKS cluster, attached to a VN subnet (hypernet). Created a pod and things work fine. 
- I create another node pool within the same AKS cluster, attached to the same VN subnet. Creating a pod in that pool, there seems to be DNS/network issues. 

# **What you expected to happen**:
- the new node pool # 2 (testlinldc2) seems to have connectivity/ DNS issues. See log: `Could not resolve host: msasg.visualstudio.com`
This issue doesn't exist for node pool # 1 (silinldc1)

# **How to reproduce it (as minimally and precisely as possible)**:

1. I create AKS cluster, attached to a VN subnet (hypernet), via the following commands: 
```
az configure --defaults group=CCMT-SI
$VNET_ID = az network vnet show --resource-group DefaultWestUS --name <VNET-NAME> --query id -o tsv;
$SUBNET_ID = az network vnet subnet show --resource-group DefaultWestUS --vnet-name <VNET-NAME> --name Subnet1 --query id -o tsv;
az aks create `
    --resource-group CCMT-SI `
    --name <myAKSCluster> `
    --network-plugin kubenet `
    --vnet-subnet-id $SUBNET_ID `
    --generate-ssh-keys `
    --nodepool-name silinldc1 `
    --nodepool-labels environment=SI oskind=linux `
    --node-vm-size Standard_B2s `
    --node-count 1 `
    --service-cidr 181.16.0.0/20 `
    --dns-service-ip 181.16.0.10 `
    --docker-bridge-address 181.17.0.1/20 `
    --pod-cidr 181.18.0.0/16 `
    --service-principal "<USERNAME>" `
    --client-secret "<PASSWORD>";
# attach acr
# enable monitoring
```
I started a pod successfully on nodepool # 1, via following config. 
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: vsts-agent-linux3-4
  labels:
    environment: TEST
    team: CCMT
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vsts-agent-linux3-4
        version: "0.1"
    spec:
      containers:
      - name: vsts-agent-linux3-4
        image: <MYACR>.azurecr.io/abinaa/vstsagent:20200604.003
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: vstsagentinfo
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: vstsagentinfo
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: vstsagentinfo
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
      nodeSelector:
        oskind: linux
        environment: SI
```

2. **Problem**
I try to add another nodepool in the same subnet. 
```
az aks nodepool add `
    --cluster-name <myAKSCluster> `
    --name testlinldc2 `
    --resource-group CCMT-SI `
    --os-type Linux `
    --vnet-subnet-id $SUBNET_ID `
    --labels environment=TEST-WUS-LDC2 oskind=linux `
    --node-vm-size Standard_B2s `
    --node-count 1 `
    --mode User;
```
I try to spawn similar pod in this nodepool, however, there seems to be some issues with DNS resolution. 
Issue reproduces while trying with new cluster/ different azure subscription/ without $SUBNET_ID/ without --mode param. 

# **Anything else we need to know?**:

Details as follows: 

```
PROMPT> kubectl logs vsts-agent-linux3-5-48cdc
[1;36m1. Determining matching Azure Pipelines agent...[0m
curl: (6) Could not resolve host: msasg.visualstudio.com
```
```
PROMPT> kubectl get pod
NAME                        READY   STATUS             RESTARTS   AGE
vsts-agent-linux3-4-fpdtc   1/1     Running            0          26m
vsts-agent-linux3-5-48cdc   0/1     CrashLoopBackOff   6          12m
```
```
PROMPT> kubectl describe pod vsts-agent-linux3-5-48cdc
Name:           vsts-agent-linux3-5-48cdc
Namespace:      default
Priority:       0
Node:           aks-testlinldc2-31416990-vmss000000/<VNET_IP>
Start Time:     Thu, 04 Jun 2020 20:18:37 +0000
Labels:         app=vsts-agent-linux3-5
                version=0.1
Annotations:    <none>
Status:         Running
IP:             181.18.2.3
IPs:            <none>
Controlled By:  ReplicationController/vsts-agent-linux3-5
Containers:
  vsts-agent-linux3-5:
    Container ID:   docker://de890ac59f8ccfb3e1c4c4a19fa40be7e570f653cac081a7293cc536419f36fe
    Image:          <MyAcr>.azurecr.io/abinaa/vstsagent:20200604.003
    Image ID:       docker-pullable://<MyAcr>.azurecr.io/abinaa/vstsagent@sha256:d26226d771e4d583bdb02a73a71b388684f37f83158992d6d5e030e34144e81d
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    6
      Started:      Thu, 04 Jun 2020 20:32:50 +0000
      Finished:     Thu, 04 Jun 2020 20:33:10 +0000
    Ready:          False
    Restart Count:  7
    Environment:
      AZP_URL:    <set to the key 'AZP_URL' in secret 'vstsagentinfo'>    Optional: false
      AZP_TOKEN:  <set to the key 'AZP_TOKEN' in secret 'vstsagentinfo'>  Optional: false
      AZP_POOL:   <set to the key 'AZP_POOL' in secret 'vstsagentinfo'>   Optional: false
    Mounts:
      /var/run/docker.sock from docker-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fmp6h (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  docker-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:
  default-token-fmp6h:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fmp6h
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  environment=TEST-WUS-LDC2
                 oskind=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                          Message
  ----     ------     ----                  ----                                          -------
  Normal   Scheduled  15m                   default-scheduler                             Successfully assigned default/vsts-agent-linux3-5-48cdc to aks-testlinldc2-31416990-vmss000000
  Normal   Pulling    15m                   kubelet, aks-testlinldc2-31416990-vmss000000  Pulling image "<MyACR>.azurecr.io/abinaa/vstsagent:20200604.003"
  Normal   Pulled     14m                   kubelet, aks-testlinldc2-31416990-vmss000000  Successfully pulled image "<MyACR>.azurecr.io/abinaa/vstsagent:20200604.003"
  Normal   Created    11m (x5 over 13m)     kubelet, aks-testlinldc2-31416990-vmss000000  Created container vsts-agent-linux3-5
  Normal   Pulled     11m (x4 over 13m)     kubelet, aks-testlinldc2-31416990-vmss000000  Container image "<MyACR>.azurecr.io/abinaa/vstsagent:20200604.003" already present on machine
  Normal   Started    11m (x5 over 13m)     kubelet, aks-testlinldc2-31416990-vmss000000  Started container vsts-agent-linux3-5
  Warning  BackOff    4m51s (x31 over 13m)  kubelet, aks-testlinldc2-31416990-vmss000000  Back-off restarting failed container
```

# **Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-13T17:40:34Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
```
PROMPT> kubectl get nodes
NAME                                  STATUS   ROLES   AGE    VERSION
aks-silinldc1-31416990-vmss000000     Ready    agent   111m   v1.15.11
aks-testlinldc1-31416990-vmss000000   Ready    agent   85m    v1.15.11
aks-testlinldc2-31416990-vmss000000   Ready    agent   26m    v1.15.11
```
```
PROMPT> kubectl get pods
NAME                        READY   STATUS             RESTARTS   AGE
vsts-agent-linux3-3-88dw4   0/1     CrashLoopBackOff   11         39m
vsts-agent-linux3-4-fpdtc   1/1     Running            0          38m
vsts-agent-linux3-5-48cdc   0/1     CrashLoopBackOff   8          24m
```
Metrics: 
![image](https://user-images.githubusercontent.com/3484074/83815729-ba960600-a675-11ea-98cb-56f4bf34f3ec.png)
![image](https://user-images.githubusercontent.com/3484074/83815751-c71a5e80-a675-11ea-8f14-2147ad16afb2.png)
![image](https://user-images.githubusercontent.com/3484074/83815786-d4cfe400-a675-11ea-9bcc-450ebdd8b6d2.png)
![image](https://user-images.githubusercontent.com/3484074/83815816-e44f2d00-a675-11ea-8047-fd4b7c4ff656.png)
![image](https://user-images.githubusercontent.com/3484074/83815865-fcbf4780-a675-11ea-8515-ab58b561ba90.png)
![image](https://user-images.githubusercontent.com/3484074/83815882-0648af80-a676-11ea-8c13-7509cd89acfc.png)

PS, for omsagent agent warn, "View Container Logs" do not give any logs. So, can't debug, 
![image](https://user-images.githubusercontent.com/3484074/83816025-5162c280-a676-11ea-8b92-ef43d44dae30.png)

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
* VSTS agent (customized) on Linux
- Others:
`NA`
