### ISSUE TITLE
Small PersistentVolumeClaims with default storage class take long time to be available

### ISSUE THREAD

**Issue by bitsofinfo** [Azure/AKS#1658]
Using AKS 1.16.9

I have PersistentVolumeClaims such as the below which I assume go against the default storage class.

Why do these take upwards of 3 to 4 minutes to be available? I feel like the slowness is once they are being mounted, is it formatting?

```
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
```
