### ISSUE TITLE
Virtual nodes never started

### ISSUE THREAD

**Issue by ifle** [Azure/AKS#1720]
**What happened**:
I have AKS linux cluster with virtual nodes based on ACI. But I've nver seen that pods started on ACI

**What you expected to happen**:
During load pods will be started on ACI

**Environment**:
- Kubernetes version: 1.16.7
- Size of cluster - 2 nodes
- General description of workloads in the cluster - java spring boot application

**Comment by palma21** [comment]
@MikkelHegn @macolso

**Comment by macolso** [comment]
Hello! Are you adding a toleration for virtual-kubelet in your pod spec?

**Comment by ifle** [comment]
Hi,

I created virtual nodes by azure portal, not something special.

**Comment by macolso** [comment]
@ifle makes sense! When you go to deploy pods, you must use a toleration for virtual node otherwise the pods will be deployed on normal worker nodes. I've included an example from [our documentation](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-portal) below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aci-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aci-helloworld
  template:
    metadata:
      labels:
        app: aci-helloworld
    spec:
      containers:
      - name: aci-helloworld
        image: microsoft/aci-helloworld
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
```

**Comment by ifle** [comment]
Thanks for your reply.
How virtual nodes will work with horizontal autoscaler? For example, I have 2 physical nodes, the virtual nodes should started if the CPU usage exceeds 90%. I tried define the HorizontalPodAutoscaler, but I'm not sure about it

```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: route-hpa
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: route
  targetCPUUtilizationPercentage: 90 # target CPU utilization

```
