### ISSUE TITLE
aks failed to provision pvc with azurefile-premium storage class

### ISSUE THREAD

**Issue by rvashishth** [Azure/AKS#1740]
**What happened**:
Failed to use default storage class `azurefile-premium`

**What you expected to happen**:
We should be able to create PVC with `azurefile-premium` storage class.  While other default storage classes as, `default`, `managed-premium` and `azurefile` works as expected.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Create a spec file with below content
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-premium-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: mypod
      image: nginx:1.15.5
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azurefile-premium-pvc
```
2.  `kubectl apply -f my-spec-file.yaml -n mynamespace`

3. PVC creation will remain in pending status.  with below error 
Exception 
```
Failed to provision volume with StorageClass "azurefile-premium": failed to create share kubernetes-dynamic-pvc-29ec35ce-5e01-4863-a787-9235ad4158da in account f788bbc1f369148ea8e864b: failed to create file share, err: storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format. RequestId:868a226f-b01a-00c6-7c33-5f9e72000000 Time:2020-07-21T07:46:30.9712861Z, RequestInitiated=Tue, 21 Jul 2020 07:46:30 GMT, RequestId=868a226f-b01a-00c6-7c33-5f9e72000000, API Version=2018-03-28, QueryParameterName=, QueryParameterValue=
```

**Anything else we need to know?**:

Above spec file works with custom StorageClass and other defaul AKS storage classes as defualt, managed-premium, azurefile.  But fails only with azurefile-premium.

**Environment**:
- Kubernetes version (use `kubectl version`):
    client - 1.16.8
    server - 1.16.10
- Size of cluster (how many worker nodes are in the cluster?)
   3
