### ISSUE TITLE
securityContext doesn't work in deployment

### ISSUE THREAD

**Issue by programmersommer** [Azure/AKS#1751]
I am using AKS version 1.15.11 with 3 nodes and ASP.NET Core applications.
[Based on Best practices for pod security in Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/aks/developer-best-practices-pod-security) I am trying to add securityContext for deployment. But I am receiving next one exception:

> error: error validating "deploy-website.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext; if you choose to ignore these errors, turn validation off with --validate=false

If you want to reproduce, please add next part to deployment yaml:

```
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
          allowPrivilegeEscalation: false
```

When I am trying to apply deployment with --validate=false I see that my service couldn't start.
