### ISSUE TITLE
Controlling egress ip for pods when using multiple load balancers

### ISSUE THREAD

**Issue by heppth** [Azure/AKS#1754]
**What happened**:
The AKS cluster uses randomly one of the load balancers IP address (as correctly described [here](https://docs.microsoft.com/azure/aks/egress)).
In detail: We have 5 pods. Each pod has its own load balancer service with its own public IP adress. Once the the first load balancer service is created, all pods of the cluster are using its IP address for egress traffic. When a node pool is updated or the 1st loadbalancer is briefly removed, the IP address for outgoing traffic changes randomly for all pods.
The problem: It is impossible to set up IP filter rules for external services.

**What you expected to happen**:
A solution controlling which IP is used for egress traffic. In my case, each Pod communicates with external services that need to white list a static IP address. I want each pod to use the IP address of its load balancer for outgoing traffic.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create two deployments. Each one having its own service of type load balancer
2. Execute curl within the pod to determine the public IP --> Both pods using the public IP of load balancer no. 1
3. Temporary remove load balancer no. 1 and apply again --> Both pods using the public IP of the other load balancer

**Anything else we need to know?**:
Several guys have the same problem, but their issues were closed without solution (see #1116 and #487)

**Environment**:
- Kubernetes version: 1.15.10
- Size of cluster: 3 woker nodes
- Because I know it will be asked: We are currently using load balancer with basic SKU. If there is any possibility with standard SKU, we will gladly modify the cluster.

**Comment by posix4e** [comment]
I'd love to see this fixed..I have a lower requirement . I want to restrict the outbound source IP to be any IP that's not the ingress. Some options for us

1. Preventing outbound on a the IP of the ingress
2..having full control over what ip comes out of

**Comment by TomGeske** [comment]
If you use Standard LB you should have a fixed IP for all egress traffic: https://docs.microsoft.com/en-us/azure/aks/egress.

**Comment by heppth** [comment]
> If you use Standard LB you should have a fixed IP for all egress traffic: https://docs.microsoft.com/en-us/azure/aks/egress.

Thanks TomGeske,
the article you have linked describes exactly the behaviour I have described (which is why I have also linked it).
You write that a Standard LB would behave differently here. Can you describe in how far the behavior differs?
Is it possible to use different egress IP addresses for different services? 

By the way: As I wrote in my issue, there are situations where the egress IP address is not static (e.g. when updating the K8s version)

**Comment by TomGeske** [comment]
Sorry, I meant to post a different link. Basic LB is behaves the way you described.

Standard LB is documented here: https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#update-the-cluster-with-your-own-outbound-public-ip-prefix 

Yes, you can use different egress IPs for different services, if needed. Egress IP remains the same for Standard LB after upgrade.

**Comment by heppth** [comment]
> Yes, you can use different egress IPs for different services, if needed. Egress IP remains the same for Standard LB after upgrade.

I have just created a cluster with StandardLB. The cluster has been assigned its own IP address (A). Then I created two services (test1 and test2) with two more static IP addresses (B and C). If I now execute `curl ifconfig.me` the clusters IP (A) is returned both times. 

How can I use IP address (B) as egress IP address for service (test1) and IP address (C) as egress IP address for service (test2)?

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test1
spec:  
  selector:
    matchLabels:
      app: nginx-test1
  template:
    metadata:
      labels:
        app: nginx-test1
    spec:
      containers:
      - name: nginx-test1
        image: nginx:1.16
        ports:
        - containerPort: 80
          name: http    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test1
spec:
  type: LoadBalancer
  loadBalancerIP: 51.138.102.94 # IP (B)
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-test1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test2
spec:  
  selector:
    matchLabels:
      app: nginx-test2
  template:
    metadata:
      labels:
        app: nginx-test2
    spec:
      containers:
      - name: nginx-test2
        image: nginx:1.16
        ports:
        - containerPort: 80
          name: http    
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test2
spec:
  type: LoadBalancer
  loadBalancerIP: 51.138.102.197 # IP (C)
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nginx-test2
```
