### ISSUE TITLE
Is Azure NPM for AKS production ready ?

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [Azure/AKS#1810]
**What happened**:
AKS supports Calico and Azure NPM as Network Policy Manager. We opted to go with Azure NPM over well renowned Calico since Azure NPM is supported by Azure Support and its backed by microsoft engineers. And Calico has Community Support https://docs.microsoft.com/en-us/azure/aks/use-network-policies#differences-between-azure-and-calico-policies-and-their-capabilities.

Recently we have faced two production incidents due to regression bugs introduced with AKS NPM Component upgrade.

1. When network policies are deleted , the deleted network policies were not removed from iptable. Issue was happening in NPM v1.1.1. When the npm pods in the `kube-system` were deleted forcefully the deleted entries were removed. Raised an Azure support ticket with Severity A. Later Azure support informed that this is a known bug in NPM and is fixed in https://github.com/Azure/azure-container-networking/releases/tag/v1.1.2. The related bug https://github.com/Azure/azure-container-networking/pull/555. It took nearly 1 month to rollout the fix to AKS clusters globally. During that time we were unable to test any network policies in AKS since its really awkward and annoying to recreate npm pod after deleting network policies.

1. All of a sudden in-cluster inter-service connections made timeout errors in connections. Since we did not perform any changes related to cluster networking , we suspected this is due to network policies. Our first suspect was Azure NPM since it has brought enough pain in the past. We could notice that NPM version was upgraded to v1.1.5 recently. These network policies were working fine in NPM v1.1.4. As the quick fix we removed all the network policies applied in the cluster and recreated all the npm pods in `kube-system`. It mitigated the timeout issue and services were back to normal. Raised an Azure severity A support ticket. And also created a github issue https://github.com/Azure/azure-container-networking/issues/657. After series of Azure support discussion, the NPM version of the clusters were downgraded to NPM v1.1.4 by Azure from their backend after 2 days. Until that time we had to run with no network policies in the clusters.

- NPM component version upgrade is not available in AKS release notes. https://github.com/Azure/AKS/issues/1807
- Inconsistent behaviours are observed when NPM is used as network policy manager https://github.com/Azure/azure-container-networking/issues/579

**What you expected to happen**:
NPM component version upgrade does not break existing fine working AKS clusters.

**Environment**:
- Kubernetes version:
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1da71a35d52fa82847fd61c3db20c4f95d283977", GitTreeState:"clean", BuildDate:"2020-07-15T21:59:26Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster (how many worker nodes are in the cluster?)
Affected all the running AKS clusters in the subscription.

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Ballerina

**Comment by dhananjaya-senanayake** [comment]
Following is the RCA provided by Azure Support on the 2nd incident.

- What caused the issue in NPM v1.1.5?

A typo in code caused this this issue. The feature customer using is called "named ports", NPM started supporting this feature from this May, version 1.1.1

https://github.com/Azure/azure-container-networking/pull/553

A change in v1.1.5 which has a typo in set type cause named ports feature failed. A fix is already merged before customer find this failure. But it didn't got deployed until v1.1.7

https://github.com/Azure/azure-container-networking/pull/625/files


- How the NPM component upgrade changes were propagated to AKS globally without detecting this issue?

Test didn't cover named ports feature yet.


- What are the steps that azure would take in order not to have these issues occurred in the future ?

Added unit test to cover named ports feature. Any failure for named port feature will be caught in unit test, much earlier before releasing. Named port feauture will be gated through test.

https://github.com/Azure/azure-container-networking/pull/661

**Comment by dhananjaya-senanayake** [comment]
With Azure NPM v1.1.7 also the timeout issues are encountered.

**Comment by avpines** [comment]
Having the same timeout issues with Azure NPM v1.1.7, cannot access pod logs.

**Comment by mpeterson** [comment]
I am experiencing the same issue with timeouts, also using Azure NPM v1.1.7 

A ticket is open in Azure Portal about this and the support representative is aware of this ticket.

BTW, this is a blocker for going to Production for us.

**Comment by aanandr** [comment]
@dhananjaya-senanayake @avpines @mpeterson - sorry to know that you are still seeing timeout issues with 1.1.7. I am working to get an Engineer investigate this. Stay tuned.

**Comment by csfmomo** [comment]
Hi @mpeterson , could you share the ticket number?

**Comment by csfmomo** [comment]
Hi @jluk, could you share the ticket number for this time out issue?

**Comment by csfmomo** [comment]
Hi @dhananjaya-senanayake, we have a ticket from your team and we are investigating it.

**Comment by dhananjaya-senanayake** [comment]
@csfmomo please find the ticket number `120092123000336`

**Comment by avpines** [comment]
@csfmomo, relevant ticket number is 120092121000651.

**Comment by neaggarwMS** [comment]
@avpines we have looked into your support ticket (120092121000651). 

We looked into the impacted AKS cluster details.
Region   : WestUS2
Resourceuri    : /subscriptions/b955cf73-2b1c-43d1-adbb-9d548b0d3d7a/resourceGroups/discovery/providers/Microsoft.ContainerService/managedClusters/discovery-discovery 

It is not related to above issue. There are no NetworkPolicies in your cluster. @jluk Can you help out with @avpines issue for failure to connect to API server?

**Comment by avpines** [comment]
@neaggarwMS please remove our internal information (such as resource URI) from this public page.

**Comment by mpeterson** [comment]
@csfmomo @neaggarwMS we are in the same group with @avpines so we share the same ticket id and I see he posted it.

@neaggarwMS There are no NetworkPolicies now because we removed them from the cluster after finding this issue and that in fact resolved the issue in our cluster. Thus, this is exactly the issue that is affecting us and we would very much want to put the network policies back inside so we can be compliant with security policies again.

**Comment by dhananjaya-senanayake** [comment]
@neaggarwMS and @csfmomo , as @mpeterson mentioned this issue comes only when network policies are applied. The same exact network policy worked on v1.1.4, did not work in v1.1.5 and now in v1.1.7 as well. Since security and compliance are  considered high from our end we got the NPM version downgraded to v1.1.4 on both occasions through the AKS backend team.

**Comment by mainred** [comment]
Hey @dhananjaya-senanayake , thanks for your feedback. I did not reproduce the problem with npm v1.1.7.
Do you mind sharing your pod definition here? Thanks.

Here are my tried manifests:
network policy you shared in https://github.com/Azure/azure-container-networking/issues/657
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-egress-network-policy
  namespace: test-netpol
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        # Private IP CIDRs
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12
       # Azure VM meta data URL
        - 169.254.169.254/32
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - namespaceSelector:
        matchLabels: {}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx # Allow to Nginx Ingress pods since egress traffic to cluster LB Public Ips are rewritten to pods IPs with NAT
  podSelector: {}
  policyTypes:
  - Egress
```

pod definition from the same namespace as the above network policy:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server
  name: access-server
  namespace: test-netpol
spec:
  containers:
  - args:
    - python -m SimpleHTTPServer 80
    command:
    - sh
    - -c
    image: python:2.7.11-alpine
    name: pod-container-80
    ports:
    - containerPort: 80
      name: serve-80
      protocol: TCP
  - args:
    - python -m SimpleHTTPServer 81
    command:
    - sh
    - -c
    image: python:2.7.11-alpine
    name: pod-container-81
    ports:
    - containerPort: 81
      name: serve-81
      protocol: TCP

```
