### ISSUE TITLE
LoadBalancer rules applied to NSG does not obey service tag configuration

### ISSUE THREAD

**Issue by nmiodice** [Azure/AKS#1813]
**What happened**:

When applying a `LoadBalancer` configuration, I need to lock down traffic to a particular service tag (`AzureFrontDoor.Backend`). When manually modifying the NSG in the portal I am able to get this to work. The IP is not accessible, unless through Front Door.

When following these [instructions](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard), I do see the NSG ingress rule re-created. It looks the same as the one I create in the portal. However, access via FrontDoor is **blocked**.

Is there anything on the cluster, perhaps with NGINX, that I need to be aware of?

Load Balancer configuration (without NSG rules). Applying this, then manually adding the NSG rule results in expected behavior.
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.40.3
    component: controller
    heritage: Helm
    release: nginx-ingress
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-ingress
    app.kubernetes.io/component: controller
    release: nginx-ingress
  type: LoadBalancer
```

Load Balancer configuration (WITH NSG rules)
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-allowed-service-tags: AzureFrontDoor.Backend
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.40.3
    component: controller
    heritage: Helm
    release: nginx-ingress
  name: nginx-ingress-controller
  namespace: nginx-ingress
spec:
  # without this, an ingress rule to allow 0.0.0.0/0 is created, which is not ideal!
  loadBalancerSourceRanges:
  - 127.0.0.1/24
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-ingress
    app.kubernetes.io/component: controller
    release: nginx-ingress
  type: LoadBalancer
```

**What you expected to happen**:

Applying the second YAML configuration that I provided should result in access from Front Door. 

**How to reproduce it (as minimally and precisely as possible)**:
Apply first YAML and then create an ingress rule for AFD. It should work. But the second one does not.

**Anything else we need to know?**:

Applying the second YAML and then manually creating the NSG in Azure does not actually allow traffic from Azure Front Door. I'm wondering why this might be...

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"89d8075525967c7a619641fabcb267358d28bf08", GitTreeState:"clean", BuildDate:"2020-06-23T02:52:37Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
`3 worker nodes`

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP(S) based micro-services using NGINX ingress
