### ISSUE TITLE
Adding HPA into cluster is causing a lot of timeouts trying to connect to the kube api server.

### ISSUE THREAD

**Issue by arsnyder16** [Azure/AKS#1822]
**What happened**:
When adding HPA into cluster its causing a lot of timeouts with the kube api server. 

**What you expected to happen**:
No timeouts 

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-balancer
spec:
  maxReplicas: 16
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-balancer
  targetCPUUtilizationPercentage: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
spec:
  replicas: 3
  template:
    metadata:
      labels:
        aadpodidbinding: bind
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: load-balancer
        image: ***.azurecr.io/load-balancer:v1
        resources:
          requests:
            memory: "80Mi"
            cpu: "300m"
          limits:
            memory: "500Mi"
            cpu: "600m"
         ports:
           containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-controller
spec:
  selector:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        aadpodidbinding: bind
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: my-controller
        image: ***.azurecr.io/my-controller:***
        resources:
          requests:
            memory: "80Mi"
          limits:
            memory: "250Mi"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-manager
rules:
- apiGroups: ["", "metrics.k8s.io"]
  resources: ["pods", "pods/status", "nodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: load-balancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-cluster
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - example.com
    secretName: ingress-tls
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: load-balancer
          servicePort: 80
        path: /
```

**Anything else we need to know?**:

I am trying to setup auto scaling for a deployment within my cluster using HPA and the node pool auto scaling. When i add this to the cluster i start to see some networking issues with other pods in the cluster.  "load-balancer" pod in my cluster is a node server that is reverse proxying to a pool of stateful pods on another node pool. Those pods are management by a custom controller i created running in node, to manage the scale and lifetime of those stateful pods i am leveraging the kube api server for both metrics and to add/modify/delete those stateful pods.   

Once the HPA is added to the cluster the custom controller becomes very unreliable and is repeatedly receiving timeouts trying to connect to the api server when trying to make concurrent modification to pods `{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"10.0.0.1","port":443}`, 

I also start get some errors trying to get metrics `Error: Failed getting metrics 503 - "service unavailable\n" https://10.0.0.1:443/apis/metrics.k8s.io/v1beta1/nodes`

Within those stateful pods and the custom controller they start to fail to connect to app insights as well `ApplicationInsights:Sender [ 'Ingestion endpoint could not be reached 5 consecutive times. There may be resulting telemetry loss. Most recent error:',    
  { Error: connect ETIMEDOUT 52.**.**.**:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)        
    errno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '52.**.**.**',
    port: 443 } ]`

As soon as i delete the HPA from the cluster all these errors stop. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.9
- Size of cluster (how many worker nodes are in the cluster?)
2 pools, at its minimum   2 nodes per pool, but should auto scale with load 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Nginx Ingress -< load-balancer -< machine learning/data analytics stateful pods 
- Others:
