### ISSUE TITLE
Windows Containers that use livenessProbe & readinessProbe using ExecAction fail

### ISSUE THREAD

**Issue by alikor** [Azure/AKS#1836]
**What happened**:

When Attempting either a livenessProbe or livenessProbe exec action  like the following fail

          livenessProbe:
            exec:
              command: 
              - "dir"
          readinessProbe:
            exec:
              command:
              - "dir"

Regardless of the actual command used and I have tried 

- dir
- Get-Date
- c:\customs.ps1
- powershell -command Get-Date
- powershell -command  c:\customs.ps1

I get the following error

Liveness probe failed: container ****** encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"\"powershell -command Get-Date\"", ***********}

**What you expected to happen**:

I expect the Prob to execute the appropriate command and act accordingly 

**How to reproduce it (as minimally and precisely as possible)**:

Create a Windows Container POD with exec prob

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"e3808385c7b3a3b86db714d67bdd266dc2b6ab62", GitTreeState:"clean", BuildDate:"2020-07-15T20:50:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Legacy Windows Services that are consuming messages from Que's

**Comment by immuzz** [comment]
@alikor Is the service reachable on the default path specified here?

**Comment by alikor** [comment]
> @alikor Is the service reachable on the default path specified here?

Yes 

I was told by a Microsoft support guy to look at how omsagent-rs deployment works I attempted to simulate it but with no luck

**Comment by immuzz** [comment]
@keikhara are you aware of this?

**Comment by palma21** [comment]
@marosset @jsturtevant any ideas?

**Comment by jsturtevant** [comment]
@alikor can you try adding `cmd /c` or `powershell /c` to the commands?

A working example is: 

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    args:
    - powershell
    - /c
    - mkdir c:\\tmp; fsutil file createnew c:\\tmp\healthy 100; Start-Sleep -s 30; del  c:\\tmp\healthy;  Start-Sleep -s 600
    livenessProbe:
      exec:
        command: 
        - cmd 
        - /c 
        - dir 
        - c:\tmp\healthy
      initialDelaySeconds: 5
      periodSeconds: 5
  nodeSelector:
    "kubernetes.io/os": windows
```
