### ISSUE TITLE
AKS not following kubespec 1.16.x PriorityClassName unknown field

### ISSUE THREAD

**Issue by JaeTLDR** [Azure/AKS#1841]
**What happened**:
when creating a deployment with a priority class using Azure DevOps kubectl task it errors saying it does not match the deployment spec 
`error validating data: ValidationError(deployment.spec.template): unknown field "priorityClassName" in io.k8s.api.core.v1.PodTemplateSpec;`
**What you expected to happen**:
A deployment with the correct priorityClass deployed successfully to kubernetes
**How to reproduce it (as minimally and precisely as possible)**:
create a priority class:
```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: staging
value: 1000000
globalDefault: false
description: "This priority class should be used for staging pods only."
```
create a deployment with said priority class
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: db
          env:
          - name: "POSTGRES_DB"   
            value: "postgresdb"
          - name: "POSTGRES_USER" 
            value: "postgresadmin"
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      priorityClassName: staging
```
**Anything else we need to know?**:
yaml was tested against online kubernetes yaml checkers and i read the spec for 1.16 to confirm this was expected behaviour
(https://kubeyaml.com/)

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"1c93c592501dbc0c14e23b5ea2be8f6ea947a3a5", GitTreeState:"clean", BuildDate:"2020-08-25T01:56:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
utiltiy services to support future microservice apis
- Others:
