### ISSUE TITLE
Persistent volume Azure Files OSError: [Errno 524] Unknown error 524

### ISSUE THREAD

**Issue by BlackRider97** [Azure/AKS#1848]
**What happened**:
Created PVC of size 1 Gi of Azure Files with following Storage class definition YAML

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
```

After that I have created 50 Pods with same PVC.  
Few Pods are randomly getting `OSError: [Errno 524] Unknown error 524` error while creating directories or reading/writing file.

**What you expected to happen**:
Concurrent modification & read should be supported by Azure Files Standard_LRS

**How to reproduce it (as minimally and precisely as possible)**:
1. Create PV with specified storage class of size 1 Gi
2. Create a PVC and spawn 100 Pods, do concurrent read & write

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): AKS 1.18.6
- Size of cluster (how many worker nodes are in the cluster?) 10 D4s_v3 worker nodes
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
