### ISSUE TITLE
Unable to Scale down node when dashboard-metrics-scraper is installed

### ISSUE THREAD

**Issue by ncole** [Azure/AKS#1874]
**What happened**:
After seeing https://github.com/Azure/AKS/issues/1565 I decided to try scale-to-zero.  I attempted two node pools, one CPU and one GPU and added deployments to both pools.  After scale-down the GPU node pool achieved zero nodes.  However, the CPU pool stayed available.

**What you expected to happen**:
CPU-based nodes should move to zero.

**Anything else we need to know?**:
There was one deployment left on my nodes:  `dashboard-metrics-scraper`, and I could not move it off my worker CPU nodes.  This deployment cannot be changed; the affinity gets reset every time I make a change.  The deployment has an affinity section like below, which pretty much guarantees it can be deployed on a node pool that I intend to scale to zero:
```
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.azure.com/mode
                operator: In
                values:
                - system
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
```

Are there any other taints I can use on my node pool to prevent this from happening?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.15
- Size of cluster (how many worker nodes are in the cluster?): A total of 8 nodes, with scale to zero enabled.
