### ISSUE TITLE
Windows node pool with Basic Load Balancer

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AKS#1888]
[Release 2020-07-27](https://github.com/Azure/AKS/releases/tag/2020-07-27)
> We've added additional validations to prevent the creation of multiple node pool clusters with Basic Load Balancer which isn't supported.

**Multiple node pool clusters with Basic Load Balancer is necessary for us, can you revert it back.**

We are running Windows containers, our services need static outbound ip, we bind Basic Load Balacer to Windows node pools to archive it(one BLB per pool), **we don't want to use Standard Load Balancer because it is charged per GB**, because there is heavy inbound/outbound traffic in Windows containers. 

There is at least one default Linux pool, so we can't add Windows node pool to AKS with BLB now.
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-mode: "poolname"
  name: apcs-egress-job
spec:
  type: LoadBalancer
  loadBalancerIP: 52.230.6.113
  ports:
  - protocol: TCP
    port: 80
```
