### ISSUE TITLE
Upgrade of an AKS cluster causes deletion of existing User Managed Identities

### ISSUE THREAD

**Issue by miwithro** [Azure/AKS#1903]
**Summary** 
In Managed Identity AKS clusters, when the cluster is scaled up/upgraded the identities that are associated with the underlying nodes are removed. This can cause applications that use the identity to fail while fetching a token after upgrade/scale.

Similar issue reported - #639 and #633

**Bug and Fix**
Yes, we had an issue about the role bindings removal on Oct. 5th 2020 and a remediation was deployed on Oct. 14th 2020. The fix was to add the cluster role aad-pod-id-nmi-role and cluster rolebinding aad-pod-id-nmi-binding back on clusters we identified where they had been removed.

But we may miss some of the clusters. For these clusters, customers can add back the cluster role / cluster role binding by themselves.

**Comment by miwithro** [comment]
Opened issue for advisory purposes.  Closing issue now.

**Comment by bcho** [comment]
for the cluster role / role binding to add back:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aad-pod-id-nmi-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureidentitybindings", "azureidentities", "azurepodidentityexceptions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["aadpodidentity.k8s.io"]
  resources: ["azureassignedidentities"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aad-pod-id-nmi-binding
  labels:
    k8s-app: aad-pod-id-nmi-binding
subjects:
- kind: ServiceAccount
  name: aad-pod-id-nmi-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: aad-pod-id-nmi-role
  apiGroup: rbac.authorization.k8s.io
```
