### ISSUE TITLE
AKS not able to create outbound connections 

### ISSUE THREAD

**Issue by david-freistrom** [Azure/AKS#1918]
**What happened**:
Nodepool could not configured because of unable to create outbound connection

"Deployment failed. Correlation ID: 11a09b34-8fca-4bc7-b16c-83328932c306. Unable to establish outbound connection from agents, please see https://aka.ms/aks-required-ports-and-addresses for more information. Details: VMSSAgentPoolReconciler retry failed: deployment operations failed with error messages: {\n  \"code\": \"VMExtensionProvisioningError\",\n  \"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=50\\n[stdout]\\nThu Oct 22 04:38:26 UTC 2020,aks-akspoolmin-35064155-vmss000000\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \",\n  \"details\": [\n   {\n    \"code\": \"VMExtensionProvisioningError\",\n    \"message\": \"VM has reported a failure when processing extension 'vmssCSE'. 

**What you expected to happen**:
Nodes are able to create outbound connections

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
---
- name: Include variables for VPC
  include_vars:
    file: "{{ role_path }}/vars/vpc.yml"

- name: Create a resource group for VPC
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    tags:
      environment: testing

- name: Create virtual network (HUB)
  block:
    - name: Create virtual network (HUB)
      azure_rm_virtualnetwork:
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        name: "{{ hub_vnet.name }}"
        address_prefixes: "{{ hub_vnet.cidr }}"
        tags:
          environment: testing

    - name: For all Subnets do
      include_tasks: subnet.yml
      loop: "{{ hub_vnet.subnets }}"
      loop_control:
        loop_var: sn
        label: "{{ sn.name }}"
      vars:
        vn_name: "{{ hub_vnet.name }}"

    - name: Create Public IP for Firewall
      azure_rm_publicipaddress:
        state: present
        resource_group: "{{ resource_group }}"
        name: "{{ firewall.public_ip.name }}"
        location: "{{ location }}"
        allocation_method: static
        sku: standard
      register: public_ip


    - name: Set Facts about created public IP address
      set_fact:
        fw_public_ip: "{{ public_ip.state }}"

    - name: Debug
      debug:
        msg: "{{ fw_public_ip }}"

    - name: Create Azure Firewall Instance
      azure_rm_azurefirewall:
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        name: "{{ firewall.name }}"
        tags:
          environment: testing
        ip_configurations:
          - name: fw_ip_config
            subnet: "{{ vars['AzureFirewallSubnet'] }}"
            public_ip_address: "{{ firewall.public_ip.name }}"
        network_rule_collections:
          - name: aksbasics_network
            priority: 100
            action: Allow
            rules:
              - name: allow_all
                destination_addresses: ["*"]
                destination_ports: ["*"]
                protocols: ["UDP", "TCP"]
                source_addresses: ["*"]
              - name: allow_ntp
                destination_addresses: ["*"]
                destination_ports: ["123"]
                protocols: ["UDP"]
                source_addresses: ["*"]
              - name: allow_dns
                destination_addresses: ["*"]
                destination_ports: ["53"]
                protocols: ["UDP"]
                source_addresses: ["*"]
              - name: allow_services
                destination_addresses: ["AzureContainerRegistry", "MicrosoftContainerRegistry", "AzureActiveDirectory", "AzureMonitor", "AzureDevSpaces", "AzureCloud"]
                destination_ports: ["*"]
                protocols: ["TCP", "UDP"]
                source_addresses: ["*"]

        application_rule_collections:
          - name: aks_services
            priority: 101
            action: Allow
            rules:
              - name: allow_kube_service
                source_addresses: ["*"]
                fqdn_tags:
                  - AzureKubernetesService
                protocols:
                  - port: '80'
                    type: http
                  - port: '443'
                    type: https
          - name: aksbasics_apps
            priority: 102
            action: Allow
            rules:
              - name: allow network
                source_addresses: ["*"]
                target_fqdns:
                  - "*"
                  - "*.hcp.westeurope.azmk8s.io"
                  - "mcr.microsoft.com"
                  - "*.cdn.mscr.io"
                  - "*.data.mcr.microsoft.com"
                  - "management.azure.com"
                  - "login.microsoftonline.com"
                  - "packages.microsoft.com"
                  - "acs-mirror.azureedge.net"
                  - "gov-prod-policy-data.trafficmanager.net"
                  - "raw.githubusercontent.com"
                  - "dc.services.visualstudio.com"
                  - "cloudflare.docker.com"
                  - "gcr.io"
                  - "storage.googleapis.com"
                  - "dc.services.visualstudio.com"
                  - "*.monitoring.azure.com"
                  - "*.oms.opinsights.azure.com"
                  - "*.ods.opinsights.azure.com"
                  - "security.ubuntu.com"
                  - "azure.archive.ubuntu.com" 
                  - "changelogs.ubuntu.com"
                protocols:
                  - port: '80'
                    type: http
                  - port: '443'
                    type: https

    - name: Get facts about created Firewall
      azure_rm_azurefirewall_info:
        resource_group: "{{ resource_group }}"
        name: "{{ firewall.name }}"
      register: aks_fw

    - name: Set facts about created Firewall
      set_fact:
        aks_fw: "{{ aks_fw.firewalls }}"

    - name: Debug FW
      debug:
        msg: "{{ aks_fw }}"

    - name: Enabe DNS proxy for the FW
      command: az network firewall update \
        --resource-group "{{ resource_group }}" \
        --name "{{ firewall.name }}" \
        --enable-dns-proxy true \
        --require-dns-proxy-for-network-rules true

    - name: Create Public IP for VPN
      azure_rm_publicipaddress:
        state: present
        resource_group: "{{ resource_group }}"
        name: "{{ vpn.public_ip.name }}"
        location: "{{ location }}"
        allocation_method: static
        sku: "{{ vpn.sku }}"
        tags:
          envrionment: testing
      register: public_ip

    - name: Create virtual network gateway
      azure_rm_virtualnetworkgateway:
        state: present
        resource_group: "{{ resource_group }}"
        name: "{{ vpn.name }}"
        location: "{{ location }}"
        enable_bgp: "{{ vpn.enable_bgp }}"
        gateway_type: vpn
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        secret: "{{ lookup('env', 'AZURE_SECRET') }}"
        tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
        subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
        ip_configurations:
          - name: vpn_ip_config
            private_ip_allocation_method: "{{ vpn.private_ip_allocation_method }}"
            public_ip_address_name: "{{ vpn.public_ip.name }}"
            #subnet: VPNSubnet
        virtual_network: "{{ hub_vnet.name }}"
        tags:
          envrionment: testing

- name: Create virtual network (SPOKE)
  block:
    - name: Create virtual network (SPOKE)
      azure_rm_virtualnetwork:
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        name: "{{ kube_vnet.name }}"
        address_prefixes: "{{ kube_vnet.cidr }}"
        tags:
          environment: testing

    - name: For all Subnets do
      include_tasks: subnet.yml
      loop: "{{ kube_vnet.subnets }}"
      loop_control:
        loop_var: sn
        label: "{{ sn.name }}"
      vars:
        vn_name: "{{ kube_vnet.name }}"

- name: Create virtual network peering hub2spoke
  azure_rm_virtualnetworkpeering:
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ hub_vnet.name }}"
    name: "{{ hub_vnet.name }}_to_{{ kube_vnet.name }}"
    remote_virtual_network:
      resource_group: "{{ resource_group }}"
      name: "{{ kube_vnet.name }}"

- name: Create virtual network peering spoke2hub
  azure_rm_virtualnetworkpeering:
    resource_group: "{{ resource_group }}"
    virtual_network: "{{ kube_vnet.name }}"
    name: "{{ kube_vnet.name }}_to_{{ hub_vnet.name }}"
    remote_virtual_network:
      resource_group: "{{ resource_group }}"
      name: "{{ hub_vnet.name }}"

- name: Create Route Table for AKS
  azure_rm_routetable:
    resource_group: "{{ resource_group }}"
    name: "{{ routetable.name }}"
    tags:
      purpose: testing

- name: Create a route for Outbound Traffic
  azure_rm_route:
    resource_group: "{{ resource_group }}"
    name: Outbound2FW
    address_prefix: 0.0.0.0/0
    next_hop_type: virtual_appliance
    next_hop_ip_address: "{{ aks_fw.ip_configurations[0].properties.privateIPAddress }}"
    route_table_name: "{{ routetable.name }}"

- name: Associate RouteTable to Subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: "{{ kube_vnet.subnets[0].name }}"
    virtual_network: "{{ kube_vnet.name }}"
    address_prefix: "{{ kube_vnet.subnets[0].cidr }}"
    route_table: "{{ routetable.name }}"

- name: Create a DNS zone
  azure_rm_dnszone:   
    resource_group: Global
    name: "{{ dns_zone }}"
    tags:
      environment: testing
  register: dns

```

```bash
az aks create --resource-group "{{ resource_group }}" \
    --name "{{ aks_name }}" \
    --load-balancer-sku "{{ loadbalancer.sku | lower  }}" \
    --vm-set-type "{{ agent_pool_profiles[0].type }}" \
    --network-plugin "{{ network.network_plugin }}" \
    --network-policy "{{ network.network_policy }}" \
    --vnet-subnet-id /subscriptions/"{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"/resourceGroups/VPC/providers/Microsoft.Network/virtualNetworks/testingVNetKube/subnets/AKSSubnet \
    --docker-bridge-address "{{ network.docker_bridge_cidr }}" \
    --dns-service-ip "{{ network.dns_service_ip }}" \
    --service-cidr "{{ network.service_cidr }}" \
    --service-principal "{{ service_principal.client_id }}"
    --client-secret "{{ service_principal.client_secret }}" \
    --kubernetes-version "{{ aks_version }}" \
    --outbound-type userDefinedRouting \
    --ssh-key-value "{{ ssh_key }}" \
    --admin-username "{{ admin_username }}" \
    --dns-name-prefix "{{ dns_prefix }}" \
    --enable-cluster-autoscaler \
    --location "{{ location }}" \
    --node-vm-size "{{ agent_pool_profiles[0].vm_size }}" \
    --nodepool-name "{{ agent_pool_profiles[0].name }}" \
    --node-count "{{ agent_pool_profiles[0].count }}" \
    --max-count "{{ agent_pool_profiles[0].max_count }}" \
    --min-count "{{ agent_pool_profiles[0].min_count }}" \
    --tags [environment=testing] \
    --nodepool-tags [environment=testing]
```

```yaml
- name: Create Autoscaling strategy for VMSS
  azure_rm_autoscale:
    target: "{{ aks_vmss.id }}"
    enabled: true
    profiles:
      - name: MetricScaler
        count: "{{ agent_pool_profiles[0].count }}"
        min_count: "{{ agent_pool_profiles[0].min_count }}"
        max_count: "{{ agent_pool_profiles[0].max_count }}"
        rules:
          - direction: Increase
            metric_resource_uri: "{{ aks_vmss.id }}"
            metric_name: Percentage CPU
            operator: GreaterThan
            threshold: 70
            statistic: Average
            cooldown: 5
            value: 1
            time_grain: 1
            time_window: 10
            type: ChangeCount
          - direction: Decrease
            metric_name: Percentage CPU
            metric_resource_uri: "{{ aks_vmss.id }}"
            operator: LessThan
            threshold: 30
            statistic: Average
            cooldown: 5
            value: 1
            time_grain: 1
            time_window: 10
            type: ChangeCount
    name: autoscale
    resource_group: "{{ aks.properties.nodeResourceGroup }}"

- name: Upgrade all VMSS instances
  command: az vmss update-instances -g "{{ aks.properties.nodeResourceGroup }}" -n "{{ aks_vmss.name }}" --instance-ids "*"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.8
- Size of cluster (how many worker nodes are in the cluster?): 3-9
- AKS is created behind a firewall each in its own subnets with a rozting table for the kube subnet and dns proxy enabled as well as outboundType=userDefinedRouting and firewall is fully opened for all tarffik for debugging purposals.
