### ISSUE TITLE
Provide a configuration to define a registry mirror on AKS worker nodes

### ISSUE THREAD

**Issue by nmeisenzahl** [Azure/AKS#1940]
With the new Docker Hub rate-limit in place, it is a best practice to run/use a registry mirror.

I think this is something that needs to be defined on containerd and is therefore abstracted. It would be good to have a configuration parameter to optionally provide a registry mirror URL that then gets added to all nodes.

**Comment by simongottschlag** [comment]
Maybe something like this can be used until it's supported?


https://github.com/patnaikshekhar/AKSNodeInstaller

**Comment by TomGeske** [comment]
@nmeisenzahl: You want to provide a 3rd party mirror during cluster create?

**Comment by nmeisenzahl** [comment]
@TomGeske Yes. To minimize external dependencies (Docker Hub rate-limiting, Downtime of external registries) as well as faster pull-times. Retagging external images sometimes is an issue due to missing upgrade strategies and processes.

That said, a managed mirror (provided by Azure, maybe ACR) would be the best solution.

**Comment by TomGeske** [comment]
Maybe @SteveLasker has some thoughts on this.

**Comment by mayrstefan** [comment]
Is there any progress/planning with this issue?

This seems very similar to [aks-engine #3961](https://github.com/Azure/aks-engine/issues/3941) which also requests to make the ability of containerd to configure mirrors available via configuration
I would also request to add private ca certificates for those mirrors. With docker on earlier AKS versions some people have used [DaemonSets](https://github.com/coreos/tectonic-docs/blob/master/Documentation/admin/add-registry-cert.md) to add CA certificates to the docker daemon. I guess this won't work anymore.

**Comment by phealy** [comment]
Containerd backend support on Linux for this was implemented in 1.5, which shipped with AKS 1.22. I have implemented the configuration options to allow for configuring registry settings and CA certs in the Azure/AgentBaker#1369 PR, which should merge soon. Because of the holiday, it won't hit AKS until the first release next year, which should hit production probably around the end of January 2022. Once the release in January is created, this option will be applied when nodes are re-created on a [nodepool upgrade](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#upgrade-a-node-pool) or [node-image upgrade](https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade) **as long as the cluster is running at least version 1.22**. Check out [Containerd registry configuration](https://github.com/containerd/containerd/blob/0def98e462706286e6eaeff4a90be22fda75e761/docs/hosts.md) for information on what you can put in hosts.toml and how to use it.

You copy your registry configuration files into place using something like the following DaemonSet and ConfigMap. If you want to configure multiple registries, add more ConfigMaps (one for each registry) and mount them to `/src/certs.d/registryhostname`. Note that if you use a port in your image pull (like `myregistry.mydomain.com:5000`) you must put that port in the directory name. Also note that if you change the configmaps you'll need to restart the DaemonSet pods with `kubectl rollout restart -n kube-system daemonset/containerd-registry-config-daemon`.

```yaml
apiVersion: v1
data:
  docker-mirror.crt: |
    -----BEGIN CERTIFICATE-----
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    -----END CERTIFICATE-----
  hosts.toml: |
    [host."https://docker-mirror.internal"]
      capabilities = ["pull", "resolve"]
      ca = "docker-mirror.crt"
kind: ConfigMap
metadata:
  name: containerd-dockerio-mirror
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: containerd-registry-config-daemon
  namespace: kube-system
  labels:
    app: containerd-registry-config
spec:
  selector:
    matchLabels:
      app: containerd-registry-config
  template:
    metadata:
      labels:
        app: containerd-registry-config
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: copy-files
          image: busybox
          command:
            - /bin/sh
            - -c
            - cd /src;
              find */* -type d ! -name '..*' -exec mkdir -pv '/etc/containerd/{}' \;;
              find */* -type l ! -name '..*' -exec cp -v '{}' '/etc/containerd/{}' \;;
              echo "Done copying files.";
              sleep infinity
          volumeMounts:
            - name: hostcontainerd
              mountPath: /etc/containerd
            - name: dockerio
              mountPath: /src/certs.d/docker.io
      terminationGracePeriodSeconds: 0
      volumes:
        - name: hostcontainerd
          hostPath:
            path: /etc/containerd
            type: Directory
        - name: dockerio
          configMap:
            name: containerd-dockerio-mirror
```

**Comment by phealy** [comment]
reopening this issue until the change actually rolls to prod - it auto linked and I didn't realize it.

**Comment by phealy** [comment]
We're thinking about ways to make this more configurable, but for now the containerd change is available for new-build clusters on at least version 1.22 in eastus, with further regions to follow in the next week or so.

**Comment by giskou** [comment]
@phealy
Does AgentBaker support windows hosts?
Will the above, with the right path/image changes, work for windows hosts as well?

**Comment by phealy** [comment]
Not quite yet - but we are working on that!

**Comment by srikiz** [comment]
> Containerd backend support on Linux for this was implemented in 1.5, which shipped with AKS 1.22. I have implemented the configuration options to allow for configuring registry settings and CA certs in the [Azure/AgentBaker#1369](https://github.com/Azure/AgentBaker/pull/1369) PR, which should merge soon. Because of the holiday, it won't hit AKS until the first release next year, which should hit production probably around the end of January 2022. Once the release in January is created, this option will be applied when nodes are re-created on a [nodepool upgrade](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#upgrade-a-node-pool) or [node-image upgrade](https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade) **as long as the cluster is running at least version 1.22**. Check out [Containerd registry configuration](https://github.com/containerd/containerd/blob/0def98e462706286e6eaeff4a90be22fda75e761/docs/hosts.md) for information on what you can put in hosts.toml and how to use it.
> 
> You copy your registry configuration files into place using something like the following DaemonSet and ConfigMap. If you want to configure multiple registries, add more ConfigMaps (one for each registry) and mount them to `/src/certs.d/registryhostname`. Note that if you use a port in your image pull (like `myregistry.mydomain.com:5000`) you must put that port in the directory name. Also note that if you change the configmaps you'll need to restart the DaemonSet pods with `kubectl rollout restart -n kube-system daemonset/containerd-registry-config-daemon`.
> 
> ```yaml
> apiVersion: v1
> data:
>   docker-mirror.crt: |
>     -----BEGIN CERTIFICATE-----
>     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
>     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
>     -----END CERTIFICATE-----
>   hosts.toml: |
>     [host."https://docker-mirror.internal"]
>       capabilities = ["pull", "resolve"]
>       ca = "docker-mirror.crt"
> kind: ConfigMap
> metadata:
>   name: containerd-dockerio-mirror
>   namespace: kube-system
> ---
> apiVersion: apps/v1
> kind: DaemonSet
> metadata:
>   name: containerd-registry-config-daemon
>   namespace: kube-system
>   labels:
>     app: containerd-registry-config
> spec:
>   selector:
>     matchLabels:
>       app: containerd-registry-config
>   template:
>     metadata:
>       labels:
>         app: containerd-registry-config
>     spec:
>       nodeSelector:
>         kubernetes.io/os: linux
>       tolerations:
>         - key: node-role.kubernetes.io/master
>           operator: Exists
>           effect: NoSchedule
>       containers:
>         - name: copy-files
>           image: busybox
>           command:
>             - /bin/sh
>             - -c
>             - cd /src;
>               find */* -type d ! -name '..*' -exec mkdir -pv '/etc/containerd/{}' \;;
>               find */* -type l ! -name '..*' -exec cp -v '{}' '/etc/containerd/{}' \;;
>               echo "Done copying files.";
>               sleep infinity
>           volumeMounts:
>             - name: hostcontainerd
>               mountPath: /etc/containerd
>             - name: dockerio
>               mountPath: /src/certs.d/docker.io
>       terminationGracePeriodSeconds: 0
>       volumes:
>         - name: hostcontainerd
>           hostPath:
>             path: /etc/containerd
>             type: Directory
>         - name: dockerio
>           configMap:
>             name: containerd-dockerio-mirror
> ```

This works great, the only thing I suggest updating is adding toleration for everything so this runs on specific worker nodes from nodepools that have taints added.
`

        # tolerate everything so all nodepool taints are tolerated.
        - key: ""
          operator: Exists

`

**Comment by braunsonm** [comment]
Are there any plans to support registries with authentication? It seems the config for containerd in the supported directory (/etc/containerd/certs.d) does not support setting the CRI [registry credentials](https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-credentials).

This seems to require a daemon reload.

**Comment by alexeldeib** [comment]
> does not support setting the CRI [registry credentials](https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-credentials).

have you seen https://github.com/containerd/containerd/blob/main/docs/hosts.md#client-field?

> This seems to require a daemon reload.

that is unfortunately necessary right now, would be interesting to see if we can get containerd upstream to automatically reload those...

**Comment by braunsonm** [comment]
@alexeldeib That's for client certificates not auth tokens, identity tokens or username/passwords. You can get away with bas64 encrypted username/password with some registries but not all. Registries implementing OIDC authentication and [tokens limited to the scope](https://docs.docker.com/registry/spec/auth/token/) of the image being pulled (docker hub does this in most cases) would need clients to do this negotiation/token exchange. Containerd can do this from what I understand but only under the old config at the time of writing my original comment.

**Comment by alexeldeib** [comment]
hmm interesting point. does the mirror config + imagePullSecrets at k8s layer work for your use case? 

at a glance, it seems like the CRI config still works but is deprecated and the only supported way to pass creds for image pull/push to containerd is via CRI API? @cpuguy83 is that accurate?

I'd rather not add support for deprecated config, but not sure I totally follow what the alternative is // what your use case is if pull secrets or similar doesn't work

**Comment by braunsonm** [comment]
Yea exactly @alexeldeib 

That doesn't work in my use case as I'm trying to automatically my AKS cluster authenticate with docker hub for all pulls to avoid rate limiting.

**Comment by cpuguy83** [comment]
The deprecated config is the only other way to do this right now.
This *should* remain in place at least until 1.7 and would be removed after that in 2.0.

The only other approach at the moment is to use a registry cache which has the creds already.

**Comment by braunsonm** [comment]
> The only other approach at the moment is to use a registry cache which has the creds already.

You basically mean acting as a proxy right? A registry that sits on the AKS internal subnet without auth that can renegotiate with docker hub for the pull?

As far as I know there is no such offering in ACR

**Comment by cpuguy83** [comment]
@braunsonm Correct

**Comment by janegilring** [comment]
This might be of interest:
[Public Preview of Caching for ACR](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-public-preview-of-caching-for-acr/ba-p/3744655) was released  Feb 16 2023.

**Comment by phillebaba** [comment]
I have built a project called Spegel that does something similar but different. It is basically a best effort registry mirror that runs inside of your cluster while not requiring any additional PVs.
https://github.com/xenitAB/spegel

It relies on configuring Containerd mirror configuration in the node. Currently that is done through mounting the host path into the container and writing the required mirror configuration. This works because Containerd mirror configuration is hot loaded so no restart required. My thought was that it would be nice to not have to do this and instead write the configuration in the node template instead.

**Comment by masinger** [comment]
This issue has become more important since Docker now enforces the image pull limits for pulls coming from Azure (see https://github.com/Azure/acr/issues/754).

**Comment by zekena2** [comment]
What's the status of this issue? Can I configure registry mirrors through without the need of a hack like daemonset?

**Comment by scpcy** [comment]
At least give an interface so we can edit containerd specific configuration parameters.

**Comment by phealy** [comment]
This can be made to work today using a Daemonset to modify configuration files on the node. The example below is for mcr.microsoft.com, but this will work for any registry ACR caching supports.

There are two configurations given below:
 
1. The first option uses a static registry token, which is not optimal from a security perspective, but will work with any AKS cluster.
2. The second option uses [cloud-provider-azure](https://github.com/kubernetes-sigs/cloud-provider-azure)'s new support for [`--registry-mirror`](https://cloud-provider-azure.sigs.k8s.io/topics/credential-provider/#registry-mirror) in the kubelet credential plugin for Kubernetes 1.31+.

## Static token configuration (any AKS version)

1. Create your ACR cache rule. This sets up `<ACRNAME>.azurecr.io` with a cache rule to forward `/mcr/*` to `mcr.microsoft.com/*`.
   ![Image](https://github.com/user-attachments/assets/6ba2d02e-b42f-4c2c-8a62-6835cc8550c5)

2. Create an [ACR registry scoped token](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions):
   ![Image](https://github.com/user-attachments/assets/ab68c6e5-07cd-4266-95da-ed00aae1d004)

3. [Add a configuration file to your nodes to direct containerd to the appropriate mirror and path](https://github.com/containerd/containerd/blob/main/docs/hosts.md): `/etc/containerd/certs.d/mcr.microsoft.com/hosts.toml`
   ```toml
   [host."https://<ACRNAME>.azurecr.io/v2/mcr"]
     capabilities = ["pull", "resolve"]
     override_path = true
   ```

4. [Add credentials to your containerd configuration](https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-credentials):
   ```toml
   [plugins."io.containerd.grpc.v1.cri".registry.configs."<ACRNAME>.azurecr.io".auth]
     username = "TOKENNAME"
     password = "TOKENPASS"
   ```

5. Restart containerd:
   ```shell
   systemctl restart containerd
   ```

## Cluster identity configuration (AKS 1.31+)

1. Create your ACR cache rule. This sets up `<ACRNAME>.azurecr.io` with a cache rule to forward `/mcr/*` to `mcr.microsoft.com/*`.
   ![Image](https://github.com/user-attachments/assets/6ba2d02e-b42f-4c2c-8a62-6835cc8550c5)

2. [Make sure your cluster's identity has the AcrPull permission on your ACR.](https://learn.microsoft.com/azure/aks/cluster-container-registry-integration)

3. [Add a configuration file to your nodes to direct containerd to the appropriate mirror and path](https://github.com/containerd/containerd/blob/main/docs/hosts.md): `/etc/containerd/certs.d/mcr.microsoft.com/hosts.toml`
   ```toml
   [host."https://<ACRNAME>.azurecr.io/v2/mcr"]
     capabilities = ["pull", "resolve"]
     override_path = true
   ```

3. Modify the credential provider configuration at `/var/lib/kubelet/credential-provider-config.yaml`:
   ```yaml
   apiVersion: kubelet.config.k8s.io/v1
   kind: CredentialProviderConfig
   providers:
     - name: acr-credential-provider
       matchImages:
         - "*.azurecr.io"
         - "*.azurecr.cn"
         - "*.azurecr.de"
         - "*.azurecr.us"
         - "mcr.microsoft.com"
       defaultCacheDuration: "10m"
       apiVersion: credentialprovider.kubelet.k8s.io/v1
       args:
         - /etc/kubernetes/azure.json
         - --registry-mirror=mcr.microsoft.com:<ACRNAME>.azurecr.io
   ```
