### ISSUE TITLE
Specify outbound ip cause load balancer sync fail

### ISSUE THREAD

**Issue by oscar60310** [Azure/AKS#1945]
**What happened**:
According to [the document](https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#update-the-cluster-with-your-own-outbound-public-ip), we use our own public ip as the outbound ip of load balancer and it works well. But when we creating service with type `LoadBalancer`, the status of service stuck in `Pending`. Following events involving this service:

```
Code="LinkedAuthorizationFailed" Message="The client 'xxxxxx' with object id 'xxxxxx' has permission to perform action 'Microsoft.Network/loadBalancers/write' on scope '/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/loadBalancers/kubernetes'; however, it does not have permission to perform action 'Microsoft.Network/publicIPAddresses/join/action' on the linked scope(s) '/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/publicIPAddresses/xxxxxx' or the linked scope(s) are invalid."
```

```
Error syncing load balancer: failed to ensure load balancer: timed out waiting for the condition
```

After we given required permission to the application which the error message mentioned, everything works again.

**What you expected to happen**:
AKS will create a public ip for services with type `LoadBalancer`, so it shouldn't need additional permission on the outbound ip we provided.

**How to reproduce it (as minimally and precisely as possible)**:
1. Request a public IP

	```
	az network public-ip create -g xxx -n xxx --sku Standard
	```

1. Create a cluster and specify outbound ip

	```
	az aks create -g xxx -n xxx  --load-balancer-outbound-ips xxx
	```

1. Create a pod and a service with type LoadBalancer like below

	```yaml
   kind: Service
    apiVersion: v1
    metadata:
    name: test
    spec:
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: http
    selector:
      name: test
    type: LoadBalancer
   ```

1. Check the status and event of the service

**Anything else we need to know?**:
None.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.15
- Size of cluster (how many worker nodes are in the cluster?) 2 Node in single pool
