### ISSUE TITLE
NetworkPolicy with matchExpressions is not applied to matching pods

### ISSUE THREAD

**Issue by minrk** [Azure/AKS#2006]
**What happened**:

NetworkPolicy with matchExpressions is not applied to matching pods

**What you expected to happen**:

NetworkPolicy with matchExpressions is applied to matching pods

**How to reproduce it (as minimally and precisely as possible)**:

1. create a network policy with:

```yaml
    matchExpressions:
      - key: component
        operator: In
        values:
          - first-value
          - second-value
```

2. create a pod with:

```yaml
labels:
  component: first-value
```

3. verify whether network policy is applied. It will not be.

I used this policy to deny-all egress:

```yaml
spec:
  egress: []
  podSelector:
    matchExpressions:
    - key: component
      operator: In
      values:
      - first-value
      - second-value
  policyTypes:
  - Egress
```

and tested with `curl http://example.com`. It should be blocked. If the policy is applied, it is blocked. If the policy is not applied, it is not blocked. Interestingly, if `matchExpressions` values list has only one item, it is applied correctly. But if there are two or more items, matching pods are not considered to be matching pods, and no restrictions are applied. matchLabels and other selectors are applying as expected.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.10
- Size of cluster (how many worker nodes are in the cluster?): 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) web app: running http://mybinder.org via https://github.com/juptyerhub/mybinder.org-deploy, but I think any cluster running azure-npm will have this issue
- Others: azure-npm image:  mcr.microsoft.com/containernetworking/azure-npm:v1.1.8

original discovery of the issue: https://github.com/jupyterhub/mybinder.org-deploy/issues/1468
