### ISSUE TITLE
Low speed limitations for premium FileShares mounted to AKS

### ISSUE THREAD

**Issue by aristosvo** [Azure/AKS#2021]
**What happened**:
When we used on of our applications (photo viewer capability) in combination with an Azure Premium Storage Account and it's FileShare (size 600Gb) our maximum egress plateaued at 1MiB/s. It's a clear straight line after reaching it's max.

![MaxEgress](https://user-images.githubusercontent.com/8375124/102007837-8ee28f80-3d2c-11eb-9e86-630599b0e845.png)

**What you expected to happen**:
To have maximum egress capacity, which for 600Gb is  96.0 MiBytes / s

**How to reproduce it (as minimally and precisely as possible)**:
- Create a premium file share (Storage Account type: FileStorage, FileShare size 600Gb, VNET Service Endpoint)
- Create a secret containing `azurestorageaccountname`and `azurestorageaccountkey`
- Create a PVC and PV for the fileshare:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 600Gi
  storageClassName: azurefile-premium
  volumeMode: Filesystem
  volumeName: pv
```
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: <storage-credentials>
    shareName: <fileshare name>
  capacity:
    storage: 600Gi
  mountOptions:
  - file_mode=0777
  - nobrl
  - mfsymlinks
  - dir_mode=0777
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-premium
  volumeMode: Filesystem
```

**Anything else we need to know?**:
- 

**Environment**:
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?)
7 (different machines didn't solve the issue or change max egress)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
HTTP microservices, Java app
- Others:
-
