### ISSUE TITLE
Metrics does not treat lost node as NotReady

### ISSUE THREAD

**Issue by yene** [Azure/AKS#2034]
**Steps**
1. Create new cluster with insights
2. Enable Recommeded Alert (preview) **Node NotReady status**
3. SSH into node and stop kubelet with `sudo systemctl stop kubelet`

**Expected**
1. Metrics nodesCount (Insights.Container/nodes) to display that a node is NotReady
2. An alert that NotReady count is bigger than 0

**whats happening**
Metrics show missing value, instead of a NotReady node.
![shot 2020-12-22 at 10 06 59](https://user-images.githubusercontent.com/63942/102870998-1ec7be00-443e-11eb-9adc-73f83b24c0d0.png)

**Other notes**
kubelet losing connection is a real issue we had three times on older Kubernetes versions, thats why I want this metric/alert to be solid.

K9s correctly shows that node is problematic.
![shot 2020-12-22 at 10 04 12](https://user-images.githubusercontent.com/63942/102871043-330bbb00-443e-11eb-9518-69e53280fc4a.png)

Node has taint:
```
    taints:
    - effect: NoSchedule
      key: node.kubernetes.io/unreachable
      timeAdded: "2020-12-21T17:57:35Z"
```
