### ISSUE TITLE
hostPort not working with kubenet and Kubernetes >= 1.19.3

### ISSUE THREAD

**Issue by lkysow** [Azure/AKS#2070]
**What happened**: Host ports do not seem to be supported with kubenet networking. Tested with Kubernetes 1.19.3, 1.19.6

**What you expected to happen**: host ports should be routable

**How to reproduce it (as minimally and precisely as possible)**:

Run this DaemonSet that exposes host port 8080 and a test deployment.
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
              hostPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostport-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostport-test
  template:
    metadata:
      labels:
        app: hostport-test
    spec:
      containers:
        - image: curlimages/curl
          name: hostport-test
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do curl -sS $(HOST_IP):8080/get; sleep 1; done;" ]
```

Look at the logs for hostport-test:
```
kubectl logs -f deploy/hostport-test
curl: (7) Failed to connect to 10.240.0.4 port 8080: Connection refused
curl: (7) Failed to connect to 10.240.0.4 port 8080: Connection refused
...
```

On GKE:
```
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "10.128.0.55:8080",
    "User-Agent": "curl/7.74.0-DEV"
  },
  "origin": "10.32.9.84",
  "url": "http://10.128.0.55:8080/get"
}
...
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3 and 1.19.6 `Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}`
- Size of cluster (how many worker nodes are in the cluster?) 3
