### ISSUE TITLE
HPA shows up abnormal behaviour when there is a rolling update

### ISSUE THREAD

**Issue by ThilinaManamgoda** [Azure/AKS#2132]
**What happened**:
We have deployed the following HPA and we could observe that when there is a rolling update, HPA scales up the pod count even when the average memory consumption is lower than the target memory threshold 65%.  We tried the same thresholds with the HPA API version `autoscaling/v2beta2`, still we could observe the same behaviour. 
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"Resource","resource":{"name":"memory","targetAverageUtilization":65}}]'
  name: app-hpa
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  targetCPUUtilizationPercentage: 65
```
**What you expected to happen**:
When there is an on going rolling update, HPA doesn't scale up the pod count when the average memory consumption is lower than the defined threshold.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Please note that we have defined the resource request/limits for memory and CPU in the Deployment.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.3
- Size of cluster (how many worker nodes are in the cluster?): 5
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Java application
- Others:
