### ISSUE TITLE
Should nmi (Pod Managed Identity) add-on tolerate all taints?

### ISSUE THREAD

**Issue by ckittel** [Azure/AKS#2146]
In my cluster with four node pools (one system, three user pools).  Two of the three user node pools share a taint. The remaining has it's own (different) Taint as well. This means that all user node pools have a taint. In this cluster workloads all need to have their appropriate tolerations (one or both of those). I was caught by surprise when `nmi` was subject to the taints. All other system add-ons seem to have the standard `:NoExecute op=Exists` and `:Schedule op=Exists` and `CriticalAddonsOnly op=Exists` tolerations, but `nmi` has no tolerations (outside of default daemonset condition taints like node disk-pressure, pid-pressure, etc).

Two observations:
1. `nmi` doesn't have doesn't have the `CriticalAddonsOnly` toleration. For me this is fine, because if I taint the system node pool (as suggested by the docs), it won't be scheduled there as I don't have needs for it there.  However, I could see some wanting it on the system node pool (even if you shouldn't be running user workloads there).
1. Because `nmi` doesn't have `:NoExecute op=Exists` and `:Schedule op=Exists` tolerations, my nodepool taints used for the [dedicated nodes use case](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases) (vs system caps concerns), are blocking the deployment of the `nmi` cluster wide.

Should `nmi` -- as deployed as an add-on -- be more permissive in its tolerations?

Kubernetes version: 1.20.2

**Comment by miwithro** [comment]
@aramase @bcho

**Comment by bcho** [comment]
Ack and thanks for the feedback, we will add these taints for nmi deployment in the upcoming release. cc @miwithro

**Comment by adammal** [comment]
This request would be very useful to us. We would like to make use of dedicated node pools and at present the NMI DaemonSet is not deploying to our tainted node pool.
Any idea when this might become available?

**Comment by bcho** [comment]
In AKS side, we already added these tolerations to the nmi daemonset:

```
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
```
