### ISSUE TITLE
Unable to provision PVC due to bad apiVersion ARM send from AKS

### ISSUE THREAD

**Issue by mark-nexplore** [Azure/AKS#2148]
**What happened**:
When trying to provision new deployment (I was loading prometheus via Helm3), there seems to be a problem for it to provision the necessary PVCs via ARM, as these events pops up:
```
monitoring   0s          Warning   FailedAttachVolume       pod/prometheus-server-594d88c7df-5bpfb                      AttachVolume.Attach failed for volume "pvc-c881a64b-1d64-4d9f-8b1d-1845a6869b8b" : rpc error: code = Unknown desc = Attach volume "/subscriptions/67f83782-d232-49e3-a3c4-67ff9365673a/resourceGroups/mc_rg-eas-dev-cpcs55_laiotest-cpcs55-aks_eastasia/providers/Microsoft.Compute/disks/pvc-c881a64b-1d64-4d9f-8b1d-1845a6869b8b" to instance "aks-agentpool1-13087634-2" failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "InvalidParameter",
    "message": "Storage account type 'StandardSSD_LRS' is supported by Microsoft.Compute API version 2018-04-01 and above",
    "target": "dataDisk.managedDisk.storageAccountType"
  }
}
```
It seems the ARM request sent is using a old version and thus failing.

**What you expected to happen**:
The Persistent Volume Claim should be created with the appropriate ARM apiVersion and return a HTTP 200 instead of 400.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new AKS cluster
2. Install Helm chart for Prometheus from prometheus-community.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T15:16:40Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster: 7 worker nodes
- Workload: This is a fresh cluster just created running on Kubernetes 1.20
- Others:

**Comment by andyzhangx** [comment]
which region are you on? and could you provide your helm config?
I tried to use this example on aks 1.20.2 cluster, it could not repro. Would you try this example on your cluster, you only need to change `managed-csi` to `default` and then apply that statefuset: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/statefulset.yaml#L38

**Comment by mark-nexplore** [comment]
HI @andyzhangx,

Our cluster sits on `eastasia`. I actually try to run the helm based on default that triggered this. Have not tried with managed-csi actually since it still preview I assume from reading the from docs.microsft.com.

As for triggering the repo:
```
> helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
> helm repo update
> helm install prometheus prometheus-community/prometheus \
     --namespace monitoring \
     --set alertmanager.persistentVolume.storageClass="default" \
     --set server.persistentVolume.storageClass="default"
```
The logs comes a few seconds when I do `kubectl get events --watch`

**Comment by andyzhangx** [comment]
just try this, does it work?
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azuredisk
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-azuredisk
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-azuredisk
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/azuredisk
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: default
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
```
