### ISSUE TITLE
AKS does not create Loadbalancer in the correct subnet

### ISSUE THREAD

**Issue by hibri** [Azure/AKS#221]
I'm using https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters and the Terraform provider
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

AKS spins up the agent nodes in the specified subnet. However when I spin up a service with the yaml below, the internal load balancer is spun up in the MC_ resource group and the Vnet in the MC_resource group and not in the subnet specified in vnetSubnetID parameter

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kuard-service-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kuard-front
```
