### ISSUE TITLE
Performance of Azure Premium Files (NFS/CFIS)/file.csi seems poor

### ISSUE THREAD

**Issue by jabbera** [Azure/AKS#2211]
**What happened**: Local disk is 190X the performance of using a mount backed by Azure Files Premium NFS or CIFS

![image](https://user-images.githubusercontent.com/301208/112010827-09763480-8afe-11eb-93f4-0dc651150af4.png)

**What you expected to happen**: Mounts should be faster

**How to reproduce it (as minimally and precisely as possible)**:

Create pod with volume NFS\CIFS and emptyDir mount. Run the following in each.

```
curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_3367a.zip
time unzip -q kagglecatsanddogs_3367a.zip
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Size of cluster (how many worker nodes are in the cluster?): 8
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Jupyterhub
- Others:

```
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
mountOptions:
  - dir_mode=0700
  - file_mode=0700
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
  - actimeo=30
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-user
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # if set as "Delete" file share would be removed in pvc deletion
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      resourceGroup: blah  # optional, only set this when storage account is not in the same resource group as agent node
      storageAccount: blah
      shareName: users  # only file share name, don't use full path
      protocol: nfs
```
