### ISSUE TITLE
No outgoing connections possible after sigterm

### ISSUE THREAD

**Issue by joggeli34** [Azure/AKS#2223]
**What happened**:

As soon as the containers receives the sigterm, they lose all the outgoing connections. This way we are not able to terminate websockets gracefully and to save the current state to the azure storage. It's also not possible to open new connections (eg. to the azure storage)

**What you expected to happen**:

All outgoing connections staying open, so that they can be ended gracefully. New connection to save state should work without problems.

**How to reproduce it (as minimally and precisely as possible)**:

Create a container that calls a http-enpoint as part of the shutdown hook when receiving sig term

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.2
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Http microservices & Java with websockets
- Others:

**Comment by joggeli34** [comment]
I now tried it with version 1.20.5 and node-pools with version (1.19.9, 1.20.2, 1.20.5) and the problem still exists every where. Is there something that I can do so the network stay up until the grace-period of the pod has ended?

With the current situation we lose every time a container restart the state and data. 
Can you confirm that this behavior is normal or just somehow special in my case?

**Comment by paulgmiller** [comment]
My understanding is CNI shouldn't get a DELETE until after the containers in a pod are torn down. So I don't have any reason to believe this would happen.  Do you have an example container/dockerfile?

**Comment by joggeli34** [comment]
Hi @paulgrimley 

Yes that's my understanding too. When I'm running following deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
  labels:
    app: test
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      restartPolicy: Always
      containers:
      - name: test
        image: byrnedo/alpine-curl:latest
        command: [ "/bin/sh" ]
        args: [ "-c", "while true; echo call; do curl --silent --show-error -w \"\n\" https://postman-echo.com/get; sleep 5;done" ]
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sh","-c","echo ending > /proc/1/fd/1" ]
``` 

I get following log:

```
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-6086802f-749695882046c9be6ae77ce7","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
call
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-60868034-689a109a7d5330b42e54ad23","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
call
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-6086803a-4ac5577278bfb5f21aed1c46","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
call
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-6086803f-2cf370d503239e9954a98890","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
call
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-60868045-13e8384b0b0dcbf834745b90","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
call
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-6086804a-5f9678d5240a945b7bb97116","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
call
{"args":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-6086804f-6619e6f76dcb05ae64ae6be9","user-agent":"curl/7.66.0","accept":"*/*"},"url":"https://postman-echo.com/get"}
ending
call
curl: (6) Could not resolve host: postman-echo.com

call

curl: (6) Could not resolve host: postman-echo.com
```

As we see, as soon as the preStop hook is called ("ending" log) the calls don't reach their target any more. Here it are host-resolving errors. In our production code we mostly get socket timeouts
