### ISSUE TITLE
Public IPs are not freed after Kubernetes resource deletion

### ISSUE THREAD

**Issue by lynshi** [Azure/AKS#2239]
**What happened**:

We installed a Helm release including the following resource:
```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadBalancerName | quote }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.dnsLabelName | quote }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ .Values.selectorName | quote }}
  ports:
  - port: {{ .Values.loadBalancerPort }}
    targetPort: {{ .Values.containerPort }}
```

After some time, we deleted the release and namespace (thereby deleting the Load Balancer resource). A few hours later, we reinstalled the release with the same Helm values file as before. This time, the Load Balancer never became Ready due to a DNS name conflict.

```
Name:                         lb-name
Namespace:                namespace-name
Labels:                         app.kubernetes.io/managed-by=Helm
Annotations:               meta.helm.sh/release-name: helm-release-name
                                    meta.helm.sh/release-namespace: namespace-name
                                    service.beta.kubernetes.io/azure-dns-label-name: dns-label-name
Selector:                      app.kubernetes.io/name=selector-name
Type:                           LoadBalancer
IP Families:                  <none>
IP:                               10.0.54.163
IPs:                             <none>
Port:                            <unset>  443/TCP
TargetPort:                  16385/TCP
NodePort:                    <unset>  32246/TCP
Endpoints:                   10.240.0.105:16385,10.240.0.74:16385,10.240.1.63:16385
Session Affinity:           None
External Traffic Policy:  Cluster
Events:
  Type     Reason                         Age                  From
 Message
  ----     ------                         ----                 ----
 -------
  Normal   EnsuringLoadBalancer           76s (x6 over 3m55s)  service-controller    Ensuring load balancer
  Warning  CreateOrUpdatePublicIPAddress  76s (x6 over 3m54s)  azure-cloud-provider  network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DnsRecordInUse" Message="DNS record <dns-name>.eastus.cloudapp.azure.com is already used by another public IP." Details=[]
  Warning  SyncLoadBalancerFailed         76s (x6 over 3m54s)  service-controller    Error syncing load balancer: failed to ensure load balancer: timed out waiting for the condition
```

**What you expected to happen**:
Deleting the Kubernetes Load Balancer resource should also delete the provisioned public IP. We have observed this to be the case in the past.

**Anything else we need to know?**:
Having gone through a list of provisioned public IPs in the Azure Portal, it appears that some older IPs associated with deleted Kubernetes Load Balancers were also not deleted.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.16
- Size of cluster (how many worker nodes are in the cluster?): 20
- VMs: [Standard_DC4s_v2](https://docs.microsoft.com/en-us/azure/virtual-machines/dcv2-series)
