### ISSUE TITLE
Service Tag Annotation is not being enforced

### ISSUE THREAD

**Issue by tshaiman** [Azure/AKS#2281]
**What happened**:
using AKS version 1.19.4 and with nginx-ingress controller I have created the following custom definition for the ingress-nginx controller : 

```yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-allowed-service-tags: "AzureFrontDoor.Backend"
    loadBalancerSourceRanges: ["20.193.26.137/32","<other_ip>"]

```
The definitions appear as  NSG rules accordingly , but the FrontDoor is still blocked from access.  the loadBalancerSourceRanges rule is being respected correctly.
when removing the loadBalancerSourceRanges list, only then, the FrontDoor rule is being enforced.

working example (which prevents us from enforcing specific IP ranges) :

```yaml
controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-allowed-service-tags: "AzureFrontDoor.Backend"
   
```

**What you expected to happen**:
The Front Door service tag should be enforced along side with the loadBalancerSourceRanges as they both appear in the NSG rule list. 
**How to reproduce it (as minimally and precisely as possible)**:
- create AKS cluster in any region
- install nginx-ingress controller
- apply the above custom definitions and notice that FrontDoor traffic is blocked when there Source rangers are defined.

**Anything else we need to know?**:

could be related to https://github.com/Azure/AKS/issues/1813

**Environment**:
- Kubernetes version (use `kubectl version`):  1.19.4
- Size of cluster (how many worker nodes are in the cluster?) 4 worker nodes , 2-5 nodes each ,size : Standard_D3_v2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : Https web server with nodeJS as Linux containers.
