### ISSUE TITLE
Schedule pod on System node poolds

### ISSUE THREAD

**Issue by jeliasson** [Azure/AKS#2293]
**What happened**:

I have one `System` node pool and one `User` node pool with two agents in each. I want to have my pods in a `DaemonSet` also schedule on the `System` node pool, as this DaemonSet is a Telegraf pod for monitoring the node.

**What you expected to happen**:
When I set a DaemonSet's spec `priorityClassName` to either `system-cluster-critical` or `system-node-critical` it should also schedule the pods on the `System` node pool(s).

**How to reproduce it (as minimally and precisely as possible)**:
1. Have one `System` node pool and one `User` node pool
2. Apply a `DaemonSet` with `priorityClassName` set to `system-cluster-critical`
3. Pods is now scheduled only on `User` node pool(s)

```yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: nginx
          image: nginx
```

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.20.5`
- Size of cluster (how many worker nodes are in the cluster?) `4`
- General description of workloads in the cluster: General web applications and database
- Others:

**Comment by awillows** [comment]
Priorities shouldn't affect what is scheduled to the system pool. 

Does your system pool have a taint on it that could prevent the DS pods being scheduled? If you created it as per documentation it may have CriticalAddonsOnly=true:NoSchedule. If so then a toleration on your DS should help:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: nginx
          image: nginx
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
```
