### ISSUE TITLE
[k8s 1.20] BYO Public static IP is deleted automatically after k8s service of type LoadBalancer is deleted

### ISSUE THREAD

**Issue by petermicuch** [Azure/AKS#2301]
**What happened**: After deletion of kubernetes service of type `LoadBalancer` associated **public static IP address** was also deleted.

**What you expected to happen**: When I delete kubernetes service of type `LoadBalancer` that is associated with **public static IP address** from the same or different resource group, I do not expect that the IP address would be deleted. This forces us to update DNS records with new IP if we are going to recreate the service again. This is a bug and according to description in this [article](https://docs.microsoft.com/en-us/azure/aks/static-ip), public static IP address should not be deleted when k8s service related to such IP is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
* Create AKS cluster with SKU Basic LoadBalancer with contributor access to resource group with your public IPs (e.g. PUBLIC-IPS-RESOURCE-GROUP).
* Create **public static IP address** (SKU Basic) in PUBLIC-IPS-RESOURCE-GROUP resource group (e.g. 52.174.23.140).
* Create LB service that uses that **public static IP address**
```
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: PUBLIC-IPS-RESOURCE-GROUP
  name: reverse-proxy
  labels: 
    area: platform
    track: latest
spec: 
  loadBalancerIP: 52.174.23.140
  type: LoadBalancer
  selector: 
    platform-app: reverse-proxy-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
  - protocol: TCP
    port: 443
    targetPort: https
    name: https
```
* Once IP is associated with LoadBalancer, delete the service
```
kubectl delete service reverse-proxy
```
* Observe resource group PUBLIC-IPS-RESOURCE-GROUP and notice, that IP address will get deleted in few minutes.

**Environment**:
- Kubernetes version: v1.20.2
- Size of cluster: 8 nodes
- General description of workloads in the cluster: HTTP microservices
- Others: Subscription where I reproduced this multiple times - 90a3dc22-a884-4560-ab8f-45222e67333e
