### ISSUE TITLE
Azure Files with Docker DIND on AKS 

### ISSUE THREAD

**Issue by Shaked** [Azure/AKS#2360]
**What happened**:

We are trying to run pods on AKS with a PVC using Azure Files (`ReadWriteMany` is required). 

We have followed https://docs.microsoft.com/en-us/azure/aks/azure-files-volume#mount-file-share-as-an-persistent-volume. 

Our pods use Docker DIND: https://hub.docker.com/_/docker as we want to use docker to build on our AKS cluster. 

The whole idea is to save docker's cache in Azure Files so basically `/var/lib/docker` is a volume that points to that storage.

This is our setup: 

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    os: ubuntu
  name: symlink-example
spec:
   containers:
   - image: singharunk/dev:latest  #container image with cifs package
     name: symlink
     env: 
     - name: DOCKER_CLI_EXPERIMENTAL
       value: "enabled"
     - name: DOCKER_TLS_CERTDIR
       value: ""
     - name: DOCKER_HOST 
       value: "tcp://localhost:2375"
     - name: DEMO_ACC
       value: "<>"
     - name: DEMO_KEY
       value: "<>"
     - name: DEMO_SHARE
       value: "dockercache"
     securityContext:
       privileged: true
       allowPrivilegeEscalation: true
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo hello; sleep 10;done"]
     lifecycle:
       postStart:
         exec:
           command: ["/bin/sh", "-c", "mkdir /opt/share && mount --verbose -t cifs //$DEMO_ACC.file.core.windows.net/$DEMO_SHARE /opt/share -o vers=3.0,username=$DEMO_ACC,password=$DEMO_KEY,dir_mode=0777,file_mode=0777,serverino,mfsymlinks"]
   - name: dind
     image: "docker:20.10.6-dind"
     env:
     - name: DOCKER_TLS_CERTDIR
       value: ""
     ports: 
       - containerPort: 2375
     resources: 
       requests: 
           cpu: 400m
           memory: 2G
     securityContext: 
         privileged: true
     volumeMounts:  
         - name: azure-cache
           mountPath: /var/lib/docker
         - name: daemon-json-volume
           mountPath: /etc/docker/daemon.json
           subPath: daemon.json
   volumes:
     - name: node-dir
       hostPath:
           path: /mnt
     - name: daemon-json-volume
       configMap:
         name: daemon-json-config
     - name: azure-cache
       persistentVolumeClaim:
           claimName: azurefile
   restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: dockercache
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - nobrl
  - mfsymlinks
  - serverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T
```

Once applied, we run the following commands and unexpected errors appear: 

```
$ kubectl exec -it symlink-example -c dind -- /bin/sh
# docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
Unable to find image 'multiarch/qemu-user-static:latest' locally
latest: Pulling from multiarch/qemu-user-static
d60bca25ef07: Extracting [==================================================>]  766.6kB/766.6kB
7045fbe28d35: Download complete
ed8a5179ae11: Download complete
1ec39da9c97d: Download complete
0421b3622b1a: Download complete
docker: failed to register layer: Error processing tar file(exit status 1): link /bin/[ /bin/[[: operation not supported.
See 'docker run --help'.
```

**What you expected to happen**:

We are currently using `docker run --rm --privileged multiarch/qemu-user-static --reset -p yes` with other non ReadWriteMany solutions such as local node storage (host storage) and it works fine. However, with Azure Files this seems to fail. 

**How to reproduce it (as minimally and precisely as possible)**:

Just apply the above YAML and run the above commands. 

**Anything else we need to know?**:

You might find this repository interesting: https://github.com/multiarch/qemu-user-static

**Environment**:
- Kubernetes version (use `kubectl version`):
```
╰─$ kubectl version                                                                                                                                                                      [Tue Jun  1 18:48:44 2021] 125 ↵
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)  - 2 nodes at the moment. 
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) - the cluster is used for CI so mainly for docker builds 

UPDATE:

I tried to use a different docker image, unrelated to multiarch, but got the same issue: 

> failed to register layer: Error processing tar file(exit status 1): link /bin/bunzip2 /bin/bzcat: operation not supported
##[warning]DOCKER_HOST variable is set. Please ensure that the Docker daemon is running on: tcp://localhost:2375
##[error]failed to register layer: Error processing tar file(exit status 1): link /bin/bunzip2 /bin/bzcat: operation not supported
##[error]The process '/usr/bin/docker' failed with exit code

**Comment by Shaked** [comment]
Update: 

We have also tried to use [Azure Files NFS option](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-create-nfs-shares?tabs=azure-portal#register-the-nfs-41-protocol) but unfortunately, after setting this up we have encountered in a similar problem: 

```
╰─$ k exec -it symlink-nfs-example -c dind -- /bin/sh                                                                                                                                    [Fri Jun  4 23:56:50 2021] 130 ↵
/ # docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
Unable to find image 'multiarch/qemu-user-static:latest' locally
latest: Pulling from multiarch/qemu-user-static
d60bca25ef07: Extracting [==================================================>]  766.6kB/766.6kB
7045fbe28d35: Download complete
ed8a5179ae11: Download complete
1ec39da9c97d: Download complete
0421b3622b1a: Download complete
docker: failed to register layer: Error processing tar file(exit status 1): link /bin/[ /bin/lsof: remote I/O error.
See 'docker run --help'.
/ # %
``` 

a YAML example to set the pod: 

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    os: ubuntu
  name: symlink-nfs-example
spec:
   containers:
   - image: singharunk/dev:latest  #container image with cifs package
     name: symlink
     env: 
     - name: DOCKER_CLI_EXPERIMENTAL
       value: "enabled"
     - name: DOCKER_TLS_CERTDIR
       value: ""
     - name: DOCKER_HOST 
       value: "tcp://localhost:2375"
     - name: DEMO_ACC
       value: "demoacc"
     - name: DEMO_KEY
       value: "demokey"
     - name: DEMO_SHARE
       value: "dockercache"
     securityContext:
       privileged: true
       allowPrivilegeEscalation: true
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo hello; sleep 10;done"]
     lifecycle:
       postStart:
         exec:
           command: ["/bin/sh", "-c", "mkdir /opt/share && mount --verbose -t cifs //$DEMO_ACC.file.core.windows.net/$DEMO_SHARE /opt/share -o vers=3.0,username=$DEMO_ACC,password=$DEMO_KEY,dir_mode=0777,file_mode=0777,serverino,mfsymlinks"]
   - name: dind
     image: "docker:20.10.6-dind"
     env:
     - name: DOCKER_TLS_CERTDIR
       value: ""
     ports: 
       - containerPort: 2375
     resources: 
       requests: 
           cpu: 400m
           memory: 2G
     securityContext: 
         privileged: true
     volumeMounts:  
         - name: azure-cache
           mountPath: /var/lib/docker
         - name: daemon-json-volume
           mountPath: /etc/docker/daemon.json
           subPath: daemon.json
   volumes:
     - name: node-dir
       hostPath:
           path: /mnt
     - name: daemon-json-volume
       configMap:
         name: daemon-json-config
     - name: azure-cache
       persistentVolumeClaim:
        claimName: devopsagent-nfs-claim
   restartPolicy: Always
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devopsagent-nfs-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devopsagent-nfs-filestore
  namespace: default
spec:
  capacity:
    storage: 1T
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - minorversion=1
    - sec=sys
  nfs:
    path: /example/dockercache
    server: example.file.core.windows.net
  claimRef:
    namespace: default
    name: devopsagent-nfs-claim
```

Of course you would have to enable Azure Files NFS preview:

```
az login
subscriptionId=?? 
az feature register \
			    --name AllowNfsFileShares \
			    --namespace Microsoft.Storage \
			    --subscription $subscriptionId

az provider register \
			    --namespace Microsoft.Storage
```

Then create your file share based on the link above.
