### ISSUE TITLE
Network policies in AKS not always additive

### ISSUE THREAD

**Issue by reinventit** [Azure/AKS#2372]
I'm trying to implement two (additive) Network policies in AKS. The first to restrict all egress except DNS and network traffic in the namespace. If I apply the first network policy everything works as expected and traffic between pods in the namespace is allowed and also DNS traffic to the kube-system namespace is also working.

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-egress
  namespace: test
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: test
  policyTypes:
  - Egress
```

But when I also apply some an additive Network Policy for a specific pod (in this example allowing egress traffic to a pod in another namespace):

```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: example
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: ingress
    ports:
    - protocol: TCP
      port: 80
```

I would expect that traffic between pods within the 'test' namespace remains allowed, but this is not the case and it is now blocked. The egress traffic to 53 remains working, so only part of the rules are conflicting in some way.

I would expect the rules to work 'additive' and adding a rule for a specific pod does not impact other rules that also apply for that pod specified in other Network Policies.

(I also found potentially related issues like #1386 , but these seems to be marked as solved)

**Comment by reinventit** [comment]
To more easily reproduce the issue here is a complete yaml exposing the issue:
```
apiVersion: v1
kind: Namespace
metadata:
  name: networking-test
  labels:
    networking/namespace: networking-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: networking-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-2
  namespace: networking-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-2
  template:
    metadata:
      labels:
        app: example-2
    spec:
      containers:
      - name: example
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-egress
  namespace: networking-test
spec:
  podSelector: {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: networking-test
  policyTypes:
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example
  namespace: networking-test
spec:
  podSelector:
    matchLabels:
      app: example
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: ingress
    ports:
    - protocol: TCP
      port: 80
```

With this configuration a ping from example to example-2 pod is not allowed (however expected). When the rule for egress traffic within the namespace is added lik so:

```
apiVersion: v1
kind: Namespace
metadata:
  name: networking-test
  labels:
    networking/namespace: networking-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: networking-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-2
  namespace: networking-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-2
  template:
    metadata:
      labels:
        app: example-2
    spec:
      containers:
      - name: example
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-egress
  namespace: networking-test
spec:
  podSelector: {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: networking-test
  policyTypes:
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: example
  namespace: networking-test
spec:
  podSelector:
    matchLabels:
      app: example
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: ingress
    ports:
    - protocol: TCP
      port: 80
  - to:
    - namespaceSelector:
        matchLabels:
          networking/namespace: networking-test
```

Then it is working as expected. However, the rules should be regarded as additive and it should not be needed to add the extra rule I think.
