### ISSUE TITLE
Very slow container startup with Azure Container Instances and ContainerLimitGreaterThanContainerGroupTotalRequest error

### ISSUE THREAD

**Issue by zipper11** [Azure/AKS#2373]
**What happened**:
Whenever kubernetes HPA or I increase the replica count the container creation takes over 60 seconds. This only happens when using Azure Container Instances.

Sometimes I get this error:
`Warning  ProviderCreateFailed  43s (x14 over 2m15s)  virtual-node-aci-linux/pod-controller  api call to https://management.azure.com/subscriptions/**********/resourceGroups/MC_*****_******_********/providers/Microsoft.ContainerInstance/containerGroups/*****-*****?api-version=2018-10-01: got HTTP response status code 400 error code "ContainerLimitGreaterThanContainerGroupTotalRequest": The 'Cpu' limit '0.5' in container 'express-deployment' is greater than the total request '0.25' of container group '*******-95894df7b-fmtzj'.`

**What you expected to happen**:
To start within 10 seconds (like it's happening when deployed to a kubernetes node). And not get the error above.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a kubernetes cluster
- Use Azure Container Instances
- Increase replica count of deployment
- 
**Anything else we need to know?**:
This is my yaml file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  namespace: ingress-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-deployment
  template:
    metadata:
      labels:
        app: express-deployment
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: express-deployment
        image: ***.azurecr.io/*****:*****
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
        - key: virtual-kubelet.io/provider
          operator: Exists
        - key: azure.com/aci
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: express-deployment
  labels:
    app: express-deployment
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 3000
  selector:
    app: express-deployment
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: express-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-deployment
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
```
NAME                                STATUS   ROLES   AGE     VERSION
aks-agentpool-*****-vmss000000   Ready    agent   56m     v1.20.7
virtual-node-aci-linux              Ready    agent   6d10h   v1.18.4-vk-azure-aci-v1.3.5
```
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Node.js app with prometheus, grafana and nginx ingress controller
- Others:
None
