### ISSUE TITLE
Azurefile mount Permission denied

### ISSUE THREAD

**Issue by solacens** [Azure/AKS#2383]
**What happened**:

Mounting w/ cifs keep crashing with permission denied error.

Event pod the crashing pod:
```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    12m                   default-scheduler  Successfully assigned elastic-system/mypod to aks-default-17728794-vmss00001d
  Warning  FailedMount  10m                   kubelet            Unable to attach or mount volumes: unmounted volumes=[log], unattached volumes=[default-token-whr4b log]: timed out waiting for the condition
  Warning  FailedMount  2m36s (x13 over 12m)  kubelet            MountVolume.SetUp failed for volume "log" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t cifs -o ro,file_mode=0777,dir_mode=0777,vers=3.0,actimeo=30,mfsymlinks,<masked> //<redacted>.file.core.windows.net/log-active /var/lib/kubelet/pods/48b8e93b-805d-4882-806a-f24af0f29617/volumes/kubernetes.io~azure-file/log
Output: mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  109s (x4 over 8m36s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[log], unattached volumes=[log default-token-whr4b]: timed out waiting for the condition
  Normal   Pulling      33s                   kubelet  Pulling image "mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine"
  Normal   Pulled       30s                   kubelet  Successfully pulled image "mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine" in 2.797205265s
  Normal   Created      29s                   kubelet  Created container mypod
  Normal   Started      29s                   kubelet  Started container mypod
```

My testing pod yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: elastic-system
spec:
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    name: mypod
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
      - name: log
        mountPath: /mnt/log
  volumes:
  - name: log
    azureFile:
      secretName: <redacted>
      shareName: log-active
      readOnly: true
  nodeSelector:
    kubernetes.io/hostname: aks-default-17728794-vmss00001d # For specifying node for debugging
```

So to test the mount, I went into the selected node with `ssh`, and done the following

1. `sudo su`
2. `mkdir /var/lib/kubelet/pods/48b8e93b-805d-4882-806a-f24af0f29617/volumes/kubernetes.io~azure-file/log`
3. `mount  -t cifs -o ro,file_mode=0777,dir_mode=0777,vers=3.0,actimeo=30,mfsymlinks,user=<redacted>,password=<redacted> //<redacted>.file.core.windows.net/log-active /var/lib/kubelet/pods/48b8e93b-805d-4882-806a-f24af0f29617/volumes/kubernetes.io~azure-file/log`
4. Mount successfully without error
5. Pod events passed the error and start pulling the image. i.e.
```
Normal   Pulling      33s                   kubelet  Pulling image "mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine"
```

**What has been confirmed on my side**:

1. Networking is not an issue for the cluster <=> storage account (Manual mount on the node is fine)
2. Recently shown problem (~1-2 months)
3. The azurefile secret itself is correct. Confirmed so many times. And it has been placed in both `elastic-system` & `default` namespace

**What you expected to happen**:

Successfully mounted

**How to reproduce it (as minimally and precisely as possible)**:

Steps shown above.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", 
GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", 
GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): Auto-scaling, mostly 6-10 nodes of `Standard_B2ms`
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Elastic stack

@andyzhangx Could you please help?
