### ISSUE TITLE
Hard to explain OOMKilled events while performing disk IO

### ISSUE THREAD

**Issue by copierrj** [Azure/AKS#2390]
**What happened**:
We encountered hard to explain OOMKilled events while executing Argo workflows (https://github.com/argoproj/argo-workflows) with many large artifacts (> 10GiB) on AKS. 

Steps in an Argo workflow consists of a single Pod with three different containers: init, main and wait. The init container retrieves data to be processed by the main container and the wait container waits for the main container to complete and subsequently stores the results somewhere.

Because we often run multiple large workflows (= many individual steps) simultaneously on a single cluster we had to configure fairly low memory limits everywhere to ensure both stable operations and preventing idle nodes.

This setup worked quite well until we started to execute workflows operating on larger datasets. Steps started to fail because the init container was OOMKilled. Unfortunately increasing the memory limit didn't help much. There always seems to be some chance that this init container gets OOMKilled and in more extreme cases it basically always occurred.

We discovered that this only happened while multiple large downloads where running simultaneously and started investigating. First we created a test workflow based on a 'real' workflow that almost always failed and changed it in such a way that the downloading was no longer done by generic Argo functionality (read: we stopped using workflow 'artifacts') so that we could try other http clients (tested: curl and axel) to obtain the files. This didn't make any difference (similar chance of failure) and we proceeded to try to eliminate networking or disk IO from the equation.

First we tried writing to /dev/null instead and this completely eliminated the problem. We concluded that the problem was most likely caused by disk IO and we changed the workflow to generate similarly sized files on disk utilizing dd while reading from /dev/zero and this did indeed result in OOMKilled containers.

We concluded that disk IO can (and in some cases nearly always does) results in OOMKilled containers.

**What you expected to happen**:
We expected that after figuring out a proper memory limit for a particular container to be able to use this config anytime without any memory issues whatsoever.

**How to reproduce it (as minimally and precisely as possible)**:
The problem can be reproduced by a executing a simple shellscript:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  generateName: write-test-
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: app
        emptyDir:
      containers:
      - name: writer
        image: bash
        resources:
          limits:
            memory: "50Mi"
            cpu: 3
        volumeMounts:
        - name: app
          mountPath: /app
        workingDir: /app
        command:
        - bash
        - -c
        - |
          set -eu

          n=3
          bs=32768
          count=327680

          function write() {
            echo start writing $1
            dd if=/dev/zero of=$1 bs=$bs count=$count
            echo done writing $1
          }

          echo writing files...

          for (( i=0; i<$n; i++ ))
          do  
            write "file_$i" &
          done

          wait

          ls -lh
          echo done

```

**Anything else we need to know?**:
We currently limit the cpu of the offending container in order to slow down the disk IO and this works reliably.

**Environment**:
- Kubernetes version: v1.19.11
- Size of cluster: between 6 and 60 nodes of size 'Standard_D4s_v3' (cluster autoscaler enabled)
- General description of workloads in the cluster: Argo workflows containing steps implemented in Bash, Python, Java and many off the shelf command line tools.
