### ISSUE TITLE
Access `clouddrive` by `hostpath` with NFS drive

### ISSUE THREAD

**Issue by Azbesciak** [Azure/AKS#2399]
Hello, I would like to share `clouddrive` with my NFS service. I did a simple NFS service, like below
```yml
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name: nfs-server
          image: k8s.gcr.io/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: mypvc
      volumes:
        - name: mypvc
          hostPath:
            path: "/home/user/clouddrive/myOwnInnerDir" # <-- update here, local files path
            type: "Directory"
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  type: ClusterIP
  clusterIP: 10.0.87.87 # <-- update this
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
```
However, when I schedule this service, there is an error: 
> hostPath type check failed: /home/user/clouddrive/myOwnInnerDir is not a directory

I thought that maybe relative path (`clouddrive/myOwnInnerDir`) might help, but rather no.

So a question - is it possible to somehow attach this `clouddrive` via `hostpath`? Or any other solution that I would be able to share it via NFS?

Thanks
Witold
