### ISSUE TITLE
fsGroup for StatefulSet volumes is ignored on AKS 

### ISSUE THREAD

**Issue by jkroepke** [Azure/AKS#2403]
**What happened**:

I tried to install kube-prometheus-stack (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) today. But everything works fine expect the prometheus instance could not write to the data directory.

```
/ $ ls -lah /data/
total 8K     
drwxr-xr-x    2 root     root        4.0K Jun 24 10:44 .
drwxr-xr-x    1 root     root        4.0K Jun 24 10:45 ..
```

It looks like fsGroup is ignored here.

I can confirm, I get the expected behavior on a onprem Kubernetes 1.19.

**What you expected to happen**:

```
/ $ ls -lah /data/
total 8K     
drwxrwsrwx    2 root     2000        4.0K Jun 24 11:47 .
drwxr-xr-x    1 root     root        4.0K Jun 24 11:54 ..
```

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f - <<API
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: demo
spec:
  serviceName: demo
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: 'busybox'
          command:
            - sleep
            - "10000000"
          ports:
            - name: web
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: sub
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        runAsNonRoot: true
        fsGroup: 2000
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: data
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
API
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"g
o1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"ca992926ba9f76abd853859a64b5b04a1b562362", GitTreeState:"clean", BuildDate:"2021-05-19T22:29:12Z", GoVersion:"g
o1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) kube-prometheus-stack
- Others:

**Comment by andyzhangx** [comment]
are you using csi driver? what's the storage class this statefulset is referencing?

**Comment by jkroepke** [comment]
I'm using the default settings and the Statefulset is using the default class. It's a newly provisioned 1.21.1 cluster.

This is the default StorageClass

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: 'true'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  selfLink: /apis/storage.k8s.io/v1/storageclasses/default
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
```

> are you using csi driver?

Looks like I'm using the CSI driver.
