### ISSUE TITLE
Completed/Failed pods not being cleaned up 

### ISSUE THREAD

**Issue by jmezach** [Azure/AKS#2414]
**What happened**:
We are seeing pods that are run as part of a CronJob not being cleaned up, even though the Succeeded and Failed Job History Limit is set (to 3 and 1 respectively). 

**What you expected to happen**:
When I have a CronJob with a Succeeded Job History Limit of 3 and a Failed Job History Limit of 1 I expect to see at most 4 pods for the CronJob, 3 in the Succeeded state and 1 in the Failed state. However, I'm currently seeing 18 in the Succeeded state and 113 in the Failed state.

**How to reproduce it (as minimally and precisely as possible)**:
I guess it could be as easy as creating a CronJob with some Job History limits and checking if those are being honored. The funny thing is that we didn't have this behaviour before and I'm not entirely sure when it started.

**Anything else we need to know?**:
This is also increasing our costs for Container Insights significantly since it seems to be compiling metrics for those pods, as well as increased CPU usage by the metrics pods.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-13T17:14:18Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)
2

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
We're using this cluster to run a set of developer tools, so for example SonarQube runs on it, together with a Postgres database. We also have Renovate Bot running on it (as a CronJob) as well as some other smaller tools.

- Others:

**Comment by justindavies** [comment]
Hi there, this definitely shouldn't be happening, but I am unable to recreate the issue.  Would you be able to give me one of the yaml files for a CronJob so I can test with a dummy container.

**Comment by jmezach** [comment]
Sure thing, here's an example of a CronJob we currently have deployed:

```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:25.18.3
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.js'
              envFrom:
                # This needs to contain both the Azure DevOps (RENOVATE_TOKEN) and GitHub tokens (GITHUB_COM_TOKEN)
                - secretRef:
                    name: renovate-secrets
              volumeMounts:
                # This needs to contain both the config.js and base-renovate.json files
                - mountPath: /opt/renovate/
                  name: config-volume
                - mountPath: /tmp/renovate/
                  name: work-volume
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
```

I did just notice that we haven't explicitly specified the maximum number of pods to keep in the YAML, although I thought we did. But I believe there are defaults for those values, and if I describe this particular CronJob I'm seeing the following:

```
Successful Job History Limit:  3
Failed Job History Limit:      1
```

But if I look at the pods right now I'm seeing 51 succeeded and 16 failed ones that have all been created by this CronJob.
