### ISSUE TITLE
ImagePullBackOff error for specific image

### ISSUE THREAD

**Issue by Jagdeep1** [Azure/AKS#245]
I am running very simple Nodejs application on AKS cluster. Everything was working fine till the time I was using the base image as `node:9-alpine` but now I have changed base image to `node:9`, and I am getting ImagePullBackOff error. As I understand there should not be any difference from AKS perspective, except image size because later is a heavy image. 

I see this error on dashboard `Failed to pull image "myregistry.azurecr.io/my-image:latest": rpc error: code = Canceled desc = context canceled`

Any clue ?

**Comment by slack** [comment]
On AKS we take the kubelet default for image pull timeout. Which, afair, is ~ 2minutes without pull progress.

How big is the image, and are you able to pull it without issue to other machines?

**Comment by Jagdeep1** [comment]
Image size is ~ 1.1GB. It is working fine on my local docker, I haven't tried it on any other Kubernetes cluster.
I am using Basic- SKU on ACR, do I need to upgrade this?

**Comment by kautsig** [comment]
I'm also running into this with a very large images (> 3gb). 

This seems to be related to this settings: https://github.com/kubernetes/kubernetes/issues/59376

**Comment by kautsig** [comment]
I can confirm that the setting in question is `image-pull-progress-deadline`.

 I did following testcase:
* SSH into the k8s nodes
* Set `KUBELET_OPTS=--image-pull-progress-deadline=60m` in `/etc/default/kubelet`
* Restart kubelet using `sudo systemctl restart kubelet`
* Created the deployment using the problematic image

In `kubectl describe pod <pod>` I saw that the image is pulled, which took roughtly 8 min.

@slack, is there an option to set KUBELET_OPTS while provisioning the cluster? Our would you consider increasing the default value?

**Comment by kautsig** [comment]
My solution to this for now was to provision a temporary jump host in the aks network and run following ansible tasks:

```
  - name: Replace line in kubeconfig
    lineinfile:
      dest: /etc/default/kubelet
      regexp: "^KUBELET_OPTS=$"
      line: "KUBELET_OPTS=--image-pull-progress-deadline=60"
    become: yes
  - name: Restart kubelet service
    service:
      name: kubelet
      state: restarted
    become: yes
```
