### ISSUE TITLE
In aks  pod can't able to ping 8.8.8.8 or any public ip with AZURE CNI plugin

### ISSUE THREAD

**Issue by balakrishna222111** [Azure/AKS#2465]
![image](https://user-images.githubusercontent.com/22685723/127655762-e2b7f087-27b9-49f6-9b47-f74c072c592a.png)

i can't to ping to google.com or 8.8.8.8 or any public ip

My aks cluster configuration

![image](https://user-images.githubusercontent.com/22685723/127655970-01da3d96-6430-4327-8528-202545a5ad67.png)

**Comment by dstrebel** [comment]
What did you set as the outbound type or did you not specify? Do you have any UDRs on the vNet? Is it an existing vNet or new vNet?

**Comment by balakrishna222111** [comment]
Yes,
It's an **existing vNet** . In existing vNet only i configured aks

Below is  my subnet configuration for aks **i didn't configured any UDR**  on  vNet

![image](https://user-images.githubusercontent.com/22685723/127728903-4becb1a6-bd80-4a6b-98ff-44cb12d881cc.png)

 **agent pool Inbound and outbound rules**

![image](https://user-images.githubusercontent.com/22685723/127728929-6a37af46-8bf6-41be-b0b5-5706e2d2de08.png)

**VM Scale set Networking configuration**

InBound rules

![image](https://user-images.githubusercontent.com/22685723/127728957-6b598119-13d2-4a02-ac7e-67a720923958.png)

OutBound rules

![image](https://user-images.githubusercontent.com/22685723/127728977-044b9b50-91e8-4ac5-857d-37a833d7d082.png)


LoadBalancing


![image](https://user-images.githubusercontent.com/22685723/127729000-660f6582-8300-4921-81cb-cda9bae6a949.png)

**Comment by phealy** [comment]
- Do you have any network policies assigned?
- Do you have any network configuration or hostNetwork settings in your deployment spec?
- Can you reproduce the problem in a simple busybox pod like this one?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox:latest
    imagePullPolicy: Always
    name: busybox
    command:
      - /bin/sh
      - -c
      - "tail -f /dev/null"
```
