### ISSUE TITLE
Available parameters that can be specified for azurefile

### ISSUE THREAD

**Issue by sheshasb** [Azure/AKS#2487]
I am trying to use specific storage account and share when I use dynamic provisioning of the azurefile PVC. However, I get the error 

 Failed to provision volume with StorageClass "my-azurefile": could not get storage key for storage account <MYACCOUNT>:
 
1. How can I specify the key ?
2. Where can I find all the parameters available ?

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile
provisioner: kubernetes.io/azure-file
**parameters:**
  skuName: Standard_LRS
  storageAccount: 
  resourceGroup: 
  shareName:

**Comment by andyzhangx** [comment]
here are the parameter list: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters-intree.md
just set `skuName: Standard_LRS`, and this driver would search available storage accounts or create new storage account automatially:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: my-azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
```
