### ISSUE TITLE
Unable to attach or mount volumes: timed out waiting for the condition

### ISSUE THREAD

**Issue by brechtvhb** [Azure/AKS#2494]
I have an AKS cluster (test environment) with 2 nodes. Mounting an NFS file share works fine on one node but when the POD gets moved to another node I do receive this error "Unable to attach or mount volumes: timed out waiting for the condition". On our dev environment everything seems to work fine. Everything worked fine before (for about 40 days before this error started occuring). The file share is in an on prem datacenter.

YAML for the volume & pvc is

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  namespace: default
  labels:
    type: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-volume
  resources:
    requests:
      storage: 10Gi
  selector: 
    matchLabels:
      type: nfs

```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.11
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster: .NET 5 & Angular microservices
