### ISSUE TITLE
Error creating load balancer (will retry): Failed to create load balancer for service default/traefik: user supplied IP Address  was not found

### ISSUE THREAD

**Issue by giorgited** [Azure/AKS#253]
I have followed this documentation https://docs.microsoft.com/en-us/azure/aks/static-ip to create a static IP for my traefik svc but im keeping getting the "not found" error like the one shown in the documentation.

I have verified that the public-ip is in the same resource group as the AKS. 

When i run this query: `az network public-ip list --resource-group myAksRG --query [0].ipAddress --output tsv` i can verify that my static ip is indeed in the right palce.

**Comment by Cono52** [comment]
I have the exact same issue

Error creating load balancer (will retry): Failed to ensure load balancer for service default/whenyoumove-widget: user supplied IP Address 52.178.99.212 was not found

**Comment by slack** [comment]
Make sure the ip address is in the resource group that holds the nodes. That resource group is prefixed with `MC_`

**Comment by ZaidDreakhGE** [comment]
@Cono52 @giorgited Hi, did you manage to find a fix? I also have the same problem and I'm pretty sure my IP address is in the same resource group as the cluster.

**Comment by lionelperrin** [comment]
Is there a limitation to only one public ip ?

**Comment by lionelperrin** [comment]
@slack Thanks for this very quick answer. Actually, I've created several services like:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    service: env1-webui
  name: env1-webui
spec:
  loadBalancerIP: X.X.X.X
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    targetPort: 5000
  selector:
    app: test
    service: env1-webui
```

The first service works as expected but the other services fail with the following error message:
```
Error creating load balancer (will retry): Failed to ensure load balancer for service default/env3-webui: network.SecurityGroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SecurityRuleParametersMissing" Message="Required security rule parameters are missing for security rule with Id: /subscriptions/xxxxxxxx/resourceGroups/MC_xxxxxx_eastus/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-xxxxxx-nsg/securityRules/a6942766a46dd11e8ab840a58ac1f001-TCP-80-Internet. Security rule must specify SourceAddressPrefixes, SourceAddressPrefix, or SourceApplicationSecurityGroups." Details=[]
```
I've noticed that the ip name is always the first ip. `a6942766a46dd11e8ab840a58ac1f001-TCP-80-Internet`.
