### ISSUE TITLE
azurefile pvc error with policy "Public network access onStorage accounts should be disabled"

### ISSUE THREAD

**Issue by Morriz** [Azure/AKS#2552]
**What happened**:

A pvc based on the (AKS provided) storage class "azurefile" could not be created on a managed AKS cluster, showing this error:
```
Failed to provision volume with StorageClass "azurefile": could not get storage key for storage account
```

**What you expected to happen**:

The pvc to be created.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a pvc:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:  
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-file
  name: xx
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1G
  storageClassName: azurefile
  volumeMode: Filesystem
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"8dc42052754bfacb111a0426830122dd9cc9cfa0", GitTreeState:"clean", BuildDate:"2021-08-31T00:01:04Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miwithro** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
The storage account creation failed due to policy `Public network access onStorage accounts should be disabled`.

`allowBlobPublicAccess` is added in azure file csi driver v1.6.0: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/782, if your cluster version is 1.21, set `volume.beta.kubernetes.io/storage-provisioner: azurefile-csi`; another workaround is bring your own storage account with `allowBlobPublicAccess` disabled setting, and use storage class like following:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  resourceGroup: EXISTING_RESOURCE_GROUP_NAME
  storageAccount: EXISTING_STORAGE_ACCOUNT
```
