### ISSUE TITLE
Support nodes with Ephemeral OS with BYOK 

### ISSUE THREAD

**Issue by jmalkiew** [Azure/AKS#2569]
Node(pool)s with Ephemeral OS are not available for customers that have AKS clusters with a customer-managed encryption key.
Please add support for nodes Ephemeral OS for AKS clusters with a customer-managed encryption key.

**Comment by andyzhangx** [comment]
Ephemeral OS does not support custom managed key:
Temporary disks and ephemeral OS disks are encrypted at rest with platform-managed keys when you enable end-to-end encryption. The OS and data disk caches are encrypted at rest with either customer-managed or platform-managed keys, depending on the selected disk encryption type. For example, if a disk is encrypted with customer-managed keys, then the cache for the disk is encrypted with customer-managed keys, and if a disk is encrypted with platform-managed keys then the cache for the disk is encrypted with platform-managed keys.

https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption#encryption-at-host---end-to-end-encryption-for-your-vm-data

**Comment by andyzhangx** [comment]
while you could add `diskEncryptionSetID: /subscriptions/{subs-id}/resourceGroups/{rg-name}/providers/Microsoft.Compute/diskEncryptionSets/{diskEncryptionSet-name}` in azure disk storage class to encrypt data disk with BYOK, e.g.
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
  diskEncryptionSetID: /subscriptions/{subs-id}/resourceGroups/{rg-name}/providers/Microsoft.Compute/diskEncryptionSets/{diskEncryptionSet-name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
