### ISSUE TITLE
Using Aks stop does not preserve a Pod when not part of a deployment

### ISSUE THREAD

**Issue by petegrimsdale** [Azure/AKS#2589]
**What happened**:  Using Aks stop and Aks start to manage a new AKS cluster - a single Pod had been deployed for testing.  On restart of the cluster the Pod was not started - this is not mentioned as a limitation in the docs.  Should this be supported or should a limitation be added to the docs to reflect this?

**What you expected to happen**: Pod to be recovered as per Deployments and other Kubernetes types

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a single pod manifest to an AKS cluster - example below that was being used to validate CSI driver and secrets from KV
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: SECRET_DEMO1
        valueFrom:
          secretKeyRef:
            name: demo1
            key: demosecret
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  ```

Stop the AKS cluster using az aks stop then start using az aks start.  On restart service is recreated as are the CSI pods but the nginx pod does not get restarted

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?) 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:
