### ISSUE TITLE
Cluster Autoscaler - Balanced Similar Node Groups - Not balancing Similar Nodepools when scaling up

### ISSUE THREAD

**Issue by aido123** [Azure/AKS#2606]
**What happened**:

Scaling applications running on similar nodepools in different AZ's, does not result in the nodes across these AZ's been balanced

**What you expected to happen**:

Nodes in nodepools in different AZ's should be balanced

**How to reproduce it (as minimally and precisely as possible)**:

1. Enabled autoscaler profile  balance similar node groups
```
az aks update --subscription <sub> --resource-group <rsg> --name <clu> --cluster-autoscaler-profile balance-similar-node-groups=true
```

2. Create 3 nodepools, 1 in each AZ with autoscaling enabled. Autoscaling settings count 1, min 1, max 5.
```
az aks nodepool add --subscription <sub> --resource-group <rsg> --cluster-name <clu> --kubernetes-version 1.20.9  --name npolaz1 --mode User --max-pods 20 --zones "1" --node-count 1 --node-vm-size Standard_D4s_v3 --node-osdisk-size 200  --enable-cluster-autoscaler --min-count 1 --max-count 5  --node-taints "common=true:NoSchedule" --labels "common=true" --tags "common=true" --priority Regular --vnet-subnet-id "/subscriptions/<sub>/resourceGroups/<rsg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>"
```

```
az aks nodepool add --subscription <sub>--resource-group <rsg> --cluster-name <clu> --kubernetes-version 1.20.9  --name npolaz2 --mode User --max-pods 20 --zones "2" --node-count 1 --node-vm-size Standard_D4s_v3 --node-osdisk-size 200  --enable-cluster-autoscaler --min-count 1 --max-count 5  --node-taints "common=true:NoSchedule" --labels "common=true" --tags "common=true" --priority Regular --vnet-subnet-id "/subscriptions/<sub>/resourceGroups/<rsg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>"
```

```
az aks nodepool add --subscription <sub> --resource-group <rsg> --cluster-name <clu> --kubernetes-version 1.20.9  --name npolaz3 --mode User --max-pods 20 --zones "3" --node-count 1 --node-vm-size Standard_D4s_v3 --node-osdisk-size 200  --enable-cluster-autoscaler --min-count 1 --max-count 5  --node-taints "common=true:NoSchedule" --labels "common=true" --tags "common=true" --priority Regular --vnet-subnet-id "/subscriptions/<sub>/resourceGroups/<rsg>/providers/Microsoft.Network/virtualNetworks/<vnet>/subnets/<subnet>"
```

3. Deploy the following application
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnew
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: nginx
        image: library/nginx:1.15
        ports:
        - containerPort: 80
          name: web
        resources:
          requests:
            cpu: 1000m
            memory: 9Gi
          limits:
            cpu: 1000m
            memory: 10Gi
      tolerations:
      - effect: NoSchedule
        key: common
        operator: Equal
        value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: common
                operator: In
                values:
                - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: common
                operator: In
                values:
                - "true"
            topologyKey: kubernetes.io/hostname
```

4. The pods come up as expected, 1 per nodepool

- 1 pods in AZ1 
- 1 pod in AZ2
- 1 pod in AZ3

5. Next I scale the deployment from 3 to 6 replicas
```
kubectl scale deployment/webnew --replicas=6
```

6. Now I would have expected the autoscaler to spin up a new node in each nodepool and schedule a pod from the deployment to it. But instead the autoscaler spins up a 3 new nodes in the AZ1 nodepool.

So we end up with
- 4 pods in AZ1 
- 1 pod in AZ2
- 1 pod in AZ3

7. Next scale the application up again

```
kubectl scale deployment/webnew --replicas=9
```

Now we end up with
- 5 pods in AZ1 
- 3 pod in AZ2
- 1 pod in AZ3

On the first application scale I would have expected
- 2 scaleset pods in AZ1
- 2 scaleset pod in AZ2
- 2 scaleset pods in AZ3

and on the second application scale, I would have expected
- 3 scaleset pods in AZ1
- 3 scaleset pod in AZ2
- 3 scaleset pods in AZ3

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?): 9-15
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Simple nginx application purposely added large resource requests, so scaling the app would also scale the nodepool.
- Others:
