### ISSUE TITLE
Windows pods cannot reach themselves via service IP

### ISSUE THREAD

**Issue by giskou** [Azure/AKS#2608]
**What happened**:
Windows pods cannot reach themselves via service IP

**What you expected to happen**:
A windows deployment with one replica and a service on top of it should be able to reach the service IP, which refers to itself.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an aks cluster with AzureCNI and some windows nodes
2. Deploy the following test application
```
---
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: win-webserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/os
          value: windows
      containers:
        - name: windowswebserver
          image: mcr.microsoft.com/windows/servercore:1809
          command:
            - powershell.exe
            - -command
            - "<#code used from https://gist.github.com/wagnerandrade/5424431#> ; $$listener = New-Object System.Net.HttpListener ; $$listener.Prefixes.Add('http://*:80/') ; $$listener.Start() ; $$callerCounts = @{} ; Write-Host('Listening at http://*:80/') ; while ($$listener.IsListening) { ;$$context = $$listener.GetContext() ;$$requestUrl = $$context.Request.Url ;$$clientIP = $$context.Request.RemoteEndPoint.Address ;$$response = $$context.Response ;Write-Host '' ;Write-Host('> {0}' -f $$requestUrl) ;  ;$$count = 1 ;$$k=$$callerCounts.Get_Item($$clientIP) ;if ($$k -ne $$null) { $$count += $$k } ;$$callerCounts.Set_Item($$clientIP, $$count) ;$$ip=(Get-NetAdapter | Get-NetIpAddress); $$header='<html><body><H1>Windows Container Web Server</H1>' ;$$callerCountsString='' ;$$callerCounts.Keys | % { $$callerCountsString+='<p>IP {0} callerCount {1} ' -f $$ip[1].IPAddress,$$callerCounts.Item($$_) } ;$$footer='</body></html>' ;$$content='{0}{1}{2}' -f $$header,$$callerCountsString,$$footer ;Write-Output $$content ;$$buffer = [System.Text.Encoding]::UTF8.GetBytes($$content) ;$$response.ContentLength64 = $$buffer.Length ;$$response.OutputStream.Write($$buffer, 0, $$buffer.Length) ;$$response.Close() ;$$responseStatus = $$response.StatusCode ;Write-Host('< {0}' -f $$responseStatus)  } ; "
```
3. Run the following tests to verify the application is working fine
```
kubectl exec -it deployment/win-webserver -- curl.exe -v --max-time 10 http://localhost:80 -H "Connection: close"
* Rebuilt URL to: http://localhost:80/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.55.1
> Accept: */*
> Connection: close
>
< HTTP/1.1 200 OK
< Content-Length: 97
< Server: Microsoft-HTTPAPI/2.0
< Date: Tue, 26 Oct 2021 12:02:21 GMT
< Connection: close
<
<html><body><H1>Windows Container Web Server</H1><p>IP 10.xxx.xxx.xxx callerCount 1 </body></html>* Closing connection 0
```
4. The following times out always.
```
kubectl exec -it deployment/win-webserver -- curl.exe -v --max-time 10 http://win-webserver:80 -H "Connection: close"
* Rebuilt URL to: http://win-webserver:80/
*   Trying 10.xxx.xxx.xxx...
* TCP_NODELAY set
* Connection timed out after 10000 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 10000 milliseconds
command terminated with exit code 28
```

**Anything else we need to know?**:
This happens since kubernetes 1.20. In version 1.19 everything worked fine.
Both upgrades to 1.20 from 1.19 and new 1.20 clusters have the issue.
It is also present on 1.21.

Scaling the deployment to 2, makes curl work every other time, when the other pod is picked in round robin.
Generally, services on other pods work just fine.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.9
- Size of cluster (how many worker nodes are in the cluster?): 2 linux, 1 windows
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): N/A

**Related Issues**
https://github.com/Azure/aks-engine/issues/4079
https://github.com/Azure/AKS/issues/2236
https://github.com/Azure/AKS/issues/2322
