### ISSUE TITLE
Core DNS default forward override

### ISSUE THREAD

**Issue by andriktr** [Azure/AKS#2623]
Hi, 
I'm trying to override default AKS Core DNS settings with the following:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  workaround.override: | 
        forward . 10.10.10.1
```
If I apply the configmap my core dns pods crashing with:
```
plugin/forward: this plugin can only be used once per Server Block
```
Default config already has a forward plugin in the block .:53

``` yaml
    .:53 {
        errors
        ready
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
```
and it uses import plugin to add my override config, so I assume it's simply adds one more forward plugin directive from my custom config instead of overwriting the existing one. 
Are there any other ways to change default `forward . /etc/resolv.conf` ?
