### ISSUE TITLE
Evicted Pods

### ISSUE THREAD

**Issue by Danlewis3** [Azure/AKS#2633]
**What happened**:
Pods that are evicted due to node availability or memory issues keep the evicted state visible in the portal and AKS. The garbage collector settings aren't available in AKS so we are unable to change the default value of 12500 until cleanup. If it hits a certain amount all nodes become un-responsive and slow.

**What you expected to happen**:
The ability to change the garbage collector threshold and not have to create something custom that Kubernetes does out the box

**How to reproduce it (as minimally and precisely as possible)**:
run spot nodes on aks let the nodes spot and see the evicted pods grow and eventually the cluster becomes slow

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Size of cluster (how many worker nodes are in the cluster?)
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by pcornelissen** [comment]
We also have evicted pods for no apparrent reason. While the evicted pods are a nuisance, the main problem is that the application is not available for a short time...

**Comment by larryclaman** [comment]
@Danlewis3 you could look at using the Kubernetes Descheduler tool https://github.com/kubernetes-sigs/descheduler#removefailedpods to remove the evicted pods.

A sample config policy would include a section like:

```
deschedulerPolicy:
  strategies:
    RemoveFailedPods:
     enabled: true
    params:
      failedPods:
        includingInitContainers: true
        minPodLifeTimeSeconds: 120
        namespaces:
          include:
            - "namespace1"
            - "namespace2"
```
