### ISSUE TITLE
Azure file share as inline volume with private endpoint

### ISSUE THREAD

**Issue by hadr10** [Azure/AKS#2649]
**What happened**: When we moved our storage account to private endpoint it stopped working in AKS in some countries.
Log from aks:
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/7622356f-f584-4036-80d5-2a6ae7f1b51b/volumes/kubernetes.io~azure-file/azure --scope -- mount -t cifs -o file_mode=0777,dir_mode=0777,vers=3.0,actimeo=30,mfsymlinks,<masked> //testinfra.file.core.windows.net/test /var/lib/kubelet/pods/7622356f-f584-4036-80d5-2a6ae7f1b51b/volumes/kubernetes.io~azure-file/azure
Output: Running scope as unit: run-r19ed4ed72b044e1ebfaf47ec8b370caa.scope
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
  Warning  FailedMount  109s (x2 over 4m6s)  kubelet  Unable to attach or mount volumes: unmounted volumes=[azure], unattached volumes=[azure default-token-zrn6q]: timed out waiting for the condition

**What you expected to happen**: Storage account in AKS still work after moving to storage account with private endpoint.

**How to reproduce it (as minimally and precisely as possible)**: AKS 1.19.13, https://docs.microsoft.com/en-us/azure/aks/azure-files-volume

**Anything else we need to know?**: We use southeast asia region, in another subscription with the same version AKS it works.

**Environment**:
- Kubernetes version (use `kubectl version`): kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T21:01:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13", GitCommit:"61be87ea533002fdf9251891b1a6e616c26a5cfd", GitTreeState:"clean", BuildDate:"2021-10-09T05:09:23Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (how many worker nodes are in the cluster?) 16
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) - test application with inline volume as here https://docs.microsoft.com/en-us/azure/aks/azure-files-volume
- Others:

**Comment by andyzhangx** [comment]
does pod recreation work in such scenario?

**Comment by hadr10** [comment]
State before recreation:
kubectl get pods
NAME    READY   STATUS              RESTARTS   AGE
mypod   0/1     ContainerCreating   0          12h

Still the same sitiation after recreation
kubectl get pods
NAME    READY   STATUS              RESTARTS   AGE
mypod   0/1     ContainerCreating   0          3m15s

Log from pod:
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/b716306b-3e36-4db4-9a9e-b978f04dc9be/volumes/kubernetes.io~azure-file/azure --scope -- mount -t cifs -o file_mode=0777,dir_mode=0777,vers=3.0,actimeo=30,mfsymlinks,<masked> //testinfra.file.core.windows.net/test /var/lib/kubelet/pods/b716306b-3e36-4db4-9a9e-b978f04dc9be/volumes/kubernetes.io~azure-file/azure
Output: Running scope as unit: run-reb7a6222685848b384e5dd5252edda56.scope
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

**Comment by andyzhangx** [comment]
@hadr10 only azure file CSI driver supports private end point, and if you are using private end point, the azure file server address should be `*.privatelink.file.core.windows.net`, you could specify `server` in storage class (find all csi driver parameters [here](https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters.md))

I just tried private end point feature in south east asia region, it works well.

```console
# k exec -it statefulset-azurefile-0 sh
# df -h
//f6aa0c075716540428e4381.privatelink.file.core.windows.net/pvc-bdcf2555-10c0-4db4-9d06-de4eab7ed637  100G   64K  100G   1% /mnt/azurefile
```

**Comment by andyzhangx** [comment]
BTW, from aks 1.21, CSI driver is already the default azure file driver, so you could try on 1.21 directly.

**Comment by hadr10** [comment]
OK, thank you for verification. It just weird that it worked on one AKS with the same version 1.19.13. I will try with 1.21

**Comment by andyzhangx** [comment]
@hadr10 try with following csi driver storage class directly:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS  # available values: Standard_LRS, Standard_GRS, Standard_ZRS, Standard_RAGRS, Premium_LRS
  networkEndpointType: privateEndpoint
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
```

Make sure cluster Control plane identity(with name AKS Cluster Name) has Contributor permission on vnet resource group
