### ISSUE TITLE
Feature request: ZRS managed disk and ZRS storage account Storage classes

### ISSUE THREAD

**Issue by MasterKolka** [Azure/AKS#2659]
Hello,

It would be great to have an opportunity to create a cross-zone volumes where available.

https://azure.microsoft.com/en-us/updates/zone-redundant-storage-zrs-for-azure-disk-storage-now-generally-available/

Thanks.

**Comment by larryclaman** [comment]
I'm not on the AKS team, but I think this feature is already available via the CSI drivers:  https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#dynamically-create-azure-files-pvs-by-using-the-built-in-storage-classes

**Comment by andyzhangx** [comment]
and for disk, you could follow this guide to create your own storage class: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/topology#zrs-disk-support

**Comment by MasterKolka** [comment]
@andyzhangx having a possibility to create my own storage class is not the same than having a built-in. Feature request is about that.

**Comment by andyzhangx** [comment]
> @andyzhangx having a possibility to create my own storage class is not the same than having a built-in. Feature request is about that.

There are quite a lot storage account types, aks won't create a built-in class for every account type:
`Standard_LRS, Standard_GRS, Standard_ZRS, Standard_RAGRS, Premium_LRS, Premium_ZRS`

**Comment by MasterKolka** [comment]
@andyzhangx at least for ZRS disks and storage since aks can be zone-redundant and run in multiple zones

**Comment by larryclaman** [comment]
@MasterKolka, I acknowledge that the documentation for how to achieve this could be better, as it is currently spread out over a bunch of different pages. I will look into improving that.

But as @andyzhangx noted, there's really no reason to "build this into" AKS as enabling a custom storage class is pretty trivial.  Follow the guidance on this page https://docs.microsoft.com/en-us/azure/aks/azure-disk-csi#create-a-custom-storage-class , but in this case you'll change the sku name to Premium_ZRS, eg
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-csi-zrs
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_ZRS
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
All in all, just a 10 line YAML file.   To use it, just reference this new storage class in your PersistentVolumeClaim definition.
