### ISSUE TITLE
tunnelfront low pod CPU resources

### ISSUE THREAD

**Issue by maksim-paskal** [Azure/AKS#2667]
We have AKS kubernetes `v1.20.9` - by default tunnelfront pod use this resources
```yaml
resources:
  requests:
    cpu: 10m
    memory: 64Mi
```

but actual resource usage is bigger than requested

![image](https://user-images.githubusercontent.com/17670524/142981520-c91192c5-d2b8-4ef2-90ec-df32193f3c6f.png)

changing resources in tunnelfront deployment is reverted to defaults over time.

I want to manage resources of tunnelfront or defaults resources values must have actual values
