### ISSUE TITLE
Http Proxy Preview Feature: Override Http Proxy and No Proxy environment variables for pods

### ISSUE THREAD

**Issue by implodingduck** [Azure/AKS#2674]
**What happened**:
I am trying to use the new http proxy preview feature and running into an issue where I cannot override the no_proxy list at the pod level. This is making it hard to use normal kubernetes pod to service communication unless I specify all my microservice service names in the no_proxy list at cluster creation time. 

**What you expected to happen**:
I was expecting to be able to set a no_proxy environment variable and have the pod honor it. 

**How to reproduce it (as minimally and precisely as possible)**:
With an AKS cluster that is using the http proxy preview feature deploy a nginx pod:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: no_proxy
          value: "nginx"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
```
Then run a describe on the pod to see the environment variables. It shows the clusters no_proxy list rather than what was defined in the deployment. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.2
- Size of cluster (how many worker nodes are in the cluster?) 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)  HTTP microservices
- Others:
