### ISSUE TITLE
CoreDNS Custom ConfigMap Does Not Reload Automatically

### ISSUE THREAD

**Issue by sossickd** [Azure/AKS#2689]
**What happened**:

Creating a coredns-custom.yaml, example below and applying the yaml using "kubectl apply -f" does not result in coredns automatically reloading.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  onpremzones.server: |
    example.net:53 {
        forward . 10.0.0.2 10.0.0.3
    }
```

In order for the coredns-custom configmap to be applied you need to run:

```bash
kubectl delete pod --namespace kube-system --selector k8s-app=kube-dns
```

There is an old issue that has been closed without resolution, can you clarify whether this reload functionality should work?

https://github.com/Azure/AKS/issues/841

**What you expected to happen**:

coredns-custom configmap to be reloaded automatically using the core-dns reload plugin

**How to reproduce it (as minimally and precisely as possible)**:

Create the coredns-custom.yaml and run:

```bash
kubectl apply -f coredns-custom.yaml
```

**Anything else we need to know?**:

**Environment**: AKS version 1.21.2
- Kubernetes version (use `kubectl version`): 1.21.2
- Others: Coredns version 1.8.6
