### ISSUE TITLE
az aks command invoke breaks with AAD-enabled clusters

### ISSUE THREAD

**Issue by ams0** [Azure/AKS#2698]
**What happened**:

The handy `az aks command invoke` doesn't work on AAD-enabled clusters. From a simple test I run:

| Feature       | AAD | AAD RBAC | Local Accounts | Outcome |
|---------------|-----|----------|----------------|---------|
| noazrbacnoaad | No  | No       | No             | Works   |
| noazrbac      | Yes | No       | No             | Doesn't |
| localnoaad    | Yes | No       | Yes            | Doesn't |

AAD: AAD-enabled feature
AAD RBAC: `--enable-azure-rbac`
Local accounts: `--disable-local-accounts`. Note, for the `noazrbacnoaad` cluster, the command works, but you need to enable local accounts to connect to cluster (since there's no AAD).

When it fails, the error is:

```
error: You must be logged in to the server (Unauthorized)
```

The interesting part is that even on the cluster where it works the `command-xxxxx` pod shows:

```
  Warning  FailedMount  17m (x2 over 17m)  kubelet            MountVolume.SetUp failed for volume "kube-api-access-6p6zq" : object "aks-command"/"kube-root-ca.crt" not registered
```

error but the logs shows success. The command I'm running is:

```
az aks command invoke -g resources -n noazurerbac -c "kubectl create ns pinco"
```

**What you expected to happen**:

Command works on every kind of clusters.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.2
- Size of cluster (how many worker nodes are in the cluster?): 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others:

**Comment by htuomola** [comment]
After upgrading AAD-enabled (and kubernetes rbac, but no azure rbac) cluster from 1.21.2 to 1.22.4 the pods created by cronjobs start to show this warning. The pods themselves get executed though, at least. Setting `automountServiceAccountToken: false` in PodSpec seems to fix it but that's somewhat annoying to change all jobs.

**Comment by iMichka** [comment]
Same here, I started seeing this today after an upgrade from 1.21.x to 1.22.4.
I did the update on 2 test/dev servers, and it happens only on one of both (which is weird).
It only happens to cronjobs.

I am investigating to see what is the difference between both clusteurs.

**Comment by ams0** [comment]
On 1.23.3, with no local accounts, AAD enable, RBAC enable command fails:

```
~> az aks command invoke -n gitops -g resources -c "kubectl get po -A"
command started at 2022-03-02 10:36:22+00:00, finished at 2022-03-02 10:36:23+00:00 with exitcode=1
error: You must be logged in to the server (Unauthorized)
```

But that's kinda expected, right? There are no local accounts, so how could `az aks` command execute anything?

**Comment by harshavardhanc** [comment]
Facing same issue with 1.22.6 version. Any workaround or update on this isue?

**Comment by haitch** [comment]
I tried this, and the error message is correct, it just means the current user have no access to the cluster.

another way to test is try **az aks get-credentials**, and run same command with kubectl, likely you get same error message.

**Comment by harshavardhanc** [comment]
@haitch No, I'm able to run the kubectl command against the same cluster from the machine within the same VNET with my user. Getting this error while trying to run kubectl command with **az aks invoke command**.

**Comment by haitch** [comment]
maybe one of them is cert based auth? can you do **kubectl config view**? and make sure they are using same aad user (first one)

```
users:
- name: clusterUser_xxxx_xxxx
  user:
    auth-provider:
      config:
        apiserver-id: 6dae42f8-4368-4678-94ff-3960e28e3630
        client-id: xxxx
        config-mode: "1"
        environment: AzurePublicCloud
        tenant-id: xxxx
      name: azure
```

```
users:
- name: clusterUser_xxxx_xxxx
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: REDACTED
```
