### ISSUE TITLE
PVC not created for Generic Ephemeral Volume

### ISSUE THREAD

**Issue by seddarj** [Azure/AKS#2705]
**What happened**:

We want to leverage the [local static provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) in kubernetes for which there is an [AKS example here](https://github.com/Azure/kubernetes-volume-drivers/tree/master/local) to provision Persistent Volumes on the NVMe drives on Lsv2 machines. We can see the PVs are created for our custom `nvme-disk` storage class so that part works.

We also wanted to have Pods from a Deployment with multiple replicas leverage those PVs. In order to do that, we tried to use Generic Ephemeral Volumes (they are in a beta Feature Gate in kubernetes 1.21 and are not stable until 1.23 but we were told that the feature gate is enabled on AKS 1.21.2) which adds a controller that automatically creates Persistent Volume Claims upon Pod creation. So we defined a volume (and its corresponding volume mount) of `ephemeral` type and specified the `volumeClaimTemplate` in there:

```yaml
volumes:
  - ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1600Gi
          storageClassName: nvme-disk
    name: shared-data
```

What we see is that the Deployment is created as expected and so is the underlying Replicaset i.e. the volume spec stays the same as is expected but we don't see any PVC created upon Pod creation. Even weirder, when we run `kubectl get pod POD_NAME -o yaml`, the volume spec has changed to an `emptyDir`:

```yaml
volumes:
   - emptyDir: {}
     name: shared-data 
```

Creating a PVC manually and changing the Pod spec in the Deployment to use that claim directly works for one Pod but does not work for all the replicas.
```yaml
volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: pvc-nvme-disk
```

**What you expected to happen**:

We expected a PVC to be created upon Pod creation and to be used by the Pod. We didn't expect the Pod's volume spec to change to an emptyDir.

**How to reproduce it (as minimally and precisely as possible)**:
"Luckily", the problem seems unrelated to the local nvme provisioner and can be reproduced using any storage class such as `managed`, `managed-premium`, `managed-csi`, `managed-csi-premium` etc.

So applying the following manifest and running `kubectl get pvc` should return that no PVC was created for the Pod and checking the Pod's applied manifest with `kubectl get pod test -o yaml` should show that the volume was changed to an `emptyDir`.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - image: nginx:alpine
      name: test
      volumeMounts:
      - mountPath: /data
        name: shared-data
  volumes:
  - ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
          storageClassName: managed-premium
    name: shared-data
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?) 3 (small cluster for testing purposes)
