### ISSUE TITLE
azure file driver daemonset crash on Windows node within rbac disabled cluster

### ISSUE THREAD

**Issue by lippertmarkus** [Azure/AKS#2717]
**What happened**: Azurefile CSI driver is not available for Windows containerd nodes by default

**What you expected to happen**: CSI driver should be available like the Azure Disk CSI driver

**How to reproduce it (as minimally and precisely as possible)**:
1. Create AKS cluster
2. Add Windows node pool with containerd support (https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#add-a-windows-server-node-pool-with-containerd-preview)
3. Deploy the example app with azurefile volume: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/windows
4. Get `kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name file.csi.azure.com not found in the list of registered CSI drivers`

**Anything else we need to know?**:

The daemon set `csi-azurefile-node-win` exists but the problem seems to be a missing service account: 
```
Warning  FailedCreate  7m (x118 over 27h)  daemonset-controller  Error creating: pods "csi-azurefile-node-win-" is forbidden: error looking up service account kube-system/csi-azurefile-node-sa: serviceaccount "csi-azurefile-node-sa" not found
```

When creating the service account with `kubectl create serviceaccount csi-azurefile-node-sa -n kube-system` the CSI driver is deployed to the Windows node and the example app with the AzureFile volume works.

Looking at the spec of the AzureDisk CSI DaemonSet however I think for consistency the service account spec should be removed as well.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T19:30:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?): 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): nothing
- Others: -

**Comment by andyzhangx** [comment]
@lippertmarkus I could not repro on 1.22 with Windows containerd node, did you delete service account `csi-azurefile-node-sa` by yourself?

```console
az aks nodepool add \
    --resource-group andy-aks1222 \
    --cluster-name andy-aks1222 \
    --os-type Windows \
    --name cond \
    --node-vm-size Standard_D2s_v3 \
    --kubernetes-version 1.22.2 \
    --aks-custom-headers WindowsContainerRuntime=containerd \
    --node-count 1

# k get po -n kube-system | grep csi
csi-azuredisk-node-mpfw7              3/3     Running             0          15m
csi-azuredisk-node-rgpqh              3/3     Running             0          15m
csi-azuredisk-node-win-85xql          3/3     Running             0          11m
csi-azuredisk-node-win-nhhf4          3/3     Running             0          107s
csi-azurefile-node-8cb2v              3/3     Running             0          15m
csi-azurefile-node-rfhjk              3/3     Running             0          15m
csi-azurefile-node-win-k5tx5          3/3     Running             0          11m
csi-azurefile-node-win-vddjf          3/3     Running             0          107s
	
# k get sa -A | grep csi
kube-system       csi-azuredisk-node-sa                1         17m
kube-system       csi-azurefile-node-sa                1         17m
```

**Comment by lippertmarkus** [comment]
@andyzhangx I didn't delete the service account. I just tried creating it again from scratch with the same results:

```
# k get pod -n kube-system | grep csi
csi-azuredisk-node-k9psq              3/3     Running   0          14m
csi-azuredisk-node-win-9tg47          3/3     Running   0          6m9s
csi-azurefile-node-k2h4g              3/3     Running   0          14m

# k get sa -A | grep csi
(empty)

# k get ds -n kube-system | grep csi
csi-azuredisk-node           1         1         1       1            1           kubernetes.io/os=linux        18m
csi-azuredisk-node-win       1         1         1       1            1           kubernetes.io/os=windows      18m
csi-azurefile-node           1         1         1       1            1           kubernetes.io/os=linux        18m
csi-azurefile-node-win       0         0         0       0            0           kubernetes.io/os=windows      18m

# k describe ds/csi-azurefile-node-win -n kube-system | grep "service account"
  Warning  FailedCreate  4m1s (x17 over 9m29s)  daemonset-controller  Error creating: pods "csi-azurefile-node-win-" is forbidden: error looking up service account kube-system/csi-azurefile-node-sa: serviceaccount "csi-azurefile-node-sa" not found
```

Interestingly, like I said before, `csi-azuredisk-node-win` doesn't reference any service account for me and therefore works.

Does the outcome depend on the API version which is used to create the AKS cluster? I'm using  crossplane provider azure-jet which is using Terraform behind the scenes:
```yaml
apiVersion: network.azure.jet.crossplane.io/v1alpha1
kind: VirtualNetwork
metadata:
  name: ppi-aks-net
spec:
  forProvider:
    location: "West Europe"
    resourceGroupNameRef:
      name: ppi-aks
    addressSpace:
      - "192.168.0.0/16"
  providerConfigRef:
    name: default
---
apiVersion: network.azure.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: ppi-aks-subnet
spec:
  forProvider:
    resourceGroupNameRef:
      name: ppi-aks
    virtualNetworkNameRef:
      name: ppi-aks-net
    addressPrefixes:
      - "192.168.0.0/24"
  providerConfigRef:
    name: default
---
apiVersion: containerservice.azure.jet.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: ppi
spec:
  writeConnectionSecretToRef:
    name: ppi-aks-kubeconfig
    namespace: crossplane-system
  forProvider:
    location: "West Europe"
    resourceGroupNameRef:
      name: ppi-aks
    dnsPrefix: "ppi"
    kubernetesVersion: "1.22.4"
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: "Standard_D2_v2"
        vnetSubnetIdRef:
          name: ppi-aks-subnet
    identity:
      - type: "SystemAssigned"
    windowsProfile:
      - adminUsername: vmadmin
        adminPasswordSecretRef:
          name: ppi-aks-windows-password
          key: password
          namespace: crossplane-system
    networkProfile:
      - networkPlugin: azure
        networkPolicy: calico
  providerConfigRef:
    name: default
```
