### ISSUE TITLE
AKS does not create azure-storage-account secret after upgrading to v1.22.4 when secret in original namespace is deleted

### ISSUE THREAD

**Issue by pietervdheijden-calvi** [Azure/AKS#2737]
**What happened**:

In our CI/CD cluster, we're continuously creating a new environment (namespace) for each PR. In that namespace, we're deploying a Helm release of our product. Some of the Pods in Helm Chart mount a PersistentVolumeClaim, which dynamically provisions a PersistentVolume.

The PersistentVolume and PersistentVolumeClaims are provisioned successfully. However, the PersistentVolumeClaim cannot be mounted into the Pods, because the azure storage secret is missing (`azure-storage-account-<az-storage-account-name>-secret`). The Pods log the following events:

> MountVolume.MountDevice failed for volume "pvc-<pvc-name>" : fetching NodeStageSecretRef <ns>/azure-storage-account-<az-storage-account-name>-secret failed: kubernetes.io/csi: failed to find the secret azure-storage-account-<az-storage-account-name>-secret in the namespace <ns> with error: secrets "azure-storage-account-<az-storage-account-name>-secret" not found
> Unable to attach or mount volumes: unmounted volumes=[<volume-name>], unattached volumes=[kube-api-access-2bpxd <volume-name>]: timed out waiting for the condition

It seems that this issue started to occur after we upgraded the CI/CD cluster to k8s v1.22.4 (last week). Before, AKS consistently created the azure storage account secret. 

**What you expected to happen**:

AKS (automatically) creates the azure storage account secret. So when a Pod wants to mount a PersistentVolumeClaim, AKS creates the azure storage account such that the mount operation succeeds.

**How to reproduce it (as minimally and precisely as possible)**: 

I tried to make the issue reproducible with a simple K8s application (in the same cluster):

```
apiVersion: v1
kind: Namespace
metadata:
  name: debug
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: debug
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: <storage-class-name>
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
  namespace: debug
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: pvc
      mountPath: /mnt/pvc
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: pvc
```

However, this works consistently: the azure storage account secret is created when the Pods are deployed. I also tried the same with a similar Helm Chart, and again the same result: the azure storage account secret is created.

What makes this issue even more complex, is that AKS does not behave consistently. Some times it does create the azure storage account secret (in my Helm deployment), and some times it doesn't. I really don't know how I can further investigate the issue...

As a workaround, I added this script to our CI/CD pipeline to ensure that the azure storage account secret is always created:

```
kubectl create secret generic azure-storage-account-<azurestorageaccountname>-secret \
  --from-literal=azurestorageaccountname=<azurestorageaccountname> \
  --from-literal=azurestorageaccountkey=<azurestorageaccountkey> \
  -n <namespace>
```

This seems very hacky though, and as such I'd like to remove it as soon as possible...

**Anything else we need to know?**:

No

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.4
- Size of cluster (how many worker nodes are in the cluster?): varies because of Horizontal Node Autoscaling, but usually around 5 to 10.
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): websites (Angular), APIs (.NET), background services (.NET) and databases (MSSQL).
- Others: /
