### ISSUE TITLE
Specify both subnet and IP for Kubernetes Service of LoadBalancer type.

### ISSUE THREAD

**Issue by digihunch** [Azure/AKS#2758]
**What happened**:
I am trying to create a kubernetes Service of load balancer type. I would like to specify an IP address in a dedicated subnet. The Kubernetes is a private cluster and the subnet is on corp network (not public facing).

Currently, if I declare a service like below to specify an [internal subnet](https://docs.microsoft.com/en-us/azure/aks/internal-lb#specify-a-different-subnet), then the next available IP in the load-balancer-subnet is picked as the external IP for the service. I do not have control of what IP address to use.
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: load-balancer-subnet
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
```
If I declare a service like below, then I can use the specified IP address as external IP. However, the loadBalancerIP address must be inthe same subnet as the AKS cluster, according to [this](https://docs.microsoft.com/en-us/azure/aks/internal-lb#specify-an-ip-address) in the doc.
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: istio-ingressgateway
  namespace: istio-system
spec:
  loadBalancerIP: 10.10.9.134
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
```
The problem is that I'm trying to stay away from cluster's subnet to serve load balancer IP address.

I am trying to specify both a subnet (using annotation) and IP (using the loadBalancerIP field)  with the manifest below. Note that the IP address is in a different subnet than the cluster's. 
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: load-balancer-subnet
  name: istio-ingressgateway
  namespace: istio-system
spec:
  loadBalancerIP: 10.10.10.134
  type: LoadBalancer
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
```
**Observed behaviour**:
The service events indicate that "SyncLoadBalancerFailed": Error syncing load balancer: failed to ensure load balancer: ensure(istio-system/istio-ingressgateway): lb(kubernetes-internal) - failed to get subnet: aks-vnet/node-subnet
It seems that the indication of internal-subnet provided in the annotation is ignored, and it looks for loadBalancerIP in the aks cluster subnet, which is incorrect.
**Expected behaviour**:
The service is created with the specified loadBalancerIP in the subnet specified in the annotation.
This will help us bring up service using consistent IP address in a dedicated load balancer subnet.

**Environment**:
- Kubernetes version (use `kubectl version`):1.21.2
- Size of cluster (how many worker nodes are in the cluster?): 9
- General description of workloads in the cluster: HTTP
