### ISSUE TITLE
AKS - VolumeSnapshot Custom User Tags

### ISSUE THREAD

**Issue by SinglaSandeep** [Azure/AKS#2760]
We are trying to create tags on VolumeSnapshot something like below
parameters:
  tags: 'name=pvc'

But we are getting when while creating the tags

Is there any reason why tags are supported only at VolumeSnapshotClass level instead of VolumeSnapshot  as referred in below issue
https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/358

**Comment by andyzhangx** [comment]
@SinglaSandeep what do you mean providing tag support on `VolumeSnapshot`? `tags` parameter is not supported on below `VolumeSnapshot`, you can only add `labels` in  `metadata`

```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: azuredisk-volume-snapshot
spec:
  volumeSnapshotClassName: csi-azuredisk-vsc
  source:
    persistentVolumeClaimName: pvc-azuredisk
```
