### ISSUE TITLE
`readOnly: true` and `ReadOnlyMany` Access Mode Do Not Have Any Effect on `azureFile` Volumes at PV Level

### ISSUE THREAD

**Issue by GuyPaddock** [Azure/AKS#2762]
**What happened**:
If an `azureFile` persistent volume is configured to be read-only, the PV is still read-write inside containers.

**What you expected to happen**:
When a PV is declared as read-only, you should receive a message about `Create failed: Read-only file system` but instead the file is created without error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a read-only Azure Files PV using a manifest like the following (you will need to setup secrets and the share, and replace the namespace and volume names below to match your environment):
    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-my-volume
    spec:
      accessModes:
      - ReadOnlyMany
      azureFile:
        readOnly: true
        secretName: my-secret-name
        secretNamespace: my-namespace
        shareName: my-volume
      capacity:
        storage: 5Ti
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-my-volume
      namespace: my-namespace
    spec:
      accessModes:
      - ReadOnlyMany
      resources:
        requests:
          storage: 5Ti
      storageClassName: ""
      volumeName: pv-my-volume
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ubuntu-diag
      namespace: my-namespace
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: utility-ubuntu-diag
      template:
        metadata:
          labels:
            app: utility-ubuntu-diag
            role: utility
        spec:
          containers:
          - args:
            - infinity
            command:
            - sleep
            image: ubuntu:20.04
            name: ubuntu
            volumeMounts:
            - mountPath: /mnt/my-volume
              name: vol-my-volume
          volumes:
          - name: vol-my-volume
            persistentVolumeClaim:
              claimName: pvc-my-volume
    ```
2. Use `kubectl exec -it <POD NAME> -- bash` to get into the `ubuntu-diag` pod.
3. Change into the mounted folder (i.e., `cd /mnt/my-volume`).
4. Attempt to create a file (e.g., `touch test`).

**Anything else we need to know?**:
It appears that a workaround is to add `readOnly: true` to the volume mount itself:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-my-volume
spec:
  accessModes:
  - ReadOnlyMany
  azureFile:
    readOnly: true
    secretName: my-secret-name
    secretNamespace: my-namespace
    shareName: my-volume
  capacity:
    storage: 5Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-my-volume
  namespace: my-namespace
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: ""
  volumeName: pv-my-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-diag
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility-ubuntu-diag
  template:
    metadata:
      labels:
        app: utility-ubuntu-diag
        role: utility
    spec:
      containers:
      - args:
        - infinity
        command:
        - sleep
        image: ubuntu:20.04
        name: ubuntu
        volumeMounts:
        - mountPath: /mnt/my-volume
          name: vol-my-volume
          readOnly: true
      volumes:
      - name: vol-my-volume
        persistentVolumeClaim:
          claimName: pvc-my-volume
```

**Environment**:
- Kubernetes version (use `kubectl version`):
   ```
   Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", 
   GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", 
   GitTreeState:"clean", BuildDate:"2021-11-18T19:30:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
   ```
