### ISSUE TITLE
Dynamic persistent volume provisioning does not work with azure disks

### ISSUE THREAD

**Issue by AurimasNav** [Azure/AKS#2797]
**What happened**:
Creating a manifest for pvc and trying to use it in a pod results in errors:

> Events:
>  Type     Reason              Age                     From                     Message
>  ----     ------              ----                    ----                     -------
>  Warning  FailedMount         27m (x235 over 41h)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[volume], unattached volumes=[kube-api-access-4kckc volume]: timed out waiting for the condition
>  Warning  FailedMount         2m5s (x856 over 41h)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[volume], unattached volumes=[volume kube-api-access-4kckc]: timed out waiting for the condition
>  Warning  FailedAttachVolume  114s (x169 over 5h45m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-yyyyy" : rpc error: code = NotFound desc = Volume not found, failed with error: Retriable: true, RetryAfter: 0s, HTTPStatusCode: 503, RawError: {"error":{"code":"ServerTimeout","message":"The request timed out. Diagnostic information: timestamp '20220217T015824Z', subscription id 'xxxxx', tracking id '51d182a3-a748-4bfd-858c-7c04c4b3297c', request correlation id '51d182a3-a748-4bfd-858c-7c04c4b3297c'."}}

**What you expected to happen**:

Volume successfully mounted in a pod.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: csi
```

**Anything else we need to know?**:

Tried at least these storage classes which all were failing:
`default` `managed-csi` `managed-premium` `managed-csi-premium`
If I use `azurefile` storage classes then it works fine.
I've observed that the disk is in fact being provisioned on azure, but it is not being attached to the vmss  instance, If I attach the disk to vmss instance manually, the volume is then mounted to the pod and pod starts successfully.

**Environment**:
- Kubernetes version (use `kubectl version`): 
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

- Size of cluster (how many worker nodes are in the cluster?)

3 nodes.

- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)

http microservices

- Others:
AKS is in private mode

**Comment by andyzhangx** [comment]
the example works in my 1.22 cluster in `eastus2` region, which region are you in? And could you try 10 or 100Gi PVC size on that cluster?

**Comment by AurimasNav** [comment]
> the example works in my 1.22 cluster in `eastus2` region, which region are you in? And could you try 10 or 100Gi PVC size on that cluster?

westeurope, initially I've tried with 50Gi which also failed. Will try to upgrade cluster to 1.22.6 and see if that makes any difference.

**Comment by andyzhangx** [comment]
pls file an Azure support ticket when you hit again, it should be related to disk attachment issue on azure.

**Comment by andyzhangx** [comment]
close this issue since the root cause is DiskEncryptionSet is set on AKS cluster while control plane identity of cluster does not have permission to access the DiskEncryptionSet

**Comment by cheslijones** [comment]
> close this issue since the root cause is DiskEncryptionSet is set on AKS cluster while control plane identity of cluster does not have permission to access the DiskEncryptionSet

So what is the solution here?

I'm running into the same issue with:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
```
The `postgres-storage-prod` never provisions and just says: "waiting for first consumer to be created before binding." 

I try to bind with:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
        aadpodidbinding: aks-akv-identity
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_DB_FILE
              value: /mnt/secrets-store/PG-DATABASE
            - name: POSTGRES_USER_FILE
              value: /mnt/secrets-store/PG-USER
            - name: POSTGRES_PASSWORD_FILE
              value: /mnt/secrets-store/PG-PASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: "-A md5"
            - name: PGDATA
              value: /var/postgresql/data
          volumeMounts:
          - name: postgres-storage-prod
            mountPath: /var/postgresql
          - name: secrets-store01-inline
            mountPath: /mnt/secrets-store
            readOnly: true
      volumes:
        - name: postgres-storage-prod
          persistentVolumeClaim:
            claimName: postgres-storage-prod
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aks-akv-secret-provider
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service-prod
  namespace: prod
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
```
And nothing...
