### ISSUE TITLE
Azure files volume mount causing significant slowdown of network performance on Windows

### ISSUE THREAD

**Issue by artisticcheese** [Azure/AKS#2800]
**What happened**:
Azure files volume mount causing significant slowdown of network perfomance
**What you expected to happen**:
No slowdown
**How to reproduce it (as minimally and precisely as possible)**:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks
  template:
    metadata:
      labels:
        app: aks
    spec:
      containers:
        - name: aks
          image: artisticcheese/aks-servercore
          volumeMounts:
            - name: logs
              mountPath: "logs"
            - name: logs
              mountPath: "logs1"
            - name: logs
              mountPath: "logs2"
            - name: logs
              mountPath: "logs3"
            - name: logs
              mountPath: "logs4"
            - name: logs
              mountPath: "logs5"
        - name: aks-clean
          image: artisticcheese/aks-servercore
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule
      volumes:
        - name: logs
          azureFile:
            secretName: fileshare-secret
            shareName: logs
            readOnly: false

```
This deploys 2 containers, one with 6 volume mounts and another one without it. Shell into each of them and execute following, which is connecting to 1.1.1.1 via HTTP in parallel 100 times, 10 times in a row and outputs average time it took to do it

```powershell
pwsh -c {1..10 | foreach {(measure-command {1..100 | ForEach-Object -parallel { Invoke-Webrequest "http://1.1.1.1" -Method head | out-null}}) | select -property totalseconds} | measure-object -Property TotalSeconds -AllStats | select Average}
```
You shall be seeing similar statistics from both containers since they run on the same hardware, using the same image and generally exact copy of each other. In practice container with volume mounts slows down proportional to number of volume mappings. (for 6 mappings it's 6x slower)

6x volume mappings
```powershell
PS C:\workdir>  1..10 | foreach {(measure-command {1..100 | ForEach-Object -parallel { Invoke-Webrequest "http://1.1.1.1" -Method head | out-null}}) | select -property totalseconds} | measure-object -Property TotalSeconds -AllStats | select Average

   Average
   -------
6.36266226

```
No volume mappings
```powershell
PS C:\workdir>  1..10 | foreach {(measure-command {1..100 | ForEach-Object -parallel { Invoke-Webrequest "http://1.1.1.1" -Method head | out-null}}) | select -property totalseconds} | measure-object -Property TotalSeconds -AllStats | select Average

   Average
   -------
0.98009577
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"
```
- Size of cluster (how many worker nodes are in the cluster?)
2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Windows server core containers
- Others:
