### ISSUE TITLE
Question - Enable the sysctl whitelisting / allowlisting

### ISSUE THREAD

**Issue by kenchiayy** [Azure/AKS#2831]
Hello,

```
Technical Details:
- AKS Version: v1.23.3
```

One of container requires us access sysctl, therefore we configure our securityContext on pod level to be like this:

```
securityContext:
    sysctls:
      # To debug, login to the node, and cat /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts (should be 0)
      # Allow broadcast icmp for SYSLAN_MNG
      - name: net.ipv4.icmp_echo_ignore_broadcasts
        value: "0"
```

During the deployment, the pod failed with event `forbidden sysctl: "net.ipv4.icmp_echo_ignore_broadcasts" not allowlisted`

We tried to set the Pod Security Standards on namespace level:

```
pod-security.kubernetes.io/audit: privileged
pod-security.kubernetes.io/audit-version: latest
pod-security.kubernetes.io/enforce: privileged
pod-security.kubernetes.io/enforce-version: latest
pod-security.kubernetes.io/warn: privileged
pod-security.kubernetes.io/warn-version: latest
```

Still the same error event as above.

Question from us is how to configure pod deployment to allow sysctl whitelisting / allowlisting?
