### ISSUE TITLE
Support for topology spread constraints with cluster autoscaler

### ISSUE THREAD

**Issue by martin-adema** [Azure/AKS#2849]
When a deployment is applied using topology spread constraints with a maxSkew of 1 and topology key "topology.kubernetes.io/zone" the cluster autoscaler scales up 1 zone with too many nodes and after the scale-down-unneeded-time has passed they will be removed again.
There is a nodepool for each zone (3) and balance-similar-node-groups is set to true.

I would expect nodes to be added to each zone with the similar number of nodes and not unneeded nodes extra being added which are removed again the after scale-down-unneeded-time timeout.

The issue can be reproduced by applying a deployment with resource requests sized about half the size of the nodes, about 30 pods and with topology spread constraints configured:
`      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule`
Cluster setup with autoscaled nodepools per zone and with balance-similar-node-groups set to true..

MS support ticket 2112070050001650 was opened for this issue. Was told there is no special integration between pod topology spreading and CA as in this this behavior is expected. Advised to open issue and request for integration of topology spread constraints.

Kubernetes 1.21.9
1 system nodepool (Standard_D16as_v4) with 3 nodes (no autoscaling)
3 user nodepools (1 per zone, Standard_D16as_v4) and cluster autoscaling (3 - 30)

**Comment by lgmorand** [comment]
Hi my customer has the same issue using PodAntiaffinity and the CA never triggering when pods cannot be scheduled.

To be sure, is it linked to this [issue](https://github.com/kubernetes/autoscaler/issues/3879) ?

**Comment by anthonynguyen394** [comment]
Hi, requesting the same feature.
We are using AKS 1.28.5, with one nodepool spread across 3 zones. CA didn't trigger new node creation.
Topology settings: 
```
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: app-name
          minDomains: 3
```
