### ISSUE TITLE
Swagger Endpoint unavailable in AKS

### ISSUE THREAD

**Issue by j0nimost** [Azure/AKS#2854]
**What happened**:
I have a simple web api service deployed on AKS with the following `Startup.cs` configuration.
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddSwaggerGen(c =>
    {
        c.SwaggerDoc("v1", new OpenApiInfo { Title = "NashBillingService", Version = "v1" });
    });
}
// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
        app.UseSwagger();
        app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "NashBillingService v1"));
    }

    app.UseSwagger();
    app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "NashBillingService v1"));
    app.UseHttpsRedirection();
    app.UseRouting();
    app.UseAuthorization();
    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
    });
}   
```

and the following `deployment.yaml`
```yaml
apiVersion : apps/v1
kind: Deployment
metadata:
  name:  billingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billingservice
  template:
    metadata:
      labels:
        app: billingservice 
    spec:
      containers:
        - name: billingservice 
          image: nashtreasury.azurecr.io/billingservice:latest
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: nash-billingservice
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: billingservice
```

For some weird reason when I deploy on minikube I can access SwaggerUi but I can't when I deploy on AKS. However the, API endpoints are reachable.

To access the SwaggerUi locally I am using `{host}:{port}/swagger/index.html` but on AKS I get `page can’t be found`

**What you expected to happen**:
I expect the SwaggerUi to be accessible both locally and on AKS

**How to reproduce it (as minimally and precisely as possible)**:
Simply create a simple .Net Core Web API, (.net core 5) and replicate the settings

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"37f338aa38e0427e127162afe462e2f4150f0ba3", GitTreeState:"clean", BuildDate:"2022-02-07T20:49:26Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
.Net Core Web API (.net core 5)
- Others:
Swashbuckle.ASPNetCore (5.6.3)
