### ISSUE TITLE
Dynamically create and use a PV with Azure Disks is not provisioning PV and Azure Disk resource

### ISSUE THREAD

**Issue by cheslijones** [Azure/AKS#2856]
**What happened**: 
I've been using dynamically created and used PVC with Azure Disks for a couple years now. 

Currently, making a new cluster and Azure Disks refuses to allocate along with a PV when applying the PVC manifest.

Documentation for reference:

https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv

**What you expected to happen**:
My expectation is that the PV and Azure Disks will dynamically be allocated when I apply the PVC manifest. It just sits at `Pending` indefinitely.

**How to reproduce it (as minimally and precisely as possible)**:
Brand new AKS cluster and just trying to apply this.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 25Gi
```
Sits at this indefinitely:
```
NAME                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
file-storage-prod       Bound     pvc-03005337-e704-4b5f-899f-37eb56d6520e   25Gi       RWX            azurefile      3m17s
postgres-storage-prod   Pending                                                                        default        3m17s
```
Even tried to apply my `postgres.yaml` in hopes that it would wake it up:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
        aadpodidbinding: aks-akv-identity
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_DB_FILE
              value: /mnt/secrets-store/PROD-PGDATABASE
            - name: POSTGRES_USER_FILE
              value: /mnt/secrets-store/PROD-PGUSER
            - name: POSTGRES_PASSWORD_FILE
              value: /mnt/secrets-store/PROD-PGPASSWORD
            - name: POSTGRES_INITDB_ARGS
              value: "-A md5"
            - name: PGDATA
              value: /var/postgresql/data
          volumeMounts:
          - name: postgres-storage-prod
            mountPath: /var/postgresql
          - name: secrets-store01-inline
            mountPath: /mnt/secrets-store
            readOnly: true
          - name: file-storage-prod
            mountPath: /mnt/cronerapp/xls-imports
            subPath: xls-imports
      volumes:
        - name: postgres-storage-prod
          persistentVolumeClaim:
            claimName: postgres-storage-prod
        - name: file-storage-prod
          persistentVolumeClaim:
            claimName: file-storage-prod
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aks-akv-secret-provider
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service-prod
  namespace: prod
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432
```
Still nothing... just sits at `Pending`... I've tried deleting and reapplying about 100 times now.

**Anything else we need to know?**:
Nothing at this time.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22.6
- Size of cluster (how many worker nodes are in the cluster?): 1
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.):  Nothing at this point, just trying to get storage to allocate.
- Others:

**Comment by cheslijones** [comment]
... my PVC and PostgreSQL deployment weren't in the same namespace...

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-prod
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-prod
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 25Gi
```
Provisions it once the `postgres.yaml` is applied. User error.
