### ISSUE TITLE
Pod Topology Spread Constraints not working for AKS Windows node pool

### ISSUE THREAD

**Issue by markdebruijne** [Azure/AKS#2862]
**What happened**:
- AKS cluster with both a Linux `AKSUbuntu-1804gen2containerd-2022.03.02` and Windows `AKSWindows-2019-17763.2686.220309` node pool. Node pools configure with all three avalability zones usable in `west-europe` region.
- AKS cluster level and node pools all running Kubernetes `1.21.9`
- Pods (within replicaset with 2+)  running on Linux backed node pool **are spread**, although no explicit configured `topologySpreadConstraints`, **equally** across nodes (and thus availablility zones).
- Pods (within replicaset with 2+)  running on Windows backed node pool **are NOT spread equally**, also not with explicit `topologySpreadConstraints` configured.

**What you expected to happen**:
- AKS to logical spread across availablity zones and/or hostnames as per the documented default settings: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#internal-default-constraints
- AKS to respect explictly spread instruction as configured on deployment level (Windows pod).

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: win-world
  labels:
    app: win-world
spec:
  replicas: 6
  selector:
    matchLabels:
      app: win-world
  template:
    metadata:
      labels:
        app: win-world
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: win-world
      containers:
      - name: win-world
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
        ports:
        - containerPort: 80
      nodeSelector: 
          kubernetes.io/os: windows
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"37f338aa38e0427e127162afe462e2f4150f0ba3", GitTreeState:"clean", BuildDate:"2022-02-07T20:49:26Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
1x Linux node pool with 2 nodes, 1x Windows node pool with 2 nodes
```
kubernetes.azure.com/node-image-version=AKSUbuntu-1804gen2containerd-2022.03.02
kubernetes.azure.com/os-sku=Ubuntu
kubernetes.azure.com/role=agent
kubernetes.azure.com/storageprofile=managed
kubernetes.azure.com/storagetier=Premium_LRS
kubernetes.io/arch=amd64
kubernetes.io/hostname=aks-webl1-29467775-vmss000002
kubernetes.io/os=linux
kubernetes.io/role=agent
node-role.kubernetes.io/agent=
node.kubernetes.io/instance-type=Standard_D2as_v4
storageprofile=managed
storagetier=Premium_LRS
topology.disk.csi.azure.com/zone=westeurope-2 (or -0, or -1)
topology.kubernetes.io/region=westeurope
topology.kubernetes.io/zone=westeurope-2 (or -0, or -1)
```
```
kubernetes.azure.com/node-image-version=AKSWindows-2019-17763.2686.220309
kubernetes.azure.com/role=agent
kubernetes.io/arch=amd64
kubernetes.io/hostname=aksscw1000001
kubernetes.io/os=windows
kubernetes.io/role=agent
node-role.kubernetes.io/agent=
node.kubernetes.io/instance-type=Standard_D8as_v4
node.kubernetes.io/windows-build=10.0.17763
topology.disk.csi.azure.com/zone=westeurope-2 (or -0, or -1)
topology.kubernetes.io/region=westeurope
topology.kubernetes.io/zone=westeurope-2 (or -0, or -1)
```
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
ASP.NET + .NET Core, HTTP
- Others:
Recently upgraded from `v.1.20.9` to `v.1.21.9`, but in previous version also the same issue. 

Details about the node that remains empty attached.
When i drain node A, pods are being moved to node B.
![image](https://user-images.githubusercontent.com/19689903/159709022-59d60033-1d79-4c93-adec-94296caf1da3.png)
