### ISSUE TITLE
StorageClass parameter "cachingmode" is now case-sensitive

### ISSUE THREAD

**Issue by sebastianblunt** [Azure/AKS#2867]
**Describe the bug**

Setting `cachingmode: None` in a storageclass and then creating a PVC on that storageclass results in a PV with the default cachingmode `ReadWrite`. This prevents usage of ultra SSD disks, with the following error
```
HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "InvalidParameter",
    "message": "Storage Account type UltraSSD_LRS is not supported with caching type ReadWrite. Please use caching type None.",
    "target": "dataDisk.caching"
  }
}
```

If instead you set `cachingMode: None` (uppercase `M` instead of all-lowercase) then the disk correctly receives cachingmode `None`.

Lowercase `cachingmode` used to work. I have existing clusters with an unchanged StorageClass in which the existing PVs have the correct cachingmode, but attempting to create new PVCs on that StorageClass results in the new PVCs having the wrong cachingmode of `ReadWrite`.

The documentation also uses `cachingmode` in all-lowercase: https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv

**Steps To Reproduce**

Create this storageclass and PVC
```
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ultra-test-storage-class
parameters:
  cachingmode: None
  kind: Managed
  storageaccounttype: UltraSSD_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ultrassdtest
spec:
  storageClassName: ultra-test-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```
then look at the PV created by that PVC and notice that its `cachingMode` is set to `ReadWrite` instead of `None`.

**Environment**:
- Kubernetes version `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"37f338aa38e0427e127162afe462e2f4150f0ba3", GitTreeState:"clean", BuildDate:"2022-02-07T20:49:26Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}`
