### ISSUE TITLE
Unable to attach or mount volumes: timed out waiting for the condition

### ISSUE THREAD

**Issue by ermirh** [Azure/AKS#2877]
**What happened**: Deploying a Pod with volumes defined fail due to unable to attach or mount volumes. Only after a manual attach via portal or cli of the azure managed disk to the aks node, deployment was successful. 

**What you expected to happen**: Pod/Deployment successfully created and in the running state

**How to reproduce it (as minimally and precisely as possible)**:

PVC definition:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcdefault
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
```

Deployment definition:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pvcdefault
  name: pvcdefault
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvcdefault
  template:
    metadata:
      labels:
        app: pvcdefault
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - image: xxxxxxxxx.azurecr.io/ubuntu:latest
        name: pvcdefault
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: pvcdefault
          mountPath: /mnt/azure
      volumes:
      - name: pvcdefault
        persistentVolumeClaim:
          claimName: pvcdefault
```

**Anything else we need to know?**:

**Environment**:  Azure / `AKS`
- Kubernetes version (use `kubectl version`):   `1.22.6` 
- Size of cluster (how many worker nodes are in the cluster?)  3 nodes ( `AKSUbuntu-1804gen2containerd-2022.03.20` )
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
- Others: 
AKS agentPool type: `VirtualMachineScaleSets`
RBAC enabled
outboundType:  `userDefinedRouting`
Nodes encrypted using `DES`
