### ISSUE TITLE
Problems with image pull in AKS from ACR

### ISSUE THREAD

**Issue by SpyRefused** [Azure/AKS#2886]
I have an AKS cluster and an ACR registry in Azure. The cluster contains several Windows nodes where a WindowsServerCore based service is deployed. The image is in ACR, but for some reason I can't get it to pull the image, I always get the imagePullBackOff error.

I have tried all methods, attach the ACR in AKS, through a Secret (both using ACR admin and through a new Service Entity), but there is no way, everything fails. The strange thing is that when I do a `kubectl describe pod` it doesn't return me anything concrete, only the imagepull error, nothing else. It does not indicate authentication error...

```
Events:
  Type    Reason   Age                    From     Message
  ----    ------   ----                   ----     -------
  Normal  BackOff  85s (x1341 over 5h6m)  kubelet  Back-off pulling image "myacr.azurecr.io/so99:860"
```

Any idea what could be happening?

- Kubernetes version: Server: 1.21 Client: 1.23
- Size of cluster: 1 Linux Node, 2 Windows Node
- Workload: .Net 4.8 Windows Service, based on Server Core 2019 LTSC image
- Others:

**Comment by SpyRefused** [comment]
It seems that with the command `kubectl get events -w` I get more information. It is as follows:

```
0s Normal BackOff pod/sample-6cc86c967-jfh8x Error: ImagePullBackOff
0s Normal Pulling pod/sample-6cc86c967-jfh8x Pulling image "myacre.azurecr.io/so99:860"
0s Warning Failure pod/sample-6cc86c967-jfh8x Failed pulling image "toolsgroupaks.azurecr.io/so99:860": [error rpc: code = Unknown desc = an image based on Windows version 10.0.20348 is incompatible with a 10.0 host. 17763, error rpc: code = Unknown desc = Daemon error response: Head "https://toolsgroupaks.azurecr.io/v2/so99/manifests/860": unauthorized: authentication required, see https://aka.ms/acr/authorization for more information].
0s Warning Failed pod/sample-6cc86c967-jfh8x Error: ErrImagePull
```

Although this now makes little sense to me. There are two errors, one is an image incompatibility error and the other is an authentication error. What is the real error?

As I said before I am using as Base Image servercore:ltsc2019.

**Comment by brobichaud** [comment]
Random thought, but this bit me early on in my AKS with Windows journey. Is it possible one of your Linux nodes was scheduled and thus is failing to pull a Windows image? If so take a peek at your deployment yaml and see that you have a nodeAffinity setup to schedule it on Windows nodes only. For example:

```
affinity: # node scheduling: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeAffinity: # require scheduling on Windows nodes
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - windows
```
