### ISSUE TITLE
Can't mount a persistent volume claim in a pod in a private aks cluster 

### ISSUE THREAD

**Issue by aligidpro** [Azure/AKS#2979]
**What happened**:

We have two AKS clusters:

A public one for testing/staging
A private one for producrtion

We are trying to add a persistent volume to a pod on the private cluster but we keep getting an error. This works fine on the public cluster.

```
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk-nginx
```

And the error we get is: 

`  Warning  FailedMount         3m1s (x7 over 37m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[volume], unattached volumes=[kube-api-access-mnqg7 volume]: timed out waiting for the condition
  Warning  FailedAttachVolume  2m47s (x13 over 37m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1a01XXXXX0963-4d6f-XXXX-57eeb211eba6" : Attach timeout for volume /subscriptions/XXXXX-da16-4b47-b4d0-db6f7575049a/resourceGroups/mc_fnx-p-kubernetes_fnx-p-aks-01_westeurope/providers/Microsoft.Compute/disks/pvc-1a017a15-0963-4d6f-bff5-57eeb211eba6
  Warning  FailedMount         45s (x10 over 32m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[volume], unattached volumes=[volume kube-api-access-mnqg7]: timed out waiting for the condition
`

We have also tried using a manually created storage account with a private endpoint:

```
parameters:
  resourceGroup: XXXXXXX
  storageAccount: XXXXXX
  server: XXXXXX.privatelink.blob.core.windows.net
```

And then we get the following error:

`failed to provision volume with StorageClass "XXXXX-nodestorage-01": rpc error: code = InvalidArgument desc = Failed parsing disk parameters: invalid parameter server in storage class`

**What you expected to happen**:

Add the volume and mount it in a pod so the pod can use it.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a private AKS cluster
2. Add a storageclass or use existing ones
3. Try to claim a persistent volume
4. Get error and status stuck on pending

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23.5
- Size of cluster (how many worker nodes are in the cluster?): 2
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): Microservices
- Others:
