### ISSUE TITLE
Allow use of "attachable-volumes-azure-disk" as request

### ISSUE THREAD

**Issue by stefanofranz** [Azure/AKS#2989]
**What happened**:

I attempted to deploy a pod with the following resource requests:

```
        resources:
          requests:
            memory: 512Mi
            cpu: 200m
            attachable-volumes-azure-disk: '1'
```

Instead of scheduling onto an underlying node with at least 1 attachable disk, the following error was thrown

` [spec.template.spec.containers[0].resources.requests[attachable-volumes-azure-disk]: Invalid value: "attachable-volumes-azure-disk": must be a standard resource type or fully qualified, `

I cannot find reference to any microsoft specific namespaced resource types in the AKS docs. 

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to deploy a simple pod with a request of  `attachable-volumes-azure-disk: '1'`
