### ISSUE TITLE
Network policy not applied at the very beginning of a pod lifecycle

### ISSUE THREAD

**Issue by BzSpi** [Azure/AKS#2996]
Hello,

**What happened**:
* My pod has access to a resource outside pod at the very beginning of its lifecycle despite a network policy blocking egress

**What you expected to happen**:
* Resource access is blocked by network policy

**How to reproduce it (as minimally and precisely as possible)**:
Use case is with Machine Learning that access a storage, this is how it seems to be configured (closes source image)
Initial configuration:
* Network policy blocking egress outside cluster
* pod with init container that access resource outside cluster at the very beginning of its lifecycle (here, an Azure Storage Account)

Behavior:
* Resource outside cluster is accessible at the pod initialization (not expected)
* Resource outside cluster is not accessible when trying to access it later (expected)

**Anything else we need to know?**:
Answer from the Microsoft support
> From what I was been told, seems to be an expected behavior since that policy might not be taken immediately and runs after some time.

**Environment**:
- Kubernetes version: 1.23.5
- Size of cluster: 3 nodes
- General description of workloads in the cluster: Azure Machine Learning models
- Others: network policy mode is "azure" (not calico)

**Comment by BzSpi** [comment]
I went a bit further to reproduce this issue easily.

Here are the deployed configuration
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: dev
    spec:
      containers:
      - name: nginx-container
        image: nginx
      initContainers:
      - name: init-myservice
        image: curlimages/curl:latest
        command: ['curl', '-s', '--fail', "http://ip.clara.net"]
```
I've tried this configuration with Azure network policy engine and the Calico one.
This configuration has the expected behavior (aka, the pod does not start due to the init container failing) when using the Calico network policy engine.
When using the Azure engine, the pod is starting even if during the pod lifecycle the egress is blocked.

IMHO, this is a serious security issue that needs immediate mitigation.
