### ISSUE TITLE
[Issue] no matches for kind "GMSACredentialSpec" in version "windows.k8s.io/v1"

### ISSUE THREAD

**Issue by rrmistry** [Azure/AKS#3009]
Seeing this for a new AKS cluster with K8s version 1.23.5 for service plan and node pools:

```
no matches for kind "GMSACredentialSpec" in version "windows.k8s.io/v1"
```

The YAML we have is:

```yaml
apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: aks-gmsa-spec
credspec:
  ...
```

We cannot figure out if this is an issue with AKS or with `windows.k8s.io/v1` API version not being supported in K8s 1.23.5.

The same was working on AKS with K8s 1.22.6 few days ago for `windows.k8s.io/v1alpha1` but this API version stopped working for K8s 1.23.5, 1.22.6
