### ISSUE TITLE
Kubelogin is not able to convert the kubeconfig to azurecli format for 1.24.0 AKS cluster

### ISSUE THREAD

**Issue by gyuvaraj10** [Azure/AKS#3050]
**Describe the bug**
Kubelogin is not able to convert the kubeconfig to azurecli format for 1.24.0 AKS clusters.

**To Reproduce**
1. az login
2. az aks get-credentials -g "abc" -n "def"
3. kubelogin convert-kubeconfig -l azurecli

**Expected behavior**
```
- name: clusterUser_rc-zaks-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --server-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --login
      - azurecli
      command: kubelogin
      env: null
      provideClusterInfo: false
```

**Actual Config after running the command**
```
- name: clusterUser_rc-a-aks-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --client-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --tenant-id
      - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false
```

**Environment (please complete the following information):**
 -  Kubectl Client CLI Version - 1.24.1
 - Kubernetes version [e.g. 1.24.0]
 -  Kubelogin - 
  git hash: v0.0.13/52e83a071f39e9e039e95aa9a6fbea04855eae13
 Go version: go1.17.9
 Build time: 2022-04-23T00:49:14Z
