### ISSUE TITLE
[Question] How to disable or whitelist folders for Windows Defender? Windows AKS Nodes

### ISSUE THREAD

**Issue by thiagoloureiro** [Azure/AKS#3086]
**Describe scenario**
I have a cluster with windows nodes, and my app uses some files from the disk, turns out that windows defender is making the application very slow, I checked this issue here: https://github.com/Azure/AKS/issues/1462 and using the commands to disable windows defender ```Set-MpPreference -DisableRealtimeMonitoring $true``` 

Kubernetes: 1.23.5
Node Size: Standard_F4s_v2 (tried H models and many others, nothing changes)

This is before/after disabling windows defender in one of the API Calls
![image](https://user-images.githubusercontent.com/29433794/179163557-e26fa284-94bf-47e0-ab67-f2275d3bcc7a.png)

The issue here is, that every time a new node runs I have to RDP there and run commands, otherwise performance is bad.

**Question**
Is there any way to have this disabled or whitelisted by default? Or any folder that I can put my app that Windows Defender won't work like this?

**Comment by thiagoloureiro** [comment]
currently I'm running this to "fix" the issue:

```az vmss run-command invoke -g rg -n aksw01  --command-id RunPowerShellScript   --instance-id 6 --scripts "Set-MpPreference -DisableRealtimeMonitoring 1"```

**Comment by zhiweiv** [comment]
You can Windows Host Process container to make it easier, that is what I used now.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: windowsdefender
data:
  run.ps1: |- 
    while($true)
    {
        $time = Get-Date -Format 'MM-dd HH:mm'
        echo "$time - ensure anti-malware settting"
        Set-MpPreference -DisableRealtimeMonitoring $true
    	Start-Sleep 3600
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: windowsdefender
spec:
  selector:
    matchLabels:
      app: windowsdefender
  template:
    metadata:
      labels:
        app: windowsdefender
    spec:
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\SYSTEM"
      hostNetwork: true
      containers:
      - name: app
        image: mcr.microsoft.com/windows/servercore:ltsc2019
        command: ["PowerShell", "-File", "config/run.ps1"]
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: windowsdefender
      nodeSelector:
        kubernetes.io/os: windows
```
