### ISSUE TITLE
[Question] GitOps (FluxCD), HelmRepisitory ACR authentication

### ISSUE THREAD

**Issue by zaminda** [Azure/AKS#3091]
**Describe scenario**
I'm trying to use a FluxCD HelmRepisitory reference to a helm repository hosted on an ACR. The ACR is attached to the AKS. However, when I try to do this, I see an Aunauthorized 401 error on the HelmRelease. Having said that If I create a service principal with AcrPull permission and assign this, I can get the HelmRelease to work. Below is an example of a working HelmRepository manifest

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-helm-repo
  namespace: cluster-config
spec:
  type: "oci"
  interval: 1m
  url: oci://<my-acr-name>.azurecr.io/helm
  secretRef:
    name: acr-pull-user-1
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-pull-user-1
  namespace: cluster-config
stringData:
  username: <sp username>
  password: <sp password>

  
```

**Question**
How can I get the HelmRepisitory to work without specifying a service principal? Since this ACR is attached to the AKS and I can pull images without authentication, shouldn't I be able to do the same with HelmReleases? If this is possible, could you please provide an example YAML manifest?

Thank you!
