### ISSUE TITLE
[BUG] omsagent-win resource requests are undefined, set to limits.

### ISSUE THREAD

**Issue by mbelt** [Azure/AKS#3105]
**Describe the bug**
`omsagent-win` always claims half a core.

When the `omsagent` addon profile is enabled the daemonset that's installed for Linux nodes uses a reasonable resource profile.

**Linux Profile**
``` 
resources:
  requests:
    cpu: 75m
    memory: 325Mi
  limits:
    cpu: 500m
    memory: 750Mi
```
The daemonset for Windows nodes does not define requests, so they are set to the limits. 

**Windows Profile**
```
resources:
  limits:
    cpu: 500m
    memory: 600Mi
```

**Feedback**
`omsagent-win` should define a cpu request less than 100m. 

**To Reproduce**
1. Enable `omsagent` addon profile.
2. `kubectl describe -n kube-system pods omsagent-win`
3. Observe `requests.cpu` is set to 500m.

**Expected behavior**
`requests.cpu` should be less than 100m.

**Environment (please complete the following information):**
 - Kubernetes version 1.22.6
