### ISSUE TITLE
readiness probe not working with windows container

### ISSUE THREAD

**Issue by xXBasti** [Azure/AKS#3107]
**Describe the bug**
I am tring to define a readiness probe for .net containter on a windows node. Nevertheless nothing works and sets the pod to ready.
I followed the solution from https://github.com/Azure/AKS/issues/1836, which also does not work for me.
**To Reproduce**
The dockercontainer uses a entrypoint.cmd so that no exec command is defined. This is bascally the example from https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/AksSamples/teams-recording-bot/deploy/teams-recording-bot for more details
`      containers:
      - name: mycontainer
        image: "{{ include "imageDomain" . }}/project:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command:
              - powershell
              - mkdir c:\\tmp; fsutil file createnew c:\\tmp\healthy 100;
              - .\run.ps1
        readinessProbe:
          exec:
            command:
            - cmd
            - /c
            - dir 
            - c:\tmp\healthy
          initialDelaySeconds: 15
          periodSeconds: 10`

`      containers:
      - name: mycontainer
        image: "{{ include "imageDomain" . }}/project:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command:
              - powershell
              - mkdir c:\\tmp; fsutil file createnew c:\\tmp\healthy 100;
              - .\run.ps1
        readinessProbe:
          exec:
            command:
            - powershell
            - /c
            - echo $Env:FailState
          initialDelaySeconds: 15
          periodSeconds: 10
          env:
          - name: FailState
             value: "0"`

The only thing which worked was:
`      containers:
      - name: mycontainer
        image: "{{ include "imageDomain" . }}/project:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          preStop:
            exec:
              command:
              - powershell
              - mkdir c:\\tmp; fsutil file createnew c:\\tmp\healthy 100;
              - .\run.ps1
        readinessProbe:
          exec:
            command:
            - cmd
            - /c
            - echo 0
          initialDelaySeconds: 15
          periodSeconds: 10`

**Expected behavior**
Pod should be ready

**Environment (please complete the following information):**
 - Kubernetes version 1.21.9

**Additional context**

**Comment by wangyira** [comment]
@allyford @AbelHu

**Comment by junjiezhang1997** [comment]
@xXBasti I think the solution of https://github.com/Azure/AKS/issues/1836 may be out-of-time due to the upgradation of version. I use the following example and it works as expected. Hope it can help you. cc @AbelHu 
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-exec
spec:
  containers:
    - name: readiness
      image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
      command: ["powershell"]
      args: ["/c", "mkdir c:\\tmp; fsutil file createnew c:\\tmp\\healthy 100; Start-Sleep -s 30; del c:\\tmp\\healthy; rmdir c:\\tmp; Start-Sleep -s 600"]
      readinessProbe:
        exec:
          command:
          - cmd
          - /c
          - dir
          - c:\tmp\healthy
        initialDelaySeconds: 15
        periodSeconds: 10
  nodeSelector:
    "kubernetes.io/os": windows

```
**Environment:**
Since the k8s 1.21.9 is not supported now, I use k8s 1.22.6 as the environment.
