### ISSUE TITLE
[BUG] Warning on NSG creation for ipv6 service with floating ip disabled

### ISSUE THREAD

**Issue by lilinvictorms** [Azure/AKS#3136]
**Describe the bug**
Created a new ipv6 service in AKS ipv6 enabled cluster, and got event saying that the NSG creation failed due to mixed address family.

**To Reproduce**
1. Create AKS cluster with ipv6/kubenet enabled, and deploy a new ipv6 service by running command `kubectl apply -f myservice.yaml`:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-disable-load-balancer-floating-ip: "true"
  name: myservice-ipv6
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 5790
  selector:
    app: myservice
  sessionAffinity: None
  type: LoadBalancer
```
2. Run command `kubectl describe service/myservice-ipv6`
3. See error:
```
Events:
  Type     Reason                  Age   From                Message
  ----     ------                  ----  ----                -------
  Warning  SyncLoadBalancerFailed  23m   service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "ResourceCannotContainAddressPrefixesFromDifferentAddressFamilies",
    "message": "Resource /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Network/networkSecurityGroups/aks-agentpool-28343064-nsg/securityRules/ae714a780b5c64a0e970c40017465b3a-TCP-443-Internet contains IP addresses or prefixes that belong to different address families. All IP addresses or prefixes in the resource should belong to the same address family.",
    "details": []
  }
}
```
4. By checking the NSG resource in Azure portal, I can see from activity log that the rule creation request mixed ipv4 and ipv6 addesses for the target:
```
      {
        "name": "ae714a780b5c64a0e970c40017465b3a-TCP-443-Internet",
        "properties":
        {
          "access": "Allow",
          "destinationAddressPrefixes": ["10.3.0.4", "10.3.0.5", "10.3.0.6", "fd24:2675:4607:6165::4", "fd24:2675:4607:6165::5", "fd24:2675:4607:6165::6"],
          "destinationPortRange": "30342",
          "direction": "Inbound",
          "priority": 501,
          "protocol": "Tcp",
          "sourceAddressPrefix": "Internet",
          "sourcePortRange": "*"
        }
      }
```

**Expected behavior**
No warning event and the NSG rule is created successfully.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**
