### ISSUE TITLE
[BUG] cannot create azure lb when nodeport disabled

### ISSUE THREAD

**Issue by tg123** [Azure/AKS#3165]
**Describe the bug**

cannot create azure lb when nodeport disabled.
looks like health probe is based on nodeport

**To Reproduce**
1. Run command kubectl apply

```
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: default
spec:
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer
```

2. See error

```
Name:                     web
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=web
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.0.244.236
IPs:                      10.0.244.236
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                    From                Message
  ----     ------                  ----                   ----                -------
  Normal   EnsuringLoadBalancer    2m32s (x7 over 7m52s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  2m31s (x7 over 7m50s)  service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: {
  "error": {
    "code": "PortValueIsOutOfRange",
    "message": "Resource a9867d833973649cf8b733a6f68d0a4a-TCP-80 has invalid value of Port (0). The value must be between 1 and 65535.",
    "details": []
  }
}
```

**Expected behavior**

lb created

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version N/A
 - Kubernetes version: AKS 1.24.3
 - CLI Extension version N/A
 - Browser N/A

**Additional context**
