### ISSUE TITLE
AKS 1.22.11- Use of Existing/Cloned PVCs in statefulset [Question]

### ISSUE THREAD

**Issue by zohebs341** [Azure/AKS#3169]
**Describe scenario**
I've migrated in-tree storage class PVCs to CSI volumes. Now I want to use these cloned/existing PVCs in my stateful set, which is having 3 replicas. If I use the volume option in statefulset, then only the first pod is coming up with that PVC and the second pod is trying to use the same PVC(which the first pod has used). So the second pod is not coming up.

Dynamic volume provisioning is not happening, if I use existing PVC in statefulset.

**Question**
I am trying to find the best possible way to utilize my existing PVCs which is having a lot of data. 

Already I've tested the volumes option and volumeclaimtemplate option. But both are not helpful in my use case.

Refer options being used/tested: https://github.com/Azure/AKS/issues/3155

**Comment by zohebs341** [comment]
@andy-anhnguyen It would be great if you can provide your input.

**Comment by andyzhangx** [comment]
@zohebs341 you should create PV, and then create PVC with naming like volumeClaimTemplates.metadata.name-statefulsetname-num, bound PVC to PV first, and then scale statefulset replica num

**Comment by zohebs341** [comment]
@andy-anhnguyen Can you please have a look at this, I've attached a documentation with screenshot FYR.

It is just creating new PVC. If we are using volumeclaimtemplate option as you have suggested.

Please refer attachement.
[volumeclaimtemplates-existingpvc-usage.docx](https://github.com/Azure/AKS/files/9463240/volumeclaimtemplates-existingpvc-usage.docx)

**Comment by andyzhangx** [comment]
Here is the example about how to use existing volumes in statefulset:
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-storage-statefulset-azuredisk-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-azuredisk-0
  storageClassName: managed-csi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-storage-statefulset-azuredisk-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-azuredisk-1
  storageClassName: managed-csi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azuredisk
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset-azuredisk
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-azuredisk
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/azuredisk
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: managed-csi
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
```
