### ISSUE TITLE
[BUG] Internal Load Balancers not functional

### ISSUE THREAD

**Issue by Cpcrook** [Azure/AKS#3172]
**Describe the bug**
Internal load balancers are not responding to requests.  This became an issue on one of our clusters this past Sunday Aug 28, 2022.

**To Reproduce**
1. Deploy the following manifest
2. Attempt to access the IP assigned to the LoadBalancer to view the voting example app

```
apiVersion: v1
kind: Namespace
metadata:
  name: azure-vote
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: azure-vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: azure-vote
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: azure-vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: azure-vote-front
        image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
  namespace: azure-vote
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front
```
3. Describe new `azure-vote-front` service and get the LoadBalancer Ingress via `kubectl describe svc azure-vote-front`
4. Receive a timeout when accessing the internal LoadBalancerIP assigned to the resource

**Expected behavior**
I expect the Azure voting app to load in my browser (when on VPN peered with my cluster VNET).

**Screenshots**

Service describe output: 
![image](https://user-images.githubusercontent.com/643732/187744439-cc289487-8d62-4b35-80e1-9a2df7799d2b.png)

Site when functional on a public IP:
![image](https://user-images.githubusercontent.com/643732/187744317-4df887d3-8972-4302-84ae-c72bf4938722.png)

Site unresponsive on internal IP Load Balancer:

![image](https://user-images.githubusercontent.com/643732/187745851-43cbbfef-1c88-4a58-a14f-630aa9f1e95b.png)

**Environment (please complete the following information):**
 -  CLI Version:  2.33
 - Kubernetes version: 1.24.3 (also seemingly impacts 1.23.8 as we stood up a second cluster with the same k8s version as our functional prod cluster)
 - CLI Extension version: aks-preview 0.5.70

**Additional context**

For context, I have access to the VNET of the cluster via our VPN (all VNETs peered through a VWAN Hub).  We've tried restarting the hub to see if that fixes the issue, but it does not.  Confirmed I can access the VMSS pools that back the cluster via their health check HTTP endpoints, so it does not appear to be a connectivity / network security group issue with that VNET.

This seemingly occurred over the weekend, _possibly_ during an auto-upgrade of our preprod cluster.
