### ISSUE TITLE
Horizontal Pod Autoscalers don’t work with k8s 1.9.6

### ISSUE THREAD

**Issue by devkws** [Azure/AKS#318]
In k8s 1.8.7 HPAs worked fine but after upgrading they do not work. I even tried the Microsoft tutorial for HPAs in AKS, results in the same error. 

`unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)
horizontal-pod-autoscaler`

`failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from API: the server could not find the requested resource (get pods.metrics.k8s.io)`

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spacy
spec:
  replicas: 1
  template:
    metadata:
      name: spacy
      labels:
        app: spacy
    spec:
      containers:
      - name: spacy
        image: jgontrum/spacyapi:all_v2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
```
