### ISSUE TITLE
[BUG] Node says "Ready" but doesn't respond.

### ISSUE THREAD

**Issue by perosb** [Azure/AKS#3181]
**Describe the bug**
Node says "Ready" but doesn't respond.
I cannot connect to the node via RDP jump box.
Cannot shell into any of the pods.

The last log entries on the pods are from yesterday before "crash".

```
kubernetes.azure.com/node-image-version: AKSWindows-2019-containerd-17763.3287.220810
  nodeInfo:
    architecture: amd64
    bootID: "8"
    containerRuntimeVersion: containerd://1.6.6+azure
    kernelVersion: 10.0.17763.3287
    kubeProxyVersion: v1.24.3
    kubeletVersion: v1.24.3
    machineID: akswp01000014
    operatingSystem: windows
    osImage: Windows Server 2019 Datacenter
    systemUUID: 92217700-28A5-4E35-88D5-8330AA4B52C6

```

```
status:
  addresses:
  - address: 10.185.2.192
    type: InternalIP
  - address: akswp01000014
    type: Hostname
  allocatable:
    cpu: 3860m
    ephemeral-storage: 133703676Ki
    memory: 27724340Ki
    pods: "100"
  capacity:
    cpu: "4"
    ephemeral-storage: 133703676Ki
    memory: 33553972Ki
    pods: "100"
  conditions:
  - lastHeartbeatTime: "2022-09-06T06:51:43Z"
    lastTransitionTime: "2022-09-06T06:51:43Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2022-09-06T06:51:43Z"
    lastTransitionTime: "2022-09-06T06:51:43Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2022-09-06T06:51:43Z"
    lastTransitionTime: "2022-09-06T06:51:43Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2022-09-06T06:51:43Z"
    lastTransitionTime: "2022-09-06T06:51:43Z"
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
```
**Screenshots**
![image](https://user-images.githubusercontent.com/982752/188566775-6db0d521-4b9e-4b87-925d-74675cc4e4fb.png)

CPU went up to 60% more than 12h ago
![image](https://user-images.githubusercontent.com/982752/188567455-b06ed1f1-90a3-49bd-97ad-898ffbd25e3a.png)

The instance claims "Updating"
![image](https://user-images.githubusercontent.com/982752/188567525-3d91fe62-9756-4bc4-a7be-21a14b4cb701.png)

There is no manual nor automated node maintenance during this time to not sure why "Updating". All nodes are 5d18h old.
