### ISSUE TITLE
[Question] Why is cluster autoscaler not spinning up nodes to which pods have higher affinity?

### ISSUE THREAD

**Issue by AlexGoris-KasparSolutions** [Azure/AKS#3187]
**Describe scenario**
I'm trying to setup my AKS cluster in way that will leverage spot instances when excess resources are available, but in a way that there is a possibility to fall back to on-demand pricing, I have done this by defining several node pools:

- Autoscaling 0-15 standard_e2as_v4 with max price of 0.03/hr
  These nodes will have the `my-prefix.com/pricing_tier=low` label
- Autoscaling 0-15 standard_d2as_v4 with max price of 0.09/hr
  These nodes will have the `my-prefix.com/pricing_tier=high` label
- Autoscaling 0-15 standard_b2ms with on-demand pricing
  These nodes will have the `my-prefix.com/pricing_tier=max` label

I have then defined my workloads with the following affinity:
```yaml
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: my-prefix.com/pricing_tier
              operator: In
              values:
                - low
        weight: 100
      - preference:
          matchExpressions:
            - key: my-prefix.com/pricing_tier
              operator: In
              values:
                - high
        weight: 90
      - preference:
          matchExpressions:
            - key: my-prefix.com/pricing_tier
              operator: In
              values:
                - max
        weight: 80
```

This seems to work to some degree, at this moment I have 2 standard_e2as_v4 spot instance nodes running with some workloads on them, however, I also have 7 standard_b2ms on-demand nodes running most of my other workloads. There are some workloads which don't have the affinity set (mostly cluster operators like rabbitmq and elasticsearch), but I don't understand why the cluster autoscaler is not spinning up more spot instance nodes and migrating workloads to them.

**Question**
Given the above setup, why is the cluster autoscaler only spinning up 2 spot instance nodes?
Is there any way I can get more detailed logs/details on the decision-making process of the CA? I know about the `configmap/cluster-autoscaler-status` configmap but that is just showing everything is in order.
