### ISSUE TITLE
[Feedback] Slow/HighDelay Azure LoadBalancer Ingress "allocation"

### ISSUE THREAD

**Issue by brunomiguel-teixeira** [Azure/AKS#3255]
**Describe your scenario**
When creating a Service object of type LoadBalancer, probe & rules are successfully created in Azure Load Balancer. However, trying to ingress via that ALB rule takes a long time to start working.  We have use cases ranging from 5minutes to 27minutes.

**Environment**
**HTTP Client**
Location: Outside of AKS Subnet
Rate: 1 request per second

**AKS Cluster**
Kubernetes Version: v1.24.3
NodePoolCount: 1
NumberOfNodes: 1
NodeFamily: Standard_F16s_v2
CNI Plugin: Azure CNI (default one, not-overlay) - Single Subnet (both pods & nodes)
Workload: Base Nginx serving default page on port 80

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
  name: app
spec:
  ports:
    - name: https
      port: 18000
      protocol: TCP
      targetPort: 80
  selector:
    app: app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
```

**Timeline**
00h25m00s -> Manifest Applied.
00h25m00s -> HTTP Client Launched, targeting these endpoints, making 1 Request/Second.
00h25m05s -> IPTables NodePort & Port allocated & applied.
![image](https://user-images.githubusercontent.com/74252299/194867665-84e52841-e927-4c68-b69e-938d91b3a377.png)
00h25m05s -> LoadBalancer NIC, LB Rules & HealthProbes created & allocated
![image](https://user-images.githubusercontent.com/74252299/194867746-437edabd-2b78-4851-9b29-05c22abe8dad.png)
![image](https://user-images.githubusercontent.com/74252299/194867781-c0dcb4dd-e87c-47db-b118-8fdf4173cde1.png)
00h25m10s  -> Pods are READY & Endpoints are available.
00h25m15s. ->

HTTP GET Request performed locally on AKS node http://<LB-NIC-IP>:18000/
Returns 200 OK
This request hits the local netfilter rule so it does not actually go to the LoadBalancer.
However, it highlights that the Pod & Nodes rules are ready & working.

00h27m00s. -> Azure Load Balancer reports HealthProbes at 100% success rate.
![image](https://user-images.githubusercontent.com/74252299/194867930-4b61a27e-85b6-41b6-98e2-64d63ab0e640.png)

00h36m20s -> Ingress starts working via LB.
Ingress via Azure Load Balancer from Client outside of Cluster Nodes starts working ~11 minutes later.
![image](https://user-images.githubusercontent.com/74252299/194867975-cfea3f13-7abb-4287-821e-a681974f31c2.png)

Can you guys shed some information in what process/automation runs in the background that may be causing this delay?
