### ISSUE TITLE
Patch Flux extension manifests/controllers

### ISSUE THREAD

**Issue by joshuadmatthews** [Azure/AKS#3273]
### Discussed in https://github.com/Azure/AKS/discussions/3229

<div type='discussions-op-text'>

<sup>Originally posted by **pinkfloydx33** September 24, 2022</sup>
Is it possible to patch Flux-system controllers/customize manifests when using the Microsoft.flux (gitops) AKS extension?

For some workloads, such as Image Automation with reflector, it may be required to patch A. the controller arguments to enable auto Acr login and B. the pod labels for aad-pod-identity

Image reflector is disabled by default but can be enabled using  the cli via configuration settings for the extension. However there doesn't seem to be a way to patch these system controllers similar to the way you would if you bootstrapped Flux directly https://fluxcd.io/flux/guides/image-update/#using-native-azure-acr-auto-login</div>

**Comment by philwelz** [comment]
@joshuadmatthews did you try after deploying the extension to just patch the flux installation with flux :) ? I'm doing this as workaround to enable flux pulling oci artifacts from ACR.

**Comment by joshuadmatthews** [comment]
Can you share an example? Wasn’t aware there is a way to patch a manifest that flux doesn’t manage, but if that’s possible it would be great.

**Comment by philwelz** [comment]
@joshuadmatthews sure, I'm just using Kustomize for patching, checked all the labels and annotations etc from the deployment and here you go:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: source-controller
    app.kubernetes.io/instance: flux
    app.kubernetes.io/name: microsoft.flux
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: source-controller
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source-controller
  template:
    metadata:
      labels:
        app: source-controller
        app.kubernetes.io/name: microsoft.flux
    spec:
      containers:
      - name: manager
        env:
        - name: AZURE_CLIENT_ID
          value: <ID>
```
