### ISSUE TITLE
Invalidate old kubeconfigs

### ISSUE THREAD

**Issue by vlakka1** [Azure/AKS#3294]
**Describe scenario**
Our AKS cluster was recently integrated with AAD. Before that the kubeconfigs that were generated was with CN `masterclient` and O as `system:masters`.

The `client-certificate-data` for these generated kubeconfigs expired but still users are able to access all namespaces like a cluster Admin.

Sample kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://REDACTED:443
  name: REDACTED
contexts:
- context:
    cluster: REDACTED
    user: clusterUser_REDACTED_REDACTED
  name: REDACTED
current-context: REDACTED
kind: Config
preferences: {}
users:
- name: clusterUser_REDACTED_REDACTED
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: REDACTED
```

Decoded client-certificate-data:
```
Certificate Information:
Common Name: masterclient
Organization: system:masters
Valid From: October 16, 2020
Valid To: October 16, 2022
```

**Question**
How do I invalidate this kubeconfig to restrict users outside of the AAD group to not connect. Please let me know.
