### ISSUE TITLE
[BUG] Scaling from 0->X doesn't work when relying on RuntimeClass

### ISSUE THREAD

**Issue by lukerogers** [Azure/AKS#3311]
**Describe the bug**
I have a windows node pool set the a minimum of 0 and max of 50 so the pool is available if a Windows workload is needed. I set the nodeSelector and tolerations in the RuntimeClass and assign it to the Windows workload. This doesn't result in a scale up event. When I apply the settings directly to a deployment, the node pool scales up as expected.

**To Reproduce**
1. Create a windows node pool that can scale to 0. Let it scale down to 0.
2. Create the following RuntimeClass 
```
apiVersion: node.k8s.io/v1
handler: runhcs-wcow-process
kind: RuntimeClass
metadata:
  name: windows-2019
scheduling:
  nodeSelector:
    kubernetes.io/os: windows
  tolerations:
  - effect: NoSchedule
    key: os
    operator: Equal
    value: windows
```

3. Create a windows workload and assign that RuntimeClass to it. It will not scale up the node pool
4. Delete the RuntimeClass from your workload and apply the nodeSelector and tolerations directly to the workload. The node pool will scale up.

**Expected behavior**
The node pool should scale up based on RuntimeClass rules.

**Environment (please complete the following information):**
 - Kubernetes version 1.24.6

**Comment by AbelHu** [comment]
I think that node pool should be scaled by autoscaler and it seems like that autoscaler does not support RuntimeClass. @ShiqianTao will help on this.

**Comment by ShiqianTao** [comment]
I am unable to reproduce this issue. Here are the steps I followed, and the node was created by the autoscaler:  
1. Create an AKS cluster with a Windows node pool and set count to 0.  
2. Create the following RuntimeClass.  
```
apiVersion: node.k8s.io/v1
handler: runhcs-wcow-process
kind: RuntimeClass
metadata:
  name: runtimeclasswindows
scheduling:
  nodeSelector:
    kubernetes.io/os: windows
  tolerations:
  - effect: NoSchedule
    key: os
    operator: Equal
    value: windows
```
3. Deploy a Windows workload and assign the RuntimeClass to it.  
```
apiVersion: v1
kind: Pod
metadata:
  name: windows-pod
spec:
  runtimeClassName: runtimeclasswindows
  containers:
  - name: pause
    image: mcr.microsoft.com/oss/kubernetes/pause:3.9-hotfix-20230808
```
4. The Windows node was then created by the autoscaler.  

![image](https://github.com/user-attachments/assets/022f274d-957d-4309-86f5-ca90f2780db7)
