### ISSUE TITLE
[Question]  ClusterAutoScaler not working with Affintiy and Anti  Affintiy Rules

### ISSUE THREAD

**Issue by rishabh-arya95** [Azure/AKS#3378]
**Describe scenario**

I have created a deployment where I don't want pods to be scheduled together and want to be scheduled on specif nodes. For this I have used pod anti-affinity, node affinity, and taints+tolerations. Sharing my sample deployment file below.

I have a node pool with min 2 node and max 10 nodes. When trying to schedule the Cluster Auto Scaler does not add new nodes in this case, but when I manually add nodes to the pool they get scheduled.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: stage
    name: my-app
  name: my-app
  namespace: hyperexecute
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: stage
      name: my-app
  template:
    metadata:
      labels:
        environment: stage
        name: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hyenodepool
                operator: In
                values:
                - application
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector: 
              matchExpressions:
              - key: name
                operator: In
                values:
                - my-app
            topologyKey: kubernetes.io/hostname
      containers:
        image: my-app:latest
        name: my-app
        ports:
        - containerPort: 9876
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health
            port: 9876
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      terminationGracePeriodSeconds: 3600
      tolerations:
      - effect: NoSchedule
        key: application-pool
        operator: Equal
        value: "true"
```

Error Message
```
  Normal   NotTriggerScaleUp       30m                 cluster-autoscaler          pod didn't trigger scale-up: 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) didn't match Pod's node affinity/selector, 1 node(s) had taint {workload: utility}, that the pod didn't tolerate
  Normal   NotTriggerScaleUp       25m (x10 over 30m)  cluster-autoscaler          pod didn't trigger scale-up: 2 node(s) didn't match Pod's node affinity/selector, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had taint {workload: utility}, that the pod didn't tolerate
```

**Question**
Is there some configuration required for ClusterAutoScaler to work with Affinity and Anti-Affinity Rules or is this some bug?

**Comment by justindavies** [comment]
@gandhipr any ideas on this?

**Comment by gandhipr** [comment]
Could you please elaborate on the taint - workload:utility?
Why is that taint on the node and if that taint is needed, could you try having your application deployment with tolerance of that taint.

**Comment by rishabh-arya95** [comment]
Hi @gandhipr 
So we have different node groups in our AKS cluster with separate taints like `workload=utility`, `application-pool=true` etc, similarly, we have node labels for node affinity.

We have done this as want to run our microservices and services like argocd, cert-manager etc on separate node pools.
If you see my deployment config there is already toleration there
```
      tolerations:
      - effect: NoSchedule
        key: application-pool
        operator: Equal
        value: "true"
```
