### ISSUE TITLE
Enhancement: Enable DNS Metrics

### ISSUE THREAD

**Issue by malachma** [Azure/AKS#345]
This is an Enhancement/Feature Request

Currently kube-dns does not expose the dns-metrics, either via the Standard port 10055 or any other port.
Due to the missing dns-metrics port external monitoring Solutions like datadog are not able to be used, as they expect the metrics port open and available.

**Comment by slack** [comment]
This is a good call, I've created a ticket in our backlog to track.

**Comment by devkws** [comment]
+1

Having these metrics would be quite useful.

**Comment by jalberto** [comment]
any progress on this?

**Comment by NicolaiPetri** [comment]
Hi. 
I got this partially working on my aks cluster by doing the following:

`kubectl edit deployment -n kube-system kube-dns-v20
`

and then inserted the following setting
        env:
        - name: PROMETHEUS_PORT
          value: "10055"

This makes polling of port 10055 work.

**Comment by StianOvrevage** [comment]
@NicolaiPetri s workaround works here. I also added the sidecar container that exposes dnsmasq metrics.

Here is how to apply both workarounds and this makes default prometheus-operator setup to automatically start scraping both metrics. Save the following file as `kube-dns-metrics-patch.yaml` and run `kubectl patch deployment -n kube-system kube-dns-v20 --patch "$(cat kube-dns-metrics-patch.yaml)"` to apply the changes.

``` 
spec:
  template:
    spec:
      containers:
      - name: kubedns
        env:
        - name: PROMETHEUS_PORT
          value: "10055"
      - name: sidecar
        image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.10
        livenessProbe:
          httpGet:
            path: /metrics
            port: 10054
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        args:
        - --v=2
        - --logtostderr
        - --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local
        - --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local
        ports:
        - containerPort: 10054
          name: metrics
          protocol: TCP
        resources:
          requests:
            memory: 20Mi
            cpu: 10m
```
