### ISSUE TITLE
[BUG] kube-proxy uses `rprivate` mount propagation to mount host's `/var/lib/kubelet` directory

### ISSUE THREAD

**Issue by ntsiron** [Azure/AKS#3535]
**Describe the bug**

kube-proxy uses `rprivate` mount propagation to mount the host's `/var/lib/kubelet` directory:

```
        volumeMounts:
        - mountPath: /var/lib/kubelet
          name: kubeconfig
          readOnly: true

      ...

      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: ""
        name: kubeconfig
```

kube-proxy uses the default mount propagation, which is `rprivate`.

This has the potential to break CSI plugins, which mount volumes under `/var/lib/kubelet`, per the CSI specification (https://kubernetes-csi.github.io/docs/deploying.html#driver-volume-mounts).

If a kube-proxy Pod is restarted, after a CSI driver mounts a device under `/var/lib/kubelet` on the same node, then kube-proxy will keep the device mounted, even after the CSI driver unmounts it.

For example, let's take the `default` (`disk.csi.azure.com`) Storage Class. It seems that the disk is forcefully detached from the node, during `ControllerUnpublishVolume` request, even though it's still mounted in the mount namespace of the kube-proxy Pod. This results in an unclean unmount.

The `csi-azuredisk-node` Pod runs `fsck -p` when it mounts again the volume, which replays the journal and hides the issue. But, still, this is not ideal.

**To Reproduce**
1. Deploy a Pod using a PVC with the `default` storage class
2. Restart the kube-proxy Pod of the corresponding node, where the Pod is scheduled
3. Exec into the kube-proxy Pod and search for the PV in `/proc/1/mountinfo`. For example,
   ```
   # grep pvc-2bb7b21b-3f5b-4bcf-bbfb-237a5f11b6a7 /proc/1/mountinfo
   10675 10437 8:64 / /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-2bb7b21b-3f5b-4bcf-bbfb-237a5f11b6a7/globalmount rw,relatime - ext4 /dev/sde rw
   10676 10437 8:64 / /var/lib/kubelet/pods/d9f7159a-6c4b-4765-a675-e814f203b527/volumes/kubernetes.io~csi/pvc-2bb7b21b-3f5b-4bcf-bbfb-237a5f11b6a7/mount rw,relatime - ext4 /dev/sde rw
   ```

   The mounts are `private`.

**Expected behavior**

kube-proxy should use the `HostToContainer` mount propagation. This way, when the CSI driver unmounts the volume, the unmount will be visible to kube-proxy.

**Environment:**
 -  CLI Version: v1.22.13
 - Kubernetes version: v1.23.8

**Comment by ms1111** [comment]
I've been running into this when kube-proxy restarts a while after some CSI volumes have already been mounted. (Not sure why kube-proxy restarts, maybe a software update?)

I've edited the kube-proxy `DaemonSet` to work around it:

```yaml
        volumeMounts:
        - mountPath: /var/lib/kubelet
          mountPropagation: HostToContainer
          name: kubeconfig
          readOnly: true
```

I don't imagine this change will stay in place, though; I assume something is pushing this manifest into the cluster and will overwrite it before too long.

Looks like the ama-logs version of this bug (#3999) is being fixed in https://github.com/microsoft/Docker-Provider/pull/1168. Would be nice to have a fix for kube-proxy as well. For us, it prevents ZFS volumes from being exported (unmounted) and moved to another node.

**Comment by andyzhangx** [comment]
there is no `/var/lib/kubelet` hostPath mount path for kube-proxy now, so this is not an issue now

```
      volumes:
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: iptableslock
      - hostPath:
          path: /etc/sysctl.d
          type: Directory
        name: sysctls
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
```
