### ISSUE TITLE
[BUG] Workload identity has broken after warning and upgrade to latest Kubernetes AKS cluster version

### ISSUE THREAD

**Issue by xtianus79** [Azure/AKS#3546]
**Describe the bug**
I got an email back in Janurary 1/24/23 to be exact, that I needed to add the `azure.workload.identity/use: "true"` label in your pod labels as soon as possible. 

I also, got the email that I needed to upgrade my cluster (not a fan auto upgrading) that's scary per se. From this version `AKS is retiring v1.23.x on 2 April 2023` 

BTW thank you very much for the emails they were apt. 

So, I upgraded my AKS and an engineer reported that the service layer related to the workload identity pod was down. So I investigated. Also to note, the reason why I'm explaining the story this way is because the documentation seems to be different compared to the code I was running before and it's confusing me on what I should focus on to correct the issue. Let me explain. 

I updated the cluster and went back to the workload identity email and documentation. 

It now seems that the label of `azure.workload.identity/use: "true"` should be put in the pod instead of the `ServiceAccount` which is where I had the label before. Noted here. 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "xxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxx"
  labels:
    azure.workload.identity/use: "true"
  name: "xxxxx-sa"
  namespace: "xxxxx-api"
```
Side question, I can't find that service account anywhere. Where is that exactly/how do you find that? Is it in AKS or another resource group. Anyway, I had my Yaml file. 

The other file which is the pod yaml does not have the `azure.workload.identity/use: "true"` in it BUT the new documentation is showing that is where it needs to be. 

My question is, should I remove the label from the service account, reestablish it, "I'd prefer not to do that but if I have to I have to" and then add the label to the pod layer? 

It's just difficult to tell because I'm seeing the new documentation and not an upgrade instruction. 

Thanks.
