### ISSUE TITLE
[BUG] Internal load balancer unstable when autoscaling cluster

### ISSUE THREAD

**Issue by thomastvedt** [Azure/AKS#3634]
**Describe the bug**
When cluster is autoscaling a service exposed on the internal load balancer stops responding for a short while. It looks like the internal load balancer becomes unstable when cluster is autoscaling.

More details:  
We enabled autoscaling on our AKS cluster. Normally this runs at 2 nodes, when traffic increases it is scaled up to 3 for a short while, and then back down to 2 nodes.

We have a redis service hosted in our cluster, exposed as a LoadBalancer service, using annotations to use an internal load balancer:

```yaml
  service:
    type: LoadBalancer
    ports:
      redis: 6379
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.111.16.123
```

This makes our Redis service available outside the cluster, inside our vnet, reachable by a different service that currently runs on a separate virtual machine. 

When the cluster auto-scales up / down, we observe Redis timeout exceptions in our service running outside the cluster.

We observe a drop/spike in traffic to our Redis service:
![image](https://user-images.githubusercontent.com/4746639/235874852-efce89a2-6eca-4646-b000-8849b5ebf981.png)

The Redis pod/instance is not killed when autoscaling.

There is a drop in "health probe status" in the underlying load balancer resource in Azure control panel:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/4746639/235876061-f90ac8da-608d-4d8e-800a-9444eb5cafeb.png">

And data path availability:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/4746639/235876161-e5ff2616-2902-4d6c-b9bd-14db482e48dc.png">

We also observe an event in our cluster when this happens: "Updated load balancer with new hosts".

**Expected behavior**
I expected that the internal load balancer would work 100% also when the cluster is autoscaling.

**Environment (please complete the following information):**
 - Kubernetes version [e.g. 1.25.5]

How can I troubleshoot this further? Can I view logs from the internal load balancer? Where can I find logs?
