### ISSUE TITLE
[BUG] LoadBalancer services use incorrect readiness logic with appProtocol=http

### ISSUE THREAD

**Issue by howardjohn** [Azure/AKS#3646]
**Describe the bug**
Service YAML:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - name: http
      appProtocol: http
      port: 80
```

Per Kubernetes spec, endpoints of the service should be determined by the Endpoints/EndpointSlice health, which is determined by the pod's readinessProbe.

However, per https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#custom-load-balancer-health-probe, this is not the case for this service. Instead, HTTP requests to `/` will be sent to port 80 to determine health. This seems to violate the Service spec.

From a practical standpoint, this breaks usage of Istio Gateway-API, which create Services like this. However, we do not respond to `GET /` on port 80 (unless the user configures a route matching that, of course). If we do respond to it, we are likely forwarding it to some other service, which is fairly incorrect.

The end result is that users of Istio Gateway on Azure will see traffic not work due to failing health check. We can recommend users manually set a bunch of annotations to make things work, but this is tedious for users and leads to different usage for Azure vs other platforms. We could automatically detect + insert these for azure users, but we prefer to avoid vendor specific workarounds.
