### ISSUE TITLE
Azure Container Storage

### ISSUE THREAD

**Issue by olsenme** [Azure/AKS#3676]
For more information on Azure Container Storage:
• aka.ms/AzureContainerStorageBlog
• aka.ms/AzureContainerStorage
• aka.ms/AzureContainerStorageTechBlog
• aka.ms/AzureContainerStorageDocs
To sign up for the Azure Container Storage preview: aka.ms/AzureContainerStoragePreviewSignUp

**Comment by lorbichara** [comment]
GA release date: end of H2 CY23

**Comment by keult** [comment]
I've tried to test the Azure Container Storage Preview with the following StatefulSet:   

_Note the_ `persistentVolumeClaimRetentionPolicy` _key at the end of the manifest file_
```yaml
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: azurediskpvc
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
  volumeClaimTemplates:
  - metadata:
      name: azurediskpvc
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: acstor-newazuredisk
      resources:
        requests:
          storage: 10Gi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
```
The Kubernetes Documentation states:   
[https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention)

> **PersistentVolumeClaim retention**
The optional .spec.persistentVolumeClaimRetentionPolicy field controls if and how PVCs are deleted during the lifecycle of a StatefulSet. You must enable the StatefulSetAutoDeletePVC [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) on the API server and the controller manager to use this field. Once enabled, there are two policies you can configure for each StatefulSet:
**whenDeleted**
configures the volume retention behavior that applies when the StatefulSet is deleted
...  
  
The StatefulSet and the Storage Pool works fine, but once I delete the StatefulSet, the Persistent Volume Claim created by the  StatefulSet  is not deleted automatically. It seems that the `persistentVolumeClaimRetentionPolicy `key is ignored by the StatefulSet controller.   
Is the `persistentVolumeClaimRetentionPolicy` key in StatefulSet is not supported by the Azure Container Storage Preview?
I can raise this topic as a new issue if it's prefered.
