### ISSUE TITLE
[Question] Allow EnvoyFilter in Istio addon for common scnearios

### ISSUE THREAD

**Issue by ddx3r** [Azure/AKS#3792]
**Describe scenario**
Hi
I'm interested in using Istio mesh add-on for AKS, but this preview is not much configurable atm.

**Question**
Do you have some public roadmap for work on this add-on when do you plan to enable envoy filters and such, cover another Istio features?

**Comment by dpaardenkooper** [comment]
Any updates about this topic? I also have customer who have interest in de envoy filters

**Comment by metaphy6** [comment]
Yes! We need EnvoyFilters to add some important headers because our security audits complain them missing, which's not good start for startups like us who go live soon. Also, we'd like to be able to update Load Balancer properties, specifically 'externalTrafficPolicy'. For the users of cloud services providers like Azure, offering an Istio that's cut off its critical features is very discouraging

**Comment by ianphil** [comment]
This is preventing us from adopting this feature of AKS also.

**Comment by glorious-beard** [comment]
Can you add conversion of gRPC-Web to gRPC as one of the common scenarios?

i.e.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: grpc-web-filter
  namespace: <namespace>
spec:
  workloadSelector:
    labels:
      service: <service-name>
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.grpc_web
```
