### ISSUE TITLE
[Feature] Ability to use (private) registry mirror for mcr.microsoft.com

### ISSUE THREAD

**Issue by mkilchhofer** [Azure/AKS#3853]
**Is your feature request related to a problem? Please describe.**
Yes, we at @swisspost have a very strict networking design. Our K8s nodes should not connect to the internet to download "system container images" from mcr.microsoft.com.

**Describe the solution you'd like**
We should be able to provide an alternative registry (mirror) for the system components so that we could use our own ACR (an/or another registry) where we mirror the needed images.

**Describe alternatives you've considered**
We can control the config file `/etc/containerd/config.toml` on every node so that we are able to define registry mirror like described here:
https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-credentials-example---gcr-with-service-account-key-authentication
Eg.:

```toml
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://registry-1.docker.io"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = ["https://gcr.io"]
```

**Additional context**
none
