### ISSUE TITLE
[BUG] Persistent Volume Claim Annotation is not updated

### ISSUE THREAD

**Issue by sprayzcs** [Azure/AKS#3858]
**Describe the bug**
When rescheduling a pod to another node, the pvc annotation `volume.kubernetes.io/selected-node` is not updated to the name of the new node.

**To Reproduce**
1. Create Pod with PVC
2. Reschedule Pod to new Node
3. Check Annotations of the PVC

**Expected behavior**
The annotation `volume.kubernetes.io/selected-node` is updated to the new node.

**Screenshots**
This is the output after the reschedule to the new node:
```
> kubectl describe pvc unstable-report-pvc
Name:          unstable-report-pvc
[...]
Annotations:
               [...]
               volume.kubernetes.io/selected-node: aks-systempool-27372749-vmss000000
Used By:       unstable-config-5d8cf8cb46-k48vw
StorageClass:  managed-csi-hdd
```

```
> kubectl describe pod unstable-config-5d8cf8cb46-k48vw
Name:             unstable-config-5d8cf8cb46-k48vw
Node:             aks-agentpool-32048320-vmss000000/10.200.16.63
[...]
```

As you can see, the `Node` of the pod and the annotation `volume.kubernetes.io/selected-node` do not match, as i would have expected

**Environment (please complete the following information):**
 - Kubernetes version [e.g. 1.24.3]: 1.26.6

**Additional context**
I am using a custom storage class to create a HDD pv:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-hdd
parameters:
  skuName: Standard_LRS
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
