### ISSUE TITLE
 Azure Kubernetes Service Cluster User Role on a group doesn't work

### ISSUE THREAD

**Issue by ser789654** [Azure/AKS#3883]
**Describe scenario**
I set one of our users to Contributor in AKS. He succesfully ran cmd:` az aks get-credentials --resource-group ****** --name **** --admin`
We decided to switch cluster to Azure AD authentication with kubernetes RBAC. I created AD group with `Azure Kubernetes Service Cluster User Role`, then I deleted that user as a contributor and added him to that new group.   Then when he wants to run cmd: `az aks get-credentials --resource-group ***** --name **** --overwrite-existing` it gives him error: The client ****** with object id 'xxx' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/listClusterUserCredential/action' over scope....

**Question**
Can you help me how to solve this?

**Comment by PixelRobots** [comment]
Hello, the role you have given is for the AKS resource in the Azure portal. 

To view the items in the cluster and even get the Kube config you need to also assign an Kubernetes RBAC role.

Check here for the listed roles. https://learn.microsoft.com/en-us/azure/aks/concepts-identity#built-in-roles

You probably want one of the first ones depending on your needs or maybe even a custom one.

Hope that helps. 

Let me know if you have any issues. 

Thanks

Richard

**Comment by ser789654** [comment]
Yeah I forgot mention that. I already did that. I assigned the first one(Azure Kubernetes Service RBAC Reader) to the group which that user is in.

manifest:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-reader
subjects:
- kind: Group
  name: VIEW_GROUP
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
```

I used group name in the subject, is that correct? Or should I use some ID?
