### ISSUE TITLE
[Question] Azure AKS flux extension -- How do I use secrets-store-csi-driver?

### ISSUE THREAD

**Issue by Poltergeisen** [Azure/AKS#3894]
**Describe scenario**
I followed the tutorial for enabling the secrets csi driver to connect to key vault. It works great when I manually apply my manifests.

When I went to upgrade our deployments to use gitops I am not facing a problem where the `flux-applier` account doesn't seem to be able to access or apply my configurations.

**Question**
What do I need to do to get the `flux-applier` account to be able to use the secrets-store-csi-driver to get keys from key vault?

**Comment by Poltergeisen** [comment]
Here's what my logs are showing:
```
"message": "SecretProviderClass/azure-sync dry-run failed, reason: Forbidden: secretproviderclasses.secrets-store.csi.x-k8s.io \"azure-sync\" is forbidden: User \"system:serviceaccount:lighthouse-samples-tst:flux-applier\" cannot patch resource \"secretproviderclasses\" in API group \"secrets-store.csi.x-k8s.io\" at the cluster scope: Azure does not have opinion for this user.",
```

**Comment by Poltergeisen** [comment]
For anyone that might google this. 

I fixed this by creating the intial kustomization file with the `spec.serviceAccountName` property set. Once I set that to `flux-system` it worked.

```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lighthouse-samples
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
```
