### ISSUE TITLE
[Question] How to white list service-tags and IP together

### ISSUE THREAD

**Issue by ChenglongLiu** [Azure/AKS#3916]
**Describe scenario**

We are an internal team and are required to enable service tags for our service. Without loadBalancerSourceRanges, service tags work well. But After adding `loadBalancerSourceRanges` with ip, all traffic from service tags is blocked.

```
metadata:
  annotations:
    service.beta.kubernetes.io/azure-allowed-service-tags: "AzureResourceManager"
spec:
  loadBalancerSourceRanges:
  - xxx.xxx.xxx.xxx
```

Old issue: https://github.com/Azure/AKS/issues/2281

**Question**
How to allow traffic from service tags and some IPs?
