### ISSUE TITLE
TokenReview api

### ISSUE THREAD

**Issue by adaniline** [Azure/AKS#393]
Hi,

I know that RBAC is not fully supported in AKS, although all the APIs seem to be enabled.

Is it still possible to use TokenReview api for service-to-service authentication? 

I've created an ClusterRoleBinding for my service account as follows:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myservice-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: my-service
  namespace: myproject
```

However I get "401 - Unauthorized" response from the token review api endpoint /apis/authentication.k8s.io/v1/tokenreviews when I call it with the service token
