### ISSUE TITLE
[BUG] KEDA Addon Not Properly passing Authorization Header for Github

### ISSUE THREAD

**Issue by jordanrbaker** [Azure/AKS#3961]
(I have a sense this belongs in the KEDA side of the fence to resolve as the header would be constructed by the scaler but their instructions said to come here for any aks addon related woes)

**Describe the bug**
I am using the Github Scaler introduced in 2.10 (https://keda.sh/docs/2.10/scalers/github-runner/), after setting up the scaler, trigger references and secrets, the scaler fails to connect to github.  Logs show this error, indicating the Authorization header is not being passed correctly:

` Get "https://api.github.com/repos/jordanrbaker/<repo>/actions/runs": net/http: invalid header field value for "Authorization" `

**To Reproduce**
1. Set up baseline AKS Cluster, one linux nodepool, one windows server 22 node pool.
2. Enable the KEDA scaler addon
3. Generate your github PAT and base64 encode it with the following powershell code:

``` 
$Text = "<your token>"
$Bytes = [System.Text.Encoding]::Unicode.GetBytes($Text)
$EncodedText =[Convert]::ToBase64String($Bytes)
$EncodedText
```

5. Set up the scaler as indicated in the instructed linked above.
6. Check the kubeevent logs to validate that the scaler is failing to connect.

**Expected behavior**
The Authorization head should be constructed correctly to enable a functional call to the api.

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version 2.48.1
 - Kubernetes version 1.26.6

Runner Deployment YAML (Scrubbed):

``` 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghrunnerwin
spec:
  replicas: 1
  selector:
    matchLabels:
      environment: runner    
  template:
    metadata:
      labels:
       environment: runner
    spec:
      containers:
      - name: winrunner22
        image: <acr>.azurecr.io/images/win22ephem:latest        
        ports:
        - containerPort: 443
        env:
        - name: GH_OWNER
          value: "<owner>"
        - name: GH_REPOSITORY
          value: "<repo>"
        - name: GH_TOKEN
          value: "<pat>"
```

KEDA Scaler YAML (Scrubbed):

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-auth
data:
  personalAccessToken: <pat>
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: github-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: github-auth
      key: personalAccessToken
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: github-runner-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: ghrunnerwin
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: github-runner
    metadata:
      githubAPIURL: "https://api.github.com"
      owner: <owner>
      runnerScope: repo
      repos:<repo>
      labels: "Windows"
      targetWorkflowQueueLength: "1"
    authenticationRef:
     name: github-trigger-auth          
```

**Comment by jordanrbaker** [comment]
Adding some additional info - using the same image and scaler parameters in container apps works as expected.

**Comment by jordanrbaker** [comment]
Additional context - passing the value as plaintext stringData instead of the base64 converted secret also works.

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-auth
#data:
stringData:
  personalAccessToken: <plaintext pat>
  ```
