### ISSUE TITLE
[Feature] Hubble in Azure CNI Powered by Cilium

### ISSUE THREAD

**Issue by illrill** [Azure/AKS#3978]
I'd like to see support for Hubble (hubble-relay and hubble-ui) in Azure CNI Powered by Cilium

**Comment by siegenthalerroger** [comment]
Our team is also looking to have hubble enabled in Azure CNI Powered by Cilium. Less interested in hubble-ui tbh, as that is deployable in standalone mode and could easily be left to the user. 

Being able to configure Cilium the same way e.g. CoreDNS is configured would be great, allow us to enable Hubble and Service Mesh as we see fit.

**Comment by mac-kul** [comment]
is there any other good solution that could help us with network observability? On the [docs](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium) we can see the benefit: 
- Better observability of cluster traffic

How this can be achieved? I would like to be able to monitor the traffic inside the cluster.

**Comment by PixelRobots** [comment]
> is there any other good solution that could help us with network observability? On the [docs](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium) we can see the benefit:
> 
> * Better observability of cluster traffic
> 
> How this can be achieved? I would like to be able to monitor the traffic inside the cluster.

Hi @mac-kul 

Check out this doc's page. https://learn.microsoft.com/en-us/azure/aks/network-observability-managed-cli?tabs=cilium.

It is currently in preview but could be a good starting point for you to look at. It also supports non cilium clusters.

**Comment by siegenthalerroger** [comment]
@PixelRobots from what I understand, Network Observability only provides metrics about aggregate traffic (bandwidth, latency, etc). There's no capability for a "Flow" type view, where you can see/analyse individual requests/packets right?

**Comment by PixelRobots** [comment]
> @PixelRobots from what I understand, Network Observability only provides metrics about aggregate traffic (bandwidth, latency, etc). There's no capability for a "Flow" type view, where you can see/analyse individual requests/packets right?

According to the docs it currently only supports node level metrics. So it suggests that pod level metrics will hopefully come soon.

In the meantime it could also be good to look at https://www.inspektor-gadget.io/. To fill the gap when troubleshooting.

**Comment by illrill** [comment]
> Being able to configure Cilium the same way e.g. CoreDNS is configured would be great, allow us to enable Hubble and Service Mesh as we see fit.

I really like this idea. By providing a way for users to override the cilium-config CM, a lot of other Cilium-related issues (e.g. #3450 #3797) could also be closed, since we would have the ability to toggle on these things ourselves.

One approach could be to use [CiliumNodeConfig](https://docs.cilium.io/en/latest/configuration/per-node-config/) as the config override mechanism. From the AKS team's POV, I guess all you'd need to do is to bundle the CRD and write some docs.

**Comment by JitseHijlkema** [comment]
Just announced on KubeCon 2024 in Paris, which will gives us the Hubble functionality:

https://learn.microsoft.com/en-us/azure/aks/network-observability-overview?branch=main

**Comment by JitseHijlkema** [comment]
> Just announced on KubeCon 2024 in Paris, which will gives us the Hubble functionality:
> 
> Advanced Networking Observability which includes Hubble (CLI+UI) and with Retina (made OpenSource) also supports other CNI's and other platforms.

![20240319_152300.jpg](https://github.com/Azure/AKS/assets/66837808/407d4524-e1bd-49b9-8d61-d8f2ece62412)

**Comment by bartwitkowski** [comment]
@JitseHijlkema do you remember from which session is this photo?

**Comment by JitseHijlkema** [comment]
> @JitseHijlkema do you remember from which session is this photo?

This is presented during Azure Day with Kubernetes on March 19 in Paris:

[Link to presentation -Starting from slide 43](https://onedrive.live.com/?authkey=%21AKSf%5FfqiwYZAR6A&cid=015E21D773582EFF&id=15E21D773582EFF%2168245&parId=15E21D773582EFF%2168244&o=OneUp)

**Comment by PixelRobots** [comment]
> @JitseHijlkema do you remember from which session is this photo?

You can find the video on the AKS youtube Channel. here is where it starts. https://youtu.be/hb__fHnx11s?si=jJderXVXRwWpHPfh&t=2013

I would advise you to watch all the sessions if you have not.

**Comment by bartwitkowski** [comment]
I was on the KubeCon in Paris but not on the Azure day but the Cilium :-).
I'm watching Azure Day sessions in the meantime. Great stuff there!

Thanks @JitseHijlkema @PixelRobots

**Comment by CalleB3** [comment]
Hey, any updates on this issue?

**Comment by illrill** [comment]
It was released in public preview in May: https://learn.microsoft.com/en-us/azure/aks/advanced-network-observability-cli

AKS bundles hubble-relay, and then you'll need to install hubble-ui yourself.

**Comment by PixelRobots** [comment]
I did a blog post on it too. It might help. https://pixelrobots.co.uk/2024/06/advanced-network-observability-supercharging-container-network-observability-in-azure-kubernetes-service-aks/

**Comment by bartwitkowski** [comment]
Well, Advanced Network Observability is a part of Advanced Container Networking Services and it is a paid feature: https://azure.microsoft.com/en-us/pricing/details/azure-container-networking-services/.
Is there any way to do "BYO Hubble" and look through the metrics/flows/networkpolicies?

**Comment by jodr5786** [comment]
Are there plans to add the ability to export the flow logs to a logging solution? Or will the Hubble exporter ([link](https://docs.cilium.io/en/latest/observability/hubble/configuration/export/)) be a feature that can be enabled? We're in need of them due to compliance requirements.

**Comment by illrill** [comment]
> Are there plans to add the ability to export the flow logs to a logging solution? Or will the Hubble exporter ([link](https://docs.cilium.io/en/latest/observability/hubble/configuration/export/)) be a feature that can be enabled? We're in need of them due to compliance requirements.

Our company's security team also requires us to log all outbound connections destined towards any public internet endpoint. To solve this, we run a standalone deployment, which tails a filtered subset of all flow logs by executing `hubble observe --follow` directly against `hubble-relay`, and then prints it all to stdout. From there on, our normal container log collecting tools take care of the rest.

It's perhaps not the most solid solution, but we've been running this in our BYOCNI clusters with self-installed Cilium for a long time, since before the [Hubble Exporter](https://docs.cilium.io/en/latest/observability/hubble/configuration/export/) even existed. Now we're running it in our clusters with Azure CNI Powered by Cilium too. I would probably want to switch to the official Hubble Exporter when (if) supported, though.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-flowlogs-exporter
  namespace: kube-system
  labels:
    app.kubernetes.io/name: hubble-flowlogs-exporter
    app.kubernetes.io/part-of: cilium
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-flowlogs-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hubble-flowlogs-exporter
        app.kubernetes.io/part-of: cilium
    spec:
      containers:
      - command: ["sh", "-c"]
        env:
        - name: TLS_RELAY_SERVER_NAME
          value: instance.hubble-relay.cilium.io
        - name: TLS_RELAY_CA_CERT_FILES
          value: /var/lib/hubble-relay/certs/hubble-relay-ca.crt
        - name: TLS_RELAY_CLIENT_CERT_FILE
          value: /var/lib/hubble-relay/certs/client.crt
        - name: TLS_RELAY_CLIENT_KEY_FILE
          value: /var/lib/hubble-relay/certs/client.key
        args: ["hubble observe --tls --tls-server-name $TLS_RELAY_SERVER_NAME --tls-ca-cert-files $TLS_RELAY_CA_CERT_FILES --tls-client-cert-file $TLS_RELAY_CLIENT_CERT_FILE --tls-client-key-file $TLS_RELAY_CLIENT_KEY_FILE --server hubble-relay.kube-system.svc.cluster.local.:443 --ipv4 --traffic-direction egress --to-label reserved:world --follow --output jsonpb"]
        image: quay.io/cilium/cilium:v1.15.0
        name: hubble-flowlogs-exporter
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: hubble-relay-client-certs
          mountPath: /var/lib/hubble-relay/certs
          readOnly: true
      # Mount the secret containing the client-side certificate for mTLS communication with Hubble Relay.
      # This secret is already pre-created by AKS as part of the Hubble Relay installation, we just need to mount it.
      volumes:
      - name: hubble-relay-client-certs
        projected:
          defaultMode: 0400
          sources:
          - secret:
              name: hubble-relay-client-certs
              items:
                - key: tls.crt
                  path: client.crt
                - key: tls.key
                  path: client.key
                - key: ca.crt
                  path: hubble-relay-ca.crt
```
