### ISSUE TITLE
Internal Load Balancer Improperly Configured

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [Azure/AKS#398]
I've deployed an AKS cluster onto an existing vNet and installed the NGINX ingress controller via:
`helm install stable/nginx-ingress --namespace kube-system --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false -f config.yaml`

Where `config.yaml` contains:
```yaml
---
controller:
    service:
        annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

In order to have the controller utilize an internal load balancer. However, there seems to be a port mismatch on the rules created on the internal load balancer and what `nodePort` NGINX is listening on. 

The NGINX controller's `nodePort` is `31376` for HTTP and `30013` for HTTPS, however the NAT rules on the Azure ILB are `443 -> 443` and `80 -> 80` with direct server return enabled, which precludes NAT anyway. Interestingly, the TCP health probes _do_ go to the correct ports. If I navigate to `31376` or `30013` on any node directly, I can hit NGINX without issue, but connecting via the ILB times out because the nodes are not listening on `443` or `80`
