### ISSUE TITLE
[BUG] ama-logs uses rprivate mount propagation to mount host's root directory

### ISSUE THREAD

**Issue by jhatcher1** [Azure/AKS#3999]
**Describe the bug**
This issue is similar to https://github.com/Azure/AKS/issues/3535, but for the ama-logs pods that are run when container insights is enabled.

ama-logs mounts the host's root directory using the default mount propagation (`rprivate`):
```
       volumeMounts:
        - mountPath: /hostfs
          name: host-root
          readOnly: true
...
   volumes:
    - name: host-root
      hostPath:
       path: /
```

If there are any mounts created on the host and the ama-logs pod restarts, the ama-logs pod will keep the mount active, even after it has been unmounted from the host. 

For our use case, we create a zfs filesystem on the host VM's temporary disk. We're observing that zfs volumes created before the ama-logs pod restarted are unable to be destroyed, because the ama-logs pod is keeping the mounts active:
```
$ zfs destroy xyz
cannot destroy 'xyz': dataset is busy
```

**To Reproduce**
1. Deploy a pod that has access to the host:
    ```
    kubectl apply -f - <<EOF
    apiVersion: v1
    kind: Pod
    metadata:
      name: host-pod
    spec:
      hostPID: true
      containers:
      - name: mounted
        image: mcr.microsoft.com/devcontainers/base:ubuntu
        command: [ 'sleep', 'infinity']
        securityContext:
          privileged: true
    EOF
    ```
2. Exec into the pod, and create a mount on the host:
    ```
    kubectl exec -it host-pod -- /bin/bash
    /usr/bin/nsenter -m/proc/1/ns/mnt -- /bin/bash
    mkdir /tmp/myworkingdir
    mkdir /mnt/mymounteddir
    mount --bind /tmp/myworkingdir /mnt/mymounteddir
    ```
3. Restart ama-logs
    ```
    kubectl rollout restart daemonset ama-logs -n kube-system
    ```
4. Exec into the `host-pod`pod created in step 1 and attempt to unmount the mount:
    ```
    kubectl exec -it host-pod -- /bin/bash
    /usr/bin/nsenter -m/proc/1/ns/mnt -- /bin/bash
    umount /mnt/mymounteddir
    ```
5. Exec into the ama-logs pod running on the same node as `host-pod` and search for the mount:
    ```
    kubectl exec -it <ama-logs> -n kube-system -- /bin/bash
    grep mymounteddir /proc/1/mountinfo
    ```
    Output:
    ```
    6102 5761 8:1 /tmp/myworkingdir /hostfs/mnt/mymounteddir rw,relatime - ext4 /dev/root rw,discard,errors=remount-ro
    ```

**Expected behavior**
ama-logs should use the HostToContainer mount propagation when mounting the root filesystem. This way, unmount operations will be propagated to ama-logs, and the mounts will be cleanly unmounted. 

When run with HostToContainer mount propagation, the mount does not appear in step 5. above. We've run the reproduction steps with the following pod in place of the ama-logs container to confirm that this works:
```
apiVersion: v1
kind: Pod
metadata:
  name: mounted
spec:
  nodeSelector:
    kubernetes.io/hostname: <host-pod node>
  containers:
  - name: mounted
    image: mcr.microsoft.com/oss/busybox/busybox:1.33.1
    command: [ 'sleep', 'infinity']

    volumeMounts:
      - name: host-root
        mountPath: /hostfs
        readOnly: true
        mountPropagation: HostToContainer
  volumes:
    - name: host-root
      hostPath:
        path: /
```

**Environment (please complete the following information):**
 -  CLI Version: v1.28.2
 - Kubernetes version v1.27.3
