### ISSUE TITLE
[BUG] AKS expose secrets in logs in default configuration

### ISSUE THREAD

**Issue by nixx** [Azure/AKS#4021]
**Describe the bug**
The behaviour is described in https://github.com/Azure/AKS/issues/1389

The issue describes a workaround, but the default configuration is still counter intuitive. We experienced secrets in logs with the default setup.

**To Reproduce**
Deploy a pod with the following configuration (from https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/):

```
apiVersion: v1
kind: Pod
metadata:
  name: env-single-secret
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend-username
```

**Expected behavior**
SECRET_USERNAME is not shown in logs

**Environment (please complete the following information):**

**Additional context**
The standard behaviour is in counterintuitive with Kubernetes documentation in mind. See https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/ . This makes password leakage highly probable.
