### ISSUE TITLE
[BUG] Cannot specify internal loadbalancer ip if using Azure CNI

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4048]
Update: After testing, Azure CNI w/o BYON will still trigger this bug. The reproduce steps provided are under BYON.

**Describe the bug**
While using Azure CNI, if there are more than 1 nodepool existing, the whole internal loadbalancer will stuck if specifying "service.beta.kubernetes.io/azure-load-balancer-ipv4".

**To Reproduce**

Before:   
AKS version: 1.27.7  

VNet with subnets:  
![image](https://github.com/Azure/AKS/assets/142381267/a3bd2622-c57e-48d0-9b52-bc7ee5896298)

  
  
Yaml: 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-website-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.224.0.70
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: simple-website-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website-app
  template:
    metadata:
      labels:
        app: simple-website-app
    spec:
      containers:
      - name: simple-website
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - containerPort: 8080
```  

1. Create an AKS with own VNet, only including one system nodepool
2. Try create a internal loadbalancer with "service.beta.kubernetes.io/azure-load-balancer-ipv4"
3. Stucking, kubernetes-internal never being created
![image](https://github.com/Azure/AKS/assets/142381267/86390161-b3fb-4a62-9a9b-725261370b88)
![image](https://github.com/Azure/AKS/assets/142381267/92588752-a8b7-44b0-a03e-5e26ea0a50d8)

4. Delete it and try to deploy it without specifying IP
5. Good
![image](https://github.com/Azure/AKS/assets/142381267/6166f021-50b6-491e-924a-c246c1e6290c)

**Expected behavior**
The determined internal IP should be created and applied in Service.

**Environment (please complete the following information):**
 - CLI Version: 2.53.0
 - Kubernetes version: 1.27.7
 - CLI Extension version: N/A
 - Browser: Edge
