### ISSUE TITLE
HTTP Proxy enabled causes my environment variables to reorganize their order.

### ISSUE THREAD

**Issue by MSJisable** [Azure/AKS#4071]
**Describe scenario**
When using HTTP Proxy, the MutatingWebhookConfiguration aks-webhook-admission-controller is reordering my environment variables. This leads to non-deterministic ordering of the environment variables which breaks interdependent environment variables: https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/

For example, I have a container spec as follows:
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER_NAME
              value: 'FOO_$(K8S_POD_NAME)_eastus'

**Comment by sturrent** [comment]
I'm able to reproduce the same issue on AKS with HTTP proxy feature.

As a workaround (not ideal), you can use the annotation `kubernetes.azure.com/no-http-proxy-vars: "true"`

For example:

```
apiVersion: v1
kind: Pod
metadata:
  name: dependent-envars-demo-2
  annotations:
    kubernetes.azure.com/no-http-proxy-vars: "true"
spec:
  containers:
    - name: dependent-envars-demo-2
      args:
        - while true; do echo -en '\n'; printf UNCHANGED_REFERENCE=$UNCHANGED_REFERENCE'\n'; printf SERVICE_ADDRESS=$SERVICE_ADDRESS'\n';printf ESCAPED_REFERENCE=$ESCAPED_REFERENCE'\n'; sleep 30; done;
      command:
        - sh
        - -c
      image: busybox:1.28
      env:
        - name: SERVICE_PORT
          value: "80"
        - name: SERVICE_IP
          value: "172.17.0.1"
        - name: UNCHANGED_REFERENCE
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: PROTOCOL
          value: "https"
        - name: SERVICE_ADDRESS
          value: "$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
        - name: ESCAPED_REFERENCE
          value: "$$(PROTOCOL)://$(SERVICE_IP):$(SERVICE_PORT)"
```

And if the HTTP proxy envars are required on your pods you can manually add them as well (you can get them from any currently running pod). 
Again, not ideal but at least something that can be done while AKS Devs triage this issue that has been already reported internally.
