### ISSUE TITLE
[BUG] Application Gateway for Containers ALB Controller crashes when deploying a HealthCheckPolicy with an `override` policy spec

### ISSUE THREAD

**Issue by Tyagdit** [Azure/AKS#4087]
**Describe the bug**
Using the `override` field in the HealthCheckPolicy spec instead of `default` causes the alb-controller pods to panic and crash 

**To Reproduce**
With a basic nginx deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: azure-alb-system
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: azure-alb-system
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

```

and the following HTTPRoute and HealthCheckPolicy
```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nginx-httproute
  namespace: azure-alb-system
spec:
  parentRefs:
    - name: azure-gw
      namespace: azure-alb-system
  rules:
    - backendRefs:
        - name: nginx-service
          port: 80
          namespace: azure-alb-system
---
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: nginx-health-check-policy
  namespace: azure-alb-system
spec:
  targetRef:
    group: ""
    kind: Service
    name: nginx-service
  override:
    interval: 15s
    timeout: 3s
    healthyThreshold: 1
    unhealthyThreshold: 1
    protocol: HTTP
    http:
      path: /
      match:
        statusCodes: 
          - start: 200
            end: 299
```

the alb-controller pods crash immediately with the following error
```
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16e8ef8]

goroutine 407 [running]:
kubic/alb-controller/builder/serviceroutingconfig/service.(*Builder).getHealthCheckPolicyForService(0xc0006da480, {0x214a498, 0xc0004960f0}, 0xc000b93b80)
	/__w/1/s/alb-controller/builder/serviceroutingconfig/service/healthcheckpolicy.go:27 +0x1d8
kubic/alb-controller/builder/serviceroutingconfig/service.(*Builder).Build(_, {_, _}, {{{0x19ba10d, 0x7}, {0x1e6c917, 0x2}}, {{0xc000934cb0, 0xd}, {0x0, ...}, ...}, ...}, ...)
	/__w/1/s/alb-controller/builder/serviceroutingconfig/service/servicebuilder.go:50 +0x2ad
kubic/alb-controller/builder/serviceroutingconfig/gatewaybuilder.(*GatewayBuilder).processBackendRefs(0xc000b86700, {0x214a498, 0xc0004960f0}, {0xc000346320, 0x4, 0xc000473d48?}, {0x0, 0x0, 0x0}, {0xc000946900, ...})
	/__w/1/s/alb-controller/builder/serviceroutingconfig/gatewaybuilder/backendservicesbuilder.go:37 +0xeb3
kubic/alb-controller/builder/serviceroutingconfig/gatewaybuilder.(*GatewayBuilder).Build(_, {_, _}, {0xc000946900, {0xc000b94d50, 0x24}, {0x4a83063, 0xedd5693cd, 0x0}, 0xb3f, ...}, ...)
	/__w/1/s/alb-controller/builder/serviceroutingconfig/gatewaybuilder/gatewayapibuilder.go:52 +0x55b
kubic/alb-controller/builder/serviceroutingconfig.(*ServiceRoutingConfigBuilder).Build(0xc000bb2c60, {0x214a498, 0xc0004960f0}, {0xc000946900, {0xc000b94d50, 0x24}, {0x4a83063, 0xedd5693cd, 0x0}, 0xb3f, ...}, ...)
	/__w/1/s/alb-controller/builder/serviceroutingconfig/serviceroutingconfigbuilder.go:68 +0x274
kubic/alb-controller/operationhandler.(*OperationHandler).configBuildLoop(0xc000975380)
	/__w/1/s/alb-controller/operationhandler/operationhandler.go:466 +0x6a5
created by kubic/alb-controller/operationhandler.(*OperationHandler).startBuilding
	/__w/1/s/alb-controller/operationhandler/operationhandler.go:381 +0x70
```
The status of the policy remains at `Waiting for controller`
```bash
$ kubectl get healthcheckpolicy nginx-health-check-policy -o=jsonpath='{.status}' | jq .
{
  "conditions": [
    {
      "lastTransitionTime": "1970-01-01T00:00:00Z",
      "message": "Waiting for controller",
      "reason": "Pending",
      "status": "Unknown",
      "type": "Accepted"
    }
  ]
}
```

**Expected behavior**
The HealthCheckPolicy should get accepted and take effect or if it isn't valid the controller should log the issue with it and update the status of the HealthCheckPolicy resource

**Environment (please complete the following information):**
 - Kubernetes version: 1.27.7
 - ALB controller helm chart version: 0.6.3

**Additional context**
Deploying the HealthCheckPolicy alone, without deploying the Service and HTTPRoute does not cause this issue
Using both `override` and `default` also doesn't cause the crash, but the `override` section doesn't seem to work
```yaml
  override:
    interval: 15s
    timeout: 3s
    healthyThreshold: 1
    unhealthyThreshold: 1
    protocol: HTTP
    http:
      path: /health
      match:
        statusCodes: 
          - start: 200
            end: 299
  default:
    interval: 15s
    timeout: 3s
    healthyThreshold: 1
    unhealthyThreshold: 1
    protocol: HTTP
    http:
      path: /
      match:
        statusCodes: 
          - start: 200
            end: 299
```
nginx only gets requests at `/` (from the `default` field) instead of `/health` (from the `override` field)
```
10.225.0.4 - - [08/Feb/2024:09:47:53 +0000] "GET / HTTP/1.1" 200 615 "-" "Microsoft-Azure-Application-LB/AGC" "-"
10.225.0.5 - - [08/Feb/2024:09:47:53 +0000] "GET / HTTP/1.1" 200 615 "-" "Microsoft-Azure-Application-LB/AGC" "-"
10.225.0.4 - - [08/Feb/2024:09:47:54 +0000] "GET / HTTP/1.1" 200 615 "-" "Microsoft-Azure-Application-LB/AGC" "-"
10.225.0.5 - - [08/Feb/2024:09:47:54 +0000] "GET / HTTP/1.1" 200 615 "-" "Microsoft-Azure-Application-LB/AGC" "-"
10.225.0.4 - - [08/Feb/2024:09:47:55 +0000] "GET / HTTP/1.1" 200 615 "-" "Microsoft-Azure-Application-LB/AGC" "-"
10.225.0.5 - - [08/Feb/2024:09:47:55 +0000] "GET / HTTP/1.1" 200 615 "-" "Microsoft-Azure-Application-LB/AGC" "-"
```
