### ISSUE TITLE
[BUG] Pods Are Not Terminated If An AKS Node Is Stopped

### ISSUE THREAD

**Issue by Habulinec** [Azure/AKS#4093]
**Describe the bug**
Hi all, with the latest ASK OS images (e.g. AKSUbuntu-2204gen2containerd-202401.17.1), once a node is not available (stopped), the pod on that affected node does not enter a Terminating state.

**To Reproduce**
Have an AKS cluster with the latest OS image.
Create a simple statefulset like
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset
spec:
  serviceName: test
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: nginx
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
```
Check on which node the newly created pod is running and then stop (de-allocate) the node (e.g  via Azure Dashboard).
**The pod will stay in the Running state, which is wrong!** 

With the latest OS images, the pod starts to change its state only once the node is available again. Subsequently, the state procedure is Running -> **Unknown** -> Pending - Creating -> Running  

**Expected behavior**
It should enter a Terminating state immediately, once the node is not available. The state flow should be Running -> Terminating -> Pending - Creating (on another node) -> Running.

**Environment:**
- AKS 1.27.7
- OS version: AKSUbuntu-2204gen2containerd-202401.17.1

**Additional context**
I don't know, what is the latest working OS, but tested on AKSUbuntu-2204gen2containerd-202311.07.0 and there it was still working correctly.
