### ISSUE TITLE
Secondary nginx ingress controller doesn't work on AKS

### ISSUE THREAD

**Issue by AntonChernysh** [Azure/AKS#414]
*Installing ingress controller*

`helm install --name mynewingress stable/nginx-ingress --namespace kube-system --set rbac.create=false --set rbac.createRole=false --set rbac.createClusterRole=false --set controller.ingressClass=myclass`

*Adding ingress*

`kubectl create -f  ingress.yml `

*ingress.yml:*
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingressname
  annotations: 
    kubernetes.io/ingress.class: myclass
spec:
  tls:
  - hosts:
    - host-qa.mydomain.com
    secretName: mydomain_com.tls
  rules:
  - host: host-qa.mydomain.com
    http:
      paths:
      - backend:
          serviceName: javacontainer-qa
          servicePort: 8080
```
I already have one ingress controller that's working fine (was set up exactly the same way). Even if I change class for existing ingress controller and then update ingress resources respectively it (first one) works. 

I checked nginx config file in newly created controller and it looks just fine, it pulled certificates from TLS k8s secret and everything seems fine. However it looks like ingress controller is not functioning, I'm always getting fake k8s certificate.
Problem if only with additional ingress controller, 
Has anyone managed to start 2 nginx ingress controllers on AKS?

**Comment by SurushS** [comment]
I run a Nginx Controller per namespace i use so i have multiple controllers with each multiple ingress rules per controller. the key is connecting the class name of the ingress (rule) with the ingress controller as shown below. That way works for me. AKS Azure gives each of my nginx controllers a public ip on azure.

This is a sample code i made quickly. Hopefully it helps you out.

```yaml
# Ingress Controller 1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: namespace1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
          imagePullPolicy: Always
          args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
            - --publish-service=$(POD_NAMESPACE)/nginx-ingress-controller-svc
            - --annotations-prefix=nginx.ingress.kubernetes.io
            - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
            - --enable-ssl-chain-completion=false
            - --ingress-class=namespace1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            runAsNonRoot: false
          volumeMounts: 
            - mountPath: /etc/nginx-ssl/dhparam
              name: tls-dhparam-vol
      volumes: 
        - name: tls-dhparam-vol
          secret: 
            secretName: tls-dhparam
---
# Ingress Controller 1 Service
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress-controller-svc
  namespace: namespace1
  labels:
    app: nginx-ingress-controller-svc
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: nginx-ingress-controller
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
---
# Ingress Rule for Controller 1
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-controller-rule
  annotations:
    kubernetes.io/ingress.class: "namespace1" 
  namespace: namespace1
spec:
  tls:
    - hosts:
      - somehostsuffix1.domain.com
      secretName: tls-certificate
  rules:
  - host: somehostsuffix1.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: someapi1-api
          servicePort: 4000
---


# Ingress Controller 2
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: namespace2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
      annotations:
        prometheus.io/port: '10254'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
          imagePullPolicy: Always
          args:
            - /nginx-ingress-controller
            - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
            - --publish-service=$(POD_NAMESPACE)/nginx-ingress-controller-svc
            - --annotations-prefix=nginx.ingress.kubernetes.io
            - --default-ssl-certificate=$(POD_NAMESPACE)/tls-certificate
            - --enable-ssl-chain-completion=false
            - --ingress-class=namespace2
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            runAsNonRoot: false
          volumeMounts: 
            - mountPath: /etc/nginx-ssl/dhparam
              name: tls-dhparam-vol
      volumes: 
        - name: tls-dhparam-vol
          secret: 
            secretName: tls-dhparam
---
# Ingress Controller 2 Service
kind: Service
apiVersion: v1
metadata:
  name: nginx-ingress-controller-svc
  namespace: namespace2
  labels:
    app: nginx-ingress-controller-svc
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: nginx-ingress-controller
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
---
# Ingress Rule for Controller 2
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-controller-rule
  annotations:
    kubernetes.io/ingress.class: "namespace2" 
  namespace: namespace2
spec:
  tls:
    - hosts:
      - somehostsuffix2.domain.com
      secretName: tls-certificate
  rules:
  - host: somehostsuffix2.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: someapi2-api
          servicePort: 4000
---



```
