### ISSUE TITLE
Current version of docker does not support multi stage builds for CICD pipelines

### ISSUE THREAD

**Issue by IainColledge** [Azure/AKS#415]
# Overview

When using AKS as the platform for enabling CICD pipelines and specifically the building of Docker images one usually connects to the underlying node docker daemon by deploying a pod with /var/run/docker.sock being made available to the "building" pod.

For example for a Deployment or Stateful set:

```
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

...

      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock

```

The version of docker on the underlying nodes is 1.13.1 released in (2017-02-08) and multi stage builds are supported from 17.05.0 released (2017-05-04) onwards.

Please can the version of docker be updated to a modern release as the subsequent drift is minimising the utility of the Azure Kubernetes Managed Service, i.e. it cannot be utilised for modern DevOps CICD pipelines.

Ironically a side effect is that one of the examples used for developing and running applications in the AKS documentation, OpenFAAS (https://docs.microsoft.com/en-us/azure/aks/openfaas), does not work with csharp because multi stage builds are not supported.
