### ISSUE TITLE
kubectl logs / exec / attach try to connect to kubelet with user=system:anonymous

### ISSUE THREAD

**Issue by markusdresch** [Azure/AKS#418]
Default Azure AKS Kubernetes 1.9.6 (latest) upgraded step by step from 1.8.x on CLI. Error wasn't on original version but started on 1.9.x. Azure portal wasn't able to upgrade because of "enableRBAC not available".

i deleted shell storage and executed `az aks get-credentials -g -n` again to get credentials.

`kubectl logs <pod>` yields error:

> Error from server (Forbidden): Forbidden (user=system:anonymous, verb=get, resource=nodes, subresource=proxy) ( pods/log <pod>)

`kubectl [attach | exec] <pod>` yields error:

> error: unable to upgrade connection: Forbidden (user=system:anonymous, verb=create, resource=nodes, subresource=proxy)

`helm install <chart>` yields error:

> Error: forwarding ports: error upgrading connection: unable to upgrade connection: Forbidden (user=system:anonymous, verb=create, resource=nodes, subresource=proxy)

manually setting `--authorization-mode=AllowAll` in kubelets makes logs available again, but not attach, exec and helm commands. this setting doesn't feel right and it also doesn't survive scaling operations.

**Comment by markusdresch** [comment]
this is the same issue but the first solution can't be used in production and since this is managed aks i don't think i can change the api-server parameters: https://github.com/kubernetes-incubator/apiserver-builder/issues/225

**Comment by sauryadas** [comment]
Can you please try to upgrade again? We had a fix roll out . What region are you deployed to?

**Comment by markusdresch** [comment]
westeurope. ran `az aks upgrade -g <resourcegroup> -n <clustername> -k 1.9.6`, upgrade succeeded (was at 1.9.6 before already). issue didn't change. az aks get-upgrades only lists v1.9.6.

**Comment by markusdresch** [comment]
i managed to create a workaround by applying this yaml:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: anonymous-logs-role
rules:
- apiGroups: [""]
  resources: ["nodes/proxy"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: anonymous-logs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anonymous-logs-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous
```

this way logs, exec and attach work and the api server doesn't expose any information. are there any drawbacks to this solution?
