### ISSUE TITLE
[ACNS] FQDN Filtering Policies

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#4205]
### GA ETA November 2024*
  *ETA's are estimations and subject to change.

Advanced Container Networking Services supports FQDN Filtering

**Comment by EppO** [comment]
Hi @chasewilson, 
is it related to #3797 by any chance?

**Comment by TheKangaroo** [comment]
@EppO I dont think so. I think it is FQDN filtering based on the new observability tool https://retina.sh .
It was mentioned on the roadmap for retina on the Azure Day at Kubecon Europe:
https://youtu.be/hb__fHnx11s?feature=shared&t=2013

But I would love to hear from @chasewilson if this assumption is correct.

**Comment by EppO** [comment]
Retina focuses on observability, while FQDN filtering goes beyond this scope. One might expect FQDN filtering policies to be enforced at the CNI level, but this is not currently supported by the `NetworkPolicy` resource. 
Although Cilium has incorporated this feature via their `CiliumNetworkPolicy` resource, Azure CNI powered by Cilium does not support it yet. 
It's unclear whether creating an additional CRD for this feature at the Azure CNI level is more advantageous than using Cilium directly. While it would cover all non-Cilium clusters, advanced users tend to select their CNI based on specific needs and requirements.

**Comment by TheKangaroo** [comment]
Right, I just saw "FQDN filtering" on the retina roadmap and think it has something to do with ACNS FQDN policies.
I hope @chasewilson can shed some light on this.

**Comment by illrill** [comment]
Google opted to create its own [`FQDNNetworkPolicy`](https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies) CRD (probably just a wrapper around `CiliumNetworkPolicy`) in GKE's "Dataplane V2" network mode (which is just their branding of managed Cilium). 

Meanwhile, there is also an upcoming FQDN selector in the official Network Policy API: https://github.com/kubernetes-sigs/network-policy-api/pull/200. It'll be interesting to see if upstream Cilium CNI, and subsequently Azure CNI Powered by Cilium, implements this.

Hope to get some teasers from Chase!

**Comment by chasewilson** [comment]
@TheKangaroo @illrill Keep an eye out for some announcements coming in the next couple months for FQDN filtering. :)

**Comment by tamilmani1989** [comment]
update: This feature is getting released for public preview this week. We will share official docs page once it's out.

**Comment by EppO** [comment]
You can enable FQDN filtering policies on AKS now! (you need aks-preview extension for az):
`az aks update --enable-acns -n myAKS -g myRGP` and now you can use `CiliumNetworkPolicy` with DNS-based rules


```
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fqdn"
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: mediabot
  egress:
  - toFQDNs:
    - matchPattern: "*.github.com"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
```

When you add an egress policy, don't forget to allow traffic to CoreDNS in `kube-system`, otherwise you won't be able to resolve anything. 
Please note that L7 rules such as HTTP path filtering are not implemented yet.
