### ISSUE TITLE
[Question] How to disable/delete default public facing ingress controller for application routing add-on (managed nginx)

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/AKS#4233]
**Describe scenario**
I want to make sure no public facing ingress controller / load balancer / IP is created when we enable the application routing add-on (managed nginx) for our private vnet integrated AKS cluster. The requirement is to reach the private LB from front door via private link service. This [article ](https://blog.baeke.info/2022/06/13/publish-your-aks-ingress-controller-over-azure-private-link/)has the same described.

As documented [here](https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration#configuration-of-the-nginx-ingress-controller), when we enable the add on today using `az aks approuting enable` command a LB with a public IP used by the ingress controller called 'default' is created. After that we can add additional ingress controllers with private LB/IP. I couldn't find any way to disable the default creation. I do not need the public LB/IP as everything is internal.

**Question**
How can I stop creation of the default public facing ingress controller or how can I remove the same later post creation? I tried manually deleting the LBs from the AKS VMSSs but that didn't work and after certain time the 'default' ingress controller again popped up in system!

**Comment by JoeyC-Dev** [comment]
Why not replace the default one?
```
cat <<EOF | kubectl apply -f -
apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: default
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  controllerNamePrefix: nginx
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
EOF
```

**Wait two minutes** and your default one's IP should be changed to internal IP. 
![image](https://github.com/Azure/AKS/assets/142381267/79dbd032-0792-4ca2-8b94-5911089477fa)
