### ISSUE TITLE
[BUG] Dynamic volume provisioning with blob storage fails when using private endpoint

### ISSUE THREAD

**Issue by Laffs2k5** [Azure/AKS#4242]
**Describe the bug**

We have been utilizing dynamic volume provisioning for our deployments in AKS for a while. This is realized using the [Azure Blob Storage CSI driver for Kubernetes](https://github.com/kubernetes-sigs/blob-csi-driver) with a custom sc (StorageClass) and pvc (PersistentVolumeClaim) in accordance with the documentation found here: [Create a persistent volume with Azure Blob storage in Azure Kubernetes Service (AKS)](https://learn.microsoft.com/en-us/azure/aks/azure-csi-blob-storage-provision?tabs=mount-blobfuse%2Csecret#dynamically-provision-a-volume).

This week it stopped working with an error message during provisioning of the sc:

`failed to provision volume with StorageClass "sc-blob-storage-test-application-pr-203": rpc error: code = Internal desc = ensure storage account failed with create private DNS zone(privatelink.blob.core.windows.net) in resourceGroup(rg6-ss2-cm-net-dev): authenticated requests are not permitted for non TLS protected (https) endpoints`

The issue occurs for all deployments with new pvc's. Deployments with already existing pvc's continue to run fine. the result is that we are prevented from deploying any new apps with storage backed by dynamic volume provisioning.

The first part of the description, `ensure storage account failed with`, is logged from [blob-csi-driver/pkg/blob/controllerserver.go L386](https://github.com/kubernetes-sigs/blob-csi-driver/blob/v1.23.4/pkg/blob/controllerserver.go#L386). 

The next part, `create private DNS zone(privatelink.blob.core.windows.net) in resourceGroup(rg6-ss2-cm-net-dev):`, is logged from [cloud-provider-azure/pkg/provider/azure_storageaccount.go L247](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/v1.27.1/pkg/provider/azure_storageaccount.go#L247), this code is the [out-of-tree cloud provider for Azure](https://github.com/kubernetes-sigs/cloud-provider-azure/tree/v1.27.1).

NOTE: code execution should never have gotten to line 247 in our case, as the private link DNS zone already exist and thus should have been retrieved on line 243 by `az.privatednsclient.Get()`. To understand the failure better I would very much like to known what is logged by line 244, `klog.V(2).Infof("get private dns zone %s returned with %v", privateDNSZoneName, err.Error())`. But I don't know where or how to enable this logging.

I've looked through the kube-system logs and identified that the `csi-blob-node` daemonset was updated to use the image `mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.23.4` in-place of `mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.23.3` at 6AM April 23rd. We have logs indicating that the dynamic provisioning worked fine April 22nd and developers reported the first issue dynamic provisioning April 24th.

NOTE: we have not touched or modified the `csi-blob-node` daemonset ourselves, this is fully manged by AKS.

The cluster in question is on AKS `1.28.5`, and the update to version `1.23.4` of the Blob Storage CSI driver corresponds well with the [AKS Release 2024-04-11](https://github.com/Azure/AKS/releases/tag/2024-04-11) which under _Component Updates_ lists:

> - Upgraded Azure Blob CSI driver to v1.23.4 on AKS 1.28 and 1.29

If you are able to reproduce on your side, I would suggest to downgrade the Blob Storage CSI driver to version `1.23.3` until the cause of the failure is understood and mitigated.

**To Reproduce**

1. Have the private DNS zone `privatelink.blob.core.windows.net` already existing in the resource group of the AKS vnet.
2. Assign the AKS identity `Contributor` role in the resource group hosting the AKS vnet.
3. Have the blob storage CSI driver enabled: `az aks update --enable-blob-driver`
4. Deploy sc + pvc + deployment to AKS (see examples of our declarations under _Additional context_ below)

**Expected behavior**

1. Storage account + blob is created
2. Private DNS zone is updated with a record for the blob
3. The AKS deployment provisions successfully

**Screenshots**

Not applicable.

**Environment**
 - AKS `1.28.5` (cluster `kubernetesVersion` and node pool `orchestratorVersion`)
 - Node image version `AKSUbuntu-2204gen2containerd-202402.07.0`
 - Azure Blob Storage CSI driver for Kubernetes version `1.23.4`

**Additional context**

<details><summary>custom StorageClass</summary>

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  labels:
  name: sc-blob-storage-test-application-pr-203
mountOptions:
  - '-o allow_other'
  - '--file-cache-timeout-in-seconds=120'
  - '--use-attr-cache=true'
  - '--cancel-list-on-mount-seconds=10'
  - '-o attr_timeout=120'
  - '-o entry_timeout=120'
  - '-o negative_timeout=120'
  - '--log-level=LOG_WARNING'
  - '--cache-size-mb=1000'
parameters:
  allowBlobPublicAccess: 'false'
  containerName: test-application-pr-203
  matchTags: 'true'
  networkEndpointType: privateEndpoint
  protocol: fuse2
  skuName: Standard_LRS
  tags: >-
    CreatedBy=Azure Kubernetes Service,ApplicationName=AKS application
    storage,Description=Storage account for ephemeral environments in AKS
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
</details>

<details><summary>PersistentVolumeClaim</summary>

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: sc-blob-storage-test-application-pr-203
  name: pvc-blob-storage-test-application-pr-203
  namespace: test-application-pr-203
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-blob-storage-test-application-pr-203
```
</details>

<details><summary>Deployment (not a complete example, just the important parts)</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application-pr-203-deployment
  namespace: test-application-pr-203
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-application-pr-203-app
  template:
    metadata:
      labels:
        app: test-application-pr-203-app
        app.kubernetes.io/name: test-application-backend
        app.kubernetes.io/part-of: test-application
        app.kubernetes.io/version: pr-203-2024.04.25.53165
        azure.workload.identity/use: 'false'
    spec:
      containers:
        - env:
            - name: AZURE_PERSISTENT_STORAGE_MOUNT_PATH
              value: /mnt/azure-blob-storage
          image: <our ACR>/test-application-pr-203:pr-203-2024.04.25.53165
          name: test-application-pr-203-container
          volumeMounts:
            - mountPath: /mnt/azure-blob-storage
              name: blob-storage
              readOnly: false
      volumes:
        - name: blob-storage
          persistentVolumeClaim:
            claimName: pvc-blob-storage-test-application-pr-203
```
</details>
