### ISSUE TITLE
AKS (with http addon + custom VNet) can't get public IP for LB

### ISSUE THREAD

**Issue by WeidongZhou** [Azure/AKS#427]
Hi, 
I am using the example code, Kafka-aks-test, from this URL: https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-azure-container-services. Everything looks fine except getting external IP. Initially we run into the error like "autorest/azure: Service returned an error. Status=403". After some research, we added SP to the subnet and vnet for the AKS cluster. This error went away. But still still have issue in getting external IP. Currently with the following warning message: 
Error creating load balancer (will retry): failed to ensure load balancer for service default/kafka-aks-test2: timed out waiting for the condition. 
I made several different deployments using the same code (just change app name). The interesting part is that one deployment got external IP after 22 hours in pending state. Other deployments are still in pending state. We are using latest AKS release and just created the AKS cluster less than a week ago. Here are the output from kubectl get service command:
[root@exa-dev01-ue1-kfclient1-vm Kafka-AKS-Test]# kubectl get service
NAME                TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)          AGE
azure-vote-back     ClusterIP      192.168.126.17   <none>         6379/TCP         1d
azure-vote-front    LoadBalancer   192.168.98.14    <pending>      80:32062/TCP     17h
foundationservice   LoadBalancer   192.168.45.233   <pending>      3000:32046/TCP   17h
kafka-aks-test      LoadBalancer   192.168.130.97   23.100.17.58   80:32656/TCP     1d
kafka-aks-test2     LoadBalancer   192.168.120.61   <pending>      80:30686/TCP     54m
kafka-aks-test3     LoadBalancer   192.168.241.28   10.2.1.97      80:30877/TCP     11h
kubernetes          ClusterIP      192.168.0.1      <none>         443/TCP          18h

Any recommendations?

**Comment by VincentSurelle** [comment]
Hi,
Looks like #422

**Comment by WeidongZhou** [comment]
@VincentSurelle Thank you for your reply. I checked out #422. Actually I tried this trick of using annotations. It worked to get load balancer for internal ip address, but not external ip. See the output of kafka-aks-test3 service, it got 10.2.x.x IP, which is the AKS subnet. What I need is to get external IP that can be accessed from internet. Thanks.

**Comment by VincentSurelle** [comment]
@WeidongZhou Sorry didn't see it at first.
Can you provide your yml file ?

**Comment by WeidongZhou** [comment]
@VincentSurelle here it is
[root@exa-dev01-ue1-kfclient1-vm Kafka-AKS-Test]# cat k2.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-aks-test2
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kafka-aks-test2
    spec:
      containers:
        - name: kafka-aks-test2
          image: foundationcontainerregistry.azurecr.io/kafka-aks-test:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-aks-test2
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: kafka-aks-test2

**Comment by VincentSurelle** [comment]
Did you checked the `Http application routing` box on cluster creation ?

![http application routing](https://docs.microsoft.com/en-us/azure/aks/media/http-routing/create.png)

Seems that since 2-3 days it's difficult to work with external ips

**Comment by WeidongZhou** [comment]
Yes, I selected **Yes** for **Http application routing** and **Advanced** for **Network configuration**. We do have a few subnet under the same VNet. 
Also even for one case that I got an external IP after 22 hrs in pending state, I can see this IP is an Public IP type resource. I would expect it should be something like Load Balancer type resource. In my deployment, I have only one replicate. If I need multiple replicates in my deployment, I don't know how this single public IP is going to work.

**Comment by brusMX** [comment]
I'm also experiencing a problem like this. Apparently when you check both: Http Application routing and Custom VNets I cant seem to get public IPs and I get these logs:

**k get all --all-namespaces**

```accesslog
kube-system   pod/addon-http-application-routing-nginx-ingress-controller-64mdqfn   0/1       CrashLoopBackOff   597        2d

kube-system   service/addon-http-application-routing-nginx-ingress          LoadBalancer   10.0.99.228   <pending>     80:31312/TCP,443:31735/TCP   2d

kube-system   deployment.extensions/addon-http-application-routing-nginx-ingress-controller   1         1         1            0           2d
```
**k describe pod/addon-http-application-routing-nginx-ingress-controller-64mdqfn -n kube-system**

```yaml
Name:           addon-http-application-routing-nginx-ingress-controller-64mdqfn
Namespace:      kube-system
Node:           aks-agentpool-19807500-1/10.1.0.4
Start Time:     Mon, 11 Jun 2018 11:46:02 -0700
Labels:         app=addon-http-application-routing-nginx-ingress
                pod-template-hash=2005983595
Annotations:    <none>
Status:         Running
IP:             10.1.0.11
Controlled By:  ReplicaSet/addon-http-application-routing-nginx-ingress-controller-6449fd79f9
Containers:
  addon-http-application-routing-nginx-ingress-controller:
    Container ID:  docker://19dc0ec2fe04c77d943eb8016fe1c205c53ae13726757c1f4a31cfca840a6941
    Image:         quayio.azureedge.net/kubernetes-ingress-controller/nginx-ingress-controller:0.13.0
    Image ID:      docker-pullable://quayio.azureedge.net/kubernetes-ingress-controller/nginx-ingress-controller@sha256:8f3a3bf373e64d8b29e502faf58dd1b212ceb2a69627ccc1add5b9aca24e273b
    Ports:         80/TCP, 443/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --ingress-class=addon-http-application-routing
      --default-backend-service=$(POD_NAMESPACE)/addon-http-application-routing-default-http-backend
      --configmap=$(POD_NAMESPACE)/addon-http-application-routing-nginx-configuration
      --tcp-services-configmap=$(POD_NAMESPACE)/addon-http-application-routing-tcp-services
      --udp-services-configmap=$(POD_NAMESPACE)/addon-http-application-routing-udp-services
      --annotations-prefix=nginx.ingress.kubernetes.io
      --publish-service=$(POD_NAMESPACE)/addon-http-application-routing-nginx-ingress
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 13 Jun 2018 15:35:07 -0700
      Finished:     Wed, 13 Jun 2018 15:35:08 -0700
    Ready:          False
    Restart Count:  606
    Liveness:       http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:10254/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       addon-http-application-routing-nginx-ingress-controller-64mdqfn (v1:metadata.name)
      POD_NAMESPACE:  kube-system (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from addon-http-application-routing-nginx-ingress-serviceaccoun4cmsx (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  addon-http-application-routing-nginx-ingress-serviceaccoun4cmsx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  addon-http-application-routing-nginx-ingress-serviceaccoun4cmsx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                  From                               Message
  ----     ------   ----                 ----                               -------
  Warning  BackOff  4m (x14145 over 2d)  kubelet, aks-agentpool-19807500-1  Back-off restarting failed container
```


**k logs pod/addon-http-application-routing-nginx-ingress-controller-64mdqfn -n kube-system**

```python
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.13.0
  Build:      git-4bc943a
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------

I0613 21:48:35.281783       8 flags.go:162] Watching for ingress class: addon-http-application-routing
W0613 21:48:35.281957       8 flags.go:165] only Ingress with class "addon-http-application-routing" will be processed by this ingress controller
W0613 21:48:35.282410       8 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0613 21:48:35.282652       8 main.go:181] Creating API client for https://10.0.0.1:443
I0613 21:48:35.330053       8 main.go:225] Running in Kubernetes Cluster version v1.9 (v1.9.6) - git (clean) commit 9f8ebd171479bec0ada837d7ee641dec2f8c6dd1 - platform linux/amd64
I0613 21:48:35.339903       8 main.go:84] validated kube-system/addon-http-application-routing-default-http-backend as the default backend
F0613 21:48:35.355390       8 main.go:102] service kube-system/addon-http-application-routing-nginx-ingress does not (yet) have ingress points
```
