### ISSUE TITLE
[BUG] Calico crashes on arm64 system pool

### ISSUE THREAD

**Issue by paulgmiller** [Azure/AKS#4280]
**Describe the bug**
While the calico node daemonset and operator are fine but typha and kube-controllers will crash if run on a arm64 system-pool with binary not found. This is becasuse aks compiles those calico programs on arm64 which enables CGO and requires the prescence of system libraries. Tigera seems to cross compile from amd64 which disables CGO so their dockerfiles do not copy over the system libraries to scratch. 

To mitigate right now create a system pool that is not arm64. AKS is  looking to disable cgo or build on amd64 to fix this but 

**To Reproduce**
az aks create ...  --vm-size <any armsku> --network-policy calico 

**Expected behavior**
Addon pods don't creash :)

**Environment (please complete the following information):**
AKS with k8s > 1.29 (which gets a new calico 3.26)(

**Additional context**

**Comment by paulgmiller** [comment]
Currently blocked as we can't rebuiild calico upstream images unless they cherry-pick a change to build 3.26 branch o

https://github.com/projectcalico/calico/pull/8890#issuecomment-2155641537


You can disable calico and move to cilium if this is very blocking for you by seting network policy to none and then to cilium

**Comment by paulgmiller** [comment]
Calico took the fix but hasn't made a release

We're likely going to use an [imageset](https://docs.tigera.io/calico/latest/operations/image-options/imageset) to fix this by putting people on an unreleased version of calico 3.26.4 (can't rebuild older versions without commit c06a60 from https://github.com/projectcalico/calico/pull/8894
If you want to test it out before hand you can apply this imageset crd

```
apiVersion: operator.tigera.io/v1
kind: ImageSet
metadata:
  name: calico-v3.26.3 #really v3.26.4-c06a60
spec:
  images:
  - image: "calico/cni"
    digest: "sha256:c4d73d9636834e81da5a1a9d914f5967326da18aa91f268b78df151deee82a58"
  - image: "calico/kube-controllers"
    digest: "sha256:3d1c7be4e4259c8bb2ac582669d6905c977a11e59b5eb510933d15fd7b124987"
  - image: "calico/node"
    digest: "sha256:79afaa3426e573c1ba42f6c55198ae4311422149c4939c87eb6c0d90d6e9609a"
  - image: "calico/typha"
    digest: "sha256:db15c177c804ddc7c870cc72bc37a36499af3c744cb633714ea1911eba14433e"
  - image: "calico/pod2daemon-flexvol"
    digest: "sha256:688277437bb230895286ad2cf5b827d5b1c8a850ad87f912dffca3c715b1a960"
  - image: "calico/apiserver"
    digest: "sha256:b159e24deff1fe31b57d50f9c459a5ec91b4ff9fa34d8a18e2bd421c2b58d9ac"
  - image: "calico/csi"
    digest: "sha256:64765b0edd5ee3f62ccdd69b57ae389c57e23eaa8a5b1bfa0cbc446f4d66f6b8"
  - image: "calico/node-driver-registrar"
    digest: "sha256:411409512c6569aa3a29d6ee8fba6d545fc37dc9fe5b6a3117fe8887cc4252fc"
  #this is a dummy image as we don't use upgrade
  - image: "calico/windows-upgrade"
    digest: "sha256:411409512c6569aa3a29d6ee8fba6d545fc37dc9fe5b6a3117fe8887cc4252fc"
```

**Comment by JohanLindvall** [comment]
After applying the imagset, I am seeing the following warnings from the calico-node daemonset:

```
2024-06-18 18:52:40.952 [WARNING][82] felix/int_dataplane.go 1704: failed to wipe the XDP state error=failed to load BPF program (/usr/lib/calico/bpf/filter.o): stat /sys/fs/bpf/calico/xdp/prefilter_v1_calico_tmp_A: no such file or directory
libbpf: Error loading ELF section .BTF: -22. Ignored and continue.
libbpf: Program 'xdp' contains non-map related relo data pointing to section 5
Error: failed to open object file
 try=3                                                                                                                                                              
```

**Comment by paulgmiller** [comment]
Fix was in aks codebase june 26th and is currentlhy in about half the regions.
Use the release tracker to see when june 27th or later release hits your region.
https://releases.aks.azure.com/webpage/index.html

@JohanLindvall  are the warning causing any issues? AKS Managed calico does not use ebpf so likely thats not an actual problem beside noise.

**Comment by jemag** [comment]
@paulgmiller could the ImageSet deployed as part of this fix potentially be causing a degradation of the `tigerastatuses.operator.tigera.io`?

![Image](https://github.com/user-attachments/assets/a6027782-3291-4174-87e7-01c170c76c6e)

![Image](https://github.com/user-attachments/assets/e46988e4-c048-46a3-a62b-653d8a83cd00)
Here is current ImageSet:
```yaml
apiVersion: operator.tigera.io/v1
kind: ImageSet
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
  name: calico-v3.26.3
spec:
  images:
  - digest: sha256:c4d73d9636834e81da5a1a9d914f5967326da18aa91f268b78df151deee82a58
    image: calico/cni
  - digest: sha256:3d1c7be4e4259c8bb2ac582669d6905c977a11e59b5eb510933d15fd7b124987
    image: calico/kube-controllers
  - digest: sha256:79afaa3426e573c1ba42f6c55198ae4311422149c4939c87eb6c0d90d6e9609a
    image: calico/node
  - digest: sha256:db15c177c804ddc7c870cc72bc37a36499af3c744cb633714ea1911eba14433e
    image: calico/typha
  - digest: sha256:688277437bb230895286ad2cf5b827d5b1c8a850ad87f912dffca3c715b1a960
    image: calico/pod2daemon-flexvol
  - digest: sha256:b159e24deff1fe31b57d50f9c459a5ec91b4ff9fa34d8a18e2bd421c2b58d9ac
    image: calico/apiserver
  - digest: sha256:64765b0edd5ee3f62ccdd69b57ae389c57e23eaa8a5b1bfa0cbc446f4d66f6b8
    image: calico/csi
  - digest: sha256:411409512c6569aa3a29d6ee8fba6d545fc37dc9fe5b6a3117fe8887cc4252fc
    image: calico/node-driver-registrar
  - digest: sha256:411409512c6569aa3a29d6ee8fba6d545fc37dc9fe5b6a3117fe8887cc4252fc
    image: calico/windows-upgrade

```
