### ISSUE TITLE
[Feature] [NRG-lockdown] Exclude specific type of resources inside NRG from deny assignment

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/AKS#4291]
**Is your feature request related to a problem? Please describe.**
For example: I enabled NRG-lockdown within a cluster. And I enabled a Pod with PVC like below:
```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-fs-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs-nginx-log 
  namespace: nginx-fs-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: azurefile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fs-demo
  namespace: nginx-fs-demo
  labels:
    app: nginx-fs-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-fs-demo
  template:
    metadata:
      labels:
        app: nginx-fs-demo
    spec:
      containers:
      - name: nginx-fs-demo
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: logs-nginx-log
            mountPath: "/var/log/nginx"
      volumes:
        - name: logs-nginx-log
          persistentVolumeClaim:
            claimName: pvc-logs-nginx-log
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-fs-demo-service
  namespace: nginx-fs-demo
spec:
  selector:
    app: nginx-fs-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

ATM the storage account will be created in NRG. 

But if I want to pull the files down, like the scenario when I find some error inside the file and I want to understand in what part this file is corrupted: 
![image](https://github.com/Azure/AKS/assets/142381267/9523a5c3-997d-43b1-b864-5565bd743f63)

Or if I create a new Azure Disk and I want to do a backup (snapshot) manually, will hit familiar error. 
![image](https://github.com/Azure/AKS/assets/142381267/7f0b9035-b7ce-42b0-9ddf-1221f8e0fc5e)

I know I can manually specify existing storage account/disk outside NRG group. But can we make it better? 

**Describe the solution you'd like**
1. Assign deny assignment on resource level instead of resource group level.
2. Specify a different group for other non-critical/external resources' creation (but the resource group is still managed by AKS, just not being locked by deny assignment). 

**Describe alternatives you've considered**
1. Add related parameter in PV so the disk/fileshare/etc won't be created within NRG. 

**Additional context**
None.
