### ISSUE TITLE
[Question] Bearer token for Kubernetes Dashboard

### ISSUE THREAD

**Issue by Basssiiie** [Azure/AKS#4307]
**Describe scenario**
I have updated my Kubernetes Dashboard deployment to the latest version, but this version does not allow login with kubeconfig anymore. Instead I need to provide a bearer token for the Kubernetes API. 

**Question**
How can I get a bearer token for the Kubernetes Dashboard based my Kubernetes credentials generated via `az aks get-credentials --admin`?

I do not want to generate a new service account with admin permissions. I want to use my own permissions that I already have.

Thank you for your time. 🙂

**Comment by JoeyC-Dev** [comment]
My sub owner does not allow us to use kubenetes dashboard, so I cannot verify this for you.

Try: `kubectl get secret bootstrap-token-xxxx -n kube-system -o yaml` (replace "xxxx" by your own name)

**Comment by JoeyC-Dev** [comment]
If you are using Kubernetes local accounts, then the token is literally in the file. For example:
```
- name: clusterUser_xxxxxxxxxxx
  user:
    client-certificate-data: xxxxxxxxxx
    client-key-data: xxxxxxxxxx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

If not using: The dashboard has already telling you how to do it
![image](https://github.com/Azure/AKS/assets/142381267/05732b17-661f-49d1-857a-2bb846683a59)
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens
https://kubernetes.io/docs/concepts/security/service-accounts/#grant-permissions
