### ISSUE TITLE
Windows pod stuck in terminating state with subpath in volumemounts

### ISSUE THREAD

**Issue by nimblenitin** [Azure/AKS#4309]
**Describe the bug**
Windowds based node Pod is stuck in terminating state during deletion/replace of pod whenever I add two volume mounts with subpath. This does not happen if I add single volume mount with subpath.
**To Reproduce**
1. Create a deployment with below volume and volumemounts. Make sure to create the configmap as well.
```
          volumeMounts:
            - name: configs
              mountPath: C:\inetpub\wwwroot\web.config
              subPath: web.config
            - name: cloudconfig
              mountPath: C:\CloudConfig
              subPath: credentials
      volumes:
        - name: configs
          configMap:
            name: test-report-executor-cm
        - name: cloudconfig
          configMap:
            name: cloud-config
```
3. Try running below command:
kubectl replace -n namespace -f filename.yaml --force

**Expected behavior**
pod should not be stuck in terminating state. The pod is stuck at terminating state for more than 5d now.
**Screenshots**
![image](https://github.com/Azure/AKS/assets/25668152/e66ac944-6337-498a-83a4-8d89a9d1fe56)

**Environment (please complete the following information):**
 -  CLI Version - v1.27.7
 - Kubernetes version - 1.27.7

**Additional context**
kubelet logs:

E0612 15:37:32.338453    4496 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/configmap/X17e892a03e1c-configs podName:X nodeName:}" failed. No retries permitted until 2024-06-12 15:37:33.3384537 +0000 UTC m=+1476.528238001 (durationBeforeRetry 1s). Error: UnmountVolume.TearDown failed for volume "configs" (UniqueName: "kubernetes.io/configmap/X-configs") pod "XXXX4744-X" (UID: "X") : remove c:\var\lib\kubelet\pods\X\volumes\kubernetes.io~configmap\configs\..2024_06_12_15_34_06.2642743558\Web.config: The process cannot access the file because it is being used by another process.
