### ISSUE TITLE
outboundTrafficPolicy cannot be set

### ISSUE THREAD

**Issue by snowsky** [Azure/AKS#4311]
**Describe the bug**
Istio add-on parameter `outboundTrafficPolicy` cannot be set.

**To Reproduce**
1. Create a new ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-shared-configmap-asm-1-21
  namespace: aks-istio-system
data:
  mesh: |-
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
```
2. Tail logs, `kubectl -n aks-istio-system logs -f istiod-asm-1-21-6447ff5c8c-l7dpr`
3. Empty value:
```
"outboundTrafficPolicy": {

    },
```

**Expected behavior**
`outboundTrafficPolicy` should be set to `REGISTRY_ONLY` mode

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version 1.28.5
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**

**Comment by nshankar13** [comment]
@snowsky just tested this locally. For some reason, the MeshConfig value doesn't show in the logs or ConfigMap output when it's set to `REGISTRY_ONLY`. However, when it's set to `ALLOW_ANY`, the value shows in the logs explicitly. 

I also tested the end to end behavior for accessing external services, and it worked as expected when set to REGISTRY_ONLY vs ALLOW_ANY - access was allowed / denied. You can verify with these steps: https://istio.io/latest/docs/tasks/traffic-management/egress/egress-control/#change-to-the-blocking-by-default-policy

**Comment by snowsky** [comment]
Hi @nshankar13, thanks for the reply, I just tried the command in the article, and the command `kubectl exec "$SOURCE_POD" -c sleep -- curl -sI https://www.google.com | grep  "HTTP/"; kubectl exec "$SOURCE_POD" -c sleep -- curl -sI https://edition.cnn.com | grep "HTTP/"` returns `200` with `REGISTRY_ONLY` policy. Can you please share how you tested it?

**Comment by nshankar13** [comment]
@snowsky:

1. `kubectl label ns default istio.io/rev=asm-1-21`
2. `kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/sleep/sleep.yaml`
3. `export SOURCE_POD=$(kubectl get pod -l app=sleep -o jsonpath='{.items..metadata.name}')`
4. `kubectl apply -f valid-meshconfig.yaml`
5. `kubectl exec "$SOURCE_POD" -c sleep -- curl -sI https://www.google.com | grep  "HTTP/"; kubectl exec "$SOURCE_POD" -c sleep -- curl -sI https://edition.cnn.com | grep "HTTP/"`

Here is `valid-meshconfig.yaml`
```yaml
apiVersion: v1
data:
  mesh: |-
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
kind: ConfigMap
metadata:
  name: istio-shared-configmap-asm-1-21
  namespace: aks-istio-system
```

My output:

```
$ kubectl exec "$SOURCE_POD" -c sleep -- curl -sI https://www.google.com | grep  "HTTP/"; kubectl exec "$SOURCE_POD" -c sleep -- curl -sI https://edition.cnn.com | grep "HTTP/"
command terminated with exit code 35
command terminated with exit code 35
```
