### ISSUE TITLE
Azure Key Vault CSI Driver Add-on doesn't enable Kubernetes Secret Sync

### ISSUE THREAD

**Issue by vifani** [Azure/AKS#4319]
**Describe the bug**
Deploying a cluster with the azureKeyvaultSecretsProvider add-on and configuring the addon to enable the sync secret settings (take a look at [https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/README.md#configuration](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/charts/csi-secrets-store-provider-azure/README.md#configuration) and at the parameter called **secrets-store-csi-driver.syncSecret.enabled**)

**To Reproduce**
Deploy a AKS cluster with Bicep enabling the addon using the following configuration:

`azureKeyvaultSecretsProvider: {
        enabled: true
        config: {
          enableSecretRotation: 'true'
          rotationPollInterval: '2m'
          'syncSecret.enabled': 'true'
        }
      }`

This is the add-on profile:

`az aks show -g $AKS_RG -n $AKS_NAME --query 'addonProfiles.azureKeyvaultSecretsProvider'`

`{
  "config": {
    "enableSecretRotation": "true",
    "rotationPollInterval": "2m",
    "syncSecret.enabled": "true"
  },
  "enabled": true,
  "identity": {
    "clientId": "4f4a271e-f3b4-4185-b3a4-02ec47ca7b79",
    "objectId": "2424094b-c497-40f0-be03-8a7ebea04f3e",
    "resourceId": "/subscriptions/SUBSCRIPTION/resourcegroups/RESOURCEGROUP/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-CLUSTER-NAME"
  }
}`

Additional info about the aks-secrets-store-csi-driver- pod args
![image](https://github.com/Azure/AKS/assets/4315570/3c0ed2f3-1d3f-4a6f-b44f-b7e0e8b8eb49)
as you can see, there is an argument to enable secret rotation, an argument to configuration rotation poll interval, but nothing about syncSecret setting.

**Expected behavior**
AKS Add-on CSI provider should automatically create Kubernetes secrets when a key vault secretproviderclass is defined and used to mount secret values into a pod.

**Environment (please complete the following information):**
 - Kubernetes version 1.28.9

**Comment by PixelRobots** [comment]
Hey @vifani 

that option in the helm chart just enables the RBAC it seems. what you are requesting can already be done you just need to configure it in your secret provider class and ensure that teh secret provider class is used by a pod.

He is an example one for ingress:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
  namespace: ingress
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: ingresscert
      key: tls.key
    - objectName: ingresscert
      key: tls.crt
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "$MIClientId"
    keyvaultName: "$keyvaultName"          # the name of the KeyVault
    cloudName: ""          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: ingresscert
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: "$resourceGroupNameKV"     # [REQUIRED] the resource group name of the key vault
    subscriptionId: "$subscriptionid"          # [REQUIRED] the subscription ID of the key vault
    tenantId: "$tenantid"  
```

You need to define the `secretObjects` part so it syncs the secret to a Kubernetes secret. The secret name will take the name used in the secret provider class.

Is this what you were after?

Thanks

Richard
