### ISSUE TITLE
[BUG]Priority expander in cluster-autoscaler doesn't work

### ISSUE THREAD

**Issue by zhangchl007** [Azure/AKS#4348]
**Describe the bug**
Priority expander in cluster-autoscaler doesn't work

**To Reproduce**
1. cat cluster-autoscaler-priority-expander.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-priority-expander
  namespace: kube-system
data:
  priorities: |-
    5:
      - .*spotazlinux2.*
    80:
      - .*spotazlinux1.*
```
2. kubectl create apply -f cluster-autoscaler-priority-expander.yaml

**Expected behavior**

 it enables your cluster to prioritize a node group , and if it is unable to scale for any reason, it will choose the next node group in the prioritized list

**Screenshots**
it look like autoscaler-priority-expander doesn't work and choose the node group randomly.

![image](https://github.com/Azure/AKS/assets/13577471/a75188bd-83d8-46b7-923a-d21f945536b1)

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 
![image](https://github.com/Azure/AKS/assets/13577471/850886f0-8358-44ce-a92d-4e22eba8dddd)
![image](https://github.com/Azure/AKS/assets/13577471/4c2706ea-5d85-4c0c-9ee1-ede14b8b84a6)
