### ISSUE TITLE
Upgrade flux extension from 1.7.5 to 1.9.1 fails

### ISSUE THREAD

**Issue by vetlesillerud** [Azure/AKS#4359]
**Describe scenario**
I upgraded my microsoft.flux extension in my AKS cluster directly from 1.7.5 to 1.9.1. After upgrade the fluxconfig-agent are unable to access the dataplane for kubernetesconfiguration. Comparing other similar clusters where the upgrade operation worked fine, I can see the following difference:  “IdentityClientId”, “IdentityPrincipalId” and “IdentityType” properties in helm values for flux are not present in the helmdeployment that is failing. In other clusters, these properties are populated by the id's related to the identity created in the aks managed resource group.

Log snippet from fluxconfig-agent:
```
fluxconfig-agent {"Message":"2024/06/12 09:40:44 Get configuration","LogType":"ConfigAgentTrace","LogLevel":"Information","Environment":"prod","Role":"ClusterConfigAgent","Location":"norwayeast","ArmId":"/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED","CorrelationId":"","AgentName":"FluxConfigAgent","AgentVersion":"1.9.1","AgentTimestamp":"2024/06/12 09:40:44.165"}
fluxconfig-agent {"Message":"2024/06/12 09:40:44 URL:\u003e https://norwayeast.dp.kubernetesconfiguration.azure.com/subscriptions/REDACTED/resourceGroups/REDACTED/provider/Microsoft.ContainerService-managedclusters/clusters/REDACTED/configurations/getPendingConfigs?api-version=2021-11-01","LogType":"ConfigAgentTrace","LogLevel":"Information","Environment":"prod","Role":"ClusterConfigAgent","Location":"norwayeast","ArmId":"/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED","CorrelationId":"","AgentName":"FluxConfigAgent","AgentVersion":"1.9.1","AgentTimestamp":"2024/06/12 09:40:44.165"}
fluxconfig-agent {"Message":"2024/06/12 09:40:44 Error in getting Token for clusterType: {managedclusters}: error {parameter 'userAssignedID' cannot be empty}","LogType":"ConfigAgentTrace","LogLevel":"Information","Environment":"prod","Role":"ClusterConfigAgent","Location":"norwayeast","ArmId":"/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED","CorrelationId":"","AgentName":"FluxConfigAgent","AgentVersion":"1.9.1","AgentTimestamp":"2024/06/12 09:40:44.165"}
fluxconfig-agent {"Message":"2024/06/12 09:40:44 Error: in getting auth header : error {parameter 'userAssignedID' cannot be empty}","LogType":"ConfigAgentTrace","LogLevel":"Information","Environment":"prod","Role":"ClusterConfigAgent","Location":"norwayeast","ArmId":"/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED","CorrelationId":"","AgentName":"FluxConfigAgent","AgentVersion":"1.9.1","AgentTimestamp":"2024/06/12 09:40:44.165"}
fluxconfig-agent {"Message":"Failed to create the Managed Service Identity token: parameter 'userAssignedID' cannot be empty","LogType":"ConfigAgentTrace","LogLevel":"Error","Environment":"prod","Role":"ClusterConfigAgent","Location":"norwayeast","ArmId":"/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED","CorrelationId":"","AgentName":"FluxConfigAgent","AgentVersion":"1.9.1","AgentTimestamp":"2024/06/12 09:40:44.165"}
fluxconfig-agent {"Message":"Error in getting the token from adal for MSI cluster: error {parameter 'userAssignedID' cannot be empty}","LogType":"ConfigAgentTrace","LogLevel":"Error","Environment":"prod","Role":"ClusterConfigAgent","Location":"norwayeast","ArmId":"/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED","CorrelationId":"","AgentName":"FluxConfigAgent","AgentVersion":"1.9.1","AgentTimestamp":"2024/06/12 09:40:44.165"}
```

values.yaml for flux helm chart 1.9.1 in failing cluster:
```
Azure:
  Cluster:
    Cloud: AZUREPUBLICCLOUD
    Distribution: ""
    Infrastructure: ""
    Region: norwayeast
    ResourceId: /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED
  Extension:
    Name: flux
    ResourceId: /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED/providers/Microsoft.KubernetesConfiguration/extensions/flux
  Identity:
    MSIAdapterYaml: |
      - command:
          - /addon-token-adapter
        args:
          - --secret-namespace=kube-system          # Note that this must match consts.DefaultSecretNamespace in addon-token-reconciler
          - --secret-name=extensions-aad-msi-token  # Note that this must match consts.ExtensionManagerGenevaTokenSecretName in addon-token-reconciler
          - --token-server-listening-port=8888
          - --token-server-forwarding-port=8889
          - --ignore-aud-trailing-slash=true
        image: "mcr.microsoft.com/aks/msi/addon-token-adapter:master.240510.2"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9999
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
    isEnabled: false
  proxySettings:
    isCustomCert: false
    isProxyEnabled: false
global:
  azure:
    cluster:
      cloud: AZUREPUBLICCLOUD
      distribution: ""
      infrastructure: ""
      region: norwayeast
      resourceId: /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED
    extension:
      name: flux
      resourceId: /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.ContainerService/managedclusters/REDACTED/providers/Microsoft.KubernetesConfiguration/extensions/flux
    identity:
      isEnabled: false
      mSIAdapterYaml: |
        - command:
            - /addon-token-adapter
          args:
            - --secret-namespace=kube-system          # Note that this must match consts.DefaultSecretNamespace in addon-token-reconciler
            - --secret-name=extensions-aad-msi-token  # Note that this must match consts.ExtensionManagerGenevaTokenSecretName in addon-token-reconciler
            - --token-server-listening-port=8888
            - --token-server-forwarding-port=8889
            - --ignore-aud-trailing-slash=true
          image: "mcr.microsoft.com/aks/msi/addon-token-adapter:master.240510.2"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9999
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 50Mi
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
    proxySettings:
      isCustomCert: false
      isProxyEnabled: false
multiTenancy:
  enforce: false
scope: cluster
useKubeletIdentity: true

```

**Question**
Have anybody experienced the same issue? How can i fix this?
