### ISSUE TITLE
RBAC config for HTTP Application Routing - Nginx-ingress fails for leader elect

### ISSUE THREAD

**Issue by FrodeHus** [Azure/AKS#436]
When using a out-of-the-box AKS cluster with RBAC and HTTP Application Routing enabled, the nginx-ingress controller will keep reporting errors like this:
` Failed to update lock: configmaps "ingress-controller-leader-addon-http-application-routing" is forbidden: User "system:serviceaccount:kube-system:addon-http-application-routing-nginx-ingress-serviceaccount" cannot update configmaps in the namespace "kube-system"`

This is because ingress-class is set to `addon-http-application-routing` and it will then try to create/update a ConfigMap called `ingress-controller-leader-addon-http-application-routing`, but the Role is set to give update access to `ingress-controller-leader-nginx` (nginx being the default ingress-class)

It's not possible to edit the role and fix this as the master seems to reload the original config moments after editing it.

**Comment by twendt** [comment]
We have the same issue.

As a workaround I added a new role with the missing permission and a new rolebinding to bind the new role to system:serviceaccount:kube-system:addon-http-application-routing-nginx-ingress-serviceaccount. 

Now it works as expected.

Here are my resources:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: addon-http-application-routing-ingress-nginx
    kubernetes.io/cluster-service: "true"
  name: my-addon-http-application-routing-nginx-ingress-role
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - ingress-controller-leader-addon-http-application-routing
  resources:
  - configmaps
  verbs:
  - get
  - update
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: addon-http-application-routing-ingress-nginx
    kubernetes.io/cluster-service: "true"
  name: my-addon-http-application-routing-nginx-ingress-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-addon-http-application-routing-nginx-ingress-role
subjects:
- kind: ServiceAccount
  name: addon-http-application-routing-nginx-ingress-serviceaccount
  namespace: kube-system
```
