### ISSUE TITLE
[BUG] Azure CLI missing from Node Image AKSUbuntu-2204gen2containerd-202406.19.0

### ISSUE THREAD

**Issue by aolear-ss** [Azure/AKS#4375]
**Describe the bug**
I created a similar issue here: https://github.com/Azure/AgentBaker/issues/4568 but thinking this repository may get more eyes.

After adding a new Node Pool to an AKS cluster in a nonproduction environment, workloads using the azure-blob-fuse storage class fail in "ContainerCreating" with the following error message:
``` 
MountVolume.MountDevice failed for volume "***" :   rpc error: code = Internal desc = Mount failed with error: rpc error: code =   Unknown desc = exit status 1 Error: failed to initialize new pipeline [Azure CLI not found on path]
```

Upon logging into the node, it is confirmed that the Azure CLI is not installed. After manually installing Azure CLI onto the node, the error message is resolved. 

It seems that the az cli utility is missing from the node image version and is required for the azure-blob-fuse storage class to mount a blob container as a volume.

I was able to reproduce this issue after deploying a new cluster to the same subscription and also by upgrading an existing node pool on the first cluster to the latest version of:
![image](https://github.com/Azure/AKS/assets/143454796/44c3ca32-6bf7-4bf1-8dfc-e1dea86488c6)

**To Reproduce**
1. Create a new node pool in an existing cluster, deploy a new cluster or upgrade an existing node pool to the latest node image version
2. Deploy a pod that mounts a volume using the `azure-blob-fuse-premium` storage class
3. Observe the pod get scheduled to the node, but gets stuck in "ContainerCreating" status
![image](https://github.com/Azure/AKS/assets/143454796/6ff62912-7fab-4fbe-8d7b-39e24b084717)
![image](https://github.com/Azure/AKS/assets/143454796/3b7e1d49-05fa-4eab-97b4-2708fa82e8b0)

**Expected behavior**
The scheduled pod is created and started. The volume based on the azure-blob-fuse-premium storage class is mounted.

**Screenshots**
See above

**Environment (please complete the following information):**
 -  CLI Version - N/A
 - Kubernetes version - 1.28.9
 - CLI Extension version - N/A
 - Browser - Edge

**Additional context**
N/A

**Comment by PixelRobots** [comment]
@andyzhangx is this something you know about?

**Comment by aolear-ss** [comment]
For anyone else that does run into this, I was able to work around it by creating a DaemonSet to install the Azure CLI on each node if it does not already exist. Not an ideal long-term fix, but something to keep us running for now

**Comment by andyzhangx** [comment]
> For anyone else that does run into this, I was able to work around it by creating a DaemonSet to install the Azure CLI on each node if it does not already exist. Not an ideal long-term fix, but something to keep us running for now

This is a breaking change in blobfuse 2.3.0 (using AzureStorageIdentityClientID depends on azure cli from blobfuse 2.3.0), to avoid having to install Azure CLI on worker nodes, user should use AzureStorageIdentityClientID or AzureStorageIdentityResourceID instead of AzureStorageIdentityObjectID, blobfuse team are working on a fix.

@aolear-ss can you share the daemonset config? thx.

**Comment by aolear-ss** [comment]
@

> > For anyone else that does run into this, I was able to work around it by creating a DaemonSet to install the Azure CLI on each node if it does not already exist. Not an ideal long-term fix, but something to keep us running for now
> 
> This is a breaking change in blobfuse 2.3.0 (using AzureStorageIdentityClientID depends on azure cli from blobfuse 2.3.0), to avoid having to install Azure CLI on worker nodes, user should use AzureStorageIdentityClientID or AzureStorageIdentityResourceID instead of AzureStorageIdentityObjectID, blobfuse team are working on a fix.
> 
> @aolear-ss can you share the daemonset config? thx.

I did see this issue come through on the blob fuse GitHub repository, which outlines the fix (workaround?) you mentioned: https://github.com/Azure/azure-storage-fuse/issues/1443. It's on my short list to try and then evaluate the effort to implement.

As part of that, I wanted to understand your comment better. When you say the blobfuse team is working on a fix, are they working on a fix to support the usage of `AzureStorageIdentityObjectID` without Azure CLI installed? If so - we may hold off on the effort to migrate out volume configuration as it will be some effort to do so.

As for the daemonset implementation, I found this public GitHub repository and adopted a derivation of it to meet the needs of our cluster: https://github.com/patnaikshekhar/AKSNodeInstaller/tree/master

The repository outlines how to build a custom image for the DaemonSet to execute. From there, the Kubernetes configuration involved a ConfigMap with the install script for the Azure CLI and a Kubernetes Manifest to create the DaemonSet.

Something like:

```
apiVersion: v1
kind: Namespace
metadata:
  name: az-cli-installer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: installer-config
  namespace: az-cli-installer
data:
  install.sh: |
    #!/bin/bash

    # Update and install packages
    apt-get update
    # install Azure CLI 
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: installer
  namespace: az-cli-installer
spec:
  selector:
    matchLabels:
      job: installer
  template:
    metadata:
      labels:
        job: installer
    spec:
      hostPID: true
      restartPolicy: Always
      containers:
      - image: <uri for Docker image>
        name: installer
        securityContext:
          privileged: true
        volumeMounts:
        - name: install-script
          mountPath: /tmp
        - name: host-mount
          mountPath: /host
      volumes:
      - name: install-script
        configMap:
          name: installer-config
      - name: host-mount
        hostPath:
          path: /tmp/install
```

We used this to fix an isolated development cluster, so if anyone is looking to do the same - I recommend reviewing the approach to ensure the right controls are in place for the solution to be secure. For example, it may make more sense to some to bake the install script into the DaemonSet container image
