### ISSUE TITLE
Ingress whitelisting ip does not work

### ISSUE THREAD

**Issue by YvonneArnoldus** [Azure/AKS#438]
I'm using the following AKS configuration:

- Kubernetes version: 1.9.6
- stable/nginx-ingress  CHART VERSION:  0.20.1  APP VERSION:  0.14.0

I have the following ingress.yml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fontoxml-dev-restricted-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "xxx.xxx.xxx.xxx"
spec:
  tls:
  - hosts:
    - restricted.xxx.xxx
    secretName: my-host-com-secret
  rules:
  - host: restricted.xxx.xxx
    http:
      paths:
      - path: /
        backend:
          serviceName: restricted-example-staging
          servicePort: 80
```
I've have blurred out my real ip and domain.

If I connect to restricted.xxx.xxx on my ip xxx.xxx.xxx.xxx I get a 403.

I have checked with the [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx) to see if my configuration was wrong. But the rule is added to the nginx.conf.

```
# Deny for restricted.xxx.xxx/
geo $the_real_ip $deny_qvkHIYSeUBWaPulBjeHzAGWwbBlksOdG {
		default 1;

		xxx.xxx.xxx.xxx 0;
}
```

They suggested to check and see if the load balancer forwards the ip that request the application or its own ip.

I'm not sure how to check this with the load balancer of AKS. Or if this can indeed be the case.
