### ISSUE TITLE
[BUG] aks-node-ca-watcher cannot run

### ISSUE THREAD

**Issue by pawellrus** [Azure/AKS#4382]
**Describe the bug**
After k8s cluster reconfiguration one of nodes cannot run pod daemonset custom-ca-trust. Pod throws an error "Container image "mcr.microsoft.com/aks/aks-node-ca-watcher:static" is not present with pull policy of Never"

**To Reproduce**
1. Custom Ca certificates should be enabled. And that is all that I can say. Seems that issue is not easy reproduceable.

**Environment (please complete the following information):**
 -  AKS 1.27.7

**Comment by UtheMan** [comment]
@pawellrus - is this happening on a node that was created a while ago, but didn't have the feature enabled initially after creation? If yes, can you attempt to perform a node image upgrade on that node and see if this helps with the issue?

**Comment by pawellrus** [comment]
> @pawellrus - is this happening on a node that was created a while ago, but didn't have the feature enabled initially after creation? If yes, can you attempt to perform a node image upgrade on that node and see if this helps with the issue?

thank you for advice. I will try to perform node image upgrade in maintenance window.

**Comment by pawellrus** [comment]
Node image upgrade helped. Thank you @UtheMan

**Comment by DarthVader-JF** [comment]
I am encountering the this as well and thus I am unable to spin up new nodes.  Is there an ETA on fixing this?

**Comment by UtheMan** [comment]
We're looking into this issue, will post updates here asap.

**Comment by UtheMan** [comment]
I identified the issue and submitted a fix. As a short term mitigation, you can re-tag the image on your nodes like so:

```bash
ctr --namespace k8s.io image tag mcr.microsoft.com/aks/aks-node-ca-watcher:master.240820.1 mcr.microsoft.com/aks/aks-node-ca-watcher:static 
``` 

This would have to be ran on ever affected node, so ideally in it would be triggered using a daemonset.

**Comment by DarthVader-JF** [comment]
Thanks for the recommendation that fixed our issue.  Here is the daemonset that I deployed to update the each of the host: 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: host-command-ctr
  labels:
    k8s-app: host-command-ctr
  annotations:
    command: &cmd apt-get update -qy && apt-get install -qy open-iscsi xfsprogs && ctr --namespace k8s.io image tag mcr.microsoft.com/aks/aks-node-ca-watcher:master.240820.1 mcr.microsoft.com/aks/aks-node-ca-watcher:static
spec:
  selector:
    matchLabels:
      k8s-app: host-command-ctr
  template:
    metadata:
      labels:
        k8s-app: host-command-ctr
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
        - name: init-node
          command:
            - nsenter
            - --mount=/proc/1/ns/mnt
            - --
            - sh
            - -c
            - *cmd
          image: alpine:3
          securityContext:
            privileged: true
      containers:
        - name: wait
          image: k8s.gcr.io/pause:3.1
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
  updateStrategy:
    type: RollingUpdate
```
