### ISSUE TITLE
Failed to authenticate using azure ad rbac

### ISSUE THREAD

**Issue by richardjharding** [Azure/AKS#439]
kind bug

What happened:

I folllowed the guidance to create a new aks cluster configured for advanced networking (existing vnet) and rabc with Azure AD integration I was able to fetch the admin credentials and create the cluster role binding , query the cluster via kubectl , browse the dashboard etc

But when I fetch the normal credentials I am unable to run any commands - I get the prompt to authenticate via devicelogin page but once authenticated I see the following

error: You must be logged in to the server (Unauthorized)
I have previously built a cluster using azure ad with ACS engine so am happy that the ad settings are correct

What you expected to happen:

The cluster is created and I was able to create a cluster role binding and use kubeclt to list nodes after authenticating via azure ad

How to reproduce it (as minimally and precisely as possible):

Follow the instructions here passing in known good azure ad app details - https://docs.microsoft.com/en-us/azure/aks/aad-integration#access-cluster-with-azure-ad

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version): 1.9.6
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): windows 10
Kernel (e.g. uname -a):
Install tools: az cli v 2.0.37
Others:

**Comment by mbrancato** [comment]
Can you post the commands you ran? I'm able to make the directions work just fine, however, I only think you'll get a "devicelogin" url prompt during the `az login` part.

I'm curious if support for `kubectl --kubeconfig=aad-kubeconfig ` will be released anytime soon / how to configure.

**Comment by amanohar** [comment]
@richardjharding regarding:

```
But when I fetch the normal credentials I am unable to run any commands - I get the prompt to authenticate via devicelogin page but once authenticated I see the following
error: You must be logged in to the server (Unauthorized)
```

OOB `clusterUser` is not authorized to perform any operation. When you created cluster role binding using `clusterAdmin` kubeconfig, did you create rolebinding for your user or an AAD distribution group you belong to? 

e.g.:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-default-admin-group
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
subjects:
- kind: Group
  name: "<DISPLAY_NAME_OF_AAD_DISTRIBUTION_OR_SECURIT_GROUP>"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
