### ISSUE TITLE
[BUG] CSI snapshot controller may break whole subscription if ShareSnapshotCountExceeded

### ISSUE THREAD

**Issue by jkroepke** [Azure/AKS#4394]
**Describe the bug**
We are using velero together with CSI Snapshots. We also do CSI Snapshot for Azure File

Turns if ShareSnapshotCountExceeded, the csi snapshot controller tries infinitely to create new snapshots.

After some days (because velero create more snapshot requests), the amount of requests hit the Storage Provider Requests Limits (https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/request-limits-and-throttling#storage-throttling), e.g. more than 800 requests per 5 minutes. This affects all storage accounts operations.

**To Reproduce**
1. Setup more than 200 CSI snapshots requests again one PVC.

**Expected behavior**
The CSI snapshot controller should create such huge amount of requests. Since the controller runs inside of AKS controller plane, we are unable to get logs from it.

The csi snapshot controller should also recognized that 200 PVC Snapshots for one PVC may exists and should correctly report the error on the kubernetes events. 

**Screenshots**
![Bildschirmfoto 2024-07-10 um 13 22 55](https://github.com/Azure/AKS/assets/1560587/1177f693-1b5c-431d-bdf6-fa6e77c4d46c)
![347379004-0494c3d2-9455-4d5e-b624-1a13942b50d3](https://github.com/Azure/AKS/assets/1560587/e0f0063b-9a5e-428a-9d74-99e773564809)

**Environment (please complete the following information):**
 - Kubernetes version [e.g. 1.24.3] 1.29.4

**Additional context**

**Comment by andyzhangx** [comment]
can you email me your aks cluster fqdn? I could take a look.

**Comment by andyzhangx** [comment]
pls add useDataPlaneAPI: "true" into snapshot storage class? I think that would solve the problem.
```
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-azurefile-vsc
driver: file.csi.azure.com
parameters:
  useDataPlaneAPI: "true"  # unlimited azure file api call
deletionPolicy: Delete
```

useDataPlaneAPI:     specify whether use data plane API for file share create/delete/resize, this could solve the SRP API throttling issue since data plane API has almost no limit, while it would fail when there is firewall or vnet setting on storage account
