### ISSUE TITLE
[BUG]  Blob storage does not overwrite files with the same name.

### ISSUE THREAD

**Issue by win5923** [Azure/AKS#4415]
**Describe the bug**
When overwriting a file with the same name in Azure Blob storage, the file content remains unchanged or old.

**To Reproduce**
1. Bind PV (Persistent Volume) and PVC (Persistent Volume Claim) to Pods.
2. Add a file "test2.json".
3. Attempt to overwrite the file with the same name.
4. The file content remains unchanged.

**Expected behavior**
Files with the same name should be overwriteable.

**Screenshots**
First file:
![image](https://github.com/user-attachments/assets/93f223ab-a489-450c-91d1-138392c003cf)

Pod's file:
![image](https://github.com/user-attachments/assets/de408173-dd5d-45c2-8472-36591b1b6374)

Second file to overwrite:
![image](https://github.com/user-attachments/assets/e4065824-9809-40bf-9172-3e3448337ad0)

Pod's file did not overwrite:
![image](https://github.com/user-attachments/assets/540307f5-e22d-4383-9269-316a3fc632f2)

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]: 1.28.9
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**
PV.yml:
```yaml
  csi:
    driver: blob.csi.azure.com
    volumeAttributes:
      isHnsEnabled: 'true'
      protocol: fuse
      skuName: Standard_LRS
  accessModes:
    - ReadWriteMany
  mountOptions:
    - '-o allow_other'
    - '--file-cache-timeout-in-seconds=120'
    - '--use-attr-cache=true'
    - '--cancel-list-on-mount-seconds=10'
    - '-o attr_timeout=120'
    - '-o entry_timeout=120'
    - '-o negative_timeout=120'
    - '--log-level=LOG_WARNING'
    - '--cache-size-mb=1000'
    - '--use-adls=true'
  volumeMode: Filesystem
```
