### ISSUE TITLE
[BUG] Regression in kube-scheduler impacting Kubernetes versions v1.27.14, v1.28.10, v1.29.5

### ISSUE THREAD

**Issue by qpetraroia** [Azure/AKS#4434]
**Describe the bug**

The AKS team has found a bug that is causing regressions in kube-scheduler impacting Kubernetes versions v1.27.14, v1.28.10, v1.29.5. This regression causes the kube-scheduler to panic when a cluster has a pod with a bad node affinity. If this is the case, no pod will be scheduled. 

Below is an example condition where the bug will be triggered 

```
apiVersion: v1
kind: Pod
metadata:
  name: break-kube-scheduler
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - invalid-node # a node that doesn't exist
 
```

**Interim fix**
Be aware that Azure Kubernetes Service engineers are actively fixing all impacted clusters as well as deploying a fix to kube-scheduler which will be rolled out to all regions. These fixes will be applied automatically to your cluster.

Thank you for understanding,
The AKS team
