### ISSUE TITLE
[Feedback] Document additional steps needed to deploy Istio managed add-on in cluster using a HTTP Proxy

### ISSUE THREAD

**Issue by colincmac** [Azure/AKS#4465]
**Describe your scenario**
Additional steps are needed to deploy the Istio managed add-on in a cluster using an external HTTP Proxy, using the feature documented here: https://learn.microsoft.com/en-us/azure/aks/http-proxy

Here is the relevant Istio documentation: https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/

For applications to be able to access non-cluster/external resources using the HTTP Proxy, a ServiceEntry must be created representing the proxy. Without the ServiceEntry resource, requests from the pods with an Istio sidecar to external services will fail with a 404 error after HTTP CONNECT.

**Feedback**

We should add documentation somewhere that details the need to deploy a ServiceEntry like the below. Not sure where it should exist.

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: proxy
spec:
  hosts:
  - my-company-proxy.com # ignored
  addresses:
  - $PROXY_IP/32
  ports:
  - number: $PROXY_PORT
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL
```
 
Example error without the additional ServiceEntry:

```
[root@my-cluster ~]# curl -kv https://google.com
......additional details......
* Uses proxy env variable https_proxy == 'http://<my-proxy-ip>:8080'
*   Trying <my-proxy-ip>...
* TCP_NODELAY set
* Connected to <my-proxy-ip> (<my-proxy-ip>) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 404 Not Found
< date: Wed, 07 Aug 2024 19:35:17 GMT
< server: envoy
< connection: close
< content-length: 0
< 
* Received HTTP code 404 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 404 from proxy after CONNECT
```
