### ISSUE TITLE
[BUG] Private DNS record not created by webAppRouting addon's Internal IngressController

### ISSUE THREAD

**Issue by thehedhly** [Azure/AKS#4487]
**Describe the bug**

The web application routing addon configured to use an **internal** IngressController did not create **records** in the provided **private DNS zone**.  

**To Reproduce**

```bash
# The Ingress profile
```
```json
"ingressProfile" = {
  "webAppRouting" = {
    "dnsZoneResourceIds" = [
      "/subscriptions/xxxxxxxxxsubidxxxxxxxxxxxxxx/resourceGroups/rg-dummy-dev-westeurope-01/providers/Microsoft.Network/privateDnsZones/lab.com",
    ]
    "enabled" = true
    "identity" = {
      "clientId" = "xxxxxxxxxxclientIdxxxxxxxxxxxxx"
      "objectId" = "xxxxxxxxxxobjectIdxxxxxxxxxxxxx"
      "resourceId" = "/subscriptions/xxxxxxxxxsubidxxxxxxxxxxxxxx/resourcegroups/rg-mc-dummy-dev-westeurope-01/providers/Microsoft.ManagedIdentity/userAssignedIdentities/webapprouting-aks-dummy-dev-01"
    }
    "nginx" = {
      "defaultIngressControllerType" = "Internal"
    }
  }
}
```
```bash
# The web application routing identity "webapprouting-aks-dummy-dev-01" has the built-in role "Private DNS Zone Contributor" assigned, scoped for the whole subscription.
# The cluster resource group is "rg-dummy-dev-westeurope-01".
# The cluster's managed resource group is "rg-mc-dummy-dev-westeurope-01" as listed above.
# A vnet is created within the cluster's resource group and contains 1 subnet. A vnet Link was created to the Private DNS Zone.
```
```yaml
# Listed below are the deployed resources (ns, deploy, svc and ingress)

apiVersion: v1
kind: Namespace
metadata:
  name: hello-web-app-routing

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld  
  namespace: hello-web-app-routing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-helloworld
  template:
    metadata:
      labels:
        app: aks-helloworld
    spec:
      containers:
      - name: aks-helloworld
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Kubernetes Service (AKS)"

---

apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld
  namespace: hello-web-app-routing
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-helloworld

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  namespace: hello-web-app-routing
spec:
  ingressClassName: nginx-internal
  rules:
  - host: hello.lab.com
    http:
      paths:
      - backend:
          service:
            name: aks-helloworld
            port:
              number: 80
        path: /
        pathType: Prefix
```

```bash
NOTE: Both "aks-helloworld" Ingress Events and "nginx" Controller Events are normal i.e show no errors or issues. 
```

**Expected behavior**
The web application routing addon configured to use an **internal** IngressController should create **records** in the provided **private DNS zone**.

**Screenshots**
![Screenshot 2024-08-16 at 00 09 19](https://github.com/user-attachments/assets/f0f9d2a4-5165-49d4-bdfa-038d2652e369)
![Screenshot 2024-08-16 at 00 14 01](https://github.com/user-attachments/assets/8bda8e97-3a03-420c-b250-3d74b64fc7a4)
```bash
Services:
```
![Screenshot 2024-08-16 at 00 15 34](https://github.com/user-attachments/assets/9f3e797c-4540-44e1-8e11-85226806fc23)
```bash
The "hello" recordset *was not created* in the "lab.com" Private DNS Zone as described in the following screenshots:
```
![Screenshot 2024-08-16 at 00 17 20](https://github.com/user-attachments/assets/e78f9e4c-527f-4aa2-8e52-cb63426bd62d)
![Screenshot 2024-08-16 at 00 17 04](https://github.com/user-attachments/assets/64451679-cff8-4b8a-9dc1-663b23963e57)

**Environment:**
 - Kubernetes version: 1.30.3
 - API Version: "Microsoft.ContainerService/managedClusters@2024-06-02-preview"

**Additional context**
n/a
