### ISSUE TITLE
[BUG] : AKS service stuck into pending state when there is Karpenter node

### ISSUE THREAD

**Issue by abhishek-baranwal** [Azure/AKS#4570]
**Describe the bug**
Hi team,

Just want to understand how karpenter works with azure AKS
I saw microsoft documentation which says below that there is limitation while working with AKS, we can not create virtual machine scaleset with karpenter while Karpenter is not designed to directly create Virtual Machine Scale Sets (VMSS) in Azure; instead, it focuses on automatically provisioning individual nodes within a Kubernetes cluster based on pod requirements, essentially bypassing the need to manage VMSS explicitly, allowing for more granular scaling and cost optimization by launching only the necessary nodes.

The AKS cluster must use Virtual Machine Scale Sets for the nodes.
reference: https://learn.microsoft.com/en-gb/azure/aks/create-node-pools#limitations

we also found some issue related to it while we were trying to create internal azure LB, it was showing error
Error syncing load balancer: failed to ensure load balancer: can not extract scale set name from ipConfigurationID (/subscriptions/xxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/networkInterfaces/aks-karpenter-nodepool-xxxx/ipConfigurations/aks-karpenter-nodepool-xxxx)

let me know if there is something wrong with our service below
````yaml
apiVersion: v1
kind: Service
metadata:
  name: service-loadbalancer
  labels:
    app: service-loadbalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: xxxxxx
spec:
  type: LoadBalancer
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: service
  ports:
    - protocol: TCP
      port: 80
  sessionAffinity: None
````

**To Reproduce**
1. Install karpenter and provision nodes Reference: https://github.com/Azure/karpenter-provider-azure
3. Provision a service with type load-balencer

**Expected behavior**
Just wanted to share one point that  Karpenter is not designed to directly create Virtual Machine Scale Sets (VMSS) in Azure; instead, it focuses on automatically provisioning individual nodes within a Kubernetes cluster based on pod requirements, essentially bypassing the need to manage VMSS explicitly, allowing for more granular scaling and cost optimization by launching only the necessary nodes. 

So it by default uses virtual machines not scaleset in its nodepool so any node created by it does not have VMSS, but why load balancer is looking for scaleset name since its virtual machine 

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22] 
 - Kubernetes version [e.g. 1.24.3]: 
 `kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
`

**Additional context**
