### ISSUE TITLE
[BUG] Unable to use `node-role.kubernetes.io/control-plane=NoSchedule` as a node pool label

### ISSUE THREAD

**Issue by rhys96** [Azure/AKS#4613]
**Describe the bug**

When attempting to apply the `node-role.kubernetes.io/control-plane=NoSchedule` label to a node pool, I receive an error indicating I'm using a denied prefix. According to [Well-Known Labels, Annotations and Taints](https://kubernetes.io/docs/reference/labels-annotations-taints/) it is a supported label.

**To Reproduce**

```bash
az aks create --resource-group myResourceGroup \
  --name myAKSCluster \
  --node-count 2 \
  --nodepool-labels node-role.kubernetes.io/control-plane=NoSchedule \
  --generate-ssh-keys

(BadRequest) For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io). For more information, please check https://aka.ms/aks-node-labels-116.
Code: BadRequest
Message: For Kubernetes version greater than or equal to 1.16, node label keys in the 'kubernetes.io' or 'k8s.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io). For more information, please check https://aka.ms/aks-node-labels-116.
Target: node-role.kubernetes.io/control-plane=NoSchedule
```

**Expected behavior**

The AKS Cluster to successfully deploy with the `node-role.kubernetes.io/control-plane=NoSchedule` label applied to the nodes.

**Screenshots**
No applicable.

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22] - 2.65.0
 - Kubernetes version [e.g. 1.24.3] - 1.29
 - CLI Extension version [e.g. 1.7.5] - N/A
 - Browser [e.g. chrome, safari] - N/A

**Additional context**
N/A

**Comment by PixelRobots** [comment]
Question for you. Why do you want to add this label? What are you trying to accomplish?

**Comment by rhys96** [comment]
I'm attempting to install [KubeVirt](https://kubevirt.io/) on AKS via the [quick start](https://kubevirt.io/quickstart_cloud/) guide. It appears that from v1.3 they have configured KubeVirt components pods to be scheduled onto control plane nodes (see https://github.com/kubevirt/kubevirt/issues/12390). I'm likely missing something obvious!

**Comment by PixelRobots** [comment]
It looks like you will need to follow this. https://kubevirt.io/user-guide/cluster_admin/installation/#restricting-kubevirt-components-node-placement

And then ensure your system node pool is tainted with the critical add-ons and use that instead of the system node pool.

**Comment by rhys96** [comment]
Thank you that resolved the issue. For future reference, this was my applied `kubevirt-cr.yaml`:

```yaml
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  infra:
    nodePlacement: {}
  workloads:
    nodePlacement: {}
```
