### ISSUE TITLE
Trust domain - workload identity federation

### ISSUE THREAD

**Issue by shashankbarsin** [Azure/AKS#4658]
Trust domains will allow associating multiple AKS clusters so that FICs for workload identity federation can be created on <trust_domain_issuer, namespace, service-account> instead of <aks_cluster_issuer, namespace, service-account> to address [the current 20 FIC limitation per identity](https://learn.microsoft.com/azure/aks/workload-identity-overview?tabs=dotnet)

Tentative ETA for preview CY2025H1

**Comment by colincmac** [comment]
@shashankbarsin Will this resolve these issues?
https://github.com/Azure/AKS/issues/3982
https://github.com/Azure/AKS/issues/2861

**Comment by OmnipotentOwl** [comment]
For the ETA for a preview which type of preview is that expected to be?

**Comment by shashankbarsin** [comment]
@colincmac  - It'll address #3982. #2861 will be addressed by structured authentication integration, that's currently being planned and will share an update on that soon too..

@OmnipotentOwl - Most likely a private preview to begin with. Closer to release, we will share a form where you can share your subscriptionId and we will enable the feature flag.

**Comment by Richard87** [comment]
All the Subjects in a trust domain will have the same prefix, will it also share the Issuer?

**Comment by shashankbarsin** [comment]
reopening this issue as it was wrongly closed as stale by the bot. this feature is still on the roadmap and still on track for a preview in CY2025H1.

**Comment by shashankbarsin** [comment]
@Richard87 - this feature (trust domain) would result in the same issuer URL for the trust domain and wouldn't impact the subject part, which remains a tuple of <namespace, service-account>. For flexibility on declaration of subjects, we have a different feature on the roadmap to provide the ability to declare the subject using prefix patterns - https://github.com/Azure/AKS/issues/4688

**Comment by ChrisF987-coles** [comment]
@shashankbarsin will this feature be dependent on Fleet Manager - ie will the clusters have to be a part of a Fleet Manager fleet to be a part of the trust domain?

**Comment by shashankbarsin** [comment]
@ChrisF987-coles - no it won't be dependent on Fleet Manager

**Comment by fsforza** [comment]
Hi @shashankbarsin!

can you confirm the CY2025H1 ETA is still a valid date for the preview? 

I'm very interested to try this feature to deploy, and authenticate, at scale an app on multiple AKS clusters

Thanks!

**Comment by shashankbarsin** [comment]
Updated the issue description to capture the tentative UX planned for the feature and to provide a more granular timeline. Still tracking for CY2025H1 and looking at June 2025 for preview.

**Comment by Sathpal-Singh** [comment]
Hi @shashankbarsin,
is it still on track to be delivered in June, have a use case dependent on this feature.

**Comment by msci-horvrud** [comment]
Hi! I updated my az cli, but the command `az aks identity-binding create` is not recognized by it.
Are further steps required to try out this in preview?

**Comment by Richard87** [comment]
Hi! Any updated timeline for when we can start to test this?

**Comment by illrill** [comment]
🥳 It's about to drop: https://github.com/Azure/AKS/pull/5430

**Comment by Richard87** [comment]
It seems I have missudnerstood the feature, especially reading the documentation and the description above again. Can you confirm/deny this UX?

- 1 Managed Identity created by Platform Operators (`Platform MI`)
- Assign the `Platform MI` with Identity binding to 2-3 AKS clusters
- Our users have their own Managed Identity with Workload Identity Enabled (`AppX MI`)
- Our users can select to use their MI with our Platform MI (A jwt with the `Platform MI` as issuer, but `AZURE_CLIENT_ID` = `AppX MI` Client id

And Offocurse, `AppY MI` and `AppZ MI` etc will continue to work, but can select the `Platform MI` as issuer when they are ready (will require a RBAC role to allow selecting the `Platform MI` as issuer).

In other words, I expected a new annotation like this:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "${AppX_MI}"
    azure.workload.identity/identity-binding-client-id: "${Platform_MI}" # This guy is MIA
  name: appx-server
  namespace: appx
---
apiVersion: v1
kind: Pod
metadata:
    name: appx-server
    namespace: appx
    labels:
        azure.workload.identity/use: "true"
spec:
    serviceAccountName: appx-server
    containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
        name: oidc
        env: 
        - name: AZURE_CLIENT_ID 
            value: ${AppX_MI}
        - name: AZURE_TENANT_ID
            value: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        - name: AZURE_FEDERATED_TOKEN_FILE
            value: /var/run/secrets/azure/tokens/azure-identity-token 
        - name: AZURE_AUTHORITY_HOST  
            value: https://login.microsoftonline.com/   
```
