### ISSUE TITLE
[BUG] `CiliumNetworkPolicy` is invalid: `ValidatingAdmissionPolicy` 'advanced-networking-validating-policy' with binding 'advanced-networking-cilium-l7-binding' denied request

### ISSUE THREAD

**Issue by avanschie** [Azure/AKS#4663]
My AKS cluster (version `1.30.5`, automatic upgrade type `Patch`) is using Azure CNI Powered by Cilium. I'm creating my own `CiliumNetworkPolicies` - I'm aware that CNPs are only partially supported (https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium#frequently-asked-questions), up until now everything worked as it should.

Since a couple of days I observe that I cannot create a CNP anymore that looks as follows:
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: my-cnp
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - {}
```

The error message is:
```
The ciliumnetworkpolicies "my-cnp" is invalid: : ValidatingAdmissionPolicy 'advanced-networking-validating-policy' with binding 'advanced-networking-cilium-l7-binding' denied request: expression '
!(has(object.spec) && has(object.spec.egress) && object.spec.egress.exists(e, ((has(e.toEndpoints) || has(e.toPorts)) && e.toPorts.all(p, has(p.rules) && has(p.rules.dns))))) && !(has(object.specs) && object.specs.all(s, has(s.egress) && s.egress.exists(e, ((has(e.toEndpoints) || has(e.toPorts)) && e.toPorts.all(p, has(p.rules) && has(p.rules.dns)))))) && !(has(object.spec) && has(object.spec.ingress) && object.spec.ingress.exists(e, ((has(e.fromEndpoints) || has(e.toPorts)) && e.toPorts.all(p, has(p.rules) && has(p.rules.dns))))) && !(has(object.specs) && object.specs.all(s, has(s.ingress) && s.ingress.exists(e, ((has(e.fromEndpoints) || has(e.toPorts)) && e.toPorts.all(p, has(p.rules) && has(p.rules.dns)))))) && !(has(object.specs) && object.specs.exists(s, has(s.ingress) && s.ingress.exists(i, has(i.toPorts) && i.toPorts.exists(p, has(p.rules) && has(p.rules.dns))))) && !(has(object.specs) && object.specs.exists(s, has(s.egress) && s.egress.exists(e, has(e.toPorts) && e.toPorts.exists(p, has(p.rules) && has(p.rules.dns)))))
' resulted in error: no such key: toPorts
```

My expectation is that I can apply this CNP, since it's valid. To me it looks like AKS has its own `ValidatingAdmissionPolicy` which expects `toPorts`, and this now applies my CNPs as well. If this is indeed the case, is there a way to not let the `ValidatingAdmissionPolicy` "interfere" with my own CNPs?

**Comment by swgriffith** [comment]
This is a known issue with a fix in progress. While we wait for the fix to be rolled out, you can mitigate the issue by adding an empty 'toPorts'

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: my-cnp
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - {}
      toPorts:
      - {}
 ```
