### ISSUE TITLE
App Gateway for Containers + Azure CNI Overlay support

### ISSUE THREAD

**Issue by chasewilson** [Azure/AKS#4681]
Azure CNI Overlay does not currently work with Application Gateway for Containers. This removes that limitation and allows App Gateway for Containers to be used with your Azure CNI Overlay Clusters.

**Comment by JoeyC-Dev** [comment]
Will AGC available in all regions? It is still only available in limited regions:
![Image](https://github.com/user-attachments/assets/b46551b8-a1f4-40bb-8348-132d7f695b47)

**Comment by JackStromberg** [comment]
@chasewilson Application Gateway for Containers currently only supports Azure CNI Pod Subnet; both Dynamic and Static allocation.  CNI Overlay is on our short-term roadmap.  Kubenet will not be supported on Application Gateway for Containers, in favor of Azure CNI Overlay when available.

@JoeyC-Dev the list of regions is correct and will continue to be incrementally added over time.

#please-close

**Comment by illrill** [comment]
Eagerly waiting for this one, Azure CNI Overlay with Cilium is the winning network setup in AKS.

**Comment by Harshithraj24** [comment]
Eagerly waiting for this feature, We use self managed karpenter for autoscaling of nodes but Karpenter has a hard requirement of Azure CNI overlay for networking so We are currently not able to use Azure gateway for Containers.

**Comment by franklouwers** [comment]
Why is this ticket closed if it is not released?

**Comment by amithkk** [comment]
Seconding the above comment. is this GA?

**Comment by JackStromberg** [comment]
> is this GA?

No, this is not GA.  We will announce via Azure service updates when available.

**Comment by bongi23** [comment]
Any ETA on this? we would like to user karpenter/NAP but it does work only with Overlay, hence we cannot use it if we use App GW for Containers

**Comment by JackStromberg** [comment]
CNI Overlay for Application Gateway for Containers is planned and well along in development.

We are very aware of this ask and will provide an update once available.  We are just as eager as the community to get this feature released.  If you work through your Microsoft account team to have them reach out to me, I can provide more insight.

Thank you,
Jack

**Comment by JackStromberg** [comment]
Application Gateway for Containers can now seamlessly integrate with AKS clusters using CNI Overlay! 

More details can be found here: [https://aka.ms/agc/overlay](https://aka.ms/agc/overlay)

Cheers!

**Comment by krylop** [comment]
Hi, has anyone managed to get Application Gateway for Containers working with the CNI overlay?
I have tried both ways BYO deployment and managed by ALB controller, but every time "no healthy upstream".

**Comment by JackStromberg** [comment]
BYO VNet with Application Gateway For Containers + CNI Overlay is a valid configuration.  The only gotcha where connectivity does not currently work is if Application Gateway for Containers is in VNET A and the AKS cluster is in VNET B.

What version of ALB Controller are you running as well (please make sure it is 1.5.2)?  Are you in a peered vnet scenario?  Was this a cluster previously running Kubenet/CNI and upgraded to CNI Overlay?  If the cluster was updated, was the configuration working and then you had upgraded to overlay and things stopped?

**Comment by krylop** [comment]
AKS nodes and ALB delegated subnet are in the same VNET, location: West Europe
It's new cluster, Network configuration: Azure CNI Overlay, Network policy: Azure
I'm using alb-controller 1.5.2, pods are running, no errors in logs.
Gateway deployment creates new frontend in AGC, but there is no healthy backends in metrics.

**Comment by JackStromberg** [comment]
CNI Overlay + Application Gateway for Containers + West Europe is a valid configuration.

What do you show as the status on each of the provisioned resources (ApplicationLoadBalancer (if managed scenario), Gateway, HTTPRoute, and any other service specific resources).  In parallel, I'd recommend opening a case so we can gather these details to further troubleshoot.

**Comment by Droppers** [comment]
@krylop no I am not able to get it to work, also getting "no healthy upstream"... I am running into the exact same issues, no errors in log, but also not healthy backends. I am doing a BYO alb deployment though...

**Comment by JackStromberg** [comment]
Unfortunately, peered vnet is not supported at this time.  Out of curiosity, @Droppers are you doing regional or global vnet peering?
https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/container-networking#limitations

**Comment by Droppers** [comment]
My application gateway for containers is deployed to a subnet in the same VNET as my AKS cluster, that should be fine right? I have VNET peering enabled only to access my private cluster from another VNET, not for the application gateway / AKS combination.

How I have configured it:
**ALB**
 - 1 frontend
 - association to /24 subnet as specified

**my-managed-identity**
- Role assignment: AppGwforContainersConfigurationManager to ALB resource group
- Role assignment: NetworkContributor to association subnet

**alb-controller** 
helm install alb-controller oci://mcr.microsoft.com/application-lb/charts/alb-controller --version 1.5.2 --set albController.podIdentity.clientID={my-managed-identity}

**gateway**
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-app
  namespace: ns-gateway
  annotations:
    alb.networking.azure.io/alb-id: {my-application-gateway-for-containers-resource-id}
spec:
  gatewayClassName: azure-alb-external
  listeners:
  - name: http-listener
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All # Same
  addresses:
  - type: alb.networking.azure.io/alb-frontend
    value: {my-frontend-name}
```

**httproute**
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httproute-app
  namespace: ns-app
spec:
  parentRefs:
  - kind: Gateway
    name: gateway-app
    namespace: ns-gateway
  rules:
  - backendRefs:
    - name: svc-app
      port: 80
```
