### ISSUE TITLE
[Feature] Allow configuring the resulting StorageClass name in Container Storage `StoragePool`

### ISSUE THREAD

**Issue by felfa01** [Azure/AKS#4721]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to configure the name that the resulting StorageClass will have when deploying a `StoragePool`. One of my use cases would be to migrate from CSI Drivers to Azure Container Storage without requiring my tenants to update their PVC manifests with a new `StorageClassName`.

This was previously available in the now deprecated apiVersion v1alpha1 under `.spec.poolType.azureDisk.storageClassName`.

**Describe the solution you'd like**

```yaml
apiVersion: containerstorage.azure.com/v1alpha1
kind: StoragePool
metadata:
  name: my-storage-pool-name
  namespace: acstor
spec:
  storageClassName: my-storage-class-name # A new field for setting the resulting StorageClass name
  poolType:
    azureDisk:
      skuName: Premium_LRS
  resources:
    requests:
      storage: 1Ti
```

**Describe alternatives you've considered**
Use the deprecated apiVersion v1alpha1?
