### ISSUE TITLE
Port opened for everyone

### ISSUE THREAD

**Issue by przemolb** [Azure/AKS#474]
Hi,
whan I create the following service:
```
apiVersion: v1
kind: Service
metadata:
  name: some_app
  namespace: app_space
spec:
  loadBalancerIP: X.X.X.X
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: Y
      protocol: TCP
      targetPort: Y
  selector:
    app: some_app
```
this port (Y) becomes open wide - available to everyone. I have to go to the portal GUI and block it in NSG. Is it possible to keep it closed and then open it in NSG (more secure default setting) ?
