### ISSUE TITLE
Error: failed to create containerd container: rootpath on mountPath C:

### ISSUE THREAD

**Issue by nimblenitin** [Azure/AKS#4754]
**Describe the bug**
I am getting error on aks. Is there any workaorund for it?

Error: failed to create containerd container: rootpath on mountPath C:\Windows\SystemTemp\ctd-volume2059323837, volume c:\jsreport: CreateFile C:\Windows\SystemTemp\ctd-volume2059323837\c:: The filename, directory name, or volume label syntax is incorrect.

I am hosting nodejs app on windows node, repeatedly getting above.

Dockerfile-

```
FROM jsreport/jsreport:4.7.0-windowsservercore

WORKDIR /app

COPY .npmrc ./
COPY package.json ./

COPY /shared/customStudioAuthentication.js /app/node_modules/@jsreport/jsreport-authentication/lib/main.js

RUN npm install

COPY . ./

EXPOSE 5488

USER ContainerAdministrator # Or create a custom user as necessary

CMD ["node", "server.js"]
```
```
  volumes:
    - name: jsreport-volume
      hostPath:
        path: C:\jsreport
        type: DirectoryOrCreate
    - name: systemtemp
      hostPath:
        path: C:\Windows\SystemTemp
        type: DirectoryOrCreate

    volumeMounts:
    - mountPath: C:\jsreport
      name: jsreport-volume
    - mountPath: C:\Windows\SystemTemp
      name: systemtemp
```

**To Reproduce**
1. Run command '...'
2. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 -  CLI Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - CLI Extension version [e.g. 1.7.5] if applicable
 - Browser [e.g. chrome, safari] is applicable

**Additional context**
