### ISSUE TITLE
[Feature][ACNS] Add support to enable the Hubble UI through the Azure CLI

### ISSUE THREAD

**Issue by tiesmaster** [Azure/AKS#4768]
**Is your feature request related to a problem? Please describe.**
Although, the Hubble UI can be deployed separately, and is described in [the documentation](https://learn.microsoft.com/en-us/azure/aks/container-network-observability-how-to?tabs=non-cilium#visualize-using-hubble-ui) for Advanced Container Networking Services. The problem is that the deployment of the Hubble UI is very tightly coupled to the deployment of the Hubble Relay, which _is_ controlled by AKS, and this introduces additional maintenance toil on consumers of ACNS.

One thing that we saw, is that the version of the Hubble UI needs to match exactly the version of the manifest from the documentation. It uses v0.12 of the Hubble UI. We've tested with the latest version v0.13, and that broke the Hubble UI (I can provide detailed logs, if needed). Since, `hubble-relay` is managed by the AKS team, it makes sense to have AKS also manage the Hubble UI deployment.

**Describe the solution you'd like**
A flag in the [aks-preview Azure CLI extension](https://learn.microsoft.com/en-us/azure/aks/advanced-container-networking-services-overview?tabs=cilium#install-the-aks-preview-azure-cli-extension) to enable the Hubble UI when enabling Container Network Observability.

**Describe alternatives you've considered**
Installing the Hubble UI via the provided manifest as described above, which _works_ but has the mentioned downsides also described above.

**Additional context**
[This issue](https://github.com/Azure/AKS/issues/3978) is related, but is much broader, as it is also about situations like "BYOCNI", the Hubble Exporter. This request is solely about being able to enable the Hubble UI when AKS is already managing the `hubble-relay`.

**Comment by illrill** [comment]
It would be great if AKS could manage Hubble UI - it's not really that much added maintenance. Below is how I'm installing it myself in [standalone mode](https://docs.cilium.io/en/stable/observability/hubble/hubble-ui/#enable-the-hubble-ui), which I find smoother than using the [installation instructions by Microsoft](https://learn.microsoft.com/en-us/azure/aks/how-to-configure-container-network-logs?tabs=cilium#visualize-by-using-the-hubble-ui).

`helm install cilium cilium/cilium --version 1.15.11 --namespace kube-system`

```yaml
# values.yaml
agent: false
operator:
  enabled: false
cni:
  install: false
hubble:
  enabled: false
  relay:
    enabled: false
    tls:
      server:
        enabled: true
  ui:
    enabled: true
    standalone:
      enabled: true
      # Mount the secret containing the client-side certificate for mTLS communication with Hubble Relay.
      # This secret is already pre-created by AKS as part of the Hubble Relay installation, we just need to mount it.
      tls:
        certsVolume:
          projected:
            defaultMode: 0400
            sources:
              - secret:
                  name: hubble-relay-client-certs
                  items:
                    - key: tls.crt
                      path: client.crt
                    - key: tls.key
                      path: client.key
                    - key: ca.crt
                      path: hubble-relay-ca.crt
    backend:
      image:
        tag: v0.12.3
        useDigest: false
        pullPolicy: Always
    frontend:
      image:
        tag: v0.12.3
        useDigest: false
        pullPolicy: Always
```

Note that I'm using an old version of the Cilium chart and overriding the image tags. This is because the AKS-managed Hubble Relay is an old version v1.15.0, which is not compatible with newer Hubble UI versions. Until Microsoft upgrades Hubble Relay to a newer version, we need to stay on Hubble UI v0.12.3.

IMO, at the very least, the AKS-managed Hubble Relay should be versioned together with the AKS-managed Cilium (follow the same versioning approach as the official Cilium chart).
