### ISSUE TITLE
[BUG] Node Autoprovisioner (NAP) not working with AKS cluster with BYO Vnet

### ISSUE THREAD

**Issue by bongi23** [Azure/AKS#4777]
**Describe the bug**
NAP does not work if I deploy an AKS cluster in my own VNet, e.g. by specifying `--vnet-subnet-id` parameter. Same command without that parameter creates a cluster with a fully functioning NAP

**To Reproduce**

Create a cluster with this command
```
az aks create -n "myCluster" -g "myRg" \
    --node-provisioning-mode Auto \
    --network-plugin azure \
    --network-plugin-mode overlay \
    --network-dataplane cilium \
    --enable-aad --aad-admin-group-object-ids "************************" \
    --api-server-authorized-ip-ranges ***.***.***.***/32 \
    --enable-oidc-issuer \
    --enable-workload-identity \
    --tier "Standard" \
    --nodepool-name system \
    --nodepool-taints CriticalAddonsOnly=true:NoSchedule \
    --node-count 2 \
    --node-vm-size "standard_b2ls_v2" \
    --vnet-subnet-id "/subscriptions/*******/resourceGroups*******/providers/Microsoft.Network/virtualNetworks/myVnet/subnets/mySubnet"
```

Then define a node pool:

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  disruption:
    expireAfter: Never
    consolidationPolicy: WhenUnderutilized
  limits:
    cpu: 32
    memory: 64Gi
  weight: 100
  template:
    spec:
      nodeClassRef:
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"] # arm64
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"] # spot
        - key: karpenter.azure.com/sku-family
          operator: In
          values: [D]
        - key: karpenter.azure.com/sku-cpu
          operator: In
          values: ["2", "4", "8"]
        - key: karpenter.azure.com/sku-version
          operator: Gt
          values: ["4"]
```

And launch some pods: ` kubectl create deployment nginx --image=nginx --replicas=30`

**Expected behavior**
VMs should be created, they shuold join the cluster and nginx pod should be deployed within a minute or so. Instead of this, nothing happens

**Environment (please complete the following information):**
 -  CLI Version 2.68.0 with aks-preview 13.0.0b2
 - Kubernetes version 1.30.7
