### ISSUE TITLE
[BUG] Istio Proxy Metadata Setting Quotation Marks are needed

### ISSUE THREAD

**Issue by jonas-budde** [Azure/AKS#4799]
**Describe the bug**
This issue is about the service-mesh addon for istio and the configuration of the proxyConfig.
When configuring the parameter "EXIT_ON_ZERO_ACTIVE_CONNECTIONS" the setting would only work if the value is set to "true" in quotation marks.

The config:
```yaml
"accessLogFile": "/dev/stdout"
"defaultConfig":
  "holdApplicationUntilProxyStarts": true
  "proxyMetadata":
    "EXIT_ON_ZERO_ACTIVE_CONNECTIONS": "true"
```

**To Reproduce**
Use the Config from above.

**Expected behavior**
The config should be able to use a bool and not a string. (true, not "true")
It should be the same behavior as holdApplicationUntilProxyStarts.

**Environment (please complete the following information):**
 - istio asm-1-22 revision
 - aks 1.29.5

**Additional context**
I know that the [proxyMetadata Block](https://learn.microsoft.com/en-us/azure/aks/istio-meshconfig#proxyconfig-meshconfigdefaultconfig) block is currently only “allowed”, but I still wanted to inform about this wrong behavior.
