### ISSUE TITLE
no kind "CustomResourceDefinition" is registered

### ISSUE THREAD

**Issue by ivalexa** [Azure/AKS#482]
Unable to create a new CustomResourceDefinition, getting error:

> error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1"

**Details:**
When creating a new crd, using the code snippet below. it fails:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  version: v1
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
```
 kubectl logs crd/crontabs.stable.example.com:
`error: no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1"`
Version: AKS v1.10.3
