### ISSUE TITLE
[BUG] Unable to mount deprecated Azure file in-tree volume from kubernetes 1.32

### ISSUE THREAD

**Issue by MichalMeszaros** [Azure/AKS#4821]
**Describe the bug**

For the kubernetes version 1.32.0 there is issue to mount azure fileshares. Pod will not be started with this error

MountVolume.SetUp failed for volume "VOLUME_NAME" : kubernetes.io/csi: mounter.SetUpAt failed to get service accoount token attributes: failed to fetch token: serviceaccounts "SERVICE_ACCOUNT_NAME" is forbidden: audience "api://AzureADTokenExchange" not found in pod spec volume

**To Reproduce**

Create any PV for example:
```yaml
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: "test"
  spec:
    accessModes:
      - ReadOnlyMany
    capacity:
      storage: 1Gi
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ""
    claimRef:
      name: test
      namespace: test
    azureFile:
      shareName: test
      secretNamespace: kube-system
      secretName: "azure-storage-account-test-secret"
      readOnly: false
    mountOptions:
    - dir_mode=0777
    - file_mode=0444
    - uid=5000
    - gid=5000
    - cache=strict
    - nosharesock
    - actimeo=30
```

and try to mount in to any pod

**Expected behavior**

kubernetes will start pod that will have mounted fileshare with name test from the specific sotrageaccount

**Environment (please complete the following information):**

- Kubernetes version 1.32.0

**Additional context**
Exactly same configuration work as is on the aks with kubernetes version of 1.31.5
