### ISSUE TITLE
Cannot create Persistent Volume In newly provisioned AKS Cluster

### ISSUE THREAD

**Issue by cwoolum** [Azure/AKS#485]
I created a new Azure AD RBAC enabled AKS cluster in US West using [these](https://docs.microsoft.com/en-us/azure/aks/aad-integration#create-rbac-binding) instructions.  The issue I'm running into is that I'm not able to add any persistent volumes. They just get stuck at the pending status.  Below is an example of a Persistent Volume I tried to add.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-premium
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

I'm starting to think it might be a permissions issue but my Client Application has contributor permissions for both the RG that the cluster is provisioned in as well as the MC_ group created by the cluster. What's the best way to further debug this?

Thanks,
Chris
