### ISSUE TITLE
[BUG] Application Gateway For Containers Default Health Probe does not understand named ports

### ISSUE THREAD

**Issue by pinkfloydx33** [Azure/AKS#4861]
**Describe the bug**
Application Gateway for Containers will use a default health probe based on (amongst other things) the target pod's `readinessProbe`. If the readiness probe uses a named port rather than a numeric one, then the built-in policy fails requiring you to create a custom `HealthCheckPolicy`.

Changing the port target to be numeric will correct the issue. 

**To Reproduce**

Have a readiness probe on the pods behind the target service using a named port, such as:

```yaml
containers:
 - name: my-container
   ports:
   - name: health
     containerPort: 8090
     protocol: TCP
   readinessProbe:
     httpGet:
       path: /healthz/ready
       port: health  # <------------- uses port name
       scheme: HTTPS
       httpHeaders:
       - name: Host
         value: localhost
```

Create a `Service` pointing to pod containing the above container as well as an `HTTPRoute` using that `Service`. Observe that traffic does not flow because there are no healthy upstreams

**Expected behavior**
The upstream should be healthy, because there is a readiness probe defined, even if it uses a named port.

**Environment (please complete the following information):**

- Kubernetes version 1.30.9

**Additional context**

If it matters, the target application is accepting traffic over TLS1.2 and TLS1.3 with a self-signed certificate on the health check port/routes. If the traffic is _only_ served over TLS1.3 then all health probes will fail even if port _numbers_ or a custom policy are used .
