### ISSUE TITLE
[BUG] AGC with Gateway API does not work with two gateways

### ISSUE THREAD

**Issue by starteNCS** [Azure/AKS#4864]
**Describe the bug**

I am using the Application Gateway for Containers with the kubernetes Gateway API and try to implement the cert-manager. As with this bug: #4758 i created two gateways with two frontends in AGC: one already set up with all my routes and one with just the http-listener for the cert-manager:

This is my gateway with all the applications:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.networking.azure.io/alb-id: {{ .Values.alb.id }}
    cert-manager.io/cluster-issuer: {{ .Values.certs.issuer }}
spec:
  gatewayClassName: azure-alb-external
  listeners:
    - name: grafana-listener
      port: 443
      protocol: HTTPS
      hostname: grafana.{{ .Values.hostname }}
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: grafana-tls-secret
        mode: Terminate
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
        namespaces:
          from: All
    - name: argo-listener
      port: 443
      protocol: HTTPS
      hostname: argo.{{ .Values.hostname }}
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: argo-tls-secret
        mode: Terminate
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
        namespaces:
          from: All
    - name: app-listener
      port: 80
      protocol: HTTP
      hostname: app.{{ .Values.hostname }}
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
            group: gateway.networking.k8s.io
        namespaces:
          from: All
  addresses:
    - value: cluster-frontend
      type: alb.networking.azure.io/alb-frontend
```

and this is the gateway with just the cert-manager http-listener:

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cert-manager-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.networking.azure.io/alb-id: {{ .Values.alb.id }}
    cert-manager.io/cluster-issuer: {{ .Values.certs.issuer }}
spec:
  gatewayClassName: azure-alb-external
  listeners:
    - name: http-listener
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
  addresses:
    - value: cert-manager-cluster-frontend
      type: alb.networking.azure.io/alb-frontend
    - value: argo.{{ .Values.hostname }}
      type: Hostname
    - value: grafana.{{ .Values.hostname }}
      type: Hostname
```

Now the problem is, that every route from the `cert-manager-gateway` returns just a 200 OK with no body. Even if I add a http listener for an app (i.e. argocd) (which does work on the `gateway` gateway!). Both the `cert-manager-gateway` and the HTTPRoutes from cert-manager have the "Application Gateway for Containers resource has been successfully updated." condition.

From my point of view i think the gateways are the same and should both work? Is it not supported to have two frontends in one cluster?
