### ISSUE TITLE
[BUG] Gitops (Flux) source controller can't pull helm chart from OCI registry after upgrade Gitops extension 1.6.1

### ISSUE THREAD

**Issue by Bastichou** [Azure/AKS#4900]
**Describe the bug**

We are using Flux with AKS Extension to provision Flux controller in ou AKS cluster.

The GitOps extension has been updated from 1.15.1 to 1.16.1

Azure extension triggered the upgrade of our Flux to the latest version 2.5.1.
Since the upgrade we have an issue with the source-controller while pulling Helm chart in OCI repository:

For all OCI Helm repository I got:
`failed to construct Helm client: /dev/null/.config/helm/registry/config.json: stat /dev/null/.config/helm/registry/config.json: not a directory
`

I fixed the issue manually adding an extra env vars:
```yaml
 - name: DOCKER_CONFIG                                                                                                                                                                                                                                              
   value: /tmp/.docker/config.json  
```

Then for a few others OCI repository (like Karpenter) I had another issue:
`failed to construct Helm client: /dev/null/.config/helm/registry/config.json: stat /dev/null/.config/helm/registry/config.json: not a directory
`

Fixed by adding
```yaml
  - name: HELM_CONFIG_HOME
    value: /tmp/.config/helm
```

I think I could add the HOME environment variable to fix both of the issues.

Not sure what is happening, I quickly review CHANGELOG and I couldn't find any reference to the Gitops/Flux extension.


**Environment (please complete the following information):**

- Kubernetes version 1.31.3
- Flux extension 1.16.1

**Additional context**

Here one exemple the Helmrepository object:

```yaml
apiVersion: v1
items:
- apiVersion: source.toolkit.fluxcd.io/v1
  kind: HelmRepository
  metadata:
    labels:
      kustomize.toolkit.fluxcd.io/name: backbone-configs
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: bitnami-charts
    namespace: ingress-internal
  spec:
    interval: 2h
    provider: generic
    type: oci
    url: oci://registry-1.docker.io/bitnamicharts
```

Here the manifest of the source-controller deployed by Azure:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: flux
    meta.helm.sh/release-namespace: flux-system
  creationTimestamp: "2024-12-11T10:15:24Z"
  generation: 3
  labels:
    app.kubernetes.io/component: source-controller
    app.kubernetes.io/instance: flux
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: microsoft.flux
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.5.1
    azure.workload.identity/use: "true"
    clusterconfig.azure.com/extension-version: 1.16.1
    control-plane: controller
  name: source-controller
  namespace: flux-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: source-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: source-controller
        app.kubernetes.io/name: microsoft.flux
        azure.workload.identity/use: "true"
    spec:
      containers:
      - args:
        - --events-addr=http://notification-controller.$(RUNTIME_NAMESPACE).svc.cluster.local./
        - --watch-all-namespaces=true
        - --log-level=info
        - --log-encoding=json
        - --enable-leader-election
        - --storage-path=/data
        - --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
        - --helm-cache-max-size=20
        - --helm-cache-ttl=1h
        - --helm-cache-purge-interval=10m
        - --concurrent=2
        - --requeue-dependency=30s
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DOCKER_CONFIG # Manually added and fixing the issue
          value: /tmp/.docker/config.json # Manually added and fixing the issue 
        image: mcr.microsoft.com/oss/v2/fluxcd/source-controller:v1.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthz
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 8080
          name: http-prom
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1337
      serviceAccount: source-controller
      serviceAccountName: source-controller
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
```
