### ISSUE TITLE
[BUG] in-tree azure file PVC don't mount and pod hangs on

### ISSUE THREAD

**Issue by rogelioamancisidor** [Azure/AKS#4947]
**Describe the bug**

When mounting PVC to the Pod the volume will not mount and it will hang on

**To Reproduce**
1. Create Azure cluster with Kubernetes 1.32.0
2. Create PV claim

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
```
3. Create Pod and mount PVC

**Expected behavior**
Volume mounted successfully with Pod running.

**Environment:**

- Kubernetes version: 1.32.0

**Error Message**
```
Type     Reason       Age                From     Message
  ----     ------       ----               ----     -------
  Warning  FailedMount  16s (x7 over 48s)  kubelet  MountVolume.SetUp failed for volume "azurefile" : kubernetes.io/csi: mounter.SetUpAt failed to get service accoount token attributes: failed to fetch token: serviceaccounts "default" is forbidden: audience "api://AzureADTokenExchange" not found in pod spec volume
```

**Comment by rogelioamancisidor** [comment]
When is the kubernetes version `1.32.2` available for `westeurope`? I think that patch fixes the problem

**Comment by andyzhangx** [comment]
@rogelioamancisidor pls use `provisioner: file.csi.azure.com` in storage class, the in-tree driver is already deprecated.

**Comment by rogelioamancisidor** [comment]
I guess I need to migrate from in-tree storage to CSI drivers, right?. Is it a way to confirm that my cluster is actually using in-tree storage before I attempt to move to CSI?

**Comment by philwelz** [comment]
Step 2 means just that you can create a StorageClass tailored to your needs (the file options) with provisioner set to `file.csi.azure.com` or use one of the default ones which are created by the csi-driver. So if you good with the default storage classes for Azure Files  you can proceed with Step 3.

**Comment by jeffpatt24** [comment]
> [@andyzhangx](https://github.com/andyzhangx) I guess I need to migrate from in-tree storage to CSI drivers, right?. Is it a way to confirm that my cluster is actually using in-tree storage before I attempt to move to CSI?
> 
> My `storageclass` has the provisioner set to `file.csi.azure.com`. Do I need to follow these [steps](https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-file-share-volumes) skipping step 2?

In your steps to reproduce, the storage class is using the in-tree driver (provisioner: kubernetes.io/azure-file). Let us know if you encounter any issues when following the [steps](https://learn.microsoft.com/en-us/azure/aks/csi-migrate-in-tree-volumes#migrate-file-share-volumes) to migrate from in-tree to Files CSI driver.

**Comment by rogelioamancisidor** [comment]
@jeffpatt24  Sorry for the confusion, but I thought that the link that I provided was exactly the same problem that I am facing. I found the manifest that was used to create the `StorageClass` (I uptated it above now), and it actually uses `provisioner: file.csi.azure.com`. In addition, my output of  `kubectl describe storageclass azurefile` is this:

```
Name:            azurefile
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"azurefile"},"mountOptions":["dir_mode=0777","file_mode=0777","uid=1000","gid=1000","mfsymlinks","nobrl","cache=none"],"parameters":{"skuName":"Standard_LRS"},"provisioner":"file.csi.azure.com"}

Provisioner:           file.csi.azure.com
Parameters:            skuName=Standard_LRS
AllowVolumeExpansion:  True
MountOptions:
  dir_mode=0777
  file_mode=0777
  uid=1000
  gid=1000
  mfsymlinks
  nobrl
  cache=none
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```

**Comment by andyzhangx** [comment]
@rogelioamancisidor you need to migrate both in-tree storage classes and persistent volumes, here is an example of deprecated in-tree pv, it contains `spec.azureFile` field. and you only need to make sure `volumeHandle` is unique, you could set like this `volumeHandle: {resource-group-name}#{account-name}#{file-share-name}`

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: default
    shareName: aksshare
    readOnly: false
```
