### ISSUE TITLE
[BUG] Azure Container Storage - ZRS volume creation is not working properly.

### ISSUE THREAD

**Issue by frank-m** [Azure/AKS#4979]
**Describe the bug**

If this documentation is followed: https://learn.microsoft.com/en-us/azure/storage/container-storage/enable-multi-zone-redundancy#use-zone-redundant-storage-zrs-disks

Instead of creating a single zrs volume, it will create three zrs volumes divided over the three zones. 

**To Reproduce**
- Install Container Storage on a zone-redundant node pool
- Create a Storagepool like this:
```
apiVersion: containerstorage.azure.com/v1
kind: StoragePool
metadata:
  name: azuredisk
  namespace: acstor
spec:
  poolType:
    azureDisk:
      skuName: Premium_ZRS
  resources:
    requests:
      storage: 100Gi
```
- Now three ZRS volumes of 33Gi are created, each in one zone.

![Image](https://github.com/user-attachments/assets/398cdbb9-c8f9-4116-a9ab-7f9077f26317)

- If you describe the object, you see that it has zones configured:
```
Spec:
  Pool Type:
    Azure Disk:
      Sku Name:    Premium_ZRS
  Reclaim Policy:  Delete
  Resources:
    Requests:
      Storage:  100Gi
  Zones:
    1
    2
    3
```

**Expected behavior**
A single ZRS volume gets created of 100Gi. This is also what the documentation describes. Instead it seems it creates a volume in each zone to let the application handle redundancy.

But what happens is three zrs volumes get created. One in each zone. 

**Screenshots**
If applicable, add screenshots to help explain your problem. Make sure not to include sensitive or personal information.

**Environment (please complete the following information):**

- CLI Version [e.g. 3.22]: 
```
❯ az version
{
  "azure-cli": "2.70.0",
  "azure-cli-core": "2.70.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "k8s-configuration": "2.2.0"
  }
}
```
- Kubernetes version: 1.31.5

**Additional context**
I can of course add a single zone, but what happens when a zone fails in that case?

**Comment by frank-m** [comment]
Update to the above. If you try to create the volume with zones specified as an empty list:

```
apiVersion: containerstorage.azure.com/v1
kind: StoragePool
metadata:
  name: azuredisk
  namespace: acstor
spec:
  zones: [""]
  poolType:
    azureDisk:
      skuName: Premium_ZRS
  resources:
    requests:
      storage: 1Ti
```

You get the following error:

`The StoragePool "azuredisk" is invalid: Zones: Invalid value: []string{""}: Cannot specify no zones on zoned nodepools`
