### ISSUE TITLE
Cluster-user can't access to AKS cluster with RBAC enabled

### ISSUE THREAD

**Issue by mleneveut** [Azure/AKS#505]
We followed this procedure to enable RBAC in our 1.10.3 AKS : https://docs.microsoft.com/en-us/azure/aks/aad-integration#access-cluster-with-azure-ad

We did the procedure with a global admin account, as with a "normal" admin it was not working.

We can access the cluster as a cluster-admin : 
  * az aks get-credentials --resource-group myAKSCluster --name myAKSCluster --admin
  * kubectl get nodes
  * set the provided code in the Azure device login page
  * get the nodes details : OK

But for a normal user : 
  * az aks get-credentials --resource-group myAKSCluster --name myAKSCluster
  * kubectl get nodes
  * set the provided code in the Azure device login page
  * Error : we don't recognize your code

We tried with kubectl get nodes --v=9 but it displays no log after the "we don't recognize your code" error.

The user trying to login is "member" in the AAD, we even gave him the "Contributor" role on the resource group of the AKS. Still not working.

We tried tips of https://github.com/MicrosoftDocs/azure-docs/issues/10326 and #478 : 
  * Global admin : checked
  * Click Grant permissions button : checked
  * Client app is native : checked
  * Member account : checked
  * private AD account 'me@myprivatetenant.onmicrosoft.com' : checked

Reading this comment (https://github.com/Azure/AKS/issues/439#issuecomment-397782517) I tried adding a RoleBinding before his login. But same issue. 

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yre-role
  namespace: yre
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["deployments", "replicasets", "pods", "pods/status", "pods/logs", "services", "ingresses", "configmaps", "daemonsets", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "extensions", "apps"]
    resources: ["services", "ingresses", "configmaps", "secrets"]
    verbs: ["create", "update", "delete", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yre-role-binding
  namespace: yre
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "yre@mycompany.onmicrosoft.com"
    namespace: yre
roleRef:
  kind: Role
  name: yre-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yre-dashboard-role-binding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: "yre@mycompany.onmicrosoft.com"
roleRef:
  kind: Role
  name: user-dashboard-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-dashboard-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["services/proxy"]
    verbs: ["get"]
```

The only difference seems that working admin users have the "client application" with the role "Default access" in their "Applications" (in their AAD user's profile). But I think it has been automatically added when we logged in and gave our consent.

Do we have to manually edit the manifest ? The oauth2Permissions part ?

Any help will be appreciated :)
