### ISSUE TITLE
AKS RBAC seems to have stopped working for AD Group bindings. (Forbidden error)

### ISSUE THREAD

**Issue by MarkTopping** [Azure/AKS#515]
Hi.

Summary:
Newly provisioned 1.10.3 clusters (which exactly replicate a existing 1.10.3 clusters) forbid user to interact with AKS resources when Cluster Role Bindings are setup using Azure AD Groups. Everything works fine when the same users are added to the bindings individually as Users. Authentication works correctly in both cases (via the AD Server/Client App Registrations), but authorisation seems to be an issue.

Error Message:
Error from server (Forbidden): pods is forbidden: User "removed@account.onmicrosoft.com" cannot list pods in the namespace "default"

To be clear the user is within a group configured as a cluster-admin. The issue here is not the namespace.

__Working (subject type: User)__
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: individual-users-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "usersemail@account.onmicrosoft.com"
```

__No longer working (subject type: Group)__
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sorted_react_prod_admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "Azure-AD-Group-Name"
```

More Detail:
Approximately 2 weeks ago I built two RBAC-enabled clusters using AKS Version: 1.10.3. Cluster Role Bindings where provisioned which linked up to several Azure Active Directory Groups and everything worked fine. Unfortunately I needed to alter the Service Principle these ran under so it become necessary to tear them down and re-build.

So, yesterday I re-provisioned my clusters and did so using the same scripts I'd generated for building them up first time round - this includes cluster creation and the cluster role bindings setup. The only thing I changed in my scripting was that I altered my parameters.json file to take account of the new Service Principle credentials (I create my clusters using the acs-engine and resource templates).

There were also a couple of steps in the whole process which I did not repeat. That is I did not re-create my Azure AD Groups, and I did not create new AD Server/Client App Registrations. I expect to leverage the fact these are already in place. 

As such, my new cluster use the same AppServerId, ClientServerId, and ServerApplicationSecret as the initial clusters did, and to repeat/confirm, I can successfullly authenticate via https://login.microsoftonline.com/common/oauth2/deviceauth and the code provided when I run aks get-credentials.

To experiment I also created a new AD Group and gave that group cluster-admin. Members of the group where still forbidden to access resources.

Note that the users in my AD Groups are NOT guest accounts. Been there and tackled that one previously.
