### ISSUE TITLE
Heapster missing rbac roles for kube-system namespace

### ISSUE THREAD

**Issue by devkws** [Azure/AKS#520]
With a new rbac cluster heapster is constantly throwing missing role errors for kube-system namespace.

``
deployments.extensions "heapster" is forbidden: User "system:serviceaccount:kube-system:heapster" cannot update deployments.extensions in the namespace "kube-system"
``

**Comment by devkws** [comment]
An update: after some digging, running the following rbac yaml fixes the issue. It is my opinion that this should be run by Microsoft during the creation of the heapster deployment.

https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/rbac/heapster-rbac.yaml

**Comment by weinong** [comment]
@benjamingorman can you send your resource ID to aks-help@service.microsoft.com and reference this issue please?

**Comment by benjamingorman** [comment]
The workaround I found was this:

`$ kubectl edit clusterrole system:heapster`

Then change the `extensions` apiGroups block, adding a new verb `update`:

```yaml
rules:
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update # add this 
```
