### ISSUE TITLE
Unable to create PersistentVolumeClaims in RBAC enabled cluster

### ISSUE THREAD

**Issue by jsteenbeek** [Azure/AKS#525]
When creating an RBAC enabled cluster, the Service Account persistent-volume-binder is not granted permissions on the Secrets store. This permission is required when creating a PersistentVolumeClaim on an Azure file share.

1. Create a cluster with RBAC
`az aks create -n myname -g myrg --node-count 1 --enable-rbac`

2. Create a file share
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  location: westeurope
  storageAccount: mystorage
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfile
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
```

3. Note the provisioning of the PersistentVolumeClaim gets stuck on 'pending'
```
PS C:\> kubectl describe pvc
Name:          myfile
Namespace:     default
StorageClass:  azurefile
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"azurefile"},"name":"myfile...
               volume.beta.kubernetes.io/storage-class=azurefile
               volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/azure-file
Finalizers:    []
Capacity:
Access Modes:
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  13m   persistentvolume-controller  Failed to provision volume with StorageClass "azurefile": Couldn't create secret secrets is forbidden: User "system:serviceaccount:kube-system:persistent-volume-binder" cannot create secre
ts in the namespace "default"
```

I solved this for me by granting the persistent-volume-binder the cluster-admin role (which is a bit much):

**Edit** Do not do this. Check role creation and binding by andyzhangx below

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: persistent-volume-binder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: persistent-volume-binder
    namespace: kube-system
```

I think this is a bug, but I could also easily missed some logical config step.

**Comment by jalberto** [comment]
I have same problem in AKS 1.10, probably related to: https://github.com/kubernetes/kubernetes/issues/59543
maybe @andyzhangx can help :)

**Comment by jalberto** [comment]
thanks @andyzhangx, your previous workaroudn did work well, I don't know if is a good idea to remove previous workaroudn to add new one while there is alreadt PVCs running.

It seems there is not mechanism or process to sync bugfixes between ACS & AKS and that causes lot of back and forth and noise. I suggest to take care of this too.

**Comment by andrewcole** [comment]
thanks @andyzhangx this workaround worked for me too

**Comment by przemolb** [comment]
Does @andyzhangx solution work as well if I create everything in namespaces ?

**Comment by andyzhangx** [comment]
@przemolb yes, go ahead

**Comment by przemolb** [comment]
How does that differ to https://bugzilla.redhat.com/show_bug.cgi?id=1575933#c10 ?

**Comment by andyzhangx** [comment]
@przemolb it's same issue

**Comment by przemolb** [comment]
But a bit different approach, isn't it ?

**Comment by stijnbrouwers** [comment]
@przemolb , @andyzhangx 's solution worked for me in a custom namespace.
Thanks @andyzhangx !

**Comment by aglorei** [comment]
Is there any traction on getting this fixed?

**Comment by andyzhangx** [comment]
@aglorei you still need to run `kubectl create -f https://raw.githubusercontent.com/andyzhangx/Demo/master/acs-engine/rbac/azure-cloud-provider-deployment.yaml` on AKS before creating azure file pvc

**Comment by andyzhangx** [comment]
@aglorei we are fixing it.

**Comment by yvan** [comment]
1 - am i correct to infer that the official recommendation is to use the v1beta api? is this api stable?
 
2 - i tried following this suggestion; azurefile PVCs are still stuck in a 'Pending' state.

3 - is there a good reason this role should be a clusterrole and not a role?

pvc: 

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyterhub-shared
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

storage class:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  storageAccount: STORAGE_ACCT
```

clusterrole and clusterrolebinding:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: system:azure-cloud-provider
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
```

kubectl version output:
```sh
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
