### ISSUE TITLE
ILB Frontend IP configuration does not changes while updating service

### ISSUE THREAD

**Issue by di9383** [Azure/AKS#532]
AKS version 1.8.7

How to re-produce:

AKS service is created using .yaml manifest. ILB is described as it is shown in the documentation:

```
annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
  type: LoadBalancer
  loadBalancerIP: 10.240.200.2
```
ILB instance with the "kubernetes-internal" name is created with a correct private IP address pointing to the service described. If I change the "loadBalancerIP" to another internal IP address and re-deploy the service, the last is deployed with the correct new IP address, but "kubernetes-internal" ILB still has the old Frontend IP configuration.
