### ISSUE TITLE
Intermitent Problem - CreatingLoadBalancerFailed

### ISSUE THREAD

**Issue by ErickWendel** [Azure/AKS#537]
**What happened**:
Error to expose Services as LoadBalacer type

`kubectl describe svc mongodb`
```
  Normal   EnsuringLoadBalancer        4s (x4 over 44s)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  3s (x4 over 40s)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service default/mongodb-svc: timed out waiting for the condition
```
`kubectl get svc `
`mongodb-svc                 LoadBalancer   10.0.208.59    <pending>        27018:32303/TCP`

**What you expected to happen**:

Generate Ip Addes LoadBalancer
**How to reproduce it (as minimally and precisely as possible)**:
```yaml
#svc.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    name: mongodb
spec:
  type: LoadBalancer
  ports:
  - port: 27018
    targetPort: 27017
  # clusterIP: None
  selector:
    role: mongodb
---
```
`kubectl create -f svc.yaml`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```sh
kubectl version --short
Client Version: v1.10.2
Server Version: v1.9.9
```
- Size of cluster (how many worker nodes are in the cluster?)
 `3`
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
`Node.js apps and Databases (RabbitMQ, MongoDB)`
- Others:
