### ISSUE TITLE
[Question] Auto assign DNS name label on generated public ip resource

### ISSUE THREAD

**Issue by northtyphoon** [Azure/AKS#538]
I deployed an nginx ingress. k8s auto created a static public ip resource in MC_* resource group and use the ip for the load-balance. 

Now I want to configure the public ip as a traffic manager endpoint but it requires the public ip has DNS name label.

Is it possible to let k8s auto assign a DNS name label (eg, random guid or based on annotation) on the public ip?

**Comment by neumanndaniel** [comment]
Don't use Azure endpoint as type for the Traffic Manager endpoint. Just switch to external endpoint and you can specify the public ip without having a DNS name label for it.

**Comment by northtyphoon** [comment]
Thanks @neumanndaniel . If I remove the nginx deployment from k8s, will the external endpoint be auto-removed from the traffic manager? If I use Azure endpoint, it is auto-removed.

**Comment by weinong** [comment]
try this
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: myservice
```
This [PR](https://github.com/php-coder/kubernetes/commit/e686b634654e4d74aeb4b245899d6ebcc1485b85) implemented this.
