### ISSUE TITLE
Automate login to AAD-enabled AKS cluster

### ISSUE THREAD

**Issue by timwebster9** [Azure/AKS#556]
**What happened**:  After logging in as a service principal, running `kubectl ...` again prompts for login.

**What you expected to happen**: As I'm already logged in, it shouldn't prompt for a second login.  I had to login as myself (the cluster admin) and therefore could access everything, instead of only the restricted namespace as intended.

**How to reproduce it (as minimally and precisely as possible)**:  Follow these docs: https://docs.microsoft.com/en-us/azure/aks/aad-integration

Then create a Role/RoleBinding mapping the SP to the role. e.g. 

```
apiVersion: v1
kind: Namespace
metadata:
  name: devteam1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devteam1-role
  namespace: devteam1
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devteam1-rolebinding
subjects:
- kind: User
  name:  <SP APP ID>
  namespace: devteam1
roleRef:
  kind: Role
  name: devteam1-role 
  apiGroup: rbac.authorization.k8s.io
```

Then login as the service principal and get the config:

`az aks get-credentials --resource-group <resource group> --name <cluster name?`

Then run `kubectl <some command>`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5
- Size of cluster (how many worker nodes are in the cluster?): 3

I appreciate that this might not be supported/tested yet, but is it something that should in theory be possible?  The use case would be automating login from an external application (e.g. a Jenkins CI server), and restricting resources to only those that the rolebinding for the SP would allow.
