### ISSUE TITLE
addon-http-application-routing options documentation

### ISSUE THREAD

**Issue by timmydo** [Azure/AKS#564]
I'm using ingress with addon-http-application-routing. Sample config below. Are there a list of documented options/annotations anywhere? I'm trying to disable port 80/http because I only want to serve over 443 with my host names (the allow-http option doesn't seem to exist). Thanks

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: ppe-ingress
    envtype: ppe
  name: ppe-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - hosts:
      - ppe2.xxx.microsoft.com
      secretName: tls-prod-cert
  rules:
    - http:
        paths:
        - path: /api/config
          backend:
            serviceName: configapi-prod
            servicePort: 80
        - backend:
            serviceName: platform-prod
            servicePort: 80

```
