### ISSUE TITLE
LoadBalancer network connection problem - IP assigned but not reachable

### ISSUE THREAD

**Issue by zixo** [Azure/AKS#591]
**What happened**:

Some LoadBalancer endpoints in VNET are not reachable. 

For debugging purposes I created test VM in the same subnet with IP 10.8.17.4.

```
# nc 10.8.17.5 80 -v
Connection to 10.8.17.5 80 port [tcp/http] succeeded!
# nc 10.8.17.6 80 -v
nc: connect to 10.8.17.6 port 80 (tcp) failed: Connection timed out
```

kubectl get svc -n test
```
service/svc1-lb     LoadBalancer   10.0.79.36    10.8.17.6      80:31265/TCP      20m
service/svc2-lb     LoadBalancer   10.0.255.24   10.8.17.5      80:30033/TCP      20m
```

services.yaml
```
---
apiVersion: v1
kind: Service
metadata:
  name: svc2-lb
  namespace: test
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-subnet2-lb"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.8.17.5
  ports:
    - port: 80
  selector:
    app: svc2
---
apiVersion: v1
kind: Service
metadata:
  name: svc1-lb
  namespace: test
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-subnet2-lb"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.8.17.6
  ports:
    - port: 80
  selector:
    app: svc1
```
Same behavior without **service.beta.kubernetes.io/azure-load-balancer-internal-subnet** or  static assignment.

**Environment**:
There is not problem with RBAC, IPs are normally assigned. Pods are listening.
- Kubernetes version 
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Size of cluster 
 1x Standard A8 v2 (8 vcpus, 16 GB memory)

VNET is from different RG, but aks RG has Contributor role for VNET.
