### ISSUE TITLE
Get non-AAD credentials from a AAD-enabled Kubernetes cluster setup

### ISSUE THREAD

**Issue by schroedan** [Azure/AKS#600]
**What happened**:
* we try to setup an automated CI workflow with Travis CI and an Azure Kubernetes cluster setup with enabled AAD integration
* we try to use the login credentials from `az aks get-credentials --resource-group <resource-group> --name <name> -f -` which returns:
```yaml
# ...
users:
- name: <username>
  user:
    auth-provider:
      config:
        apiserver-id: <apiserver-id>
        client-id: <client-id>
        tenant-id: <tenant-id>
      name: azure
```
* but these credentials are incompatible to a sane automated workflow because a user interaction is necessary: in order to get the access/refresh tokens a user must open the login page and paste the provided code into the form and press the submit button and so on

**What you expected to happen**:
* `az aks get-credentials --resource-group <resource-group> --name <name> -f -` returns:
```yaml
# ...
users:
- name: <username>
  user:
    token: <user-token>
```
as `az aks get-credentials --resource-group <resource-group> --name <name> -a -f -` does but without the admin privileges

**How to reproduce it (as minimally and precisely as possible)**:
```bash
kubectl config set-cluster ${KUBE_CLUSTER_NAME} \
    --server=${KUBE_CLUSTER_SERVER} \
    --certificate-authority=${HOME}/kube_ca.crt --embed-certs=true

## Token authentication does not work with Azure
#kubectl config set-credentials ${KUBE_USER} \
#    --token=${KUBE_TOKEN}

kubectl config set-credentials ${KUBE_USER} \
    --auth-provider=azure \
    --auth-provider-arg=environment=AzurePublicCloud \
    --auth-provider-arg=client-id=${KUBE_AZURE_CLIENT_ID} \
    --auth-provider-arg=tenant-id=${KUBE_AZURE_TENANT_ID} \
    --auth-provider-arg=apiserver-id=${KUBE_AZURE_APISERVER_ID}

kubectl config set-context ${KUBE_CONTEXT} \
    --cluster=${KUBE_CLUSTER_NAME} \
    --user=${KUBE_USER} \
    --namespace=${KUBE_NAMESPACE}

kubectl config use-context ${KUBE_CONTEXT}

kubectl get nodes
```

**Anything else we need to know?**:
* The following constellation seem to work but we did not verify if the privileges are the correct ones (admin or user) for now:
```yaml
# ...
users:
- name: <username>
  user:
    client-certificate-data: <admin-client-certificate-data>
    client-key-data: <admin-client-key-data>
    token: <user-token>
```
The `admin-client-certificate-data` and `admin-client-key-data` was taken from `az aks get-credentials --resource-group <resource-group> --name <name> -a -f -`.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.1
