### ISSUE TITLE
Is it possible to create an Internal Load Balancer with one front-end IP + multiple ports?

### ISSUE THREAD

**Issue by msdotnetclr** [Azure/AKS#602]
**What happened**:
In an AKS cluster version 1.10.5, I already have a service "myapp" exposed on port 30443 in "default" namespace via an internal load balancer. The load balancer has IP address 10.201.102.253. Our DNS record points to a FQDN like myapp.company.domain to this IP address. We use https://myapp.company.domain:30443 to access this service.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.201.102.253
  ports:
  - port: 30443
    targetPort: 8443
    name: https
  selector:
    app: myapp
```

Later on I wanted to expose the same service - in a different namespace (say "development") - on port 30444, via the same internal load balancer IP address, so we could use https://myapp.company.domain:30444 to visit another instance of the service.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.201.102.253
  ports:
  - port: 30444
    targetPort: 8443
    name: https
  selector:
    app: myapp
```

When the second service was created, it got stuck on "CreatingLoadBalancerFailed" state with message "Error creating load balancer (will retry): failed to ensure load balancer for service development/myapp: timed out waiting for the condition". 

The activity log of the underlying kubernetes-internal load balancer shows error like this:
```quote
Operation name
Create or Update Load Balancer
Time stamp
Tue Aug 14 2018 10:36:48 GMT-0400 (Eastern Daylight Time)
Event initiated by
SRZ-AKS-01SP-...............
Error code
MultipleIpConfigsRequestSamePrivateIpAddress
Message
IP configuration /subscriptions/........../resourceGroups/............../providers/Microsoft.Network/loadBalancers/kubernetes-internal/frontendIPConfigurations/................... is requesting the same private IP address 10.201.102.253 as IP Configurations /subscriptions/................./resourceGroups/.............../providers/Microsoft.Network/loadBalancers/kubernetes-internal/frontendIPConfigurations/.............. Private IP address 10.201.102.253 from the subnet can be assigned to only one IP configuration.
```

If I remove the loadBalancerIP from the second service file, a new internal IP address will be added to the existing load balancer's front-end IP configuration and a new load balancing rule will be added successfully. However, in this situation we will not be able to use https://myapp.company.domain:30444 to access the new service instance, as we will have to create a new DNS entry for the new IP address. 

Question: what is the correct way to achieve my goal?
