### ISSUE TITLE
Source IP Not available within Cluster using Nginx Ingress

### ISSUE THREAD

**Issue by moomzni** [Azure/AKS#607]
**What happened**:
Our scenario is that we have deployed an AKS cluster using advanced networking and nginx ingress and we've noticed that the SourceIP address for requests originating from the internet is not visible on the ingress controller.

We have tried setting `controller.service.externalTrafficPolicy=Local` which didn't resolve the issue.

The IP addresses reported to nginx vary between pods/nodes connected to the VNET in which AKS is resident and the Azure LB's internal IP.

**What you expected to happen**:
Upon setting `controller.service.externalTrafficPolicy=Local` the source IP address should have been reported in nginx.

**How to reproduce it (as minimally and precisely as possible)**:
1. Build a new AKS cluster (v1.10.5) using advanced networking
2. Deploy nginx-ingress using Helm (v.0.23.0)
3. Enable `controller.service.externalTrafficPolicy=Local` annotation in ingress controller
4. Try accessing your cluster and observing the IP addresses nginx is reporting; they will all be local

**Anything else we need to know?**:
This is a pretty significant gap as short of a fix we have no idea which public IP addresses are making requests of our AKS hosted services.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Internet facing www and api endpoints

**Comment by blackentropy** [comment]
I've reached out to Azure support and they have confirmed that a fix is being deployed and will be available in about a week

**Comment by JunSun17** [comment]
Many thanks to @marrobi for providing a temporary fix for this issue. Please save the following contents to yaml files, and deploy the config map and daemon set to mitigate this issue.

daemonset.yaml
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: source-ip-fix
  labels:
    app: source-ip-fix
spec:
  template:
    metadata:
      labels:
        name: source-ip-fix
    spec:
      hostNetwork: true
      containers:
        - name: source-ip-fix
          securityContext:
            privileged: true
          image: alpine
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            echo "copy scripts to /tmp"
            cp /scripts/*.sh /tmp
            echo "chmod"
            chmod +x /tmp/run.sh
            echo "execute"
            /tmp/run.sh
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
          - mountPath: /scripts
            name: scripts
      volumes:
      - name: scripts
        configMap:
          name: source-ip-fix
```

configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  source-ip-fix
data:
  run.sh: |
    #!/bin/sh

    echo "adding iptables"

    apk add iptables
    while true; do
      echo $(iptables -t nat -L POSTROUTING )

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE
      EXISTS=$?

      # delete rule if exists        
      if [ $EXISTS  -eq 0 ]
      then
        echo "Bad rule exists"

        iptables -t nat -D POSTROUTING  -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE

        echo "Deleted Rule"
      else 
        echo "Bad rule does not exist"
      
      fi
    

      # Get subnet of azure nic, sufficient as source traffic comes from same subnet in our instance
      SUBNET_CIDR=$(ip -o -f inet addr show | awk '/azure0/ {print $4}')

      echo "Subnet is " ${SUBNET_CIDR}

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE
      EXISTS=$?

      if [  $EXISTS  -eq 0  ]
      then
        
        echo "Rule already exists"

      else 
          
        iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE

        echo "Added rule"

      fi

      sleep 60
    
    done

    exit 0
```

**Comment by marrobi** [comment]
@JunSun17 as per @serbrech comment need to ensure specify ```--wait``` in the iptables commands above.

**Comment by denniszielke** [comment]
It works the `x-forwarded-from` header gets set with the source-ip with the following configuration.
The wait needs to be set and the lock file needs to be mounted into the daemonset.
configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name:  source-ip-fix
data:
  run.sh: |
    #!/bin/sh

    echo "adding iptables"

    apk add iptables
    while true; do
      echo $(iptables -t nat -L POSTROUTING)

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE -w
      EXISTS=$?

      # delete rule if exists        
      if [ $EXISTS  -eq 0 ]
      then
        echo "Bad rule exists"

        iptables -t nat -D POSTROUTING  -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d 10.0.0.0/8 -j MASQUERADE -w

        echo "Deleted Rule"
      else 
        echo "Bad rule does not exist"
      
      fi
    

      # Get subnet of azure nic, sufficient as source traffic comes from same subnet in our instance
      SUBNET_CIDR=$(ip -o -f inet addr show | awk '/azure0/ {print $4}')

      echo "Subnet is " ${SUBNET_CIDR}

      # check if exists
      iptables -t nat -C POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE -w
      EXISTS=$?

      if [  $EXISTS  -eq 0  ]
      then
        
        echo "Rule already exists"

      else 
          
        iptables -t nat -A POSTROUTING -m iprange ! --dst-range 168.63.129.16 -m addrtype ! --dst-type local ! -d $SUBNET_CIDR -j MASQUERADE -w

        echo "Added rule"

      fi

      sleep 60
    
    done

    exit 0
```

daemonset
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: source-ip-fix
  labels:
    app: source-ip-fix
spec:
  template:
    metadata:
      labels:
        name: source-ip-fix
    spec:
      hostNetwork: true
      containers:
        - name: source-ip-fix
          securityContext:
            privileged: true
          image: alpine
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - |
            echo "copy scripts to /tmp"
            cp /scripts/*.sh /tmp
            echo "chmod"
            chmod +x /tmp/run.sh
            echo "execute"
            /tmp/run.sh
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
          - mountPath: /scripts
            name: scripts
          - mountPath: /var/run/xtables.lock
            name: xtables
      volumes:
      - name: scripts
        configMap:
          name: source-ip-fix
      - name: xtables
        hostPath:
          path: /run/xtables.lock
```
