### ISSUE TITLE
Cluster unavailable after upgrade from 1.10.5 to 1.11.2

### ISSUE THREAD

**Issue by derekperkins** [Azure/AKS#626]
This issue feels very similar to many others reported, where there are severe networking issues and seemingly infinite CrashLoopBackoffs for multiple `kube-system` services.

I have been running this cluster through 4-5 upgrades since 1.8.x, and this is the first major downtime I've had. I have tried scaling down to one node and then back up to 6, but that didn't work.

_related issues_: https://github.com/Azure/AKS/issues/56, https://github.com/Azure/AKS/issues/153, https://github.com/Azure/AKS/issues/249, https://github.com/Azure/AKS/issues/533

### kube-svc-redirect fails to start
```
kube-svc-redirect-2xtsk                 1/2       CrashLoopBackOff    6          9m        10.0.1.192   aks-nodepool1-39874233-1   <none>
kube-svc-redirect-7xp8s                 1/2       OOMKilled           5          9m        10.0.0.226   aks-nodepool1-39874233-4   <none>
kube-svc-redirect-p7vm5                 1/2       CrashLoopBackOff    6          9m        10.0.2.47    aks-nodepool1-39874233-5   <none>
kube-svc-redirect-t8khz                 1/2       CrashLoopBackOff    5          7m        10.0.0.115   aks-nodepool1-39874233-3   <none>
kube-svc-redirect-vksnw                 1/2       CrashLoopBackOff    5          7m        10.0.1.81    aks-nodepool1-39874233-2   <none>
```

### ingress controller won't start / getting weird errors with helm
`$ helm del --purge nginx`
`Error: Get https://10.1.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)nginx%!C(MISSING)OWNER%!D(MISSING)TILLER: dial tcp 10.1.0.1:443: i/o timeout`

### $ az aks show -o yaml
```
aadProfile: null
addonProfiles:
  omsagent:
    config:
      logAnalyticsWorkspaceResourceID: /subscriptions/1234
    enabled: true
agentPoolProfiles:
- count: 6
  maxPods: 110
  name: nodepool1
  osType: Linux
  storageProfile: ManagedDisks
  vmSize: Standard_E16s_v3
  vnetSubnetId: /subscriptions/1234
dnsPrefix: nozzle
enableRbac: false
fqdn: cluster-f1a00dc7.hcp.canadacentral.azmk8s.io
id: /subscriptions/1234
kubernetesVersion: 1.11.2
linuxProfile:
  adminUsername: username
  ssh:
    publicKeys:
    - keyData: 'ssh-rsa ... '
location: canadacentral
name: nozzle
networkProfile:
  dnsServiceIp: 10.1.0.10
  dockerBridgeCidr: 172.17.0.1/16
  networkPlugin: azure
  networkPolicy: null
  podCidr: null
  serviceCidr: 10.1.0.0/16
nodeResourceGroup: MC_cluster_canadacentral
provisioningState: Succeeded
resourceGroup: rg
servicePrincipalProfile:
  clientId: abc123
type: Microsoft.ContainerService/ManagedClusters
```
