### ISSUE TITLE
How do you enable SSL support for hosted applications?

### ISSUE THREAD

**Issue by ormico** [Azure/AKS#65]
I have a hosted website in a k8 service exposing port 80?
How do I add a certificate and enable SSL?
Can I do this with a service or do I need to create an Ingress?

**Comment by ormico** [comment]
tried tackling this by creating an Ingress using the following:

```
apiVersion: v1
data:
  tls.crt: <certificate request file as base64>
  tls.key: <certificate p7b file as base64>
kind: Secret
metadata:
  name: webapplication2ssl
  namespace: default
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapplication2-ingress
spec:
  tls:
  - secretName: webapplication2ssl
  backend:
    serviceName: webapplication2-svc
    servicePort: 80

```
this succeeded but when I run this
```
PS> kubectl get ing
NAME                      HOSTS     ADDRESS   PORTS     AGE
webapplication2-ingress   *                   80, 443   1h

```
I can see the ingress got created but it is showing no address.

I'm new at this so I might be doing it wrong, but I don't seem to be getting anywhere.

**Comment by ormico** [comment]
Update on my progress. I've tried a couple of different things.
First, I tried installing nginx-ingress manually using the scripts on github, but that didn't work, though I could see what it was trying to do and it felt like progress.
Then I watched a channel 9 video where someone mentioned using helm to install nginx-ingress. So I found [https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm](https://docs.microsoft.com/en-us/azure/aks/kubernetes-helm) . I followed those steps, which were much easier, and tried re-creating my deployment, service, and ingress but it still isn't working.

I'm getting 2 different errors.
First error is an SSL error from the browser SEC_ERROR_UNKNOWN_ISSUER.  Instead, of using the certificate that I passed in, it is using a certificate issued by Kubernetes Ingress Controller Fake Certificate which I assume is some kindof self signed certificate.

It probable that I've somehow misconfigured the tls secret or the Ingress but I don't know how.

Second error, is that instead of showing me the website from my container/deployment, it is just giving me the text "default backend - 404". Same as other error, I might have something misconfigured but I don't know what and don't know how to figure it out.

**Comment by ormico** [comment]
also, if I run 
`kubectl get ing`
it lists 10.240.0.4 as the address, which I think is an internal k8 address. I was expecting the public IP address. Maybe I'm wrong to expect that, but it confused me. I ended up running the k8 dashboard to fidn the public IP.

**Comment by slack** [comment]
@ormico you will see the internal service address on the ingress resource unless you enable `controller.publishService.enabled=true` for the controller.

Default backend sounds like a routing issue, double check that the hostname is correct in the ingress resource.

Ingress Controller Fake Certificate is also usually a routing issue which pops up if hostnames can't be matched or the secrets don't contain the appropriate CN or subjectAltName.

<https://github.com/kubernetes/ingress-nginx/blob/master/docs/troubleshooting.md>

**Comment by ormico** [comment]
Thanks for the feedback, I just recently got this working and wanted to follow up here for anyone who comes after.

I had a variety of issues that I managed to work through. I'll list a few in case it is helpful to anyone else.
1. Certificate issues - I had a lot of issues with the certificates but mostly figuring out what type of certificate file was expected, converting the certificate that I had to that format, having it work in the browser but fail when when pod tried to communicate with another over SSL. This last one really threw me until I realized that while my browser was fine the inter-container web service call (using the public DNS) was failing because I hadn't included the intermediate certificates in the cert file when i added it to the Secret.  I had to copy and past the intermediate file contents at the bottom of my PEM certificate file before I Base64ed it and pasted the Base64 text into the Secret file.

I also had some trouble with the YAML as far as figuring out the the proper way to list multiple domains. Almost all of the examples I could find dealt with a single domain and the indented nature of YAML kept biting me.

2. Proper Ingress declaration. I was only able to get this to work by declaring my ingress as a nginx.

Originally, I couldn't get it to work w/o declaring it as an nginx ingress but I may go back and try again now that I have a lot of the kinks worked out.

3. I'm currently having a problem where the Headers are too large for the nginx buffer and its causing nginx to return an error. Took me a while to realize it was an nginx problem and not a problem with my application or k8 configuration.  I'm currently working on figuring out how to pass the param in the configmap to tell nginx to increase it's header buffer sizing, but I'm hoping to have that resolved soon.

Here is an example of what worked for me:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: my-ingress
spec:
  rules:
  - host: www-test.example.com
    http:
      paths:
      - backend:
          serviceName: wwwtest-svc
          servicePort: 80
        path: /
  - host: login-test.example.com
    http:
      paths:
      - backend:
          serviceName: wwwlogintest-svc
          servicePort: 80
        path: /
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: www-svc
          servicePort: 80
        path: /
  - host: www.example.com
    http:
      paths:
      - backend:
          serviceName: www-svc
          servicePort: 80
        path: /
  - host: login.example.com
    http:
      paths:
      - backend:
          serviceName: wwwlogin-svc
          servicePort: 80
        path: /
  tls:
  - hosts:
    - example.com
    - www.example.com
    - login.example.com
    - www-test.example.com
    - login-test.example.com
    secretName: my-tls
```
