### ISSUE TITLE
[ACI Virtual kubelet] Possible to have persistent storage with aks and aci-connector?

### ISSUE THREAD

**Issue by mollyporph** [Azure/AKS#657]
Hi!
(If this is the wrong forum for the question, please direct me to the correct spot)

I've just deployed a windows container based solution on aks with the aci-connector and now I'm trying to attach some form of persistent storage to it but without any success. In both cases below, when I try to create the replicationcontroller I get a bunch of ProviderFailed statuses and the logs from the aci-virtual-kubelet pod says `Error creating pod" error="Pod abc-qvhp6 requires volume volume which is of an unsupported type` I've tried both azurefile and managed-premium storageclasses but both are unsupported for the k8s/aci scenario, but I can't find any information on what supported storage options there are.

What I've tried:
1. managed disk
pvc.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 128Gi
```
replicationcontroller.yml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: abc
spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: abc
      spec:
        containers:
        - name: abc
          image: abc.azurecr.io/abc
          imagePullPolicy: Always
          resources:
            requests:
              memory: 14G
              cpu: 2
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "c:\\abc"
            name: volume
        volumes:
        - name: volume
          persistentVolumeClaim:
          claimName: azure-managed-disk
        dnsPolicy: ClusterFirst
        nodeName: virtual-kubelet-aci-connector-win
        tolerations:
          - key: azure.com/aci
            effect: NoSchedule
```

2. azure file storage
I tried creating the storage both in the aks node resource group and the ACI resource group, the file share only got successfully created in the aks node resource group.

azure-file-storageclass.yml
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  storageAccount: abcstorage
```
azure-file-clusterrole.yml
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: system:azure-cloud-provider
rules:
- apiGroups: ['']
  resources: ['secrets']
  verbs:     ['get','create']
```
azure-file-clusterrolebinding.yml
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: system:azure-cloud-provider
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:azure-cloud-provider
subjects:
- kind: ServiceAccount
  name: persistent-volume-binder
  namespace: kube-system
```
persistent-volume-claim.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 128Gi
```
replicationcontroller.yml
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: abc
spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: abc
      spec:
        containers:
        - name: abc
          image: abc.azurecr.io/abc
          imagePullPolicy: Always
          resources:
            requests:
              memory: 14G
              cpu: 2
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "c:\\abc"
            name: volume
        volumes:
        - name: volume
          persistentVolumeClaim:
          claimName: azurefile
        dnsPolicy: ClusterFirst
        nodeName: virtual-kubelet-aci-connector-win
        tolerations:
          - key: azure.com/aci
            effect: NoSchedule
```
