### ISSUE TITLE
DNS lookup timeouts

### ISSUE THREAD

**Issue by juan-lee** [Azure/AKS#667]
**Symptoms**
Outbound requests from pods can see a 5 second delay during DNS lookups. This is known to impact containers based off of the alpine image.

**Root Cause**
https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts

**Workaround**
Add the following to your impacted pod's manifest.
```
postStart:
  exec:
    command:
    - /bin/sh
    - -c
    - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
```

**What is single-request-reopen?**
``` 
single-request-reopen (since glibc 2.9)
  Sets RES_SNGLKUPREOP in _res.options.  The resolver
  uses the same socket for the A and AAAA requests.  Some
  hardware mistakenly sends back only one reply.  When
  that happens the client system will sit and wait for
  the second reply.  Turning this option on changes this
  behavior so that if two requests from the same port are
  not handled correctly it will close the socket and open
  a new one before sending the second request.
```
