### ISSUE TITLE
Fix authentication for https endpoint on kubelets

### ISSUE THREAD

**Issue by StianOvrevage** [Azure/AKS#680]
**What happened**:

Installed `prometheus-operator` and `kube-prometheus` helm charts.

This creates among other things a ServiceMonitor for gathering metrics from the kubelets running on the nodes installed by AKS.

One of the entries look like this:
```
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: https-metrics
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
```

However that gives a 401 Unauthorized in Prometheus.

A known workaround is to patch the ServiceMonitor so that it uses http instead:
```
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics
    scheme: http
```

It would be nice to not have to manually add this patch every time we install prometheus on a new cluster (which we do daily).

**So in short: Fix the https metrics endpoint on kubelets to accept the same auth as the http endpoint.**

**What you expected to happen**:

Be able to view kubelet metrics without any changes.

**How to reproduce it (as minimally and precisely as possible)**:

Use helm to install prometheus-operator and kube-prometheus. View targets in Prometheus UI.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.2
- Size of cluster (how many worker nodes are in the cluster?) 3

**Comment by tomasr** [comment]
You can add that service monitor configuration directly in the prometheus chart configuration before feeding it to Helm. It's what I do:

```yaml
prometheus:
  ingress:
    enabled: false
  retention: 168h
  ruleNamespaceSelector: {}
  rulesSelector: {}
  rules:
    specifiedInValues: true
    additionalLabels: {}
    value: {}
...
  serviceMonitors:
    # override the default kubelet monitor
    # to use HTTP and not HTTPS
    - name: kubelet
      selector:
        matchLabels:
          k8s-app: kubelet
      namespaceSelector:
        matchNames:
          - kube-system
      endpoints:
        - port: http-metrics
          scheme: http
          interval: 30s
          bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        - port: http-metrics
          scheme: http
          path: /metrics/cadvisor
          interval: 30s
          bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  storageSpec:
...
```
