### ISSUE TITLE
Unable to assign public static IP

### ISSUE THREAD

**Issue by PlasmaPower** [Azure/AKS#70]
I have created a (static) Public IP Address in the same resource as my AKS cluster. I was hoping to assign it to a Kubernetes service of type LoadBalancer. As specified [here](https://kubernetes.io/docs/concepts/services-networking/service/#type-loadbalancer), I set the `spec` `loadBalancerIP` property to the IP address. However, I get this error:

```
Error creating load balancer (will retry): Failed to ensure load balancer for service kube-system/traefik: user supplied IP Address XX.XX.XX.XX was not found
```

Am I missing something, or is this not currently supported?

**Comment by PlasmaPower** [comment]
May be fixed with kubernetes/kubernetes#53557 but I'm not sure.

**Comment by AceHack** [comment]
I'm getting this same issue, just created a new cluster and tried to follow the simple azure-vote.yml and got this error and saying pending forever and never get's a external IP

**Comment by AceHack** [comment]
Any suggestion on when this may be fixed?  I would really like to get some workloads moved over and test them out but it's not going to work without an external IP.

**Comment by slack** [comment]
As mentioned, the Azure cloud provider integration doesn't support attaching to an existing ip address. Instead, let the Kubernetes service provision a new ip for the service. The most basic service + app that should work looks like:

```
# basic service + deployment
apiVersion: v1
kind: Service
metadata:
  name: basic-service-lb
  labels:
    app: basic-service-lb-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: basic-service-lb-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basic-service-lb-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: basic-service-lb-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.10.1
        ports:
        - containerPort: 80
```
