### ISSUE TITLE
Assign internal IP address to loadbalancer

### ISSUE THREAD

**Issue by okke-formsma** [Azure/AKS#71]
I'm trying to create a cluster with an internal (non-docker) service, but it seems I can only make the service available through a load-balanced *public* IP address. 

Is there a possibility to assign an internal IP address to the loadbalancer, so my service is only accessable from our Azure network?

**Comment by relferreira** [comment]
According to this [page](https://kubernetes.io/docs/concepts/services-networking/service/), I think your service should be something like this:
```
metadata:
    name: my-service
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

But I'm not 100% sure!
