### ISSUE TITLE
Azure file mount permission denied

### ISSUE THREAD

**Issue by guillaumegiordana** [Azure/AKS#714]
**What happened**:

Hello,

I am trying to mount a persistent volume using dynamic provisionning.
But it fails showing this message : 

`MountVolume.SetUp failed for volume "agrial-magento-media" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/7628a8e8-e348-11e8-9daa-4603d9f6b58b/volumes/kubernetes.io~azure-file/agrial-magento-media --scope -- mount -t cifs -o dir_mode=0777,file_mode=0777,uid=1000,gid=1000,username=XXXXX,password=XXXXXX=,vers=3.0 //westeuropeqamutu.file.core.windows.net/agrial-magento-media /var/lib/kubelet/pods/7628a8e8-e348-11e8-9daa-4603d9f6b58b/volumes/kubernetes.io~azure-file/agrial-magento-media Output: Running scope as unit run-rb926671bca1e461d9f616036166b9a8b.scope. mount error(13): Permission denied Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)`

**What you expected to happen**:

I expect to have a proper volume mounted. It worked perfectly with previous versions of Kubernetes.
But since 1.11.2 it doesn't seem to work anymore.

**How to reproduce it (as minimally and precisely as possible)**:
Mount a persistent volume share using azure file.

This is the configuration used to create a azure-file storage class : 

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: azure-file
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
  storageAccount: XXXXX
```

And my volumes are created through PVs : 

```
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: {{ template "magento.media" . }}
  labels:
    app: {{ template "magento.name" . }}
    chart: {{ template "magento.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: {{ .Values.mediaStorageSize }}  
  accessModes: [ "ReadWriteMany" ]
  storageClassName: {{ .Values.storageClassName }}
  azureFile: 
    secretName: {{ template "magento.secret" . }}
    shareName: {{ .Values.azure.storage.mediaShareName }} 
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
```

**Anything else we need to know?**:
Mount with the same parameters didn't fail on previous versions : 1.7.1, 1.10.8

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3 / 1.11.2
- Size of cluster (how many worker nodes are in the cluster?) 3
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : testing purposes, no workload

**Comment by andyzhangx** [comment]
I just tried on a k8s v1.11.2 AKS cluster on west europe region, azure file mount works well. I used following azure file storage class:
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
```

To narrow down this issue, could you ssh to that agent VM under resource group with prefix name as `MC_`, and try following directly on the VM:
```
mount -t cifs -o dir_mode=0777,file_mode=0777,uid=1000,gid=1000,username=XXXXX,password=XXXXXX=,vers=3.0 //westeuropeqamutu.file.core.windows.net/agrial-magento-media /var/lib/kubelet/pods/7628a8e8-e348-11e8-9daa-4603d9f6b58b/volumes/kubernetes.io~azure-file/agrial-magento-media
```
