### ISSUE TITLE
Unable to update the load balancer to open another service

### ISSUE THREAD

**Issue by jbouzekri** [Azure/AKS#715]
**What happened**:

I have followed the tutorial to setup a static ip for my cluster : https://docs.microsoft.com/en-us/azure/aks/ingress-static-ip

Now, I want to open another service (SFTP) on the same IP.

So I created a new `Service` of type `LoadBalancer` with the same external IP.

But, it does not bind to the previous public IP and it shows this error message : `Warning   CreatingLoadBalancerFailed   service-controller   Error creating load balancer (will retry): failed to ensure load balancer for service mynamespace/myservice: timed out waiting for the condition`

The resource : 

```
apiVersion: v1
kind: Service
metadata:
  name: sftp-expand
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: <my cluster public IP>
  ports:
  - name: sftp
    nodePort: 32222
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    io.kompose.service: sftp
  sessionAffinity: None
  type: LoadBalancer
```

**What you expected to happen**:

The existing load balancer should have been updated to loadbalance trafic on this new port 22 to the nodeport 32222 on the nodes and to the selected pod on its port 22.

**How to reproduce it (as minimally and precisely as possible)**:

Just follow previous steps

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Size of cluster (how many worker nodes are in the cluster?) : 6
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.) : HTTP microservices
