### ISSUE TITLE
Mixed protocols on azure load balancer 

### ISSUE THREAD

**Issue by rhollins** [Azure/AKS#754]
**What happened**:

Currently its impossible to create service running on same port and two different protocols due to the following error:  cannot create an external load balancer with mix protocols

**What you expected to happen**:

Azure ILB should create two rules one for TCP and other for UDP

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Service
metadata:
  name: appname
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
  labels:
    app: appname
spec:
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 10.103.10.200
  ports:
  - port: 53
    targetPort: 53
    protocol: UDP
  - port: 53
    targetPort: 53
    protocol: TCP   
  selector:
    app: appname
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.11.5
