### ISSUE TITLE
Differences with Virtual Nodes (DNS, IP addresses) causing angst with certain applications

### ISSUE THREAD

**Issue by npnelson** [Azure/AKS#901]
**What happened**:
DNS settings as evidenced by ````cat /etc/resolv.conf ```` on virtual nodes are missing the search config that a "real" node has. This can cause DNS resolution to fail on the virtual node because of the missing search suffixes.

Additionally, virtual nodes appear to be multi-homed  as evidenced by ````hostname -I````. A virtual node will return 2 IP addresses, one of which being a 169.x.y.z address, while a real node will only return one. This can also cause angst for some applications that register their IP address.

In my case, I modified this selenium helm chart  https://github.com/helm/charts/tree/master/stable/selenium to schedule nodes on virtual nodes. First, it couldn't find the hub due to the DNS issue. Once I worked around that, the node chose the 169.x.y.z address to register instead of the 10.x.y.z address and it appears that the node cannot be reached by the 169.x.y.z address and the whole thing just won't work on virtual nodes. 

**What you expected to happen**:
I would expect DNS config to be same for a "real" and virtual node. I would also not expect the virtual node to have an extra IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Take the following yaml config (call it nodedemo.yaml):

````yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: realnode
  labels:
    purpose: demonstrate-node-differences
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c"," echo \"=======Assigned IP addresses: =======\";hostname -I ; echo \"=======DNS Settings: =======\" ; cat /etc/resolv.conf  "]
  restartPolicy: OnFailure  
---
apiVersion: v1
kind: Pod
metadata:
  name: virtualnode
  labels:
    purpose: demonstrate-node-differences
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/sh"]
    args: ["-c"," echo \"=======Assigned IP addresses: =======\";hostname -I ; echo \"=======DNS Settings: =======\" ; cat /etc/resolv.conf  "]
  restartPolicy: OnFailure
  nodeSelector:
      kubernetes.io/role: agent
      beta.kubernetes.io/os: linux
      type: virtual-kubelet
  tolerations:
    - key: virtual-kubelet.io/provider
      operator: Exists
    - key: azure.com/aci
      effect: NoSchedule      

````

Apply the yaml:
 ````kubectl apply -f nodedemo.yaml````

Pull the logs for the "real" node
````kubectl logs realnode````

You should see something like this:
````
=======Assigned IP addresses: =======
10.128.0.20
=======DNS Settings: =======
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local ehaiug5w2jkupg5bwgqpda4hdf.bx.internal.cloudapp.net
options ndots:5
````
Now pull the logs for the virtual node (this may take a few seconds while the virtual node is being provisioned):
````kubectl logs virtualnode````

Note the output:
````
=======Assigned IP addresses: =======
10.129.0.4 169.254.0.4
=======DNS Settings: =======
nameserver 10.0.0.10
````
Note the missing search and options settings for the virtual node as compared to the real node.
Also note that the virtual node has an additional IP address (169.254.0.4). I view the 169 address as undesirable.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
````
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
````
- Size of cluster (how many worker nodes are in the cluster?) 
1 real node, aci connector
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
nothing else is running on the cluster, this is strictly testing
- Others:
````kubectl get nodes````
````
NAME                       STATUS    ROLES     AGE       VERSION
aks-agentpool-15353091-1   Ready     agent     1m        v1.12.7
virtual-node-aci-linux     Ready     agent     13s       v1.13.1-vk-v0.7.4-44-g4f3bd20e-dev
````

**Comment by matthew-horrocks** [comment]
I am finding the same thing with the virtual nodes in my deployment.

I'm deploying a selenium grid using virtual-kubelets to AKS. The selenium nodes containers which get deployed are registering with the selenium grid server with their 169.x.x.x address.

Happy to provide whatever further information you require.

I've followed the steps above and added logging to the selenium node container. The results were;
```
=======Assigned IP addresses: =======
10.241.0.5 169.254.0.4
=======DNS Settings: =======
nameserver 10.0.0.10
```
Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by matthew-horrocks** [comment]
I found if I force the selenium node container to register with the hub using its 10.x.x.x address, the node registers fine.
```
        env:
          - name: HUB_HOST
            value: "urltoseleniumhub"
          - name: HUB_PORT
            value: "80"
          # - name: "SE_OPTS"
          #   value: "-host 10.241.0.5 -e NODE_PORT=5556 -p 5556:5556"
```
