### ISSUE TITLE
Failed to provision volume with StorageClass azurefile with a given storage account

### ISSUE THREAD

**Issue by hannekot** [Azure/AKS#929]
I'm trying to set up a persisten volume claim that connects to a Storage class for a given storage account. However I get the error:
Failed to provision volume with StorageClass "azurefile": could not get storage key for storage account mystorageaccount: could not get storage key for storage account mystorageaccount: storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Storage/storageAccounts/altinndevstorageaccount' under resource group 'MC_my-dev-rg_k8s-cluster_northeurope' was not found."

which makes sense because the account is not in the MC_ shadow resource group but in the resource group where the cluster is located. I have found documentation for creating storageclass stating: "Azure storage account name. If a storage account is provided, it must reside in the same resource group as the cluster,". So it sounds like it should be possible, but I somehow can't make it work. What am I missing?

Here is my code:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-repo-premium-volume
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  azureFile:
    secretName: azure-secret
    shareName: storagereposhare
    readOnly: false
  claimRef:
    name: storage-repo-premium-volume-claim
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-repo-premium-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 200Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
parameters:
  skuName: Standard_LRS
  storageAccount: mystorageaccount
```

**Environment**:
- Kubernetes version: 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by andyzhangx** [comment]
You should add `resourceGroup: xxx` to specify the resource group name otherwise on AKS, the default resource group is the shadow resource group with name "MC_xxx"
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0755
parameters:
  skuName: Standard_LRS
  storageAccount: mystorageaccount 
  resourceGroup: xxx
```
