### ISSUE TITLE
Unable to attach volumes for multinode StatefulSet

### ISSUE THREAD

**Issue by LMtx** [Azure/AKS#973]
I created a Kubernetes cluster following way:
```
$rg="KuberTestSTSVolumes"
$kub_name="KuberTestSTSVolumes01"
$loc="northeurope"

az group create -n $rg -l $loc
az aks create  --resource-group $rg  --name $kub_name  --node-count 2  --enable-addons monitoring  --generate-ssh-keys
az aks get-credentials -g $rg -n $kub_name
```

Then I used following StatefulSet definition:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 9
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
           - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumes:
          - name: www
            persistentVolumeClaim:
              claimName: azure-disk
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-disks
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-disks
  resources:
    requests:
      storage: 2Gi
```

First pod was created without any issues:

`kubectl describe po web-0`

```
Name:               web-0
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-38380500-1/10.240.0.5
Start Time:         Tue, 14 May 2019 12:58:36 +0200
Labels:             app=nginx
                    controller-revision-hash=web-5c657f48fc
                    statefulset.kubernetes.io/pod-name=web-0
Annotations:        <none>
Status:             Running
IP:                 10.244.1.4
Controlled By:      StatefulSet/web
Containers:
  nginx:
    Container ID:   docker://2759b3c8043dfddd2f4512f4923c1a0098b6c5addf65876c3afc4ee625255687
    Image:          k8s.gcr.io/nginx-slim:0.8
    Image ID:       docker-pullable://k8s.gcr.io/nginx-slim@sha256:8b4501fe0fe221df663c22e16539f399e89594552f400408303c42f3dd8d0e52
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Tue, 14 May 2019 13:01:03 +0200
    Ready:          True
    Restart Count:  0
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io
    Mounts:
      /usr/share/nginx/html from www (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lnfpg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  www:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  azure-disk
    ReadOnly:   false
  default-token-lnfpg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lnfpg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age   From                               Message
  ----     ------                  ----  ----                               -------
  Normal   Scheduled               13m   default-scheduler                  Successfully assigned default/web-0 to aks-nodepool1-38380500-1
  Normal   SuccessfulAttachVolume  11m   attachdetach-controller            AttachVolume.Attach succeeded for volume "pvc-3197bc14-7637-11e9-b944-32bee2f5b21e"
  Warning  FailedMount             11m   kubelet, aks-nodepool1-38380500-1  Unable to mount volumes for pod "web-0_default(391c9d85-7637-11e9-b944-32bee2f5b21e)": timeout expired waiting for volumes to attach or mount for pod "default"/"web-0". list of unmounted volumes=[www]. list of unattached volumes=[www default-token-lnfpg]
  Normal   Pulling                 10m   kubelet, aks-nodepool1-38380500-1  pulling image "k8s.gcr.io/nginx-slim:0.8"
  Normal   Pulled                  10m   kubelet, aks-nodepool1-38380500-1  Successfully pulled image "k8s.gcr.io/nginx-slim:0.8"
  Normal   Created                 10m   kubelet, aks-nodepool1-38380500-1  Created container
  Normal   Started                 10m   kubelet, aks-nodepool1-38380500-1  Started container
```

But the second one can not mount volume:

`kubectl describe po web-1`

```
Name:               web-1
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1-38380500-0/10.240.0.4
Start Time:         Tue, 14 May 2019 13:01:04 +0200
Labels:             app=nginx
                    controller-revision-hash=web-5c657f48fc
                    statefulset.kubernetes.io/pod-name=web-1
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      StatefulSet/web
Containers:
  nginx:
    Container ID:
    Image:          k8s.gcr.io/nginx-slim:0.8
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      KUBERNETES_PORT_443_TCP_ADDR:  kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io
      KUBERNETES_PORT:               tcp://kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:       tcp://kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:       kubertests-kuberteststsvolu-a85abb-652f871b.hcp.northeurope.azmk8s.io
    Mounts:
      /usr/share/nginx/html from www (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lnfpg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  www:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  azure-disk
    ReadOnly:   false
  default-token-lnfpg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lnfpg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age               From                               Message
  ----     ------              ----              ----                               -------
  Normal   Scheduled           13m               default-scheduler                  Successfully assigned default/web-1 to aks-nodepool1-38380500-0
  Warning  FailedAttachVolume  13m               attachdetach-controller            Multi-Attach error for volume "pvc-3197bc14-7637-11e9-b944-32bee2f5b21e" Volume is already used by pod(s) web-0
  Warning  FailedMount         1m (x5 over 10m)  kubelet, aks-nodepool1-38380500-0  Unable to mount volumes for pod "web-1_default(910dc9c8-7637-11e9-b944-32bee2f5b21e)": timeout expired waiting for volumes to attach or mount for pod "default"/"web-1". list of unmounted volumes=[www]. list of unattached volumes=[www default-token-lnfpg]
```

Pods are on two different nodes so they should use different storages:
`kubectl get po -o wide`

```
NAME      READY     STATUS              RESTARTS   AGE       IP           NODE
web-0     1/1       Running             0          16m       10.244.1.4   aks-nodepool1-38380500-1
web-1     0/1       ContainerCreating   0          14m       <none>       aks-nodepool1-38380500-0
```

I read many issues related to volumes but could not find any resolution for this problem.

@andyzhangx any help is very welcome.
