### ISSUE TITLE
Use Network Policy to whitelist external IP addresses

### ISSUE THREAD

**Issue by PeterRockstars** [Azure/AKS#974]
**What happened**:
I attempted to use a NetworkPolicy on an Ingress Controller to whitelist external IP addresses, but the result is that I cannot connect from any IP address.

**What you expected to happen**:
I expected to be able to connect to a service from my own whitelisted IP but not from another IP.

**How to reproduce it (as minimally and precisely as possible)**:

Run this in powershell:
```
# Create a namespace for your ingress resources
kubectl create namespace ingress-basic

kubectl config set-context <myCluster> --namespace=ingress-basic

# Use Helm to deploy an NGINX ingress controller
helm install stable/nginx-ingress `
    --namespace ingress-basic `
    --set controller.replicaCount=1  `
    --set controller.service.externalTrafficPolicy=Local

kubectl get service -l app=nginx-ingress --namespace ingress-basic

helm repo add azure-samples https://azure-samples.github.io/helm-charts/

helm install azure-samples/aks-helloworld --namespace ingress-basic

'apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: aks-helloworld
          servicePort: 80' > hello-world-ingress.yaml

kubectl apply -f hello-world-ingress.yaml

# expect to get html
Invoke-WebRequest -Uri http://<ingress-controller-service-external-ip> -TimeoutSec 2

'apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: ingress-basic
spec:
  podSelector:
    matchLabels:
      app: nginx-ingress
      component: controller
  ingress:
  - from:
    - ipBlock:
        cidr: <my-ip>/32' > networkpolicy.yaml

kubectl apply -f networkpolicy.yaml

sleep 10

# expect to still get html
Invoke-WebRequest -Uri http://<ingress-controller-service-external-ip>
```
My results from the web requests: 
Before applying policy, from any ip: 
```
StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html>
                    <html xmlns="http://www.w3.org/1999/xhtml">
                    <head>
                        <link rel="stylesheet" type="text/css" href="/static/default.css">
                        <title>Welcome to Azure Kubernetes Service (AKS)</title>

                    ...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Vary: Accept-Encoding
                    Content-Length: 629
                    Content-Type: text/html; charset=utf-8
                    Date: Tue, 14 May 2019 12:03:12 GMT
                    Server: nginx/1.15.10
```
After applying policy, from \<my-ip\>:
```
Invoke-WebRequest : 504 Gateway Time-out
nginx/1.15.10
```
After applying policy, form \<another ip\>:
```
Invoke-WebRequest : Unable to connect to the remote server
```

**Anything else we need to know?**:
I roughly followed this tutorial: https://docs.microsoft.com/bs-cyrl-ba/azure/aks/ingress-basic combined with information found on https://kubernetes.io/docs/concepts/services-networking/network-policies/.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (how many worker nodes are in the cluster?)
1 node
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.)
Demo application from Microsoft docs (to try this out before using it on our cluster which runs mainly HTTP microservices in asp.net core)
- Others:
I used this script to create the cluster:
```
$SP_PASSWORD="mypassword"
$RESOURCE_GROUP_NAME="myresourcegroup"
$CLUSTER_NAME="myclustername"
$LOCATION="westeurope"

# Create a resource group
az group create --name $RESOURCE_GROUP_NAME --location $LOCATION

# Create a virtual network and subnet
az network vnet create `
    --resource-group $RESOURCE_GROUP_NAME `
    --name myVnet `
    --address-prefixes 10.0.0.0/8 `
    --subnet-name myAKSSubnet `
    --subnet-prefix 10.240.0.0/16

# Create a service principal and read in the application ID
$SP_ID=$(az ad sp create-for-rbac --password $SP_PASSWORD --skip-assignment --query [appId] -o tsv)

# Wait 15 seconds to make sure that service principal has propagated
echo "Waiting for service principal to propagate..."
sleep 15

# Get the virtual network resource ID
$VNET_ID=$(az network vnet show --resource-group $RESOURCE_GROUP_NAME --name myVnet --query id -o tsv)

# Assign the service principal Contributor permissions to the virtual network resource
az role assignment create --assignee $SP_ID --scope $VNET_ID --role Contributor

# Get the virtual network subnet resource ID
$SUBNET_ID=$(az network vnet subnet show --resource-group $RESOURCE_GROUP_NAME --vnet-name myVnet --name myAKSSubnet --query id -o tsv)

# Create the AKS cluster and specify the virtual network and service principal information
# Enable network policy by using the `--network-policy` parameter
az aks create `
    --resource-group $RESOURCE_GROUP_NAME `
    --name $CLUSTER_NAME `
    --node-count 1 `
    --generate-ssh-keys `
    --network-plugin azure `
    --service-cidr 10.0.0.0/16 `
    --dns-service-ip 10.0.0.10 `
    --docker-bridge-address 172.17.0.1/16 `
    --vnet-subnet-id $SUBNET_ID `
    --service-principal $SP_ID `
    --client-secret $SP_PASSWORD `
    --network-policy azure
```
